### ISSUE TITLE
[bug]: Upgrade Logger depency

### ISSUE THREAD

**Issue by gabrielmcreynolds** [Stacked-Org/stacked#1000]
### Describe the bug

Currently `stacked_generator` ^1.4.0 (latest version) depends on logger ^1.4.0. The logger package has released v2 with some api changes (see [here](https://github.com/Bungeefan/logger/blob/master/CHANGELOG.md#200). This ticket is to upgrade stacked_generator's logger dependency to the latest version and adopt the API changes.

### To reproduce

If you have logger ^2.0.0 as a dependency in pubspec.yaml file then there will be a pub get conflict.

### Expected behavior

Stacked generator should stay up to date with dependencies.

**Comment by ihadabs** [comment]
any update?

**Comment by sebastianbuechler** [comment]
@FilledStacks can you have a look at this dependency upgrade as it is blocking quite a lot now?
