### ISSUE TITLE
[bug]: FormView initial values not syncronizing with viewModel

### ISSUE THREAD

**Issue by miroirstudiosrl** [Stacked-Org/stacked#1001]
### Describe the bug

If you set initial value in a FormTextField the function `syncFormWithViewModel` doesn't set initial viewModel's values (it only adds listeners)..

### To reproduce

```
@FormView(fields: [
  FormTextField(name: 'test', initialValue: 'testvalue'),
])
class Test extends StackedView<TestViewModel> with $Test {
...
 @override
  void onViewModelReady(viewModel) {
    syncFormWithViewModel(viewModel);

    print(testController.text); // "testValue"
    print(viewModel.testValue); // null (should be "testValue")
  }
}
```

**Comment by ferrarafer** [comment]
@miroirstudiosrl a new version of stacked_generator was released, 1.5.0. Can u update the package and see if the issue is fixed?
