### ISSUE TITLE
[feature]: Register listenableServices from a mixin

### ISSUE THREAD

**Issue by sebastianbuechler** [Stacked-Org/stacked#1003]
### Is your feature request related to a problem? Please describe.

We use mixins for commonly used functionality in our view models. So it looks something like this:
```dart
mixin CommonServiceMixin on ReactiveViewModel {
  final commonService= locator<CommonService>();

  bool get commonFlag => commonService.commonFlag;
}
```
It works great, but if we want our views to react to changes in the reactive service, we always need to register the services manually in the view models `listenableServices` override. So like this in the `ReactiveViewModel`:
```dart
  @override
  List<ListenableServiceMixin> get listenableServices => [
        _service1,
        _service2,
        _service3,
        commonService,
      ];
```

This seems a bit unnecessary, as the intent is already clear by adding the mixin to the view model in the first place, and is also a bit dangerous, as it breaks UI re-render functionality if forgotten.

### Describe the solution you would like

It would however make much more sense to let the mixin handle the listener adding. Since the `ReactiveViewModel` "just" adds a listener of `notifyListener` to the services we specify there (and remove it once it is done), we could think of adding the service from the mixin similarly. 

It's not possible to use the same override of `listenableServices` twice and also the mixin does not allow for initialization, but a second override would be possible for mixins. However, this seems a bit ugly and also would only work for one mixin at a time. 

Any other ideas?

**Comment by FilledStacks** [comment]
Thank you for the detailed issue @sebastianbuechler we appreciate that. 

Could you maybe provide an example of your ideal implementation you would like to see. 

How you would like to use it, if we had to implement this feature. I like the request, but we might have different ideas of how the final API usage should look.
