### ISSUE TITLE
[bug]: Stacked Generator: Custom TextEditingController, when used twice in same View, generates two same named functions in view.form

### ISSUE THREAD

**Issue by n-gras** [Stacked-Org/stacked#1004]
### Describe the bug

When using the same custom TextEditingController in two FormTextFields in FormView, the stacked cli generator creates a new *view.form.dart file, containing two functions that are named the same: _getCustomFormTextEditingController, leading to an error where the 'name is already defined.

### To reproduce

Create a View with this decoration:

@FormView(
  fields: [
    FormTextField(
        name: 'phone',
        validator: LoginValidators.validatePhone,
        customTextEditingController:
            LoggingTextEditingController.getLoggingTextEditingController),
    FormTextField(
        name: 'otp',
        validator: LoginValidators.validateOTP,
        customTextEditingController:
            LoggingTextEditingController.getLoggingTextEditingController),
  ],
)

class LoggingTextEditingController extends TextEditingController {
  LoggingTextEditingController({String? text}) : super(text: text) {
    log.d('TextEditingController for $hashCode was created');
  }
  static LoggingTextEditingController getLoggingTextEditingController() {
    return LoggingTextEditingController();
  }

  @override
  void dispose() {
    log.d('TextEditingController for $hashCode was disposed');
    super.dispose();
  }
}

### Expected behavior

I would expect to have only one _getCustomFormTextEditingController function created if both custom Controllers refer to the same class and have same return value.

**Comment by n-gras** [comment]
This function gets generated twice:  
LoggingTextEditingController _getCustomFormTextEditingController(
    String key,
  ) {
    if (_LoginViewTextEditingControllers.containsKey(key)) {
      return _LoginViewTextEditingControllers[key]!
          as LoggingTextEditingController;
    }
    _LoginViewTextEditingControllers[key] =
        LoggingTextEditingController.getLoggingTextEditingController();
    return _LoginViewTextEditingControllers[key]!
        as LoggingTextEditingController;
  }

**Comment by ferrarafer** [comment]
@n-gras we released a new version of `stacked_generate`, 1.5.0. Please, update the package and try again.

**Comment by n-gras** [comment]
@ferrarafer Hi, works great, as expected! Thanks for this, really enjoying the package :D
