### ISSUE TITLE
[bug]:  Command complete. ExitCode: 255

### ISSUE THREAD

**Issue by Taverz** [Stacked-Org/stacked#1006]
### Describe the bug

 stacked create view login --template -> ERRORRE  

stacked create dialog error --template empty ->  

------  
$ stacked create dialog error --template empty   

Created File: 'test/viewmodels/error_dialog_model_test.dart'   
Created File: 'lib/ui/dialogs/error/error_dialog_model.dart'   
Created File: 'lib/ui/dialogs/error/error_dialog.dart'   
Applied Modification Add 'ErrorDialog' dependency to StackedApp annotations file   
Applied Modification Add import for 'ErrorDialog' class   
Running dart format . -l 80 ...   
Formatted lib\ui\dialogs\error\error_dialog.dart   
   
Formatted lib\ui\dialogs\error\error_dialog_model.dart   
   
Formatted test\viewmodels\error_dialog_model_test.dart   
   
Formatted 28 files (3 changed) in 0.25 seconds.   
   
Command complete. ExitCode: 0   
Running dart run build_runner build --delete-conflicting-outputs ...   

Command complete. ExitCode: 255   

$

### what is the error and what does it affect?  
Command complete. ExitCode: 255    

### To reproduce

s

### Expected behavior

s

### Screenshots

s

**Comment by Taverz** [comment]
dd

**Comment by ferrarafer** [comment]
Hi @Taverz , how are you?

I just executed those commands on `stacked_cli` version `1.11.1` and all worked as expected. Which version of the cli do you have installed?

**Comment by MDSADABWASIM** [comment]
I can reproduce this bug on 1.11.2 (latest) @ferrarafer

**Comment by MDSADABWASIM** [comment]
I'm able to solve this by adding these two dev dependencies:
  mockito: ^5.3.2
  build_runner: ^2.2.0
