### ISSUE TITLE
[Question] Does NavigationService use ExtendedNavigator from auto_route package?

### ISSUE THREAD

**Issue by merfire** [Stacked-Org/stacked#101]
Does NavigationService use ExtendedNavigator from auto_route package? 
Because auto_route version 0.6 says: Without ExtendedNavigator you will lose support for RouteGuards and auto-nested navigation handling.

**Comment by FilledStacks** [comment]
@merfire It does not. The navigation service simply provides you access to the navigation key through the static get calls. You can use the ExtendedNavigator in the code outside of the navigation service and it'll work the same.

**Comment by parth181195** [comment]
you can use it like this 
` 
builder: ExtendedNavigator<Router>(
        router: Router(),
        navigatorKey: locator<NavigationService>().navigatorKey,
        guards: [AuthGuard()],
      ),
`

**Comment by surveshoeb** [comment]
@parth181195 I tried your code but this doesn't work!

@FilledStacks If the user isn't authenticated then i need them to redirect to login page via **RouteGuard** 

main.dart
```
 builder: ExtendedNavigator<route.Router>(
        router: route.Router(),
        guards: [AuthGuard()],
        navigatorKey: StackedService.navigatorKey,
        initialRoute: route.Routes.startUpViewRoute,
      ),
```

auth_gurad.dart
```
@override
  Future<bool> canNavigate(
    ExtendedNavigatorState navigator,
    String routeName,
    Object arguments,
  ) async {
    if (routeName != '/' &&
        routeName != 'loginViewRoute' &&
        routeName != 'verificationViewRoute' &&
        routeName != 'resetPasswordViewRoute') 
		return locator<AuthenticationService>().isLoggedIn();
    else
      return true;
  }
```

My code doesn't reach `canNavigte()` may I know why?

**Comment by parth181195** [comment]
@surveshoeb actually package is updated and it does not use auto_route any more so you need to use stacked_genrator to generate route
