### ISSUE TITLE
[bug]: Can't add SingleTickerProviderStateMixin to views

### ISSUE THREAD

**Issue by eh-rick** [Stacked-Org/stacked#1010]
I am trying to add the SingleTickerProviderStateMixin mixin to my view but i can't i keep getting the following error message

'SingleTickerProviderStateMixin<StatefulWidget>' can't be mixed onto 'StackedView<FavouritesViewModel>' because 'StackedView<FavouritesViewModel>' doesn't implement 'State<StatefulWidget>'.
Try extending the class 'SingleTickerProviderStateMixin<StatefulWidget>'.

Here is how i implemented my view

class FavouritesView  extends StackedView<FavouritesViewModel>  with SingleTickerProviderStateMixin {
   FavouritesView({Key? key}) : super(key: key);

### To reproduce

.

**Comment by ferrarafer** [comment]
@slic-rick hi, how are you? You should probably need a `StatefulWidget` to achieve your goal. Kind like the example below.

```dart
class FavouritesView extends StatefulWidget {
  const FavouritesView({super.key});

  @override
  _FavouritesViewState createState() => _FavouritesViewState();
}

class _FavouritesViewState extends State<FavouritesView> with SingleTickerProviderStateMixin {
  late final yourController = TabController(length: tabs.length, vsync: this);

  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder<FavouritesViewModel>.reactive(
      onModelReady: (model) => model.init(),
      viewModelBuilder: () => FavouritesViewModel(),
      builder: (
        BuildContext context,
        FavouritesViewModel model,
        Widget? child,
      ) {
        return Scaffold(
         ...
         /// use yourController here
         ...
        );
      },
    );
  }
}
```

Also, you can read [this](https://www.filledstacks.com/post/flutter-animation-guide-flutter-hooks-animation-flutter-animation-sequences/) post to get more context.

**Comment by eh-rick** [comment]
Okay thanks for the response!

**Comment by bdairy** [comment]
@ferrarafer  just to confirm, to use  SingleTickerProviderStateMixin we have to get back to old stack implementation,, ??
