### ISSUE TITLE
[bug]: Fresh created project not able to start windows

### ISSUE THREAD

**Issue by felixkriechbaum** [Stacked-Org/stacked#1011]
### Describe the bug

Created a fresh project with following command

`stacked create app appname --platforms android,ios,windows,macos,linux --org com.example`

and when i try to start the project for windows i get following error
```
[...]\windows\runner\Runner.rc(92): error RC2104: undefined keyword or key name: com.example 

[...]\build\windows\runner\appname.vcxproj]

Exception: Build process failed.
```

### To reproduce

1. Create a complete fresh project with 
`stacked create app appname --platforms android,ios,windows,macos,linux --org com.example`
2. Open the project in Visual Studio Code
3. Start the un-modified project for windows

### Expected behavior

App start normal

### Fix

Remove double qoutes in line 92 at CompanyName
`VALUE "CompanyName", ""com.exmaple"" "\0"` -> `VALUE "CompanyName", "com.exmaple" "\0"`

and in line 96 the qoutes at LegalCopyright
`VALUE "LegalCopyright", "Copyright (C) 2023 "com.example". All rights reserved." "\0"` -> `VALUE "LegalCopyright", "Copyright (C) 2023 com.example. All rights reserved." "\0"`

**Comment by ferrarafer** [comment]
Hi @felixkriechbaum, please update to version 1.11.2, I fixed the issue.

https://github.com/Stacked-Org/cli/releases/tag/v1.11.2
