### ISSUE TITLE
[bug]: Fresh created project missing files

### ISSUE THREAD

**Issue by wxkly8888** [Stacked-Org/stacked#1025]
### Describe the bug

I followed the documentation to create a new project using the command 
`stacked create app my_first_app` . 
However, after creating the project, I noticed that some files were missing.
![image](https://github.com/Stacked-Org/stacked/assets/25541238/22a65b00-7701-4b9c-83c1-ea4edf4fac41)

### To reproduce

follow the document here https://stacked.filledstacks.com/docs/getting-started/overview, to create a new project

**Comment by ferrarafer** [comment]
Hi @wxkly8888 , can you please paste your `flutter doctor` output here ?

**Comment by wxkly8888** [comment]
Hello @ferrarafer! After upgrading my Flutter version to the latest 3.13.2, the bug I was experiencing seems to be resolved. Previously, I was using Flutter 3.7.0 with Dart version 2.19, and the bug is reproducible on that version.
![image](https://github.com/Stacked-Org/stacked/assets/25541238/427d10a1-8329-45fe-8c78-0af9d4562048)

**Comment by ferrarafer** [comment]
Glad to hear that ❤️
