### ISSUE TITLE
unable to cancel a stream subscription using onDispose()

### ISSUE THREAD

**Issue by pieterbergmans** [Stacked-Org/stacked#1026]
### Describe the bug

Hi. I'm following Dane's tutorial from 2019 on building a [Location Service](https://www.filledstacks.com/snippet/build-a-flutter-location-service/).  I'm using the service in a single page of my app and I'm calling the service with [StreamViewModel()](https://stacked.filledstacks.com/docs/in-depth/viewmodels).  It works great but I want to turn off the subscription when the user navigates away from the page.  I've tried calling `onDispose` in the ViewModelBuilder in my view but it doesn't get called.

```
class LocationView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder<LocationViewModel>.reactive(
      viewModelBuilder: () => LocationViewModel(),
      onDispose: (viewModel) async {
        await viewModel.cancelSubscription();
      },
      builder: (context, viewModel, child) => Scaffold(...));
  }
```

I've also tried adding an `onDispose()` method to the view class but that doesn't work either...

```
  @override
  void onDispose(LocationViewModel viewModel) {
    await viewModel.cancelSubscription();
  }
```

I have two questions:

1. How can I call `onDispose()`?
2. What method do I call for canceling a subscription? I'm currently calling the following from my ViewModel...

```
cancelSubscription() async {
    await streamSubscription!.cancel();
  }
```

### To reproduce

None

**Comment by FilledStacks** [comment]
Hi @pieterbergmans I'm so happy to see more users using Stacked. 

The stream is cancelled automatically when the view is disposed. You can see there [here](https://github.com/Stacked-Org/stacked/blob/7e64e63115c8c82d6a8fcbf8b291d5f2bdd4df50/lib/src/view_models/data_models/single_data_models.dart#L134)

Could you share the behaviour you're seeing that's showing you that the subscription is not cancelled. Logs or anything like that.
