### ISSUE TITLE
[docs]: Should VSCode highlight missing params? 

### ISSUE THREAD

**Issue by FickleLife** [Stacked-Org/stacked#1033]
### Describe the missing piece of documentation

I am going through the documentation and I get to https://stacked.filledstacks.com/docs/getting-started/navigation-basics#navigate-to-a-view-with-arguments and when I run `stacked generate`, should there be red "error" highlighting in VSCode to signify that you need to add a param to `navigateToHomeView` ?

When I run `flutter run` it fails as expected, but was hoping the UI in VSCode would show this error before compilation?

**Comment by FilledStacks** [comment]
Hi, VS code does show it. If it's required then it'll be shown. 

Sometimes the plugin doesn't update correctly. This is a problem with the VS code flutter & dart plugin, not Stacked.
