### ISSUE TITLE
Migration instructions from an old version of Stacked

### ISSUE THREAD

**Issue by pieterbergmans** [Stacked-Org/stacked#1034]
### Describe the missing piece of documentation

Hi...I have two projects using Stacked.  I can't imagine ever doing another Flutter project without it. So, thanks! 

With that said, one of the projects is 2+ years old.  So old, in fact, I don't even have any Stacked-related dependencies in my pubspec.yaml file.  With that said, are there any directions/documentation on how to migrate to the latest version of Stacked?

Thanks in advance.

**Comment by pieterbergmans** [comment]
Even if there is no official documentation, maybe someone can provide a few bullets/steps on how I should approach this.

**Comment by FilledStacks** [comment]
Hey @pieterbergmans,

If it was before the package existed then there's no migration guide. 

The basics would be

1. Replace all the BaseViewModels with the ViewModels from Stacked
2. Create an app.dart file and register the services as dependencies
3. Register all the routes in the app.dart as well

You can generate an empty stacked project to see the setup

**Comment by pieterbergmans** [comment]
Thanks. I realize it will be quite a bit of work but I'm excited to transition to the new Stacked.  Thanks for such a great framework!
