### ISSUE TITLE
[bug]: Doubt about correction

### ISSUE THREAD

**Issue by Natan-hub** [Stacked-Org/stacked#1035]
### Describe the bug

I have this same problem using the another_flushbar package that when you swipe and the screen gets stuck and it was said to have been fixed, using the flutter documentation I saw that it doesn't crash but when swiping the snack bar ends up going to the previous screen too and it does not close. Is there no way to close it?

### To reproduce

1. click on the function to appear the snackBar
2. Swipe to the previous screen
3. the snack bar continues to appear on the screen

**Comment by FilledStacks** [comment]
The snackbar would need to be swipeable. This is not how default snackbars work so you would have to implement that yourself. 

There are packages that allow for swipable snackbars, Stacked used the built in snack from scaffold which does not allow that.
