### ISSUE TITLE
[feature]:  custom the showConfirmationDialog

### ISSUE THREAD

**Issue by ingpedroaraujo** [Stacked-Org/stacked#1039]
### Is your feature request related to a problem? Please describe.

How can I customize showConfirmationDialog in terms of its design, colors, size of buttons?
Thanks in advanced

### Describe the solution you would like

How can I customize showConfirmationDialog in terms of its design, colors, size of buttons?
Thanks in advanced

**Comment by FilledStacks** [comment]
Hey, you can create custom dialogs. 

Run `stacked add dialog [name]` and it'll add the dialog for you. Then you can treat the dialog like a normal view and build anything you want inside it. 

[Docs here](https://stacked.filledstacks.com/docs/tooling/stacked-cli#add-a-new-dialog)
