### ISSUE TITLE
[bug]: Failed to launch emulator: Error: Emulator didn't connect within 60 seconds;

### ISSUE THREAD

**Issue by sanjai-mahalingan** [Stacked-Org/stacked#1042]
### Describe the bug

New to Stacked, created a project guided by [stacked doc](https://stacked.filledstacks.com/docs/getting-started/overview) 
I'm using **AMD Ryzen 5 3500U processor**.

I'm not able to connect to the emulator i have installed for stacked project.
But no problem with the project which is non stacked project.

### To reproduce

Steps to reproduce:

1. Use AMD Ryzen 5 3500U processor laptop,
2. Install needed software for android development (eg: Android Studio, VSCode, etc),
3. Create a stacked project(guided in [stacked doc](https://stacked.filledstacks.com/docs/getting-started/overview) )
4. Open the project in VSCode editor tool.
5. Click "**ctrl + shift + p**" 
6. Select "**Flutter: Launch Emulator**"
7. Select the android emulator which is installed using sdk

Actual Result:

- Failed to launch Pixel 5 API 29: Error: Emulator didn't connect within 60 seconds

### Expected behavior

Should connect to the emulator which is installed

### Screenshots

**Stacked Project screenshot:**
![image](https://github.com/Stacked-Org/stacked/assets/81903879/f55f5a04-5e58-40d4-b983-3769879bd88b)

**Non Stacked Project screenshot**
![image](https://github.com/Stacked-Org/stacked/assets/81903879/7cf74354-c2ea-421b-98ef-ee8057d1dbeb)

**Comment by FilledStacks** [comment]
Hi, 

Stacked has no control over VS code or the emulator and launching. 

Stacked only works inside the Flutter framework, there's no code we could write to talk to VS code in anyway.
