### ISSUE TITLE
[bug]: Bad state: No element

### ISSUE THREAD

**Issue by Dionnie** [Stacked-Org/stacked#1046]
### Describe the bug

stacked generate doesnt work as expectedd

### To reproduce

run `stacked generate ` on CMD

### Screenshots

![image](https://github.com/Stacked-Org/stacked/assets/48149031/49ae3e47-4725-4b82-ae66-3c51ef3cc396)
![image](https://github.com/Stacked-Org/stacked/assets/48149031/e7f33c36-31e9-4b32-bbfe-655804ce7602)

**Comment by FilledStacks** [comment]
Stacked generate is an alias for 

```
flutter pub run build_runner build --delete-conflicting-outputs
```

So you can run that command with --verbose to get more details on your issue.
