### ISSUE TITLE
[bug]: Why is the last character when typing into a selected in my flutter application on ios?

### ISSUE THREAD

**Issue by Natan-hub** [Stacked-Org/stacked#1050]
### Describe the bug

After I updated my IOS system and ran my Flutter projects in all my TextFormField it is selecting the last letter. Is there any way to disable this?

### To reproduce

1 -> Create a Flutter project
2 -> Make a TextFormField
3 -> Type in it and the problem will appear

### Screenshots

https://github.com/Stacked-Org/stacked/assets/67711835/57f94c30-5a2b-40ea-b668-de05edcdc321

**Comment by FilledStacks** [comment]
I have never seen that, maybe it's a new Flutter behaviour. 

Have you figured it out?

**Comment by Natan-hub** [comment]
yes, the problem was on IOS, updating to the latest version the problem disappeared
