### ISSUE TITLE
[docs]: Discord link in docs returns invalid in Discord (expired or no permission)

### ISSUE THREAD

**Issue by jpet710122** [Stacked-Org/stacked#1055]
### Describe the missing piece of documentation

I'd really like to try Stacked, but I've found the docs alone are insufficient. When clicking on any of the Discord links in the docs, Discord shows a dialog with:

**Invite Invalid** 

This invite may be expired, or you may not have permission to join.

**Comment by FilledStacks** [comment]
Hi, here's a valid link. https://discord.gg/cbYcCskpXu

I don't know why it keeps expiring, I set it to never expire. 

Which parts of the documentation do you feel is lacking clarity?

**Comment by jpet710122** [comment]
Thanks, Dane.

I was getting a bit frustrated trying to figure out how to do a complex form with 3rd party input widgets, but I had another look at the example in GitHub, and it’s a bit clearer now. Still, I expected the In-Depth section to go into more detail on forms.

I’ve only been using Flutter for about 6 months, so maybe it’s my inexperience showing!

I’ll have another crack at Stacked, as it seems very good, especially its support for testing.

Cheers.
John
