### ISSUE TITLE
Which layer is more appropriate for show a dialog? View or ViewModel?

### ISSUE THREAD

**Issue by ylytddd** [Stacked-Org/stacked#106]
Which layer is more appropriate for show a dialog? why? thanks

**Comment by RodolfoSilva** [comment]
In the `ViewModel`.

**Comment by FilledStacks** [comment]
@dsmjoy ViewModel using the dialog service. Otherwise you have to pass the data to the view and show the dialog there.

**Comment by ylytddd** [comment]
thanks.
