### ISSUE TITLE
[stacked_generator]: Need upgrade analyzer to ^6.3.0

### ISSUE THREAD

**Issue by ziqq** [Stacked-Org/stacked#1061]
### Describe the solution you would like

Flutter 3.16 requires upgrade analyzer to ^6.3.0

**Comment by Sajonji** [comment]
+1

**Comment by gregorschatz** [comment]
+1

**Comment by FilledStacks** [comment]
+1 --> would be very happy to review and merge a PR for this.

**Comment by ziqq** [comment]
> +1 --> would be very happy to review and merge a PR for this.

https://github.com/Stacked-Org/generator/pull/23

**Comment by ziqq** [comment]
I close this issue myself because analyzer was upgraded.
