### ISSUE TITLE
Undefined name 'InitializableSingleton'

### ISSUE THREAD

**Issue by ujwalbasnet1** [Stacked-Org/stacked#1062]
### Describe the bug

https://github.com/Stacked-Org/stacked/issues/985

got this issue with stacked_generator-1.5.1

### To reproduce

`flutter pub run build_runner build --delete-conflicting-outputs`

running build runner with stacked_generator-1.5.1

**Comment by FilledStacks** [comment]
What version of Stacked are you using?

**Comment by ujwalbasnet1** [comment]
```
stacked: ^3.4.1
stacked_generator: 1.5.1
```

**Comment by FilledStacks** [comment]
And this happens in a brand new project?

**Comment by ujwalbasnet1** [comment]
let me check creating a new project.. will update. Thanks

**Comment by ujwalbasnet1** [comment]
doesn't happen on new project.

**Comment by ujwalbasnet1** [comment]
```
dependency_overrides:
  stacked_shared: 1.3.2
```

I was overriding `stacked_shared` to an older version due to some issues I had earlier, the issue was due to older version of `stacked_shared`.

It works with the latest version.

Thanks.
