### ISSUE TITLE
[docs]: Web platform is not supported in the pub.dev

### ISSUE THREAD

**Issue by saddemYassin** [Stacked-Org/stacked#1065]
### Describe the missing piece of documentation

I tried some basic features from stacked on the web and it's working but in the pub.dev, the package shows no support for the web.

![Screenshot 2023-12-06 110824](https://github.com/Stacked-Org/stacked/assets/10330054/b29337c1-28f3-4dfd-a2c5-4ecf4edb4ba6)

**Comment by FilledStacks** [comment]
Yeah, that's intetesting. We don't actually set that, it's automatically determined. 

If you have any ideas we can make the update and see if we can get the tag to show up.

**Comment by saddemYassin** [comment]
@FilledStacks I didn't do that before but in the official doc it's possible [link to the doc](https://dart.dev/tools/pub/pubspec#platforms).
They mention ** Version note: Support for the platforms entry was added in Dart 2.16.**

**Comment by FilledStacks** [comment]
Oh nice, we can update that. 

@ferrarafer 👆

**Comment by ferrarafer** [comment]
Fixed on latest update 3.4.2
