### ISSUE TITLE
FutureViewModel with SharedPreferences and issue with not disposing viewmodel when user logs out 

### ISSUE THREAD

**Issue by nahid18** [Stacked-Org/stacked#107]
How can I store the future data (model.data) in local storage as soon as it's data ready with `FutureViewModel` and show it in the UI instantaneously? And from there on, only show the stored data every time the user visits the view without calling the future itself. 

In my case, this future data doesn't change automatically and it won't change often.

However, I can definitely not dispose the viewmodel and continue to show the data without requesting extra future calls and also without not storing it and reading it from local storage.

But not disposing the viewmodel brings my next problem below.

When the user logs out (firebase auth) from an account and logs into another account within the same device without destroying the app lifecycle, due to not disposing the viewmodel, the future value from the previous user account shows in the next user screen, whereas it shouldn't!

**Comment by ecerroni** [comment]
As a workaround you may namespace the stored data by userId and show to the logged in user only the data relevant to him.

I guess this would make sense only for a very few number of users sharing the same device.

**Comment by nahid18** [comment]
> As a workaround you may namespace the stored data by userId and show to the logged in user only the data relevant to him.
> 
> I guess this would make sense only for a very few number of users sharing the same device.

Real users won't share the same device in reality. But this is a test case and it should not show such weird behavior. 
I am looking for a straightforward and simple approach here. Otherwise, I have to ditch the `FutureViewModel` but I really don't want to.

Also the future data doesn't change automatically for one user, but it is totally different (List of same data model) for every user on the platform. So storing every user data combination would be a bad approach, I think.

**Comment by nahid18** [comment]
Ok, I fixed it by moving all future data model logic to another service class just like `post_Service` in the example. In that file, I created two basic methods: one for fetching from the api/firestore, one for fetching from local storage. Also another method for saving to local storage.

After that, it's just basic conditional logic checking in another future function. And then used that conditional method within the viewmodel futureToRun function. That's all.

**Comment by FilledStacks** [comment]
@nahid18 sounds about right. I inject my database into my services and then read from there. if it's null from the db then I fetch from the API. you don't need two functions, just 1.  It'll be less code and you don't need a conditional in your viewmodel.

**Comment by nahid18** [comment]
> @nahid18 sounds about right. I inject my database into my services and then read from there. if it's null from the db then I fetch from the API. you don't need two functions, just 1. It'll be less code and you don't need a conditional in your viewmodel.

How about a tutorial with stacked showing exactly what you said here? Also managing cache, fetching data when user updates some data from app, save it again to local storage and also simultaneously updating the UI with reactiveViewModel etc. This will be much helpful. 

One simple use case is: Logging in, reading user data from firestore; based on user's data, make a new request from different firestore collection, also, saving all these value to the local storage and showing it to the UI. Most importantly, when user changes the data, the viewmodel will update everything instantly without going back and forth the view, while also updating the local storage.

**Comment by FilledStacks** [comment]
@nahid18 I might make a tutorial on sqlite but it won't cover any of the situations you spoke about. I'll show the pattern used which should then cover every situation you encouter when using local storage. it'll be around 13-20 minutes so it won't cover everyhing you're asking for. I don't have weeks to prepare a video, only 2 days every 2 weeks.
