### ISSUE TITLE
[feature]: FormTextField validator function various data types such as numbers

### ISSUE THREAD

**Issue by 0001arunsharma** [Stacked-Org/stacked#1074]
### Is your feature request related to a problem? Please describe.

I find it somewhat challenging when dealing with the FormTextField validator function as it exclusively accepts strings, which can make the process a bit laborious.

### Describe the solution you would like

would be appreciated it if the solution could encompass support for various data types such as numbers, in addition to strings.

### Additional Context

FormTextField FormTextField({
  String? name,
  String? initialValue,
  **String? Function(String?)? validator,**
  dynamic Function()? customTextEditingController,
})

**Comment by ferrarafer** [comment]
Hi @0001arunsharma , I think there is no need for this feature. The value is passed as a nullable String but in the function you can treat it as a number. For example, see on the [documentation](https://stacked.filledstacks.com/docs/getting-started/form-basics#form-validation) how we don't allow numbers on a input field using regex. An alternative could be to cast the value to a number and do the validation needed.

**Comment by FilledStacks** [comment]
Did this work @0001arunsharma

**Comment by Glozea** [comment]
@ferrarafer @FilledStacks Apologizes for late response. The documentation is clear to us, but for us the use case is different. Like we would like user to enter the (price as number)of product so instead of casting string as a number i thought if we can expose option to define type will be much easier.

**Comment by 0001arunsharma** [comment]
@ferrarafer @FilledStacks Apologizes for late response. 
The documentation is clear to us but we are asking user to enter the price of product and we are validating the user input. So we thought instead of casting string as a number if we can      define the parameters type in validator function will me more straight forward. As a workaround we can cast value as a number and doing the validation. Thanks

**Comment by FilledStacks** [comment]
I see, since text can take anything it'll always be string. We could probably build a cast -> type generic style middleware for the validator, but that would be more work than doing the cast in the validator as it's needed. 

Thanks for the response.
