### ISSUE TITLE
[bug]: new view creation (in web template app) gives error

### ISSUE THREAD

**Issue by Abhijit-Revamp** [Stacked-Org/stacked#1079]
### Describe the bug

1. Creating new app with stacked web template
2. Add a new view 

```
[INFO] Caching finalized dependency graph completed, took 220ms


[SEVERE] mockito:mockBuilder on test/helpers/test_helpers.dart (cached):

Null check operator used on a null value

[SEVERE] Failed after 321ms
```

### To reproduce

1. stacked update
2. stacked create app debugtest2 -t web
3. stacked create view page2

### Expected behavior

error not expected

### Screenshots

<img width="513" alt="image" src="https://github.com/Stacked-Org/stacked/assets/44320018/5e5cb812-c939-4608-a584-222b38cf7827">

**Comment by FilledStacks** [comment]
Hi, can you try to remove the number from the number form the app name and see if that helps.

**Comment by Abhijit-Revamp** [comment]
Yes, that is correct. Number seems to be an issue.

**Comment by FilledStacks** [comment]
Awesome. I'll close this now
