### ISSUE TITLE
Snackbar sample code not working - onTap

### ISSUE THREAD

**Issue by manafire** [Stacked-Org/stacked#108]
I dropped the [sample code for the Snackbar service](https://pub.dev/packages/stacked_services#snackbar-service) into my project to see what it would look like and get an error at runtime initialization with onTap:

`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type '() => Null' is not a subtype of type '(GetBar<Object>) => void'`

Sample code:

```
await _snackbarService.showSnackbar(
  /// REQUIRED
  message: 'Wow, My Regular Snackbar',

  ////////////////////////////
  /// Optional Parameters ///
  //////////////////////////
  title: 'My Regular Snackbar Title',
  iconData: Icons.hello,
  /// logic for when the snackbar is tapped!
  onTap: () {},  // <---- causes the problems
  /// defaults to `false`; accepts `bool`
  shouldIconPulse: false,
  /// defaults to `0`; accepts `double`
  barBlur: 0,
  /// defaults to `true`; accepts `bool`
  isDissmissible: true,
  /// defaults to a `Duration` of `3 seconds`; accepts `Duration()`
  duration: const Duration(seconds: 3),
);
```

**Comment by FilledStacks** [comment]
@manafire I'll check it out and get back to you.

**Comment by sebastianbuechler** [comment]
@manafire onTap requires you to provide a function of type `(GetBar<Object>) => void`. Thus it has an input variable which you do not declare in your dummy function. Just replace your `() {}` witch `(_) {}` and you're fine. This is usual the convention if you are required to provide an input variable but you have no intention of using it in the actual function.

AFAIK, the empty function `() {}` is interpreted as `null` and can also be just replaced by `null ` itself.

**Comment by FilledStacks** [comment]
@manafire I've completely reworked the snackbar service to remove all UI requirements from the public interface. I've upated the sample as well. Checkout v 0.5.0 along with the updated readme for snackbar service to see how it works.
