### ISSUE TITLE
[bug]: Not adding the .desktop .mobile and .tablet files

### ISSUE THREAD

**Issue by Sentinel111** [Stacked-Org/stacked#1086]
### Describe the bug

When creating a new view with preferWeb: true it only creates the following views:

stacked create view welcome2
templateType:empty preferWeb:true
Created File: 'test/viewmodels/welcome2_viewmodel_test.dart'
Created File: 'lib/ui/views/welcome2/welcome2_viewmodel.dart'
Created File: 'lib/ui/views/welcome2/welcome2_view.dart'

### To reproduce

1. Create a new view

### Expected behavior

From your web tutorial video, it should create another 3 files.

### Additional Context

The project was created using this command: stacked create app **** -t web --platforms web ios android windows --org *****

**Comment by FilledStacks** [comment]
Can you remove the number from the view name and see if it works

**Comment by Sentinel111** [comment]
```console
templateType:empty preferWeb:true
Created File: 'test/viewmodels/bemvindo_viewmodel_test.dart'
Created File: 'lib/ui/views/bemvindo/bemvindo_viewmodel.dart'
Created File: 'lib/ui/views/bemvindo/bemvindo_view.dart'
```
Same problem, before trying "welcome2" created "welcome".

Changed from the "Powershell" (was unstable when using "stacked generate") and I'm now on CMD, same behaviour.

Windows 11, with the VSCode terminal.

**Comment by raphasampaio** [comment]
try passing the template argument:
```
stacked create view welcome2 -t web
```

**Comment by Sentinel111** [comment]
@raphasampaio Thanks, it worked that way, both in CMD and Powershell.

```console
Created File: 'test/viewmodels/welcome2_viewmodel_test.dart'
Created File: 'lib/ui/views/welcome2/welcome2_viewmodel.dart'
Created File: 'lib/ui/views/welcome2/welcome2_view.tablet.dart'
Created File: 'lib/ui/views/welcome2/welcome2_view.mobile.dart'
Created File: 'lib/ui/views/welcome2/welcome2_view.desktop.dart'
Created File: 'lib/ui/views/welcome2/welcome2_view.dart'
```
