### ISSUE TITLE
[Feature Request] Basic Dialog with Circular Progress Indicator and Text for AsyncTask Loading

### ISSUE THREAD

**Issue by nahid18** [Stacked-Org/stacked#109]
Could you include a basic dialog with only circular progress indicator and a text widget in the `dialogService` for the purpose of showing while doing some async task like, logging in or out, getting data etc. 
As soon as the task is done, the dialog will disappear.

I have tried other solutions but they mess up with the context and unstable the widget tree.

**Comment by FilledStacks** [comment]
@nahid18 [this tutorial ](https://www.filledstacks.com/post/show-dialogs-without-context/) shows you how to register a custom dialog UI. Using that you should be able to build multiple dialog UI's to show quite easily in your UI.

**Comment by FilledStacks** [comment]
Based on the tutorial above for now I don't think we need to provide custom UI loaders since it's dependent on the application's UI being built
