### ISSUE TITLE
flutter_map >=6.0.0 depends on logger ^2.0.1 and stacked_generator >=0.6.5 depends on logger ^1.1.0, flutter_map >=6.0.0 is incompatible with stacked_generator >=0.6.5.

### ISSUE THREAD

**Issue by Dionnie** [Stacked-Org/stacked#1090]
### Describe the bug

flutter_map >=6.0.0 depends on logger ^2.0.1 and stacked_generator >=0.6.5 depends on logger ^1.1.0, flutter_map >=6.0.0 is incompatible with stacked_generator >=0.6.5.

### To reproduce

updatee pubspec.yaml

**Comment by MirzaCickusic** [comment]
Plus one here. The logger had a major version update so we should expect more and more libraries using this new version, which as a result would break any app that uses the latest stacked_generator.

**Comment by FilledStacks** [comment]
Thanks for filing the issue. 

Any chance either of you can update it?

**Comment by MirzaCickusic** [comment]
Should that be done inside this project? I tried to find the logger reference inside stacked repo, but couldn't find anything..

**Comment by FilledStacks** [comment]
It's in the stacked_generator, but I know generators are really hard to work with so we might have to tackle that ourselves.

It will be a breaking change for all other Stacked users, but I think it's time to do it.

**Comment by ferrarafer** [comment]
Hi @MirzaCickusic, please try the [prerelease](https://pub.dev/packages/stacked_generator/versions/1.6.1-pre.1) and let me know if you have any problems.

**Comment by MirzaCickusic** [comment]
thanks @ferrarafer 

Looks good on my end

I updated to the latest logger without any issues!
