### ISSUE TITLE
[bug]: ViewModelBuilder creates new ViewModel everytime

### ISSUE THREAD

**Issue by GlizzyHacker** [Stacked-Org/stacked#1095]
### Describe the bug

with both disposeViewModel and createNewViewModelOnInsert set to false, the ViewModelBuilder still creates a new ViewModel every time the View is inserted into the widget tree.

### What operating system do you use?

Windows

### Information about the installed tooling

[√] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.19045.4046], locale hu-HU)
    • Flutter version 3.19.0 on channel stable at D:\Main\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (6 weeks ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\Android\android-sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: D:\Main\Android\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version 4.0)
    • Android Studio at D:\Main\sdk
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2022.3)
    • Android Studio at D:\Main\Android
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4046]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.59
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.128

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

### Steps to reproduce the issue

I created a project to demonstrate the bug
https://github.com/GlizzyHacker/dispose_test

The problem can be reproduced by doing the following:
1. pressing the `Navigate` button
2. incrementing the counter
3. pressing the `Navigate back` button
4. pressing the `Navigate` button again
5. the counter is reset to 0

### Expected behavior

After doing the steps above I expected the counter to retain it's value.

**Comment by FilledStacks** [comment]
Thanks for filing the issue. 

We will take a look at this as soon as we're back at work. It's easter break so will only be back on open source duty on Tuesday next week.

**Comment by ferrarafer** [comment]
Hello @GlizzyHacker, I will try to help you. I think this is not a bug and we should, probably, deprecate `createNewViewModelOnInsert`.

The problem is that when you navigate back, the view and their viewmodel are pulled out of the tree, no matter if we dispose of it or not. Because of that, despite we can avoid disposing of the viewmodel, we lost the reference to it.

The solution to solve this problem is to use the locator for the ViewModel to persist the reference to it.

**Steps to fix the problem:**

1. Add the following line to dependencies at @StackedApp annotation in the app.dart file.
`LazySingleton(classType: HomeViewModel),`
2. Run stacked generate command
3. On HomeView, return HomeViewModel through the locator on viewModelBuilder like below
```
@override
  HomeViewModel viewModelBuilder(
    BuildContext context,
  ) => locator<HomeViewModel>();

```

Let me know if that doesn't work for you and I will re-open the issue.

https://github.com/Stacked-Org/stacked/assets/1505545/cb9e1c44-0744-40ae-9026-3e874af3d92d
