### ISSUE TITLE
how i can navigate to any screen if my app is in the terminated state?

### ISSUE THREAD

**Issue by 21prnv** [Stacked-Org/stacked#1104]
### Is your feature request related to a problem? Please describe.

I am building a video calling app. Whenever I receive a call notification and accept the call, I want to navigate to the call screen in my stacked Flutter app. How can I do that?
 

### Describe the solution you would like

i wanted to navigate to the call view when I accept the call, but unfortunately it's navigating to the startup view.

**Comment by FilledStacks** [comment]
You can use [this implementation](https://www.filledstacks.com/post/dynamic-links-in-flutter-a-complete-guide/) and replace the dynamic link package with whatever you're using for your deep linking. 

In short:

1. Read the link in the startup viewmodel
2. Call `navigationService.replaceWith` and navigate to the route you read from your deepLink.
