### ISSUE TITLE
Generator not working for routes

### ISSUE THREAD

**Issue by jalvespinto** [Stacked-Org/stacked#1106]
### Describe the bug

I have a @StackedApp with routes like this:
```
CustomRoute(page: StartupView, initial: true),
    CustomRoute(page: HomeView, path: '/home'),
    CustomRoute(page: CreateUserView, path: '/create-user'),
    CustomRoute(page: LoginUserView, path: '/login-user'),
    CustomRoute(page: VerificationView, path: '/verification'),
    CustomRoute(
      page: MainLayoutView,
      path: '/main',
      children: [
        CustomRoute(page: DashboardView, path: 'dashboard'), //, initial: true),
        CustomRoute(page: RecipesLandingView, path: 'recipes')
      ],
    ),
    CustomRoute(page: UnknownView, path: '/404'),
    // RedirectRoute(path: '*', redirectTo: '/404'),
  ],
```
Now `stacked generator` started to raise `[SEVERE] stacked_generator:stackedRouterGenerator on lib/app/app.dart: Exception: No config registered for null of type` when using `RedirectRoute(path: '*', redirectTo: '/404')` or setting the DashboardView as an initial route in the nested route. 

Also, even when generating the routes, the generated file is completely different from what it used to be and with a lot of errors like: `final stackedRouter = StackedRouterWeb(...` is not generated any more; what used to be`dietType: queryParams.optString('dietType'),` now is `dietType: data.queryParams['dietType'].value(),`, but `data.queryParams` does not support the `[]` operator. And more.

### What operating system do you use?

macOS

### Information about the installed tooling

❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-BR)
    • Flutter version 3.22.1 on channel stable at /Users/joaquim/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (13 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/joaquim/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 125.0.6422.141

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Steps to reproduce the issue

1. stacked create app pre_test
2. stacked create view main
3. stacked create view nested
4. add queryParam to nested (this will generate, but with errors): `final String? query; const NestedView(@queryParam this.query, {Key? key}) : super(key: key);`
5. add `NestedView` as a child of main and set it as 'initial'. This will bread `stacked generate`
6. stacked create unknown with path '/404'
7. create `RedirectRoute(path: '*', redirectTo: '/404')`. This will break `stacked generate`
8. stacked create view nested_two
9. add pathParam to NestedTwoView (this will generate, but with errors): `final String pageId; const NestedTwoView(@pathParam required this.pageId, {Key? key}): super (key:key);`
10. edit routes:
```
routes: [
    CustomRoute(page: HomeView),
    CustomRoute(page: StartupView),
    CustomRoute(page: MainView, path: '/main', children: [
    CustomRoute(page: NestedView, path: 'nested', initial: true),
    CustomRoute(page: NestedTwoView, path: 'nested-two/:pageId')
    ]),
    CustomRoute(page: UnknownView, path: '/404'),

    RedirectRoute(path: '*', redirectTo: '/404'),
  ],
```

### Expected behavior

generate routes without errors

**Comment by FilledStacks** [comment]
We need to check this @ferrarafer

**Comment by ferrarafer** [comment]
Hi @jalvespinto, how are you? I hope you are well.

1. Are you using `RouterService` or `NavigationService`?
2. Was your project created with the stacked `web` template?

I followed your steps and I didn't get your problems.

Demo of the example:

https://github.com/Stacked-Org/stacked/assets/1505545/69d5e577-b8cb-4059-8806-61ccbf6dc77c

You can check the example code [here](https://github.com/ferrarafer/issue-1106).

Let me know if you were able to fix the issue.

**Comment by jalvespinto** [comment]
Tks for the reply. In my project I am using the web template and the router service.

I will take a look at this during the weekend.

**Comment by jalvespinto** [comment]
Hi @ferrarafer, tks for the reply. My build.yaml file went missing and that is what was causing the errors. After I recreated it things got back to normal. tks again for your help.

**Comment by jalvespinto** [comment]
Hi @ferrarafer, tks for the reply. My build.yaml file went missing and that is what was causing the errors. After I recreated it things got back to normal. tks again for your help.
