### ISSUE TITLE
[bug]: optBool Error: NoSuchMethodError (NoSuchMethodError: Class 'bool' has no instance method 'toLowerCase'.

### ISSUE THREAD

**Issue by rlee1990** [Stacked-Org/stacked#1124]
### Describe the bug

When trying to get query param that is of type bool using optBool it throws an error.
```NoSuchMethodError (NoSuchMethodError: Class 'bool' has no instance method 'toLowerCase'.```
It appears that the issue is with ```_params[key]?.toLowerCase()```

### What operating system do you use?

macOS

### Steps to reproduce the issue

Try to get an optional bool query param.

**Comment by sebastianbuechler** [comment]
Can you please describe what you are trying to do? Where do want to get an optional bool query parameter from? What are the proper steps to reproduce?

**Comment by rlee1990** [comment]
@sebastianbuechler so I have query params that I am trying to retrieve. They are optional. So I am calling ```_routerService.topRoute.queryParams.optString('someName)```
I then get the above error.

**Comment by FilledStacks** [comment]
The type bool has no toLowerCase. 

If you're expecting a string then you should first do a check on the value from `_params[key]` to see if it `is String` then extract the value and toLower it.

**Comment by rlee1990** [comment]
I'm not the one trying to use to lowercase it's the stacked package once I comment out the line of code with the error the package works unless I clear cache or update the package and have to comment it out again
