### ISSUE TITLE
[docs]: How to generate view that uses existing view model using CLI

### ISSUE THREAD

**Issue by Abhijit-Revamp** [Stacked-Org/stacked#1129]
### Describe the missing piece of documentation

I am trying to create two views using the same view model (different representation of data)

what is the way to achieve this  - I need routes etc to be handled like they are.

**Comment by MDSADABWASIM** [comment]
@Abhijit-Revamp 
>[!TIP] 
If you want to reuse the viewModel just create a new widget.
check the docs [here](https://stacked.filledstacks.com/docs/tooling/stacked-cli#add-a-new-widget)

It'll be something like this: 
`class TitleSection extends ViewModelWidget<HomeViewModel> `

**Comment by Abhijit-Revamp** [comment]
@MDSADABWASIM 
I think my description was not clear. This is not documentation issue but a feature request for CLI

when I create new view using 
`stacked create view new_view`

the output is _new_view.dart_ and _new_viewodel.dart_

Is there any possibility to specify viewModel to reUse so that CLI do not create new_viewodel.dart

example:
`stacked create view newView --viewModel old_viewmodel`

**Comment by FilledStacks** [comment]
Hey, this feature doesn't exist and we don't plan to add it. 

You can simply replace the generated ViewModel with the new one and get the same functionality.
