### ISSUE TITLE
[docs]: RouterService: What is the equivalent of pushReplacement and pushAndRemoveUntil

### ISSUE THREAD

**Issue by Abhijit-Revamp** [Stacked-Org/stacked#1130]
### Describe the missing piece of documentation

when using RouterService -> What is the equivalent of pushReplacement and pushAndRemoveUntil

**Comment by MDSADABWASIM** [comment]
@Abhijit-Revamp I would suggest you to read the navigation docs [here](https://stacked.filledstacks.com/docs/getting-started/navigation-basics)

```
pushReplacement: replaceWith
pushAndRemoveUntil: clearStackAndShow
```

**Comment by Abhijit-Revamp** [comment]
@MDSADABWASIM - Thanks. The above makes things a lot clear.
Will go ahead and close this
