### ISSUE TITLE
[docs]: routeObserver in new MaterialApp.router

### ISSUE THREAD

**Issue by Abhijit-Revamp** [Stacked-Org/stacked#1131]
### Describe the bug

With the new stacked framework with web template how do I add the routeObserver in MaterialApp.router

### What operating system do you use?

macOS

### Steps to reproduce the issue

create a stacked app with web template
as per the documentation below
https://pub.dev/packages/stacked_services#route-observation
where is the option to provide routeObserver?

**Comment by Abhijit-Revamp** [comment]
@sebastianbuechler 

I was able to solve this problem. See the changes below

**Can the documentation be updated in the following URL?**
https://pub.dev/packages/stacked_services/example



```dart
class MainApp extends StatelessWidget {
//....
          child: ResponsiveApp(
            builder: (_) => MaterialApp.router(
              routerDelegate: stackedRouter.delegate(
               navigatorObservers: navigatorObserversBuilder,   // <<----- This is required
              ),
//....
  List<NavigatorObserver> navigatorObserversBuilder() => [_LoggingObserver()];   // <<----- This is required
}

class _LoggingObserver extends NavigatorObserver {
  @override
  void didPop(Route route, Route? previousRoute) {
    print(
        'route.name: ${route.settings.name}, previousRoute.name: ${previousRoute?.settings.name}');
    super.didPop(route, previousRoute);
  }
  //....
}

```

**Comment by MDSADABWASIM** [comment]
@Abhijit-Revamp isn't both things eseentially doing the same: 

```
[
        _LoggingObserver(),
 ]
```
 
 or 
 
  `List<NavigatorObserver> navigatorObserversBuilder() => [_LoggingObserver()];`

**Comment by Abhijit-Revamp** [comment]
@MDSADABWASIM 
They work same. I am just putting the issue to update the documentation (example code) in the link https://pub.dev/packages/stacked_services/example

The old way is still valid so no need to remove that. For people using the web-template, its easy for them 
Let me see if I can send a PR with doc changes

**Comment by MDSADABWASIM** [comment]
@Abhijit-Revamp You can create the PR for it, meanwhile please close this issue as it's not an issue.

**Comment by FilledStacks** [comment]
Closing this as it's not an issue. 

Thanks @MDSADABWASIM for answering.
