### ISSUE TITLE
[bug]: stacked create app does not work on Windows

### ISSUE THREAD

**Issue by namtudev** [Stacked-Org/stacked#1137]
### Describe the bug

stacked create app does not generate necessary files, for example `app` folder or `stacked.json`. 
Also behave differently when app name is string vs number ( eg: "my_first_app" vs "123").

### What operating system do you use?

Windows

### Information about the installed tooling

 Flutter version 3.24.3

### Steps to reproduce the issue

# Powershell Log and Project generated for `stacked create app my_first_app`
![image](https://github.com/user-attachments/assets/e3713a28-ed0e-49e5-9fe3-99a3bcafac42)
![image](https://github.com/user-attachments/assets/6b7ffc26-f00f-4e77-ac87-ab5dabe9a252)
# For `stacked create app 123`
![image](https://github.com/user-attachments/assets/eab3d5cd-7fce-4ebf-b304-705e8dbce29f)
![image](https://github.com/user-attachments/assets/ddb7578a-aca2-4df0-9414-3d02f2f97840)

**Comment by han023** [comment]
did you find any solution

**Comment by namtudev** [comment]
No

**Comment by gayankrish** [comment]
I faced the same issue after upgrading Android Studio [to 2024.2.1] and JDK [to 23]. My issue was the Gradle incompatibility with the JDK.
Try running the native "futter create" command (without running "stacked create app"), you shall see a warning with all the details.
What I did was uninstalling the JDK 23 and set the Flutter JDK directory manually. (flutter config --jdk-dir=<JDK_DIRECTORY>). This resolved my issue.
I'm not an expert in this area, for me it seems, due to the warning, stacked cli cannot move forward with template creation.

**Comment by namtudev** [comment]
@gayankrish That fixed it. Thanks a lot!

**Comment by Pebkac03** [comment]
The appname 123 is not in accordance with Dart's requirements found [here](https://dart.dev/tools/linter-rules/package_namesl). Partial solution to app name validation can be found here: stacked-org/cli#54. It also seems to me that a common theme about these "command not working" issues is that the stacked commands do not report errors that would be reported when running the commands it runs in the background manually leading to confusion. Any input on wheter you agree or disagree would be helpful.

**Comment by Deitho** [comment]
> I faced the same issue after upgrading Android Studio [to 2024.2.1] and JDK [to 23]. My issue was the Gradle incompatibility with the JDK. Try running the native "futter create" command (without running "stacked create app"), you shall see a warning with all the details. What I did was uninstalling the JDK 23 and set the Flutter JDK directory manually. (flutter config --jdk-dir=<JDK_DIRECTORY>). This resolved my issue. I'm not an expert in this area, for me it seems, due to the warning, stacked cli cannot move forward with template creation.

Even though my JDK was already set to 17 and had never been changed before, manually setting the Flutter JDK directory just as you suggested worked like a charm. It doesn't make much sense, but I'm happy with the result. Thanks 😄
