### ISSUE TITLE
How to pass arguments to navigation

### ISSUE THREAD

**Issue by Miamoto-Musashi** [Stacked-Org/stacked#114]
there is no documentation on how to implement arguments with NavigationService and how to retrieve them on the ViewModel built by the target view

I tried     
`await _navigationService.replaceWith(Routes.passwordResetConfirmationScreen, arguments: modelUser.fullPhoneNumber);`

on the first view and then

`print('args:${Get.arguments}');`

but does not work.

any suggestion?

thanks

**Comment by RodolfoSilva** [comment]
Hey @Miamoto-Musashi, you need define your arguments in you view, as part of the constructor view.

The `auto_route` will generate a class with the View arguments.

Check this: https://pub.dev/packages/auto_route#passing-arguments-to-routes

**Comment by YTarikKalyoncu** [comment]
After write some variable and contractor to view, run build_runner to generate classes and pass arguments
Example:
`_navigationService.navigateTo(Routes.HomeView, arguments: HomeViewArguments(title: title))`
