### ISSUE TITLE
[QUESTION] How to test View with a ViewModel mock

### ISSUE THREAD

**Issue by apomalyn** [Stacked-Org/stacked#116]
Hi! 
I was wondering it's possible to test a view will use a ViewModel mock?

**Comment by FilledStacks** [comment]
@apomalyn yes, I think it is possible. I haven't been doing it, but for you to do that you'll have to pass in a viewmodel builder function through the constructor of the view as a named optional parameter. If it's not null you use that as the viewmodel builder, else you use your original viewmodel builder

**Comment by apomalyn** [comment]
Of course! Why I didn't think about that! 
Thank you!
