### ISSUE TITLE
FutureViewModel - running future as a result of user's action

### ISSUE THREAD

**Issue by klisiewicz** [Stacked-Org/stacked#120]
Hello,

I was wondering is it possible to run the future defined in `FutureViewModel`:
```dart
Future<T> futureToRun();
```

as a result of some user's action, like tapping a button? Right now, this future is lunched automatically by `ViewModelBuilderState.initState` method, which is not the behavior I desire.

**Comment by alvinvin00** [comment]
how about :

```  @override
  Future<void> futureToRun() {
    return Future.delayed(Duration(seconds: 3), () {
      print('3 Seconds has passed');
    });
  }

**Comment by FilledStacks** [comment]
No that's not possible. in that case I'd recommend using a BaseViewModel and creating a Function that returns a future so you'll have to store your data yourself. Or you can hack it together. Check for a flag in the future to run function, if it's not set return an empty future. When your user interacts with the view, set the flag to true and then run the future again by calling the initialise function.

Thay should work.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by klisiewicz** [comment]
Thank you for your reply. I'll probably go with `BaseViewModel` then since I'm not a big fun of hacks and flags 😉 Have a good day!
