### ISSUE TITLE
[Improvement]: Make DialogResponse responseData dynamic

### ISSUE THREAD

**Issue by essboyer** [Stacked-Org/stacked#121]
Is there a reason that the `responseData` field in `DialogResponse` is a `List<dynamic>` rather than just `dynamic`? It means I have to wrap my single object response in a list when I don't really need to, whereas were it simply `dynamic`, I could pass a list back if needed.

`DialogRequest`'s `customData` is `dynamic` and that has worked great for me, as in one situation I pass back a single object value, and another time I need to pass a `Set<xxxx>`.

**Comment by FilledStacks** [comment]
@essboyer The reason is probably because i was being single minded at the time. i will fix that now and push an update.

**Comment by FilledStacks** [comment]
Done @essboyer update to 0.5.2

**Comment by essboyer** [comment]
Fantastic! Thank you!
