### ISSUE TITLE
Docs for FutureViewModel need an update?

### ISSUE THREAD

**Issue by willhaslett** [Stacked-Org/stacked#123]
For me, declaring the getter doesn't work, whereas declaring the function does. Is the getter deprecated?

:(

<img width="780" alt="Screen Shot 2020-08-06 at 7 00 39 AM" src="https://user-images.githubusercontent.com/2914495/89524983-7cbb7800-d7b3-11ea-8e75-1e3150ffb97e.png">

:)

<img width="837" alt="Screen Shot 2020-08-06 at 7 00 48 AM" src="https://user-images.githubusercontent.com/2914495/89525002-8349ef80-d7b3-11ea-90f0-4045e4050583.png">

**Comment by FilledStacks** [comment]
Yes. It does need an update. let me see if i can do that quickly.

**Comment by FilledStacks** [comment]
Updated :)
