### ISSUE TITLE
[Question] Is it possible to prevent DialogService from closing dialog after calling completeDialog method?

### ISSUE THREAD

**Issue by 0xdecade** [Stacked-Org/stacked#125]
After receiving user input from a dialog box, such as a password, an error may occur, so I'd like to keep this dialog open to show an explanation of the error and give the user a better chance to correct their input. Is it possible?

**Comment by alvinvin00** [comment]
I would run the login process on the dialog and if validation method returns true, then complete the dialog

**Comment by FilledStacks** [comment]
@0xdecade yes. If you want to close the dialog you call completeDialog, if you don't want to close it you don't call it. Also the way I show the custom dialog UI is by creating a new widget. You can simply give that widget a viewmodel and add any kind of business logic to is like you would with a normal view. 

To speed up development I'd suggest setting that view as your home in your scaffold during development and then simply moving that to your custom dialog UI when you're done developing.

**Comment by 0xdecade** [comment]
@alvinvin00 @FilledStacks Thank you, I made some edits based on your responses and now everything works well, but I'm just still not sure - can you tell if the code below looks right or it doesn't?

_contracts_vm_:
**ContractsVM >**

```
  void showContractBindingDialog(item) async{
    DialogService dialogService = locator.get<DialogService>();
    DialogResponse dialogResponse = await dialogService.showCustomDialog(
      title: "${item['account']['vc_name']}",
      variant: DialogType.ContractBindingDialog,
      customData: item
    );
  }

```

_contracts_services_module_:
**ContractServices >** 
```
  Future<bool> bindContract(id, password) async {
    try {
      FormData formData = FormData.fromMap({'password': password});
      Response r = await dio.post(config.endpoint + '/bind/contract/' + id,
          data: formData);
      if (r.statusCode == 200) {
        print(r.data);
        return true;
      }
    } on DioError catch (e) {
      if (e.response.statusCode != null) {
        print(e.response.data);
      } else {

      }
      return false;
    }
  }
```


_ui_:
**dialogService.registerCustomDialogBuilder > builder > content > child > Column > children >** 
```
OutlineButton.icon(
   label: Text('ОК'),
   icon: Icon(
   Icons.done,
    color: Colors.green,
   ),
   onPressed: () {
       contractServices
          .bindContract(dialogRequest.customData['account']['vc_code'],textController.text)
          .then((r) => r ? dialogService.completeDialog(DialogResponse()) :  false);
    },
)
```

**Comment by alvinvin00** [comment]
for last one, you could make it like this to make it more readable (unless false value are used somewhere or you just put that to make it one-liner), other than that it's good

```dart
.then((r) {
if(r) dialogService.completeDialog(DialogResponse());
});
```

Or even better with the power of async-await keyword (may look line it's long but trust me, your brain will thank you 😅)

```dart
onPressed : () async {
String id = dialogRequest.customData['account']['vc_code'];

String pass = textController.text;

bool result = await contractServices.bindContract(id, pass);

if (result) 
dialogService.completeDialog(DialogResponse());

}
```

**Comment by 0xdecade** [comment]
Yes, the multiline looks much better and the brain will be grateful for it, but I'm used to shortening the code if possible - this is how I try to beat long code scrolling. Thank you for your help!
