### ISSUE TITLE
Stacked localisation Package - Implementation Discussion and Requirements

### ISSUE THREAD

**Issue by FilledStacks** [Stacked-Org/stacked#126]
## Motivation

A question that comes up often is how to deal with localisation in stacked. I try my best to make stacked something that builds on top of Flutter meaning that everything you can currently do in Flutter should be able to be done the same using stacked. That means localisation can work exactly the same as well. Given that we've implemented localisation 3 times, once with my way through a `LocalisationService` and twice using the Flutter style setup I have clear examples of how I'd like to implement localisation. 

## Description

This issue will details what I am thinking of implementing in hopes that I can get feedback on certain parts or pointers to work with. The way that I plan an implementation or package is by defining exactly how I'd like to use it in the application. Then I reverse engineer that code to produce concrete details for the implementation 

## Dream Localisation Usage

I would personally like localisation to be available in the models and services for three reasons:

1. Easily rebuild the UI if the strings have been updated
2. Allow for easier translation of exceptions
3. Allow translation of strings with String reliant services like the dialog service

These are a few examples of what I'd like to do in code.

### 1. Translation in the View (UI) files

```dart
 Widget build(BuildContext context) {
    return ViewModelBuilder<HomeViewModel>.reactive(
      builder: (context, model, child) => Scaffold(
        body: Text(model.translate(HomeViewStrings.title))
      ),
      viewModelBuilder: () => HomeViewModel(),
    );
  }
```

### 2. Use translated exceptions (if needed)

```dart
throw Exception(translate(HomeViewScreen.feedFetchFailedException));
```

### 3. Show dialog
```dart
_dialogService.showDialot(title: translate(HomeViewScreens.dialogSuccessTitle));
```

That is how i'd like to use it in code. This is obviously personal opinion but I think if I look at it objectively that it's the cleanest and least intrusive approach to localisation. So lets reverse engineer this syntax and figure out what's required to build this localisation service. 

## Implementation

The first thing we'll need it the functionality to get strings from the `ViewModel`. This will be a simple function that indexes into the `LocalisationService` and requests the string for a key.

```dart
class LocalisedViewModel {

String translate(String key) => _localisationService[key];

}
```

This means in the localisation service we would need the following

```dart
class LocalisationService {
  // this value will be reloaded when the app is started up or when it comes back from the background.
  Map<String, String> _localisedStrings;

  /// Returns the value from the localisedStrings dictionary or the key that was requested.
  String operator[](String key) => _localisedStrings[key] ?? key;

  Future initialise() {
    // get the current locale
    // load the strings from disk into the _localisedStrings
  }
}
```

This is an example of how a language file would look that would be used with the keys above

```javascript
{
  "HomeViewStrings" : {
     "title" : "Home View Title",
     "dialogSuccessTitle" : "You have successfully done something on HomeView",
     "feedFetchFailedException" : "We could not fetch your home feed. Please check connection and try again",
  }
}
```

The type safe String keys generated will look like this.

```dart
// This title comes from the object in the json file above
class HomeViewStrings {
  static String title = 'title';
  static String dialogSuccessTitle =  'dialogSuccessTitle';
  static String feedFetchFailedException = 'ffeedFetchFailedException';
}
```

### Dynamic Values

There are other parts of the service that need to be implemented as well like dynamic value substitution which can be done by passing in a set of replacements into the translate function. If you take an example string like this

```dart
{
  "CounterViewStrings" : {
     "timesCounted" : "You have tapped {0} times",
  }
}
```

we could change the translate function to this.

```dart
String translate(String key, {List<dynamic> replacements} {
  var stringFromFile = _localisationService[key];
  for(int i = 0; i < replacements.length; i++) {
    stringFromFile = stringFromFile.replace('{$i}, replacements[i]);
  }

  return stringFromFile;
}
```

This would allow us to handle dynamic values by using a positioned based replacement function.

## Conclusion

That's basically it. The things that would have to be done for this package to be complete is:

- [x] Create the localisation service
- [x] Create a generator to generate the String key files
- [x] Write the Readme instructions
- [x] publish the package

**Comment by MaikuB** [comment]
I'd say the approach sounds good. From what I remember doing in Xamarin.Forms, what you've described is pretty close to the approach used there for projects that use MVVM and have view models invoke a service to display dialogs. Localised text was stored in .resx files where the IDE provided a visual editor and created a class that exposed the keys as properties that could then be used retrieve the corresponding values

**Comment by FilledStacks** [comment]
@MaikuB yes, it was very similar. it made it easily available throughout the project. I think i'm happy with this approach will probably start developing it this week some time.

**Comment by FilledStacks** [comment]
Update on 13 August 2020:

- [x] Create the localisation service
- [ ] Create a generator to generate the String key files
- [ ] Write the Readme instructions
- [ ] publish the package

Sunday I'll be writing the generator and hopefully build the example with all the scenarios as well.

**Comment by FilledStacks** [comment]
Update on 16 August 2020:

Basic package is complete and can be [seen here](https://github.com/FilledStacks/stacked/tree/master/packages/stacked_localisation/stacked_localisation). It works great! literally hundreds of lines of code less than the implementation we have in  our client projects now specifically because the generator generates all that setup and we don't need to write anything around reading the locales etc. It's still basic so there's a lot of functionality to be added 

**Progress**
- [x] Create the localisation service
- [x] Create a generator to generate the String key files
- [x] Write the Readme instructions
- [ ] publish the package

**Comment by FilledStacks** [comment]
This functionality has been completed and is published as [stacked_localisation](https://pub.dev/packages/stacked_localisation) and [stacked_localisation_generator](https://pub.dev/packages/stacked_localisation_generator) I will be creating a video about this next week.

**Comment by FilledStacks** [comment]
We need the following functionality as well before making this public. I discontinued the package on pub.dev to avoid issues. 

- [ ] Default functionality: When the user selects a language that doesn't have a language file defined we should load the default language.
- [ ] "Hot Reload": When the user changes language on the device and comes back they have to currently restart the app, I'd want the strings to reload when the users come back to the app from the background.

**Comment by Rayv1** [comment]
Is there already a tendency when the package will be available?

**Comment by FilledStacks** [comment]
@Rayv1 i don't know what a "trend" means in this case. The package will be available when the above functionality is implemented.

**Comment by Rayv1** [comment]
Tendency is the right Word here ;-) Iam just asking, if you plan this still for this year or maybe next year, because i need a localization in the next few Weeks and if you are too busy right now, iam looking for something other, which is totally fine.

**Comment by FilledStacks** [comment]
@Rayv1 It will probably be completed this year some time. For now I'd say you should use one of the other solutions out there.

**Comment by abdul10ahad** [comment]
any idea when this is going to to go production?

**Comment by FilledStacks** [comment]
@frodo10messi Not exactly sure. I'd be happy to put it into beta if [this](https://github.com/FilledStacks/stacked/issues/126#issuecomment-678028755) is released but at the moment it's not feature complete.

**Comment by kuanyi-ng** [comment]
Hi, may I work on the "Hot Reload" feature? (if no one is working on it currently) 
I'm currently experimenting with an implementation using `didChangeAppLifecycleState()` of `WidgetsBindingObserver`.
Got this idea from the LifeCycle manager video mentioned in the [Upcoming Feature](https://github.com/FilledStacks/stacked/tree/master/packages/stacked_localisation/stacked_localisation#upcoming-features) of the README.

**Comment by FilledStacks** [comment]
@kuanyi-ng yes you may. That would be awesome. Please keep me updated with the progress.

**Comment by kuanyi-ng** [comment]
@FilledStacks 
Updates on the "Hot Reload" feature.
Below are the implementations that I'm trying. 
```dart
class LocalisationService with WidgetsBindingObserver {
  LocalisationService() {
    WidgetsBinding.instance.addObserver(this);
  }
  
  // either this
  @override
  void didChangeLocales(List<Locale> locale) async {
    final currentLocale = locale.first.toString();
    _localisedStrings = await _stringReader.getStringsFromAssets(currentLocale);
  }

  // or this
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
    // If the user changes language on the device and come back to the app,
    // it will trigger this function with AppLifecycleState.resumed
    if (state == AppLifecycleState.resumed) {
      await _instance.initialise();
    }
  }
}
```
Details with GIF and elaborated explanations can be found in PR #263. 
What do you think about the implementation?
(I will move the details here if it's better to keep all discussions in the issues instead of pull requests.)

**Comment by calvintam236** [comment]
@FilledStacks Will this package release on pub.dev soon (maybe as preview or beta)?
Just an idea for the generator: maybe `stacked_localisation_generator` should be part of the `stacked_generator` (since it is part of the stacked ecosystem and only generate if `stacked_localisation` is there)?

**Comment by calvintam236** [comment]
> @FilledStacks Will this package release on pub.dev soon (maybe as preview or beta)?
> Just an idea for the generator: maybe `stacked_localisation_generator` should be part of the `stacked_generator` (since it is part of the stacked ecosystem and only generate if `stacked_localisation` is there)?

I found [it](https://pub.dev/packages/stacked_localisation) but it looks like outdated. (I think marking it as discontinued make the search ranking much lower). Maybe you can release the new version as preview instead of stable and remove the discontinued flag?

**Comment by FilledStacks** [comment]
@calvintam236 I'm not happy with the functionality in this package and I don't have a way to confirm it's working in production as the project we used localisation on has not had any development in the recent months. 

At this point I'm not confident in releasing this as a filledstacks package as it's not tested with latest flutter and not being used in our production apps. 

I give you permission to fork this repo and publish as-is as your own  package if you want to keep up maintenance. We'll most likely only do some localisation using this in minimum 6 months, maybe even 12 months. Until then this package will see no dedicated development time.
