### ISSUE TITLE
Theme configuration with stacked

### ISSUE THREAD

**Issue by Huzaifaahmed20** [Stacked-Org/stacked#127]
How we can implement theme configuration with stacked architecture, with dark and light mode feature for an App

**Comment by FilledStacks** [comment]
Hi [This is how I did it ](https://www.filledstacks.com/snippet/build-a-theme-manager-in-flutter/) with pure provider. I haven't made a video about doing it with stacked but it'll be the same. I'll just hide provider behind some functions with the work stacked in it.

**Comment by Huzaifaahmed20** [comment]
> Hi [This is how I did it ](https://www.filledstacks.com/snippet/build-a-theme-manager-in-flutter/) with pure provider. I haven't made a video about doing it with stacked but it'll be the same. I'll just hide provider behind some functions with the work stacked in it.

Ok, thanks I will look into this

**Comment by Huzaifaahmed20** [comment]
> Hi [This is how I did it ](https://www.filledstacks.com/snippet/build-a-theme-manager-in-flutter/) with pure provider. I haven't made a video about doing it with stacked but it'll be the same. I'll just hide provider behind some functions with the work stacked in it.

Hi, I had made a starter kit named as [Flutter kickoff](https://github.com/Huzaifaahmed20/flutter-kickoff) with all configurations of your **Stacked Architecture**, I had made a smart widget named as ThemeSwitcher to change the theme of an app, can you please check and let me know if there is anything wrong in that.



P.S: ThemeSwitcher is working fine 😃, but I am worried about the structure and code

**Comment by FilledStacks** [comment]
Follow the issue #128 for updates on the official theme implementation
