### ISSUE TITLE
onModelReady method completion?

### ISSUE THREAD

**Issue by RodBr** [Stacked-Org/stacked#13]
I have several StatefulWidgets that use exactly this syntax:
`onModelReady: (model) => model.initialise(),`

The model.initialise method does a setBusy(true), then gets on with reading data.
However, the first build of the page completes before setBusy(true) is set and notified, causing errors with incomplete data from the model.

I also tried this: `onModelReady: (model) async => await model.initialise(),`

Is there an easy way to halt until the onModelReady method has completed?

**Comment by FilledStacks** [comment]
I put the function in a postFrame callback for handling some navigation events but that was a mistake. I removed that. It should be fixed in 1.3.0+1
