### ISSUE TITLE
Localization package mispelled

### ISSUE THREAD

**Issue by VictorUvarov** [Stacked-Org/stacked#130]
`stacked_localisation` is misspelled it should be `stacked_localization` with the letter `z`

Idk how much it is worth it to change the name since the package is already on dev

**Comment by FilledStacks** [comment]
@VictorUvarov we use 's' in South Africa, Autstralia and UK I think 😄 

Localisation, Customisation

We also use a 'u' in colour 😸

**Comment by VictorUvarov** [comment]
Haha i see
