### ISSUE TITLE
DialogService Validation Example requested

### ISSUE THREAD

**Issue by Rayv1** [Stacked-Org/stacked#136]
Hi,

i try to validate a TextField inside my Dialog, but i cant get it to work. I used the onChange method, but as expected, the Dialog is not rebuilding, so it never knows of the changing value. 

Is there any example for it or a way to go with validation and dialog Service?

Best Regards,
Ray

**Comment by FilledStacks** [comment]
hi @Rayv1 there's not example. You can simply use a widget with its own ViewModel. The custom dialog builder shows a normal widget on a new page route with transparency. it's not a special widget. You can use any widget. So make your custom dialog have its own viewmodel and then call notifyListeners to rebuild the UI once you've done your validation.

**Comment by Rayv1** [comment]
Thanks. i had not in mind, that i just can create a custom Dialog which has its own ViewModel. Thanks!
