### ISSUE TITLE
What is the recommended way to choose b/w FutureViewModel and FutureBuilder?

### ISSUE THREAD

**Issue by rocketman7** [Stacked-Org/stacked#137]
I was using ViewModelBuilder(normal ViewModel only extends BaseViewModel) with FutureBuilder. 
In FutureBuilder, the Futures in the ViewModel are called with some arguments passed from the Widget. A builder function of the FutureBuilder waits until data from the Futures got completely and builds a child widget. 

Now I happen to know about FutureViewModel which I can extend in ViewModel. I want to pass some arguments when I call the Futures in FutureViewModel, but it seems unnatural to pass arguments to the Futures in futureToRun. This is because to do so, I have to pass arguments to ViewModel itself, and we usually don't do that. Every example Stacked provides is written like SomeViewModel(), not SomeViewModel(args), right? 

So, in this case, what is the recommended way to call some Futures in ViewModel and build the rest of the children widgets after the Future data come? Should I use a normal ViewModel with FutureBuilder, or make my FutureViewModel accept arguments with constructor? 

Thanks,

**Comment by FilledStacks** [comment]
Hey,

I don't have a criteria for choosing between those two. It depends on where you want the data to live I guess, or which one you prefer. The 1 point i don't get is "we don't pass arguments to viewmodels". i do that in many videos. Where we edit a post, where we get details for a certain post, etc. There are no restrictions on using the Stacked architecture besides: 

- Don't call functions on services that cause side effects from the views. 
- ViewModels should not know about each other. 
- No UI code in the ViewModels.

There are some others but those are the most important. To wrap it up, you can pass arguments to a viewmodel. Thats an expected thing to do .

**Comment by rocketman7** [comment]
I might have misunderstood about arguments in viewModel in this architecture. 

Thanks for the answer and all the great tutorials!
