### ISSUE TITLE
 '!barrierDismissible || barrierLabel != null': is not true.

### ISSUE THREAD

**Issue by Rayv1** [Stacked-Org/stacked#138]
Hi,

i updated to the newest Version of stacked_services and now receiving the following Errors, when i set barrierDismissible to true:
E/flutter (18940): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:get/src/navigation/extension_navigation.dart': Failed assertion: line 487 pos 12: '!barrierDismissible || barrierLabel != null': is not true.

``` 
  Future changeStartWeightDialog() async {
    await dialogService.showCustomDialog(
        customData: [changeWaterGlasSizeOnTap, TextInputType.number],
        takesInput: true,
        barrierDismissible: true,
        title: 'Startgewicht',
        description: 'This is my Dialog description',
        variant: DialogType.Form,
        mainButtonTitle: 'Confirm');
  }
```

i need barrierDismissible, but cant set the barrierLabel.

**Comment by FilledStacks** [comment]
Added a new property in `0.5.4+2`
