### ISSUE TITLE
get: 3.8.0 package breaks build

### ISSUE THREAD

**Issue by essboyer** [Stacked-Org/stacked#139]
Builds with `get: 3.7.0`

With `get: 3.8.0`:

`../../.pub-cache/hosted/pub.dartlang.org/stacked_services-0.5.2/lib/src/snackbar/snackbar_service.dart:172:7: Error: No named parameter with the name 'onStatusChanged'.
      onStatusChanged: snackbarConfig.onStatusChanged,
      ^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/get-3.8.0/lib/src/navigation/snackbar/snack.dart:13:3: Context: Found this candidate, but the arguments don't match.
  GetBar(
  ^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/stacked_services-0.5.2/lib/src/snackbar/snackbar_config.dart:47:3: Error: 'SnackStatusCallback' isn't a type.
  SnackStatusCallback onStatusChanged;
  ^^^^^^^^^^^^^^^^^^^`

**Comment by FilledStacks** [comment]
Thanks will check it out now and push an update.

**Comment by FilledStacks** [comment]
Pushed update on `v0.5.4+1`
