### ISSUE TITLE
Globally access the state

### ISSUE THREAD

**Issue by FANTAzeRus** [Stacked-Org/stacked#140]
![image](https://user-images.githubusercontent.com/6191326/92080165-c35bbc80-edc9-11ea-9076-058136a7a742.png)
![image](https://user-images.githubusercontent.com/6191326/92080935-fb173400-edca-11ea-920b-05cd32959b1f.png)
![image](https://user-images.githubusercontent.com/6191326/92082063-bab8b580-edcc-11ea-824a-fbce8ba4e65c.png)
![image](https://user-images.githubusercontent.com/6191326/92082114-cdcb8580-edcc-11ea-9f28-567bce647789.png)

Greetings!
Tell me why when you open a new screen, a new instance is created. What needs to be done to globally access the state from anywhere in the application ???

**Comment by alvinvin00** [comment]
register AppModel as a Singleton, then call it using locator (assuming you're using Get It) on viewModelBuilder

`viewModelBuilder : ()=> locator<AppModel>()`

**Comment by FilledStacks** [comment]
Hey, that's how Flutter works. It constructs new widgets in our case new models when a screen is opened. You can re-use the same viewmodel, but that's in rare cases where the viewmodel needs to stay alive for long. If you want to share state between viewmodels you keep it in a service that can be accessed by both

**Comment by zkx2020** [comment]
> 
> 
> Hey, that's how Flutter works. It constructs new widgets in our case new models when a screen is opened. You can re-use the same viewmodel, but that's in rare cases where the viewmodel needs to stay alive for long. If you want to share state between viewmodels you keep it in a service that can be accessed by both

Could you tell me how to re-use the viewmodel...For example,if I have a method that three different viewmodel need to use it,what should I do?Thanks!

**Comment by FilledStacks** [comment]
@zkx2020 Pu the function in a baseViewModel and extend your other viewmodels from it.
