### ISSUE TITLE
isRegistered not working for me

### ISSUE THREAD

**Issue by rdonoso** [Stacked-Org/stacked#141]
Hello,

I tried to use the method to check if a singleton is already registered, but it seems that i am doing something wrong.

This is an extract of the code and if i use this way always return false and always throw the exception with the next line that is already registered the singleton
`if (!locator.isRegistered(instance: ControlCenterViewModel))`

But this way if the instance is not loaded throw an exception, to make sure that ControlCenterViewModel is in get_it.
`if (!locator.isRegistered(instance: locator<ControlCenterViewModel>()))`

Please help, how i can make this right.

Thanks!

**Comment by FilledStacks** [comment]
Hey, 

I think for the instance you need to pass the actual instance and not a type. 

I haven't used isRegistered but I assume it's typed like everything else so you should pass a generic type instead. Unless you have the instance to pass in

**Comment by rdonoso** [comment]
This way now is working.

`if (!locator.isRegistered<ControlCenterViewModel>( ))`
