### ISSUE TITLE
The getter 'defaultDurationTransition' isn't defined for the class '_GetImpl'.

### ISSUE THREAD

**Issue by logblythe** [Stacked-Org/stacked#148]
I have been following the version two of your architecture. I am getting this error.

../../flutter/.pub-cache/hosted/pub.dartlang.org/stacked_services-0.5.4+2/lib/src/navigation_service.dart:119:33: Error: The getter 'defaultDurationTransition' isn't defined for the class '_GetImpl'.
 - '_GetImpl' is from 'package:get/src/core/get_main.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/get-3.10.2/lib/src/core/get_main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'defaultDurationTransition'.
      duration: duration ?? Get.defaultDurationTransition,

**Comment by javdhu** [comment]
I've been having the same problem. Adding get to pubspec with version 3.8.0, seems to solve it for now.

**Comment by mistyn8** [comment]
Seems fixed in Stacked_Services 0.5.4+3

**Comment by FilledStacks** [comment]
@logblythe @jdaev , @mistyn8 is correct. It's fixed in 0.5.4+3
