### ISSUE TITLE
Best approach tu initialize Firebase

### ISSUE THREAD

**Issue by rdonoso** [Stacked-Org/stacked#149]
Hello,

I am trying to solve the new initialization of FlutterFire with the new version they released (0.5.0), and now  [or always] is necessary to call in the main the next line of code.

`await Firebase.initializeApp();`

https://firebase.flutter.dev/docs/overview#initializing-flutterfire

To do that with get_it i created a FirebaseService that  all services depends of that initialization and my service locator look like 
```
 locator.registerSingletonAsync<FirebaseServices>(() async {
    final firebaseService = FirebaseServices();
    firebaseService.init();

    return firebaseService;
  });
  locator.registerSingletonWithDependencies<UserSession>(() => UserSession(),
      dependsOn: [FirebaseServices]);
```

i would like to know how you guys how solved this condition in firebase and if there is better way to do it.

Thanks!

**Comment by FilledStacks** [comment]
Our projects are not updated yet. If i had to do it it would be done similar to the shared preferences service. 

```
var firebase = FirebaseService()
await firebase.initialise()
registerSingleton(firebase)
```

The way you did it is also a nice way. I've never done it that way. I think i'll try it out when we upgrade our packages.
