### ISSUE TITLE
[Stacked Themes] Font Family parameter not working in ThemeBuilder

### ISSUE THREAD

**Issue by codezero93** [Stacked-Org/stacked#150]
I have a custom font Cairo in my app. Its working fine when ThemeData defined in Material App function but not in ThemeBuilder somehow

**Comment by FilledStacks** [comment]
@codezero93 there's nothing specifically being done for the theme builder function in regards to the font family. I pass the theme data as is directly to the builder function.

**Comment by codezero93** [comment]
> @codezero93 there's nothing specifically being done for the theme builder function in regards to the font family. I pass the theme data as is directly to the builder function.

Yes saw this in your code and thats really a head scratcher. Trying to figure out what causing this but no avail right now.

**Comment by codezero93** [comment]
> > @codezero93 there's nothing specifically being done for the theme builder function in regards to the font family. I pass the theme data as is directly to the builder function.
> 
> Yes saw this in your code and thats really a head scratcher. Trying to figure out what causing this but no avail right now.

Ok my mistake I applied text theme and when you do that you have to mention font family there too just like this: 
```
textTheme: Theme.of(context).textTheme.apply(
                            bodyColor: textColorSecondary2,
                           displayColor: textColor2,
                          fontFamily: 'Cairo')
```
Closing this now.
