### ISSUE TITLE
[Stacked Themes] Theme mode is always system

### ISSUE THREAD

**Issue by codezero93** [Stacked-Org/stacked#151]
Default theme is always system no matter what you specify in ThemeBuilder. So checked the ThemeBuilder class and found out default theme parameter missing assignment in **ThemeManager constructor**.
For now solved the issue by adding this:
**defaultTheme: defaultThemeMode**
inside **ThemeBuilder** class in **ThemeManager** constructor

**Comment by FilledStacks** [comment]
Fixed in 0.1.0+1
