### ISSUE TITLE
[Stacked Services - SnackBarService] Title cannot be null in showCustomSnackbar

### ISSUE THREAD

**Issue by codezero93** [Stacked-Org/stacked#153]
I don't want to show title in showCustomSnackBar methods same as in showSnackBar but leaving this parameter null throws Exception : "A non-null String must be provided to a Text widget "**A non-null String must be provided to a Text widget**" also assigning it empty String creates abnormal space above message.

**Comment by codezero93** [comment]
> I don't want to show title in showCustomSnackBar methods same as in showSnackBar but leaving this parameter null throws Exception : "A non-null String must be provided to a Text widget "**A non-null String must be provided to a Text widget**" also assigning it empty String creates abnormal space above message.

Can we have a boolean field to hide/show title ?

**Comment by ajnaf** [comment]
Just add title : ""

**Comment by codezero93** [comment]
> Just add title : ""
Already tried..
This results in extra height above message which is obvious because Text widget is still created in title
