### ISSUE TITLE
Pass value from AuthService to ViewModel

### ISSUE THREAD

**Issue by rocketman7** [Stacked-Org/stacked#154]
Hi,

I want to make AuthCredential using Firebase PhoneAuth.

1. PhoneAuthView passes a phone number to its viewModel which trigger a Future function using FirebaseAuth.verifyPhoneNumber in AuthService. This Future function sends a SMS code and generates a verificationId. 
2. Again, PhoneAuthView passes a SMS code that user put to the viewModel. The ViewModel has to make AuthCredential using both 'SMS code which user inserted' and 'verificationId which the Future function already generated'.

I would like to send the verificationId from AuthService to the ViewModel so that I can call a Future function in the ViewModel to make AuthCredential in AuthService. 
In that case, which way would be the best to send verificationId from AuthService to the ViewModel?
I am also wondering if this behavior is okay for the Stacked ground rules. (passing value from Service to the ViewModel)

- With this Future Function in AuthService, users can get sms code
<img width="435" alt="스크린샷 2020-09-17 오전 3 54 50" src="https://user-images.githubusercontent.com/26252769/93379955-8b5c7b00-f899-11ea-9912-e9968e4d3f1d.png">

- Here the view send sms code to the ViewModel
<img width="353" alt="스크린샷 2020-09-17 오전 3 52 54" src="https://user-images.githubusercontent.com/26252769/93379781-46d0df80-f899-11ea-803e-2a96395c1ff2.png">

- Eventually the viewModel has to call this function in AuthService using 'verificationId' and 'code' but I don't know how to get verificationId value which was generated in AuthService.
<img width="407" alt="스크린샷 2020-09-17 오전 3 55 14" src="https://user-images.githubusercontent.com/26252769/93380000-9b745a80-f899-11ea-8af7-a3bb4d391f9a.png">

Thanks,

**Comment by FilledStacks** [comment]
You should use a Completer that you complete when the value is returned. then you can just do an await call in the Viewmodel on the AuthService
