### ISSUE TITLE
No Stateful Widgets?

### ISSUE THREAD

**Issue by jtkeyva** [Stacked-Org/stacked#155]
From what I see this seems like a great architecture. I'm just concerned that Stateful Widgets, a major core feature of Flutter are never used within it. Am I worried over nothing, or is this a huge deal?

Most every tutorial I see online and stack exchange help use Stateful Widgets in their examples and solutions. So what do I do when I'm following examples and learning new stuff that use the ubiquitous Stateful Widgets?

Thank you

**Comment by alvinvin00** [comment]
well, Stateful Widget ain't going anywhere in Stacked, you can still use it like this

`ViewModelBulider<T extends ChangeNotifier>.reactive(builder:(context, model, child)=> Widget(), viewModelBuilder : ()=> T )`

**Comment by jtkeyva** [comment]
@alvinvin00 thank you, so essentially I just have to learn to "translate" when I see code written using stateful widgets to that? in your experience does it ever get cumbersome or are you glad you "bought in" to the stacked way?
thanks

**Comment by jtkeyva** [comment]
So I'm in the scenario I was worried about. Since Stacked doesn't use Stateful Widget per se or MaterialPageRoute, implementing things is difficult for me. How would I translate/implement this into the Stacked way?
Thank you

Instructions say: "Add this function to Your StateFul Widget"

Future<void> getimageditor()  {
  final geteditimage =   Navigator.push(context, MaterialPageRoute(
      builder: (context){
        return ImageEditorPro(
          appBarColor: Colors.blue,
          bottomBarColor: Colors.blue,
        );
      }
  )).then((geteditimage){
    if(geteditimage != null){
      setState(() {
        _image =  geteditimage;
      });
    }
  }).catchError((er){print(er);});

}

**Comment by FilledStacks** [comment]
You would move all the state logic into the viewmodel and then use the navigation service to navigate to the ImageEditorPro route.

**Comment by techstack2091** [comment]
Guys you can use stateful widget if it is really required. Extend the model with the State class. I use this technique for animations.

**Comment by FilledStacks** [comment]
Do not do what @techstack2091 mentioned above 😆 there's should be no UI related code in the ViewModels it will completely remove the unit testability of your viewmodel. Which is one of the signs that you're using a ViewModel and not just a different file with UI code in it.
