### ISSUE TITLE
Nested Navigator - `back` function does not have `id`

### ISSUE THREAD

**Issue by ParthaGudivada** [Stacked-Org/stacked#156]
In nested navigator, if I have to navigate back using a button option other than the default left nav bar, I could not use the current definition.  However I can use something like below to pass the id parameter to keep track of the key of the `Navigator` widget (need to handle if we do not pass the `id` like in the existing method)

```swift

 bool back({dynamic result, int id}) {
    Get.back(result: result, id: id);
    return Get.nestedKey(id).currentState.canPop();
  }

```
Is there a different way to achieve the same

**Comment by FilledStacks** [comment]
I've added that to 0.5.4+4 onto the navigation service
