### ISSUE TITLE
TabController not working

### ISSUE THREAD

**Issue by Abedi98** [Stacked-Org/stacked#157]
when use TabController in view i have error 'vsync != null': is not true.
and stacked package, not supported vsync !! **right** !???

**Comment by Abedi98** [comment]
nobody answer my question !?

**Comment by ajnaf** [comment]
Put the TabController in the viewmodel

**Comment by Abedi98** [comment]
**E/flutter (29520): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 278 pos 15: 'vsync != null': is not true.**

```
class CategoryListViewModel extends IndexTrackingViewModel  {

void initialise(){
    TabController _controller = TabController(
      vsync: this,
      length: this.myTabs.length,
      initialIndex: 0,
    );
  }

}


Widget build(BuildContext context) {
    return ViewModelBuilder<CategoryListViewModel>.reactive(
      viewModelBuilder: () => CategoryListViewModel(),
      onModelReady: (model) async => **model.initialise()**,
      fireOnModelReadyOnce: false,
      disposeViewModel: true,
      builder: (context, model, child) => ..........
```

**Comment by ajnaf** [comment]
If u define the controller straight in the initialize method u wont be able to use it anywhere 
U should define it above method so u can use it in your view like model.controller in ur Tab Widget or whatever

**Comment by ajnaf** [comment]
And u don't need initialize method for definig a controller just take it outside of the method and should work fine

**Comment by FilledStacks** [comment]
What exactly is the problem because i'm having trouble understanding your questions and what you want to achieve.

**Comment by Abedi98** [comment]
When I instance tabcontroller, the vsync parameter gives the error that you must implement TickerProvider...

Please write a complete example of using tabcontroller using this package.

thanks

**Comment by Abedi98** [comment]
Home_Screen.Dart

```
class HomeScreen extends StatelessWidget   {
  HomeScreen({Key key,}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder<CategoryListViewModel>.reactive(
      viewModelBuilder: () => CategoryListViewModel(),
      onModelReady: (model) async => model.initialise(),
      builder: (context, model, child) =>
            Scaffold(
              appBar: AppBar(
                backgroundColor: Color(0xFF002575),
                title: Text('News'),
                bottom: model.myTabs.length > 0 ? new PreferredSize(
                  preferredSize: new Size(40.0, 60.0),
                  child: GestureDetector(
                    child: TabBar(
                      key: key,
                      controller: model.tabController,
                      tabs: model.myTabs,
                      indicator: UnderlineTabIndicator(
                        borderSide: BorderSide(
                            width: 4.0, color: Colors.white),
                      ),
                      labelColor: Colors.white,
                      indicatorColor: Colors.red,
                      unselectedLabelColor: Colors.white60,
                      indicatorSize: TabBarIndicatorSize.tab,
                      isScrollable: true,
                      onTap: (int index) {
                        model.clickTab(index);
                      },
                    ),
                  )
                ) : null,
              ),
            ),
    );
  }
}
```

categorylist_viewmodel

```
class CategoryListViewModel extends IndexTrackingViewModel  {

  TabController tabController;
  List<Widget> myTabs = [];

  void initialise(){
    this.getTopCategory();
    print(this.currentIndex);

  }


  void getTopCategory() async {
    List<Category> categoryModel = await WebService().fetchTopCategory();
    . 
    . 
    .
  }

}

```

and get this error after run project

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Listener:
No TabController for TabBar.
When creating a TabBar, you must either provide an explicit TabController using the "controller"
property, or you must ensure that there is a DefaultTabController above the TabBar.
In this case, there was neither an explicit controller nor a default controller.

**Comment by Abedi98** [comment]
```
class CategoryListViewModel extends IndexTrackingViewModel with SingleTickerProviderStateMixin  {

}
```

SingleTickerProviderStateMixin<StatefulWidget>' can't be mixed onto 'IndexTrackingViewModel' because 'IndexTrackingViewModel' doesn't implement 'State<StatefulWidget>'.

**Comment by Rayv1** [comment]
@Abedi98 dont mix the SingleTicketProviderStateMixin in the ViewModel. 
First initialize your Tabcontroller as of now u just declaring it.
`TabController tabController = new TabController();`

**Comment by RohanPatil1** [comment]
Try like this :
In the ViewModel-
  final TabController _tc = TabController ();
  TabController get tc=> _tc;

**Comment by techstack2091** [comment]
Is there anyone with a solution to initialize TabController?

**Comment by techstack2091** [comment]
Yeah... got a solution. Use like this in the view model and call using onModelReady

` void initState(TickerProvider vsync) {
    tabController = TabController(length: tabs.length, vsync: vsync);
    tabController.addListener(() {
      print('Current Tab Index: ${tabController.index}');
    });
  }`

- give the controller for TabBar & TabBarView
- use a StatefulWidget with SingleTickerProviderStateMixin so that you can pass TickerProvider in initState call
