### ISSUE TITLE
[Stacked Themes] Theme persistence issue

### ISSUE THREAD

**Issue by birkoni5** [Stacked-Org/stacked#158]
​Can you please check if a theme is being saved to local storage on change? 
In my case, it remains the same as the first time I run an app, no matter which theme I select later.

I think you should add `_sharedPreferences.userThemeMode = _selectedThemeMode` to `toggleDarkLightTheme()` method in theme_manager.dart.

**Comment by FilledStacks** [comment]
@birkoni5 This should work in v0.2.0 which has the new `setThemeMode` function that will allow you to set any of the ThemeMode values. light, dark or system.

**Comment by bipinvaylu** [comment]
I am still getting theme persistence issue in version `0.2.2+2`. I am using `getThemeManager(context).setThemeMode(selectedThemeMode)` for changing theme once user select theme from list of three (System, Light and Dark) theme. Can you please let me know what is missing here from my end?

main.dart:
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FlutterStatusbarcolor.setStatusBarWhiteForeground(true);

  await Firebase.initializeApp();
  await ThemeManager.initialise();

  runApp(MultiProvider(
    providers: [
      // Provider needed by app
    ],
    child: MyApp(),
  ));
}

class MyApp extends StatelessWidget {
  MyApp();

  @override
  Widget build(BuildContext context) {
    return ThemeBuilder(
      defaultThemeMode: ThemeMode.system,
      darkTheme: darkTheme,
      lightTheme: lightTheme,
      statusBarColorBuilder: (theme) => theme.accentColor,
      themes: getThemes(),
      builder: (context, regularTheme, darkTheme, themeMode) {
        return LayoutBuilder(
            //return LayoutBuilder
            builder: (context, constraints) {
          return OrientationBuilder(
              //return OrientationBuilder
              builder: (context, orientation) {
            //initialize SizerUtil()
            SizerUtil().init(constraints, orientation);

            return ProgressDialog(
              orientation: ProgressOrientation.vertical,
              loadingText: "Please wait...",
              backgroundColor: Theme.of(context).backgroundColor,
              child: MaterialApp(
                title: "My App",
                theme: regularTheme,
                darkTheme: darkTheme,
                themeMode: themeMode,
                home: SplashScreen(),
              ),
            );
          });
        });
      },
    );
  }
}
```

setting_page.dart: 
```
// Calling this method when user selected any of theme from list of theme
void _updateSelectedThemeMode(ThemeMode selectedThemeMode) async {
    // Just gave it a try but no luck
    // getThemeManager(context).toggleDarkLightTheme();

    getThemeManager(context).setThemeMode(selectedThemeMode);
  }
```

@FilledStacks Guys do you have any idea what's going wrong here. I cross-verified implementation on [your blog](https://www.filledstacks.com/post/multiple-themes-in-flutter-dark-and-light-theme-flutter-stacked/) as well but no luck and unable to figure out exact source of issue.

**Comment by FilledStacks** [comment]
@bipinvaylu what problem are you having?

1. What do you want to happen?
2. What is happening at the moment?

**Comment by bipinvaylu** [comment]
@FilledStacks Thanks for quick response.
> 1. What do you want to happen?
- As per given details on pub.dev and checkout examples, I believe package should manage to save last selected theme mode when i set it using `getThemeManager(context).setThemeMode(selectedThemeMode)` method call.
> 2. What is happening at the moment?
- Right now, Seems like this package is not storing last selected theme mode. So always get System/Light theme mode which is my Android device theme as well.

themes.dart
```
List<ThemeData> getThemes() {
  return [lightTheme, darkTheme];
}
```
Let me know if you need anything else from me. I am having 2 themes only. Light and Dark.

**Comment by victorbalaban** [comment]
Hi @bipinvaylu 
I searched for this kind of thread, because I faced the same issue: the theme would not persist.

The issue can be solved like this:

1. create your service

`ThemeService _themeService = locator<ThemeService>();`
..

2. Use the `setThemeMode` function to persist the selected theme. I used dark and light themes.


```
switchTheme(){
    _themeService.toggleDarkLightTheme();
    _themeService.setThemeMode(_themeService.isDarkMode? ThemeManagerMode.dark : ThemeManagerMode.light);
}
```


Hope it helps,
Cheers!

**Comment by bipinvaylu** [comment]
Hey @victorbalaban Thanks for solution, I did give it a try but it still not working for me. Please find my code base here:

main.dart: where I am reading persisted theme
```
ThemeService _themeService = ThemeService.getInstance();
ThemeMode _themeMode = _themeService.isDarkMode? ThemeMode.dark : ThemeMode.light;

return ThemeBuilder(
          defaultThemeMode: _themeMode,
          darkTheme: darkTheme,
          lightTheme: lightTheme,
          ....);
```
- Getting _themeService null in main.dart only. 

settings_page.dart: where i am persisting theme selection
```
ThemeService _themeService = ThemeService.getInstance();
_themeService.toggleDarkLightTheme();
_themeService.setThemeMode(_themeService.isDarkMode? ThemeManagerMode.dark : ThemeManagerMode.light);
```

I am not sure how to locator would make difference here and had not used locator before. It would be great if you can help me out with bit more details or code sample. Thanks.

**Comment by mattrltrent** [comment]
@FilledStacks, having this same issue still. Using `getThemeManager(context).toggleDarkLightTheme();` and the theme (dark/light) is not persisting upon re-opening the app.

My `main.dart` looks as follows:

```
Widget build(BuildContext context) {
    return ThemeBuilder(
      // statusBarColorBuilder: (theme) => theme?.backgroundColor,
      defaultThemeMode: ThemeMode.light, // change to "ThemeMode.system" to get default system theme
      lightTheme: themesList[0],
      darkTheme: themesList[1],
      builder: (context, regularTheme, darkTheme, themeMode) => MaterialApp(
        title: "APP NAME",
        theme: regularTheme,
        darkTheme: darkTheme,
        themeMode: themeMode,
        debugShowCheckedModeBanner: false,
        useInheritedMediaQuery: true,
        locale: DevicePreview.locale(context),
        builder: DevicePreview.appBuilder,
        home: const Root(),
      ),
    );
  }
```

My themes.dart file looks like this:

```
List<ThemeData> themesList = [
  ThemeData(
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff333333),
      onPrimary: Colors.white,
      secondary: Color(0xffF6C0F6),
      onSecondary: Color(0xff333333),
      error: Color(0xffEB5353),
      onError: Colors.white,
      background: Colors.white,
      onBackground: Color(0xff595959),
      surface: Color(0xffEBEBEB),
      onSurface: Color(0xff595959),
    ),
  ),
  ThemeData(
    colorScheme: const ColorScheme(
        brightness: Brightness.dark,
        primary: Colors.yellow,
        onPrimary: Colors.orange,
        secondary: Colors.blue,
        onSecondary: Colors.green,
        error: Colors.pink,
        onError: Colors.white,
        background: Colors.indigo,
        onBackground: Colors.black,
        surface: Colors.orange,
        onSurface: Colors.cyanAccent),
  )
];
```

Any idea what's going on?
