### ISSUE TITLE
stacked_services - compile issue

### ISSUE THREAD

**Issue by volkangurol** [Stacked-Org/stacked#159]
Hi,

in stacked_services package -> navigation services

it uses get-3.80
defaultTransitionDuration prop name changed to  defaultDurationTransition

**Comment by FilledStacks** [comment]
Are you using stacked_services  0.5.4+3?

**Comment by ppgcharge** [comment]
> Are you using stacked_services 0.5.4+3?

same with 0.5.4+4

`Error: The getter 'defaultTransitionDuration' isn't defined for the class '_GetImpl'.
 - '_GetImpl' is from 'package:get/src/core/get_main.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/get-3.8.0/lib/src/core/get_main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'defaultTransitionDuration'.
        duration: duration ?? Get.defaultTransitionDuration,`
