### ISSUE TITLE
Force refresh of viewmodels? 

### ISSUE THREAD

**Issue by FickleLife** [Stacked-Org/stacked#160]
**EDIT**: See working example at https://github.com/FickleLife/stacked_vm_issue 

I have a List which I am loading from a graphql endpoint using v4.0.0:alpha.11 (but this also happened on all previous versions) of [flutter_graphql](https://github.com/zino-app/graphql-flutter). It's a global search with filters. All functionality seems to work well with Stacked, except for caching and it seems to point to stacked viewmodels retaining state when it shouldn't (but hey I could be wrong) - which is why I thought I'd ask the brains trust here before I quiz the flutter_graphql folks :)

Excuse the colour scheme, still testing and need to see where everything is rendered. 

When I search for "Apple" I get the correct results (makes a network call, no cache) Note the colour of the "pill" in the topmost item: 
![image](https://user-images.githubusercontent.com/844005/94378019-41ad4380-0169-11eb-9212-05d29f968274.png)

When I tick "Official Score" which removes items with a * after the number, it filters correctly (makes a network call, no cache)
![image](https://user-images.githubusercontent.com/844005/94378070-c13b1280-0169-11eb-8174-843d270dab76.png)

When I **untick** "Official Score" it correctly loads the previous results from the cache and correctly updates the text of the listitem, but as you can see the colour of the "pill" is retained, and also when you click on the top item it takes you to the previous result (Aeroplane jelly lite pineapple) that occupied that spot 
![image](https://user-images.githubusercontent.com/844005/94378152-6c4bcc00-016a-11eb-90a6-a12e36ab86f5.png)

When I turn off the cache which forces a network call all the time, it all works correctly - so this is a bit of a puzzling one. The tree of each list item looks like:
![image](https://user-images.githubusercontent.com/844005/94378203-ef6d2200-016a-11eb-9489-60b4ebb1a3b6.png)

There's a nested view/viewmodel `CircularPercent2` to render the score "pill". The colour of the pill relies on a colour service which provides colouring data for the entirety of the app.

What's even more puzzling is:
1) **text** is **correct** and that is in ListTileItemProduct2
2) **link** is **incorrect** and that is in ListTileItemProduct2
3) **Score** is **correct** and that is in ListTileItemProduct2 -> CircularPercent2
4) **Colour** is **incorrect** and that is provided by ListTileItemProduct2 -> CircularPercent2 -> (colour service)

So it doesn't seem to present a pattern - if it was just ListTileItemProduct2 that was working and child viewmodels weren't I would have somethign to work with. 

Ideally I'd like to keep local cache on and get the benefits of that. Any clues why loading from cache could cause viewmodels to not clear state/load fresh state vs an uncached call? 

EDIT: I've just changed the reference of the title of the item from `data.name` (data used in the view that was passed from the constructor) to `model.name` (data passed from view constructor to viewmodel and then returned from the viewmodel back to the view) an the title now doesn't update - so this points towards the views getting the data, but not passing the data on to the viewmodel.... this also is the case for nested views - e.g CircularPercent2 view data correctly updates the score, but the colour is in the viewmodel. So there's something up with views not passing data to viewmodels when the data returned is cached. 

Here's the code for completeness
```
ListTile(
                  title: Text(
                    model.name, //data.name,
                    style: Theme.of(context).textTheme.headline4,
                  ),
                  leading: Padding(
                    padding: const EdgeInsets.symmetric(vertical: 6),
                    child: CircularPercent2(
                      scoreData: data,
                    ),
                  ),
                  trailing: Icon(Ionicons.ios_arrow_forward),
                  onTap: () => model.navigate(),
                )
```

**Comment by FickleLife** [comment]
Since this was clear as mud, I've made a repo here with an example and a write up of what I am seeing. https://github.com/FickleLife/stacked_vm_issue

**Comment by FilledStacks** [comment]
@FickleLife wooohooooo! this was pretty interesting bug to solve. The bug in your Flutter code, not your logic. So what's happening is actually common in Flutter when it comes to lists. 

The widget tree is remembering the list items place and providing the same viewmodel as it had originally. Not only that it also takes every item that goes into index 0 and provides it with the same data that was enclosed on the **Construction** of the object. 

What I did was add print statements in:
1. HomeView: inside the itemBuilder
2. ListItem: inside the build function
3. Scorerview; inside the build function
4. ScorerViewModel: Inside the constructor
5. ScorerViewModel: inside the getColor function

Here is the logs for the first run from fresh start

```
I/flutter (11889): 1. title:No 5 score:100 index:0
I/flutter (11889): 2. title:No 5 score:100
I/flutter (11889): 3. title:No 5 score:100
I/flutter (11889): 4. title:No 5 score:100 - Construction
I/flutter (11889): 5. title:No 5 score:100
I/flutter (11889): 1. title:No 4 score:75 index:1
I/flutter (11889): 2. title:No 4 score:75
I/flutter (11889): 3. title:No 4 score:75
I/flutter (11889): 4. title:No 4 score:75 - Construction
I/flutter (11889): 5. title:No 4 score:75
I/flutter (11889): 1. title:No 3 score:50 index:2
I/flutter (11889): 2. title:No 3 score:50
I/flutter (11889): 3. title:No 3 score:50
I/flutter (11889): 4. title:No 3 score:50 - Construction
I/flutter (11889): 5. title:No 3 score:50
I/flutter (11889): 1. title:No 2 score:25 index:3
I/flutter (11889): 2. title:No 2 score:25
I/flutter (11889): 3. title:No 2 score:25
I/flutter (11889): 4. title:No 2 score:25 - Construction
I/flutter (11889): 5. title:No 2 score:25
I/flutter (11889): 1. title:No 1 score:0 index:4
I/flutter (11889): 2. title:No 1 score:0
I/flutter (11889): 3. title:No 1 score:0
I/flutter (11889): 4. title:No 1 score:0 - Construction
I/flutter (11889): 5. title:No 1 score:0
```

it all looks great. Numbers are in order and the construction of the ScorerModel happens on time with the correct data. Now look what happens when I add 1 value.

```
I/flutter (12012): 1. title:ig_hmgobnsljah_d[dwh score:48 index:0
I/flutter (12012): 2. title:ig_hmgobnsljah_d[dwh score:48
I/flutter (12012): 3. title:ig_hmgobnsljah_d[dwh score:48
I/flutter (12012): 5. title:No 5 score:100
I/flutter (12012): 1. title:No 5 score:100 index:1
I/flutter (12012): 2. title:No 5 score:100
I/flutter (12012): 3. title:No 5 score:100
I/flutter (12012): 5. title:No 4 score:75
I/flutter (12012): 1. title:No 4 score:75 index:2
I/flutter (12012): 2. title:No 4 score:75
I/flutter (12012): 3. title:No 4 score:75
I/flutter (12012): 5. title:No 3 score:50
I/flutter (12012): 1. title:No 3 score:50 index:3
I/flutter (12012): 2. title:No 3 score:50
I/flutter (12012): 3. title:No 3 score:50
I/flutter (12012): 5. title:No 2 score:25
I/flutter (12012): 1. title:No 2 score:25 index:4
I/flutter (12012): 2. title:No 2 score:25
I/flutter (12012): 3. title:No 2 score:25
I/flutter (12012): 5. title:No 1 score:0
I/flutter (12012): 1. title:No 1 score:0 index:5
I/flutter (12012): 2. title:No 1 score:0
I/flutter (12012): 3. title:No 1 score:0
I/flutter (12012): 4. title:No 1 score:0 - Construction
I/flutter (12012): 5. title:No 1 score:0
```

4 only happens **once** for the new value added. The list view (and Flutter awesomely optimised render tree) doesn't recognize that the widget has been changed so it didn't "reconstruct" it fully and provided it with the enclosed data that it was initially contructed with. This means that every new widget will be constructed with the value at list.length - 1 (the last list item).

To fix this you have to use a Key :) You HAVE to use a key for your List items especially if you're dynamically manipulating them like you are. Whether that's changing a color, showing an unread state etc. So a good habbit to form would be to pass in the key to your widget item and then set it to a unique value. The item title, or id or something. this fixes the example that you shared with me. 

The updated list item. Take note of key being passed to super

```dart
class ListItem extends StatelessWidget {
  final Thing data;
  ListItem({
    Key key,
    this.data,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    print('2. title:${data.title} score:${data.score}');
    // final do we get the latest data here?
    return ViewModelBuilder<ListItemModel>.reactive(
      builder: (context, model, child) => ListTile(
        title: Text(data.title),
        leading: Scorer(data: data),
      ),
      viewModelBuilder: () => ListItemModel(),
    );
  }
}
```

Item builder: Take note of using unique key.

```dart
ListView.builder(
          itemCount: model.listOfStuff.length,
          itemBuilder: (context, i) {
            var thingo = model.listOfStuff[i];
            print('1. title:${thingo.title} score:${thingo.score} index:$i ');
            return ListItem(
              key: Key(thingo.title),
              data: thingo,
            );
          },
    )
```

And that's it. all your cache induced stress released haha. Thanks again for the detailed issue. I had so much fun in my little break solving this.

**Comment by FilledStacks** [comment]
@FickleLife I hope that wasn't too late. To also add to the additional assumptions. Stacked will only cache ViewModels for the widget in the same way that stateless does. This is the "caching" code, which is to avoid rebuilding the ViewModel widget everytime it's removed and re-inserted into the tree in the case of a list scroll or something like that. 

```dart
  void initState() {
    super.initState();
    // We want to ensure that we only build the model if it hasn't been built yet.
    if (_model == null) {
      _createViewModel();
    }
    // Or if the user wants to create a new model whenever initState is fired
    else if (widget.createNewModelOnInsert) {
      _createViewModel();
    }
  }
```

**Comment by FickleLife** [comment]
Amazing @FilledStacks, thank you for the complete and detailed reply. I'll try it out in a few hours and close this issue.

**Comment by FickleLife** [comment]
Wonderful, it works as expected - Thanks for everything @FilledStacks!
