### ISSUE TITLE
How can I use SingleTickerProviderStateMixin with BaseViewModel

### ISSUE THREAD

**Issue by winsw-dev** [Stacked-Org/stacked#163]
I want to create animation controller in viewmodel and use vsync property which required SingleTickerProviderStateMixin so I tried 

class WorkGalleryViewModel extends BaseViewModel with SingleTickerProviderStateMixin{ }

and it said :
'SingleTickerProviderStateMixin<StatefulWidget>' can't be mixed onto 'BaseViewModel' because 'BaseViewModel' doesn't implement 'State<StatefulWidget>'.

and another question
How can I use initState() and  dispose() in viewmodel

Any suggestions would be appreciated

**Comment by SrikanthKoti** [comment]
Did you find the answer?

**Comment by FilledStacks** [comment]
ViewModels should have no UI code. You should do all UI code in the view.

**Comment by TechSatya** [comment]
Can someone please answer this? It's a bit urgent. your help is really appreciated!!
@winsw-dev @FilledStacks

**Comment by FilledStacks** [comment]
@TechSatya you should have no animation code in your viewmodel. There should be 0 UI related code in your ViewModel.

**Comment by TechSatya** [comment]
@FilledStacks can you please give a short snippet of the code or any reference on calling SingleTickerProviderStateMixin in View??

I didn't find any reference to using any controller in the docs!!

**Comment by isaacadariku** [comment]
> @FilledStacks can you please give a short snippet of the code or any reference on calling SingleTickerProviderStateMixin in View??
> 
> I didn't find any reference to using any controller in the docs!!

@TechSatya use HookWidget and you should be good to go.

Here is a snippet but you can get faster response on the [stacked community slack](https://join.slack.com/t/filledstacks/shared_invite/zt-1ntqu3xo2-jXjPS_TvEOl0MfWFkk~iOQ)
```
import 'package:flutter_hooks/flutter_hooks.dart';


class YourAnimationClass extends HookWidget {
  const YourAnimationClass({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final _tickerProvider = useSingleTickerProvider();
    final _animationController = useAnimationController(
      duration: const Duration(milliseconds: 300),
      vsync: _tickerProvider,
    );

    return ViewModelBuilder<YourAnimationClassViewModel>.reactive(
      viewModelBuilder: () => YourAnimationClassViewModel(),
      builder: (
        BuildContext context,
        BookingInvitePlayersViewModel model,
        Widget? child,
      ) {
        return AnimatedBuilder(
          animation: _animationController,
          builder: (context, child) {
            return Container(
              height: _animationController.value,
              width: _animationController.value,
              child: child,
            );
          },
          child: const Text('Hello World'),
        );
      },
    );
  }
}
```
