### ISSUE TITLE
stacked_themes 0.2.0 - error : The method 'selectThemeAtIndex' was called on null

### ISSUE THREAD

**Issue by waheed11** [Stacked-Org/stacked#164]
Hello all @FilledStacks, I tried to use stacked_themes 0.2.0
But I get an error:  Unhandled Exception: NoSuchMethodError: The method 'selectThemeAtIndex' was called on null
All I want to do is to switch between two themes from a Toggle Button, use "toggle_switch" package.
So, I simply call the method from the View:
```
onToggle: (index) {
  model.toggleBetweenThemes(index);
```

Then in my my ViewModel, I wrote this method:
```
void  toggleBetweenThemes(int index) {
   _themeService.selectThemeAtIndex(index);
}
```
I did the registration for "ThemeService and add the following line in my ViewModel:
final _themeService = locator<ThemeService>();

Here is my code in ThirdPartyServicesModule :
```
abstract class ThirdPartyServicesModule {
  @lazySingleton
  NavigationService get navigationService;
  @lazySingleton
  DialogService get dialogService;
  @singleton
  ThemeService get themeService;
  @singleton
  LocalizeAndTranslate get localizeService;
}
```

Here the generated configuration file:
```
GetIt $initGetIt(
  GetIt get, {
  String environment,
  EnvironmentFilter environmentFilter,
}) {
  final gh = GetItHelper(get, environment, environmentFilter);
  final thirdPartyServicesModule = _$ThirdPartyServicesModule();
  gh.lazySingleton<DialogService>(() => thirdPartyServicesModule.dialogService);
  gh.lazySingleton<NavigationService>(
      () => thirdPartyServicesModule.navigationService);
  // Eager singletons must be registered in the right order
  gh.singleton<LocalizeAndTranslate>(thirdPartyServicesModule.localizeService);
  gh.singleton<ThemeService>(thirdPartyServicesModule.themeService);
  return get;
}
class _$ThirdPartyServicesModule extends ThirdPartyServicesModule {
  @override
  DialogService get dialogService => DialogService();
  @override
  LocalizeAndTranslate get localizeService => LocalizeAndTranslate();
  @override
  NavigationService get navigationService => NavigationService();
  @override
  ThemeService get themeService => ThemeService();
}
```

And here is the code in the main (I use another serivced from a package for locaization my app)  :
```
Future  main() async{
  configureDependencies();
  WidgetsFlutterBinding.ensureInitialized();
  await ThemeManager.initialise();
  await translator.init(
    localeDefault: LocalizationDefaultType.device,
    languagesList: <String>['ar', 'en'],
    assetsDirectory: 'assets/lang/',
    apiKeyGoogle: '<Key>', // NOT YET TESTED
  ); // intialize
  runApp(LocalizedApp(child: MyApp()));
}
```
---------------------------------------------------------------
Note that:  below dependencies and dev_dependencies in yaml file:
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flare_flutter: ^2.0.6
  stacked: ^1.7.6
  http: ^0.12.2
  stacked_hooks: ^0.1.3
  stacked_services: ^0.5.4+4
  auto_route:
  get_it:
  injectable:
  flutter_hooks:
  observable_ish:
  toggle_switch: "^0.1.8"
  auto_size_text: ^2.1.0
  stacked_themes:
  localize_and_translate: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator:
  injectable_generator:

**Comment by FilledStacks** [comment]
It seems like you're trying to use get_it without knowing how it works? To get a registered service you should call the generic function and pass the type to it.

```dart
var service = locator<MyService>();

// not

var service = locator();
```

Using the functionality above you're using the call override in the locator which does a type retrieval.

**Comment by waheed11** [comment]
Below is what I already did:
 final  _themeService = locator<ThemeService>();

void  toggleBetweenThemes(int index) {
   _themeService.selectThemeAtIndex(index);
}

**Comment by waheed11** [comment]
```
Below is what I already did:
final  _themeService = locator<ThemeService>();
```

And then use the below method:
```
void  toggleBetweenThemes(int index) {
   _themeService.selectThemeAtIndex(index);
}
```

**Comment by FilledStacks** [comment]
Your problem is you're calling selectThemeAtIndex on null. It doesn't have much to do with the ThemeService. You're calling a function on a null value. You have to figure out why it's null.

**Comment by naamapps** [comment]
@waheed11 
I think you should register the theme service like this:
  ```
@lazySingleton
  ThemeService get themeService => ThemeService.getInstance();
```

**Comment by waheed11** [comment]
@naamapps 
Thank you so much, this solved the problem. 
My mistake is that I register theme service as follows: 
```
  @lazySingleton
  ThemeService get themeService;
```
