### ISSUE TITLE
Changing dark mode from the settings doesn't change the status bar color

### ISSUE THREAD

**Issue by abdul10ahad** [Stacked-Org/stacked#168]
when toggling dark mode settings in iOS and when theme mode is set to thememode.settings the  background color is changing according to dark and light mode  but status bar color doesn't change . only when we tap settings button that calls setthememode is when the status bar color is changing . is there a way to dynamically change status bar when we toggle dark mode from settings 
![Simulator Screen Shot - iPhone 8 - 2020-10-12 at 00 18 14](https://user-images.githubusercontent.com/28492677/95688016-8c769300-0c20-11eb-90d1-02e1fd7b8c09.png)

**Comment by FilledStacks** [comment]
mmmmmmmm, i was wondering when this will come up. I will most likely have to re-apply the appropriate theme when the application gets back into the foreground. It's not implemented yet but I'll update this issue and i'll work on it.

**Comment by abdul10ahad** [comment]
I've actually done a pr so if you can look at it that would be great !  also if you don't find it the best way i please explain me the reason so I can improve my future prs

**Comment by FilledStacks** [comment]
Thanks for the PR. I forgot to close this afterwards. It's working well :)
