### ISSUE TITLE
StreamViewModel Widget Updates Broken after 1.2.4 update

### ISSUE THREAD

**Issue by thedigitalpro** [Stacked-Org/stacked#17]
Hi. I seem to have hit a problem with the StreamViewModel between the 1.2.4 and 1.3.0 update. 

Quite simply I have a simple widget initiated like the usual from the docs ViewModelBuilder<MyViewModel>.reactive. 

On my ViewModel I know I get data back within:

`@override
  void onData(List<Offer> data) {
    print(data.length.toString());
  }
`

Within my widget I am simply doing this:

`child: model.data != null ? Container( etc etc etc) : SizedBox()`

But the widget is not rebuilt with the data. This was and still working perfectly in 1.2.4. Am I missing something here which I have not interpreted from the docs?

Thank you

**Comment by thedigitalpro** [comment]
Just looking at the source code, should this not be the other way around within stream.listen inside class StreamData<T>?

notifyListeners();
onData(_data);

**Comment by FilledStacks** [comment]
Mmm, that's weird. Is the example still working? I know it was working last I checked.

The order of those two calls won't make a difference. I wanted it to be called after the view is updated so you can handle additional actions afterwards. 

Try run the example and see if that works. I hope i didn't break something. I'm not at my desk today.

**Comment by thedigitalpro** [comment]
Hey Dane. Just tried the sample and yes you have the same problem. Instantly the screen does not get the value of the stream. Simply perform a hot reload restores the epoch in seconds. Something is not right.

**Comment by thedigitalpro** [comment]
Just want to add that if you add notifyListeners() to the onData method within the viewmodel it works as required.

**Comment by FilledStacks** [comment]
Okay. I'll  swap those two around. The normal data should be fine but it makes sense to be able to use the data and then automatically have a notifyListeners call happen.

**Comment by FilledStacks** [comment]
I'll get to my desk quickly and publish an update. The example only updates after a few seconds that's  how the stream is built. I'll check again. my tests still pass so i know it does what it's  supposed to do

**Comment by FilledStacks** [comment]
@thedigitalpro it was definitely broken. I'm reverting back to my old implementation

**Comment by FilledStacks** [comment]
@thedigitalpro Pushed v 1.3.2 update in your pubspec to ^1.3.2 and it should be working fine now. Thanks for letting me know about this. It was a PR that I merged in that caused it to break. I think the unit tests that came with the PR was faulty as well. I'll double check tomorrow and fix up everything the PR touched. 

Thanks again
