### ISSUE TITLE
possibility of adding multiple set busy instances 

### ISSUE THREAD

**Issue by parth181195** [Stacked-Org/stacked#173]
hi, 
can we add support for adding multiple set busy instances to track multiple request and async task  states. it might be a good adition.

**Comment by cyrildewit** [comment]
Hi @parth181195 ,

Isn't this already available? See https://github.com/FilledStacks/stacked/tree/master/packages/stacked#baseviewmodel-functionality.

**Comment by parth181195** [comment]
It's there but I guess it's like u set bussy state for whole viewmodel so for a page  where we have to trake states for multiple http calls and show diffrent behaviour with different widgets this can be use full

**Comment by cyrildewit** [comment]
I haven't used futures yet, so this code is more like an example of how to set up the busy functionality for multiple objects.

```dart
import 'package:http/http.dart' as http;

class YourViewModel extends BaseViewModel {
    List<User> _users;
    List<User> get users => _users;

    List<Post> _posts;
    List<Post> get posts => _posts;

    Future fetchUsers() async {
        setBusyForObject(_users, true);
        final response = await http.get('https://jsonplaceholder.typicode.com/users');
        setBusyForObject(_users, false);

        if (response.statusCode == 200) {
            return User.fromJson(jsonDecode(response.body));
        } else {
            throw Exception('Failed to load users');
        }
    }

    Future fetchPosts() async {
        setBusyForObject(_posts, true);
        final response = await http.get('https://jsonplaceholder.typicode.com/posts');
        setBusyForObject(_posts, false);

        if (response.statusCode == 200) {
            return Post.fromJson(jsonDecode(response.body));
        } else {
            throw Exception('Failed to load posts');
        }
    }
}
```

```dart
Container(
    child: model.busy(model.users)
        ? Text("Fetching users.")
        : Text("Users has been fetched.")
);
```

```dart
Container(
    child: model.busy(model.posts)
        ? Text("Fetching posts.")
        : Text("Postes has been fetched.")
);
```

I didn't have the time to test it yet, but I thought sharing my idea now could help you get further.

**Comment by FilledStacks** [comment]
@cyrildewit is correct. You use the setBusyForObject function call for the functionality you're using. If you read in the package repo is also says to use a constant value and not a dynamicly calculated value like an object. The reason for the is because the busy function uses the hashCode, which if dynamically calculated can change. 

I usually create a key for the busy state.

```dart
const String FetchLocationBusyKey = 'location-fetch-key';

// Then set it
setBusyForObject(FetchLocationBusyKey , true);

// And use in the UI
model.busy(FetchLocationBusyKey );

```
