### ISSUE TITLE
Where to store app specific data that needs to used throughout the app

### ISSUE THREAD

**Issue by krishnakumarcn** [Stacked-Org/stacked#174]
Hi Dane,

So recently I start exploring the stacked architecture and one doubt I had is that where should I store the app-specific data like darkModeOn, etc.

Should I use it as a service and shared with different view models per screen?

Another options is to use a Provider over material app and then I can access it anywhere (for setting dark mode on and off from inside screens etc.). But will that go away from the MVVM concepts?

**Comment by FilledStacks** [comment]
@krishnakumarcn that sounds like the job of a service.

**Comment by krishnakumarcn** [comment]
Thanks, Dane.
I implemented it as a service so that I don't have to mix and match different styles.
