### ISSUE TITLE
stacked_themes: Flicker issue while launching App from background

### ISSUE THREAD

**Issue by vinoopks** [Stacked-Org/stacked#175]
Thanks for this awesome package.
When using stacked themes, there is a minor flicker issue, while launching the app from the background. I guess this is happening when we load  theme properties from shared_preferences. 
Is there any way, we can fetch these values before rendering so as to avoid flickering of the screen?

**Comment by FilledStacks** [comment]
@vinoopks I haven't seen this. Does it happen in release mode as well? Everything is done before the app starts up.
