### ISSUE TITLE
getParentViewModel throwing exception when accessed from child view

### ISSUE THREAD

**Issue by geiziry** [Stacked-Org/stacked#176]
when tried to access parent viewmodel using getParentViewModel from the BaseViewwModel,
got an exception.

`debugIsInInheritedProviderUpdate': Tried to listen to a value exposed with provider, from outside of the widget tree.`

as of this issue 
#https://github.com/rrousselGit/provider/issues/313

had to add `listen: false` to get it fixed

**Comment by FilledStacks** [comment]
Are you sure the provider falls under the same tree?

**Comment by geiziry** [comment]
I was trying to access viewmodel of a view with ListView from viewmodel of ListTile.
please, check the test project in this repo
[getParentViewModel](https://github.com/geiziry/testFlutter.git)

**Comment by FilledStacks** [comment]
You're not supplying your viewmodel anywhere in that example. Please see how to use the ViewModelBuilder widget and the re-write your code to use that. 

You need to use the ViewModelBuilder.reactive / non-reactive constructor to supply the viewmodel

**Comment by geiziry** [comment]
I'm using it as in [here](https://pub.dev/packages/stacked#viewmodelbuilderwidget).
and it's working fine, but the problem is when I try to get the parentViewModel in [here](https://github.com/geiziry/testFlutter/blob/7eb7ebd00d73eb99fa9907b6df79fcdb58536e43/lib/listtile.dart#L8)
