### ISSUE TITLE
How to Update initialLength from TabController

### ISSUE THREAD

**Issue by nurdiana** [Stacked-Org/stacked#181]
I'm doing a dynamic tab, and the length of tab can be change. I'm using useTabController and define the `initialLengh` from tabs.length. Is it possible to update the `initialLength` when `tabs.length` changed?

```
Widget buildViewModelWidget(
      BuildContext context, SearchResultViewModel model) {
    final TabController _tabController = useTabController(
      initialLength: model.tabs.length,
    );
    final ScrollController _scrollController = useScrollController();
    print("model.tabs.length ${model.tabs.length}");
    print("_tabController.length ${_tabController.length}");
```

**Comment by FilledStacks** [comment]
Hey @nurdiana I haven't used that hook before. I don't know if it's possible, you can look at the source code to see if it's possible in flutter_hooks.

**Comment by FilledStacks** [comment]
You can check the [flutter hooks](https://pub.dev/packages/flutter_hooks) package to find out how to use the hooks
