### ISSUE TITLE
getParentViewModel throwing exception

### ISSUE THREAD

**Issue by geiziry** [Stacked-Org/stacked#189]
#176 
I'm using it as in [here](https://pub.dev/packages/stacked#viewmodelbuilderwidget).
and it's working fine, but the problem is when I try to get the parentViewModel in [here](https://github.com/geiziry/testFlutter/blob/7eb7ebd00d73eb99fa9907b6df79fcdb58536e43/lib/listtile.dart#L8)

**Comment by FilledStacks** [comment]
hey, that won't work in a ViewModel since it's not in the widget tree. In addition to that you shouldn't have access to viewmodels from viewmodels.

**Comment by geiziry** [comment]
Ok, thanks.
