### ISSUE TITLE
About 3rd Party Integrations

### ISSUE THREAD

**Issue by necatisozer** [Stacked-Org/stacked#19]
IMO, 3rd party integrations like [flutter_hooks](https://github.com/rrousselGit/flutter_hooks) should be optional and be provided via different packages. Otherwise the dependency stack of the core package can be huge and hard to maintain.

**Comment by FilledStacks** [comment]
totally agree. I will be moving hooks into its own package.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by FilledStacks** [comment]
Removed the Flutter Hooks dependency in favor of a [separate package](https://github.com/FilledStacks/stacked_hooks)

**Comment by necatisozer** [comment]
Nice job @FilledStacks. How about keeping all these packages in the same repository like [bloc library](https://github.com/felangel/bloc)?

**Comment by FilledStacks** [comment]
Also not a bad idea. Should be able to do that in about 12 hours after all the other things on my list are done.
