### ISSUE TITLE
MultipleStreamViewModel doesn't work as expected

### ISSUE THREAD

**Issue by ghost** [Stacked-Org/stacked#190]
Hi,

It seems there is an issue with MultipleStreamViewModel implementation. 

Using the example and changing  streams with firebase streams is causing this error:

"Background concurrent copying GC freed 153040(3MB) AllocSpace objects, 12(4MB) LOS objects, 49% free, 4MB/8MB, paused 819us total 173.633ms"

There is a stackoverflow post about this info [here](https://stackoverflow.com/questions/54117311/background-concurrent-copying-gc-freed-flutter).

The issue here is the app is consuming more memory until the app is unresponsive.

This type of issue is not happening when using StreamViewModel.

Regards,

**Comment by FilledStacks** [comment]
@eherediadev could you make a repo that reproduces the error. It might be the unsubscribe functionality in the stacked package. how exactly is the multiple stream model being used.

**Comment by ghost** [comment]
Hi @FilledStacks ,

Here's the repo: [streams_ex](https://github.com/eherediadev/streams_ex).

### **Service**

```dart

class FirestoreService {
  final CollectionReference _streamOneRef =
      FirebaseFirestore.instance.collection("StreamOne");

  final CollectionReference _streamTwoRef =
      FirebaseFirestore.instance.collection("StreamTwo");

  // Stream Controllers
  StreamController<List<Map<String, dynamic>>> _oneController =
      new BehaviorSubject<List<Map<String, dynamic>>>();
  StreamController<List<Map<String, dynamic>>> _twoController =
      new BehaviorSubject<List<Map<String, dynamic>>>();

  // Streams
  Stream<List<Map<String, dynamic>>> listenToStreamOne() {
    _streamOneRef.snapshots().listen((eventsSnapshot) {
      List<Map<String, dynamic>> events = eventsSnapshot.docs.map((event) {
        return event.data();
      }).toList();
      _oneController.add(events);
    });
    return _oneController.stream;
  }

  Stream<List<Map<String, dynamic>>> listenToStreamTwo() {
    _streamOneRef.snapshots().listen((eventsSnapshot) {
      List<Map<String, dynamic>> events = eventsSnapshot.docs.map((event) {
        return event.data();
      }).toList();
      _oneController.add(events);
    });
    return _oneController.stream;
  }
}

```

### **ViewModel**

```dart
const _streamOneKey = "stream-one";
const _streamTwoKey = "stream-two";

class HomeViewModel extends MultipleStreamViewModel {
  final FirestoreService _firestoreService = locator<FirestoreService>();

  List<Map<String, dynamic>> get streamOneData => dataMap[_streamOneKey];
  bool get hasStreamOneData => dataReady(_streamOneKey);

  List<Map<String, dynamic>> get streamTwoData => dataMap[_streamTwoKey];
  bool get hasStreamTwoData => dataReady(_streamOneKey);

  @override
  Map<String, StreamData> get streamsMap => {
        _streamOneKey: StreamData<List<Map<String, dynamic>>>(
            _firestoreService.listenToStreamOne()),
        _streamTwoKey: StreamData<List<Map<String, dynamic>>>(
            _firestoreService.listenToStreamTwo()),
      };
}

```

### **View**

```dart
class HomeView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder<HomeViewModel>.reactive(
      viewModelBuilder: () => HomeViewModel(),
      builder: (context, model, _) => Scaffold(
        appBar: AppBar(
          title: Text("Streams Example"),
        ),
        body: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Expanded(
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  model.hasStreamOneData
                      ? ListView.builder(
                          scrollDirection: Axis.horizontal,
                          shrinkWrap: true,
                          itemCount: model.streamOneData.length,
                          itemBuilder: (context, index) => Container(
                            height: 50,
                            width: 150,
                            color: Colors.green,
                            padding: EdgeInsets.all(10),
                            child: Text("Data One"),
                          ),
                        )
                      : Container(),
                ],
              ),
            ),
            SizedBox(height: 20),
            Expanded(
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  model.hasStreamTwoData
                      ? ListView.builder(
                          scrollDirection: Axis.horizontal,
                          shrinkWrap: true,
                          itemCount: model.streamTwoData.length,
                          itemBuilder: (context, index) => Container(
                            height: 50,
                            width: 150,
                            color: Colors.yellow,
                            padding: EdgeInsets.all(10),
                            child: Text("Data Two"),
                          ),
                        )
                      : Container(
                          height: 50,
                        ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

### Error:

![image](https://user-images.githubusercontent.com/58760422/102104006-10592100-3e04-11eb-8290-2a5e1522f3f5.png)



Regards,

**Comment by FilledStacks** [comment]
@eherediadev and you just show the view and then update the documents that it's listening to?

**Comment by ghost** [comment]
@FilledStacks, I'm only showing the view without updating nor adding documents. Having this issue and trying to update or create a document won't work (the view becomes unresponsive).

**Comment by ghost** [comment]
Hey @FilledStacks , did you have time to check this behavior?

**Comment by FilledStacks** [comment]
@eherediadev I haven't. I'm focusing on open source issues today so i'll look at it and see what's happening.

**Comment by FilledStacks** [comment]
@eherediadev this is fixed in 1.7.7. Please check if it works for you and let me know. I'll leave this open for you to close if it works. 

As an extra note, keep in mind if you want your "special viewmodels" to only initialise once then you can always pass 

```dart
initialiseSpecialViewModelsOnce: true
```
to your ViewModelBuilder cosntructor. That wouldn't have fixed this problem but it can cause similar problems like when a list item is a StreamViewmodel. As it scrolls in and out of the view it migh initialise everytime and continuously request the stream snapshots to listen.

**Comment by FilledStacks** [comment]
Also thank you for taking the time and the effort to create the sample repo. It helps so so much, especially when there's limited time to work on a problem. I appreciate it.

**Comment by ghost** [comment]
@FilledStacks no problem at all. Thank you for this awesome project.

**Comment by ghost** [comment]
> 
> 
> @eherediadev this is fixed in 1.7.7. Please check if it works for you and let me know. I'll leave this open for you to close if it works.
> 
> As an extra note, keep in mind if you want your "special viewmodels" to only initialise once then you can always pass
> 
> ```dart
> initialiseSpecialViewModelsOnce: true
> ```
> 
> to your ViewModelBuilder cosntructor. That wouldn't have fixed this problem but it can cause similar problems like when a list item is a StreamViewmodel. As it scrolls in and out of the view it migh initialise everytime and continuously request the stream snapshots to listen.

@FilledStacks do we need to declare the viewmodel as a singleton to use `initialiseSpecialViewModelsOnce`?

**Comment by FilledStacks** [comment]
@eherediadev no. It's not required but it works better that way. But also it's not required for this fix. The code you sent should just work without putting that property there. I tested it in the repo that you sent me.

**Comment by ghost** [comment]
@FilledStacks nice. I tried it out (as-it) and everything went smoothly.  

Just to follow-up on this, why would declare the ViewModel as a singleton work better? 

Regards,

**Comment by alvinvin00** [comment]
> Just to follow-up on this, why would declare the ViewModel as a singleton work better?

I assume that with Singleton, we can assure that only one instance of each ViewModel is created and thus it won't create more instances of same thing over and over until our RAM sucked dry cmiiw
