### ISSUE TITLE
Not able to navigate using navigator service

### ISSUE THREAD

**Issue by charantft** [Stacked-Org/stacked#194]
Unhandled Exception: You are trying to use contextless navigation without
      a GetMaterialApp or Get.key.
      If you are testing your app, you can use:
      [Get.testMode = true], or if you are running your app on
      a physical device or emulator, you must exchange your [MaterialApp]
      for a [GetMaterialApp].

```
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'locator.config.dart';

final locator = GetIt.instance;

@InjectableInit()
void setupLocator() => $initGetIt(locator);
```

```
@AdaptiveAutoRouter(
    routes: <AutoRoute>[
      AutoRoute(page: SplashView, initial: true),
      AutoRoute(page: LanguageView),
    ]
  )
  class $Router{}
```

```
void main() {
  setupLocator();
  runApp(MyApp());
}


class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      navigatorKey: locator<NavigationService>().navigatorKey,
      home: SizedBox(),
      builder: ExtendedNavigator.builder<route.Router>(
        initialRoute: route.Routes.splashView,
        router: route.Router(),
        builder: (context, extendedNav) => Theme(
            data: appTheme(),
            child: extendedNav),
      ),
    );

  }
}
```

```
class SplashViewModel extends BaseViewModel{
  final _navigationService = locator<NavigationService>();

  Future initialise() async {
    new Future.delayed(const Duration(seconds: 3), () async {
      await _navigationService.pushNamedAndRemoveUntil(Routes.languageView);
    });
  }
}
```

```
import 'package:injectable/injectable.dart';
import 'package:stacked_services/stacked_services.dart';
@module
abstract class ThirdPartyServiceModule{
  @lazySingleton
  NavigationService get navService;
}
```

**Comment by SrikanthKoti** [comment]
you need to call onGenerateRoute 
`onGenerateRoute: auto_router.Router().onGenerateRoute,`

for example :
`void main() async {
  setupLocator();
  // setupDialogUi();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Git Comment',
      initialRoute: auto_router.Routes.homeView,
      onGenerateRoute: auto_router.Router().onGenerateRoute, // this line is needed

      navigatorKey: locator<NavigationService>().navigatorKey,
    );
  }
}`

**Comment by SrikanthKoti** [comment]
You need to call onGenerateRoute first. in your MaterialApp

`onGenerateRoute: auto_router.Router().onGenerateRoute`

My Code:

```
void main() async {
  setupLocator();
  runApp(MyApp());
}
```

```
class MyApp extends StatelessWidget {
  @override  
  Widget build(BuildContext context) {  
      return MaterialApp(  
      debugShowCheckedModeBanner: false,  
      title: 'Dj Jag',
      home: LoginView(),
      initialRoute: auto_router.Routes.homeView,
      onGenerateRoute: auto_router.Router().onGenerateRoute, // this line is required 
      navigatorKey: locator<NavigationService>().navigatorKey,
      );
   }
 }
```

@charantft

**Comment by charantft** [comment]
@SrikanthKoti 
Added onGenerateRoute to the main file, but there's no use

**Comment by SrikanthKoti** [comment]
> @SrikanthKoti
> Added onGenerateRoute to the main file, but there's no use

I had the same error, for me it solved the issue.... 
Is It showing the same error now ?

**Comment by FilledStacks** [comment]
Is this still a problem?

**Comment by charantft** [comment]
@FilledStacks Yes, still getting the issue

**Comment by FilledStacks** [comment]
@charantft are there any awaits in your setupLocator function?

**Comment by sebastianbuechler** [comment]
@FilledStacks I have the same problem and no, there are not any awaits in the setupLocator function.

**Comment by FilledStacks** [comment]
@sebastianbuechler this usually happens if you try to navigate before the navigation service is setup or before the locator registrations has completed. Can you paste your locator code below please

**Comment by dashan11** [comment]
I debug the project:  https://github.com/murilosandiego/delivery-app-getx.git
same problem.

>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 3.5)

> I/flutter (17710): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17710): The following message was thrown building GetMaterialApp:
I/flutter (17710): You are trying to use contextless navigation without
I/flutter (17710):       a GetMaterialApp or Get.key.
I/flutter (17710):       If you are testing your app, you can use:
I/flutter (17710):       [Get.testMode = true], or if you are running your app on
I/flutter (17710):       a physical device or emulator, you must exchange your [MaterialApp]
I/flutter (17710):       for a [GetMaterialApp].
I/flutter (17710): The relevant error-causing widget was:
I/flutter (17710):   GetMaterialApp file:///D:/src/delivery-app-getx/app/lib/main.dart:26:12
I/flutter (17710): When the exception was thrown, this was the stack:
I/flutter (17710): #0      GetNavigation.global (package:get/get_navigation/src/extension_navigation.dart:1046:7)
I/flutter (17710): #1      GetNavigation.toNamed (package:get/get_navigation/src/extension_navigation.dart:571:12)
I/flutter (17710): #2      AuthStore.fireRoute (package:delivery_app_getx/core/stores/auth_store.dart:37:11)
I/flutter (17710): #3      ever.<anonymous closure> (package:get/get_rx/src/rx_workers/rx_workers.dart:69:44)
I/flutter (17710): #4      GetStream._notifyData (package:get/get_rx/src/rx_stream/get_stream.dart:47:21)
I/flutter (17710): #5      GetStream.add (package:get/get_rx/src/rx_stream/get_stream.dart:97:5)
I/flutter (17710): #6      RxObjectMixin.value= (package:get/get_rx/src/rx_types/rx_core/rx_impl.dart:101:13)
I/flutter (17710): #7      AuthStore.onInit (package:delivery_app_getx/core/stores/auth_store.dart:31:16)
I/flutter (17710): #8      GetLifeCycleBase._onStart (package:get/get_instance/src/lifecycle.dart:66:5)
I/flutter (17710): #9      _InternalFinalCallback.call (package:get/get_instance/src/lifecycle.dart:12:25)
I/flutter (17710): #10     GetInstance._startController (package:get/get_instance/src/get_instance.dart:290:18)
I/flutter (17710): #11     GetInstance._initDependencies (package:get/get_instance/src/get_instance.dart:244:11)
I/flutter (17710): #12     GetInstance.find (package:get/get_instance/src/get_instance.dart:334:17)
I/flutter (17710): #13     GetInstance.put (package:get/get_instance/src/get_instance.dart:103:12)
I/flutter (17710): #14     Inst.put (package:get/get_instance/src/extension_instance.dart:90:21)
I/flutter (17710): #15     InitialBinding.dependencies (package:delivery_app_getx/core/routes/bindings/initial_binding.dart:14:9)
I/flutter (17710): #16     GetMaterialApp.build.<anonymous closure> (package:get/get_navigation/src/root/get_material_app.dart:229:25)
I/flutter (17710): #17     _GetBuilderState.initState (package:get/get_state_manager/src/simple/get_state.dart:124:23)
I/flutter (17710): #18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
I/flutter (17710): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
I/flutter (17710): ...     Normal element mounting (13 frames)
I/flutter (17710): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (17710): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
I/flutter (17710): #34     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1252:16)
I/flutter (17710): #35     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1223:5)
I/flutter (17710): #36     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1165:17)
I/flutter (17710): #37     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2683:19)
I/flutter (17710): #38     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1164:13)
I/flutter (17710): #39     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:974:7)
I/flutter (17710): #40     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:955:7)
I/flutter (17710): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

**Comment by FilledStacks** [comment]
@dashan11 I have no idea what's happening. It's working when setting up with a brand new project. If you can provide me a sample where it's happening using the navigation service then please upload that to git and provide me with a link here.

**Comment by ppoza** [comment]
@sebastianbuechler @FilledStacks  @dashan11

I had started a new project and I had the same problem.

I added the navigatorKey: StackedService.navigatorKey to my ExtendedNavigator and navigation started to work. 

I hope this new line will not bring me future problems.

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      builder: ExtendedNavigator(
        router: router.Router(),
        initialRoute: router.Routes.startupView,
        navigatorKey: StackedService.navigatorKey,
     ),
    );
  }
}
```

**Comment by charantft** [comment]
@FilledStacks Is the above solution or workaround given by @ppoza correct? can we go ahead with it?

**Comment by FilledStacks** [comment]
@charantft yes, if you're using the extended navigator you can pass the key into that instead. That will work just fine
