### ISSUE TITLE
Not sure if a bug or bad use, Future build does not cause child views to rebuild when data is ready..

### ISSUE THREAD

**Issue by bdairy** [Stacked-Org/stacked#196]
Hello there,
I have. a FutureBased view model that eventually shows a map... with list. of markers,, child BaseView model is a map that generates markers when receiving data in widget vida constructor.

Basically on parent view 

` model.isBusy ?    NearbyMapView(rests:  []) :  NearbyMapView(rests:  model.data.hits),`

and the child view onmodalready function creates markers for the map when receiving the data..

` onModelReady: (model) => model.setMarkers(rests)`

the setMarkers functions basically converts the rests object to markers and notify listeners,,

But because the view is rendered already,, it does not fire again.. so it only takes the firs init which has an empty array,, once the data is received from the parent view ,, it does not rebuild the child view..

It works only If i used a different widget like this 
` model.isBusy ?    Container() :  NearbyMapView(rests:  model.data.hits),`

But that is not how I want it to look like..

any help.. thanks.

**Comment by FilledStacks** [comment]
Hey @bdairy this is a common Flutter problem. Doesn't have anything to do with stacked :) 

Pass in a unique key to each of the constructors. Flutter doesn't know that it's a different widget so it re-uses the same one. That's the default behaviour to ensure a performant build tree. To tell flutter it's a "different widget" or the same widget with different data pass in a key that's different for each of the widgets. 

```
model.isBusy ? NearbyMapView(key: Key('empty'), rests: []) : NearbyMapView(key: Key('not-empty'), rests: model.data.hits),
```

**Comment by bdairy** [comment]
@FilledStacks  thanks for the. reply,, It served the purpose,, but that opens another question.. how can I run a function in the View model,  from another widget.. 
Take this example:

1. ParentView init.
2. Child View loads with empty data
3. Parent view receives data from Future
4. Child view manipulate the received data without rebuild the whole tree,,  basically just add markers to the map..

In may case :
1. Parent is a FutureViewModel ,, that has a futureToRun.
2. While module.isBusy I want to show an empty map
3. Once future is ready and busy is false, I want to run a function on the child map to add markers to the map,, without re-initing the map.
4. Normally I would use `didUpdateWidget(covariant NearbyMapView oldWidget)` But from their I cannot access the model function that builds the markers,, I don't have access to the model outside the viewmodel builder, I  solved that by changing the. child to a lazysinglton and this way I can access from everywhere,, But I am  not sure if that is the correct behavior..plus now this viewmodel cannot be disposed,, I guess.. 

**I appreciate your patience,, I really like your package and I want it to rely on it,, That is why I am bugging u with questions**.. 


Check the attached video,, you will see how the screen flicks... that what I will have using the key to re-render the widget,, the other solution is with get it,, which might memory leak my vm..

https://user-images.githubusercontent.com/10797121/104618471-6c2df880-5695-11eb-8acf-b74f2892c7f3.mov

**Comment by FilledStacks** [comment]
Hey, I interact from ViewModel to ViewModel through streams on a service. I add a stream on the service, I subscribe to it in the Viewmodel that I want to react to something. Then i put a value on that stream when I want the viewmodel to react. 

I don't know if that'll help with the flicker but that's how I "call" a function in a different viewmodel. It's not actually calling it, it's just reacting to an event put on a stream that was triggered by another viewmodel.

**Comment by bdairy** [comment]
So Basically a side service,, with a stream that all vms will listen to,, a good approach,, Basically looks like what a provider would do,, but provider manages the leaks and destroys listeners,,, downside providers needs context..
What do u think???

**Comment by FilledStacks** [comment]
@bdairy I don't have many leaks, the `ViewModel` will dispose of the stream subscription if it needs to. The stream in the service will "just be there" and available to subscribe to at any time. Any `ViewModel` that wants to subscribe will subscribe and then dispose of its subscription if it doesn't want to listen to the stream anymore.
