### ISSUE TITLE
[Stacked-Services] Barrier dismissible not working for bottomSheetService

### ISSUE THREAD

**Issue by akifarhan** [Stacked-Org/stacked#198]
I tried to use `showCustomSheet` and set the `barrierDismissible` to `false` but it is not working. I've checked the source code and found that the `barrierDismissible` was not assigned to Get's `isDismissible`. I'm not sure either it is intentionally or not. 

![image](https://user-images.githubusercontent.com/38977468/104818463-cfb95100-5862-11eb-951c-00109f575731.png)

I wanted to create a PR but it seems like Stacked-Services gonna get a major changes so I'm kinda afraid. 😅

**Comment by FilledStacks** [comment]
haha, no man. Please make the PR from the latest version of the code and I'll merge that in. The way I make the services is to only expose what's needed. When a dev, like yourself, comes a long and needs something we add that in :) . I'll tag this issue with Waiting for PR if you're happy with that?

**Comment by FilledStacks** [comment]
We're going to tackle this and add it into the code.

**Comment by akifarhan** [comment]
I think this issue has been solved @FilledStacks through [this PR](https://github.com/FilledStacks/stacked/pull/203). I forgot to close this issue
