### ISSUE TITLE
notifySourceChanged not changing streams in MultipleStreamViewModel

### ISSUE THREAD

**Issue by ghost** [Stacked-Org/stacked#199]
Hi,

As the title implies, Streams are not changing when calling notifySourceChanged. Only after killing the app the streams change.

Regards,

Edit:

I'm using firestore to get 2 streams. The issue here is that if I logout and login with a different user, the stream is giving me the previous user. If I add a value, the stream gets the correct stream (new user). I'm using the exact example from the repo but with firestore.

**Comment by FilledStacks** [comment]
@eherediadev could you post the section of code that swaps the streams out and calls notifySourceChanged please. That would help me find the problem to fix

**Comment by ghost** [comment]
**Home Viewmodel**
```dart
class HomeViewModel extends MultipleStreamViewModel {
  ...
  @override
  Map<String, StreamData> get streamsMap => {
        _OneStream: StreamData(_streamOneService.listenToStream(uid: _uid)),
        _TwoStream: StreamData(_streamTwoService.listenToStream(uid: _uid)),
      };

 // * New User - change id
 void changeStreams() {
       _uid = _authService.uid; // Auth Service  sets the uid each time the user logs in.
       notifySourceChanged(clearOldData: true);
  }
 ...
}
```

**Home View**

```dart
class HomeView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder<HomeViewModel>.reactive(
      viewModelBuilder: () => HomeViewModel(),
      onModelReady: (model) => model.changeStreams(),
      fireOnModelReadyOnce: true,
      ...
}
```
Regards,

**Comment by FilledStacks** [comment]
@eherediadev Thank.

It loos like Your ViewModel is not being re-used. It'll create a new ViewModel when you get to the HomeView again (or that's how it looks). But even if that happens it should still work. 

i'll take a look in the week and let you know what I find.

**Comment by ghost** [comment]
Hey @FilledStacks, did you have time to check this issue?

**Comment by FilledStacks** [comment]
@eherediadev unfortunately not. I confirmed that the unit tests are working for the functionality meaning the base functionality works. I haven't gotten around to setting up an example where it happens to debug the issue.

**Comment by Afsal102** [comment]
Same issue is there a solution for this or else a resource to set it up correctly for the MultipleStreamViewModel @FilledStacks  ?

**Comment by Afsal102** [comment]
when the notifySourceChanged is called it cancels all the subscriptions but doesnt resubscribe!

**Comment by FilledStacks** [comment]
@Afsal102 can you give me an example where this is happening and I'll be able to take a loot at it. A working sample where the bug is happening would be awesome.

**Comment by Afsal102** [comment]
So the thing that happnd is , the initial subscriptions of the multiple
stream viewmodel is working fine!!!!! The problm occurs when the notify
source changed is called all the subscriptions are disposed but it doesn't
subscribe to the new data !!!


*I tried to find it so in the override method of on subscribe and
onSubscription cancel *
*I did a print statement !! In that i found out that when the notify source
changed is called is disposes all the subscription but does not subscribe
to new one's!!!*

*So if u check the resubscription there is an error on that !!!*


*I was a bit if i can reach home quick i will send u the debug prints !!!!
Its the exact same thing as i explained above ... Thanks 😘 for this
amazing package ... It's really helping me out in the production code along
side with the clean architecture .. so i hope this might help u guys to
figure out the problm .. see ya tc kudos*

**Comment by FilledStacks** [comment]
@Afsal102 that's quite a lot of screaming you're doing there with all the exclamation points :D I'm working on getting more time from the team to help me with the issues like this. I haven't been able to spend much time on it but I'm making upgrades now so I'll get some time to look at these issues.

**Comment by Afsal102** [comment]
Sounds good  👍 Sry for the exclamation points !!!!! 😂😂 Ok anyways great
architecture for building production app. I have already published 3 high
scalable apps , and ur package made it easy for testing and states . ❣️

**Comment by FilledStacks** [comment]
@Afsal102 awesome man. I'm really happy to hear that. Looking forward to getting bugs like this fixed up and improving the system.

**Comment by FilledStacks** [comment]
We're going to look at this now. We'll try to reproduce and follow the issue steps then we'll fix if anything is broken.

**Comment by Afsal102** [comment]
This happns when using non-reactive constructor but with the reactive
constructor it works fine

**Comment by FilledStacks** [comment]
@Afsal102 is this still happening?
