### ISSUE TITLE
MultipleStreamViewModel with parameters

### ISSUE THREAD

**Issue by x1z7** [Stacked-Org/stacked#20]
How would you initialize/use `MultipleStreamViewModel` when a `Stream` which needs to take in parameters? And those parameters change over the lifetime of your model; and you have to cancel that stream and listen to a new stream with new values for your parameters.

e.g.: 

```
Stream<int> getIdsByDate(DateTime date) async* {
 ...
}
```

**Comment by FilledStacks** [comment]
oooooooo, good question. This was probably something I was going to run into in one of the new apps we're building that will be using firestore and requires streams to change based on filters. I guess there's two routes I can take here.

1. Add functionality to allow you to mark a model as dirty so it gets rebuilt. Mostly likely by calling like markNeedsRebuild()

2. Add an interface similar to ChangeNotifier with a function notifyDataSourceChanged() which will rebuild the viewmodel, unsubscribe current source and re-subscribe. 

Reading those two things again it'll basically be 1 implementation but I'll leave it as two points so I can process better. I think I'll actually implement this now. I want to show it in the next video as well so the timing is great.

**Comment by FilledStacks** [comment]
@RollyPeres just pushed the functionality. Basically once you've changed your source for the stream you can call `notifySourceChanged` and it will cancel the current streams then rerun all the initialisation logic. 

In the example project you can see how it's called.
