### ISSUE TITLE
Cannot adjust bottom sheet height up to 50%

### ISSUE THREAD

**Issue by yusufhnf** [Stacked-Org/stacked#200]
I am using stacked_services to show Bottom Sheet. But i have problem. I cannot adjust height of BottomSheet up to 50% of screen height. There is my code:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:stacked_services/stacked_services.dart';
import 'package:zeniora/app/locator.dart';
import 'package:zeniora/enums/bottom_sheet_type.dart';
import 'package:zeniora/screens/components/flat_text_field.dart';
import 'package:zeniora/utils/app_style.dart';

void setupBottomSheetUi() {
  final bottomSheetService = locator<BottomSheetService>();

  final builders = {
    BottomSheetType.floating: (context, sheetRequest, completer) =>
        _FloatingBoxBottomSheet(
          request: sheetRequest,
          completer: completer,
        ),
    BottomSheetType.list: (context, sheetRequest, completer) =>
        _ListBottomSheet(
          request: sheetRequest,
          completer: completer,
        )
  };

  bottomSheetService.setCustomSheetBuilders(builders);
}

class _FloatingBoxBottomSheet extends StatelessWidget {
  final SheetRequest request;
  final Function(SheetResponse) completer;
  const _FloatingBoxBottomSheet({
    Key key,
    this.request,
    this.completer,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.all(25),
      padding: EdgeInsets.all(25),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(15),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            request.title,
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              color: Colors.grey[900],
            ),
          ),
          SizedBox(height: 10),
          Text(
            request.description,
            style: TextStyle(color: Colors.grey),
          ),
          Row(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              MaterialButton(
                onPressed: () => completer(SheetResponse(confirmed: true)),
                child: Text(
                  request.secondaryButtonTitle,
                  style: TextStyle(color: Theme.of(context).primaryColor),
                ),
              ),
              FlatButton(
                onPressed: () => completer(SheetResponse(confirmed: true)),
                child: Text(
                  request.mainButtonTitle,
                  style: TextStyle(color: Colors.white),
                ),
                color: Theme.of(context).primaryColor,
              )
            ],
          )
        ],
      ),
    );
  }
}

class _ListBottomSheet extends StatelessWidget {
  final SheetRequest request;
  final Function(SheetResponse) completer;
  const _ListBottomSheet({
    Key key,
    this.request,
    this.completer,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      child: Container(
        height: 0.8.sh,
        padding: AppStyle.standarScreenPaddingAll,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.only(
              topLeft: Radius.circular(15.0), topRight: Radius.circular(15.0)),
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              request.title,
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: Colors.grey[900],
              ),
            ),
            SizedBox(height: 10),
            FlatTextField(
              hint: "Cari nama kampus",
            ),
            Row(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                FlatButton(
                  onPressed: () => completer(SheetResponse(confirmed: true)),
                  child: Text(
                    request.mainButtonTitle,
                    style: TextStyle(color: Colors.white),
                  ),
                  color: Theme.of(context).primaryColor,
                )
              ],
            )
          ],
        ),
      ),
    );
  }
}
````

**Comment by FilledStacks** [comment]
where are you trying to set the height of the container to height * 0.5?

**Comment by yusufhnf** [comment]
> where are you trying to set the height of the container to height * 0.5?

This is Viewmodel code:
`class HomeViewModel extends BaseViewModel {
  final _bottomSheetService = locator<BottomSheetService>();
  String _getToken;
  String _deviceID;
  Future initial() async {
    setBusy(true);
    setBusy(false);
  }

  Future showListBottomSheet(String title, String detail) async {
    await _bottomSheetService.showCustomSheet(
      variant: BottomSheetType.list,
      title: title,
      description: detail,
      mainButtonTitle: "MANTAP"
    );
  }
}`

My UI code:
`import 'package:auto_size_text/auto_size_text.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:stacked/stacked.dart';
import 'package:zeniora/viewmodels/home_viewmodel.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder<HomeViewModel>.reactive(
      viewModelBuilder: () => HomeViewModel(),
      onModelReady: (model) => model.initial(),
      builder: (context, model, child) => ScreenUtilInit(
        child: Scaffold(
          appBar: AppBar(
            title: Text("Beranda"),
          ),
          body: model.isBusy || model.busy(model.resultProfile)
              ? CircularProgressIndicator()
              : SingleChildScrollView(
                  child: Padding(
                      padding: EdgeInsets.all(16.0),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          CircleAvatar(
                            radius: 50.0,
                            backgroundImage: NetworkImage(
                                model.resultProfile.data.avatarUrl),
                          ),
                          AutoSizeText(
                              "Nama: ${model.resultProfile.data.name}"),
                          AutoSizeText(
                              "Saldo: Rp ${model.resultProfile.data.pointsFormatted}"),
                          AutoSizeText(
                              "Berlangganan: ${model.resultProfile.data.isMembershipText}"),
                          SizedBox(
                            height: 20.0,
                          ),
                          SizedBox(
                            width: double.infinity,
                            child: RaisedButton.icon(
                                onPressed: () {
                                  model.navigateStatistik();
                                },
                                icon: Icon(Icons.bar_chart),
                                label: Text("Statistik")),
                          ),
                          SizedBox(
                            height: 20.0,
                          ),
                          SizedBox(
                            width: double.infinity,
                            child: RaisedButton.icon(
                                onPressed: () {
                                  model.navigateQuiz();
                                },
                                icon: Icon(Icons.question_answer),
                                label: Text("Quiz")),
                          ),
                          SizedBox(
                            height: 20.0,
                          ),
                          SizedBox(
                            width: double.infinity,
                            child: RaisedButton.icon(
                                onPressed: () {
                                  model.navigateZenito();
                                },
                                icon: Icon(Icons.featured_play_list),
                                label: Text("Zenito")),
                          ),
                          SizedBox(
                            height: 20.0,
                          ),
                          SizedBox(
                            width: double.infinity,
                            child: RaisedButton.icon(
                                onPressed: () {
                                  model.navigateProfil();
                                },
                                icon: Icon(Icons.people),
                                label: Text("Profil")),
                          ),
                          SizedBox(
                            height: 20.0,
                          ),
                          SizedBox(
                            height: 20.0,
                          ),
                          SizedBox(
                            width: double.infinity,
                            child: RaisedButton.icon(
                                onPressed: () {
                                  model.navigateLeaderBoard();
                                },
                                icon: Icon(Icons.featured_play_list),
                                label: Text("Leaderboard")),
                          ),
                          SizedBox(
                            height: 20.0,
                          ),
                          SizedBox(
                            width: double.infinity,
                            child: RaisedButton.icon(
                                onPressed: () {
                                  model.navigateAnalisis();
                                },
                                icon: Icon(Icons.featured_play_list),
                                label: Text("Analisis Pembahasan")),
                          ),
                          SizedBox(
                            height: 20.0,
                          ),
                          SizedBox(
                            width: double.infinity,
                            child: RaisedButton.icon(
                                onPressed: () {
                                  model.navigateTopup();
                                },
                                icon: Icon(Icons.featured_play_list),
                                label: Text("Topup Saldo")),
                          ),
                          SizedBox(
                            height: 20.0,
                          ),
                          SizedBox(
                            width: double.infinity,
                            child: RaisedButton.icon(
                                onPressed: () {
                                  model.showListBottomSheet("title", "detail");
                                },
                                icon: Icon(Icons.featured_play_list),
                                label: Text("Testing")),
                          ),
                        ],
                      )),
                ),
        ),
      ),
    );
  }
}
`

**Comment by AndreasTschipang** [comment]
Hey, I have a similar problem. I try to set the bottom sheet height to 95% of the entire screen height.

**Comment by FilledStacks** [comment]
Hey, can you try v 0.6.4. The property `isScrollControlled` has been added which should fix this.

**Comment by yusufhnf** [comment]
> Hey, can you try v 0.6.4. The property `isScrollControlled` has been added which should fix this.

problem has been done, thank you
