### ISSUE TITLE
No navigator key in latest prerelease of auto_route

### ISSUE THREAD

**Issue by Reprevise** [Stacked-Org/stacked#206]
In the latest prerelease of auto_route there is no way to pass in a navigator key which I believe is essential to be able to use the navigation service. What should I do in order to be able to navigate without context?

**Comment by FilledStacks** [comment]
@Reprevise I haven't worked on the pre-release, that sounds worrying. I'll check this out today and see if I can find a workaround for you.

**Comment by FilledStacks** [comment]
yeah that's a pretty drastic change. I'll have to spend some more time figuring out how use it together with Get.

**Comment by Reprevise** [comment]
> yeah that's a pretty drastic change. I'll have to spend some more time figuring out how use it together with Get.

Any updates?

**Comment by FilledStacks** [comment]
No @Reprevise I spoke to the author of Auto_route. I'll publish a new package using the old version under stacked_routing. I'm not going to switch the implementation of the current navigation just yet. At the moment I would not use the latest pre-release. I'll be keeping the api consistent with the version at 0.6.6 and add navigator 2.0 features if required into the generator as well. We use it mostly as a generator, he's trying to make it its own navigation service that requires the context.

**Comment by FilledStacks** [comment]
After talking to the author of the package we will fork the version at 0.6.6 and publishing our own stacked router_package which provides the same functionality. We're still determining a date of when we can start working on that package.

**Comment by FilledStacks** [comment]
This functionality has been merged into stacked through the new `StackedApp` annotation and generation functionality
