### ISSUE TITLE
[Question] is it ok to store TextEditingControllers in the viewmodel?

### ISSUE THREAD

**Issue by deity256** [Stacked-Org/stacked#209]
I have complex form with a lot of validation and the communication between the TextEditingController and ViewModel is necessary,
so what the drawbacks of initializing the TextEditingController in the viewModel and what the alternative solution

**Comment by FilledStacks** [comment]
The drawback is the fact that your ViewModel is now not pure any more. It contains your business logic as well as some of the UI code. 

In most cases nothing comes of it, I make it a rule to not mix any UI code into the ViewModel so we can have a separation of concerns. But if it's use sparingly I'm sure no real maintenance issue will arise. 

The alternative is to keep it in the widget and update the viewmodel from the outside as its values are changing.

**Comment by deity256** [comment]
thanks for the explanation

**Comment by KevMorelli** [comment]
Would this be the best way to implement the call the viewmodel or it could create issues with the re-building?

![image](https://user-images.githubusercontent.com/12283570/107139785-940f2580-68fc-11eb-837f-326c98e412b2.png)

**Comment by FilledStacks** [comment]
@KevMorelli that's perfectly fine. I have done something similar in the `FormViewModels` that I've built. 

```dart
  @override
  Widget build(BuildContext context) {

    final firstNameController = useTextEditingController();
    final lastNameController = useTextEditingController();
    final phoneController = useTextEditingController();

    void updateData(UserInformationViewModel model) {
      model.setData({
        FirstNameValueKey: firstNameController.text,
        LastNameValueKey: lastNameController.text,
        MobileNumberValueKey: phoneController.text,
      });
    }

    // Each Outline form simply calls updateData and passes the model to it.
   return Column(
    ....
    OutlineTextForm(
        hintText: 'Firstname',
        currentFocus: firstNameFocusNode,
        nextFocus: lastNameFocusNode,
        controller: firstNameController,
        onChanged: (_) => updateData(model),
     ),
  }
```

It's been working great for us with no build issues. Yours is a more shorthand version of what I did above so it should be fine.

**Comment by KevMorelli** [comment]
Thank you!

**Comment by deity256** [comment]
@FilledStacks @KevMorelli thanks guys for the help
