### ISSUE TITLE
Making dialog title or content optional

### ISSUE THREAD

**Issue by Reprevise** [Stacked-Org/stacked#211]
It would be nice if I didn't have to specify `description` when I just want a title and vice versa on a dialog.

**Comment by FilledStacks** [comment]
Hi, could you be a bit more specific about the changes in the api that you want. 

- Which function? 
- what do you want to change?
- what's the scenario you're trying to accomplish?
- what's the current problem with it?

**Comment by Reprevise** [comment]
All I want is to be able to not have a dialog title which is showcased below as part of Material Design.
![image](https://user-images.githubusercontent.com/25782944/106904055-b4ef3500-66c8-11eb-888f-f44de495b8a6.png)

In its current state, both the `description` and `title` parameters of DialogService#showDialog are required which shouldn't be the case. In Flutter, you don't have to specify a title for a dialog so I don't see why it's required here.

**Comment by FilledStacks** [comment]
Oooooh I see. I also don't see why it's required here. 

I'll get on to that. I should be able to look at it on Thursday if I get some time during the day.

**Comment by FilledStacks** [comment]
I'll ask one of the filledstacks developers to look at it before they start work today.

**Comment by FilledStacks** [comment]
@Reprevise pushed in 0.6.7
