### ISSUE TITLE
model type dynamic in builder function

### ISSUE THREAD

**Issue by yvzoncu** [Stacked-Org/stacked#214]
When I try to use model inside builder function I see it as dynamic and can not reach it? It can be useful to make it object of type model. 

ViewModelBuilder.reactive(
      viewModelBuilder: () => EmailLoginModel(),
      onModelReady: (model) => model.loginLogic(),
      builder: (context, model, child) {
     =>   EmailLoginModel m = model;
        return SafeArea(
            child: Scaffold(
          backgroundColor: Colors.black,
          body: Stack(
            children: [
              _switcher(context, model),
              if (m.gameState == GameStates.busy)
                HourGlass(
                  message: 'Loading...',
                )
            ],
          ),
        ));
      },
    );

**Comment by FilledStacks** [comment]
The ViewModelBuilder is generic so you have to pass it the type you want it to be. 

```
ViewModelBuilder<CheckoutViewModel>.reactive();
```
