### ISSUE TITLE
Search list inside bottom sheet can’t update

### ISSUE THREAD

**Issue by yusufhnf** [Stacked-Org/stacked#216]
I make listview search field inside Bottom Sheet with Stacked_services. When input some text inside field, listview not update. But if I close bottom sheet and open again, listview can update.

**Comment by FilledStacks** [comment]
@yusufhnf give the widget in the bottom sheet it's own viewmodel, when you update the list data simply call notifyListeners and should rebuild. It's just a basic widget so you can give it its own viewmodel.

**Comment by yusufhnf** [comment]
> @yusufhnf give the widget in the bottom sheet it's own viewmodel, when you update the list data simply call notifyListeners and should rebuild. It's just a basic widget so you can give it its own viewmodel.

Do you have some examples or tutorials? I try your suggestion, but can't work for me.

**Comment by FilledStacks** [comment]
I don't but if you know how to make a view with a viewmodel then you should simply do the exact same thing and set that view as your custom bottom sheet. 

At [this point](https://github.com/FilledStacks/stacked/blob/2f910e29e5f865b659f5790c02647fb156e00f37/packages/stacked_services/example/lib/ui/setup_bottom_sheet_ui.dart#L28) add a ViewModelBuilder.reactive and give it a viewmodel for that view.

**Comment by yusufhnf** [comment]
Thank you. This problem has been solved.
