### ISSUE TITLE
Selected theme is not saved/persisted 

### ISSUE THREAD

**Issue by bipinvaylu** [Stacked-Org/stacked#217]
I am still getting theme persistence issue in version `0.2.2+2`. I am using `getThemeManager(context).setThemeMode(selectedThemeMode)` for changing theme once user select theme from list of three (System, Light and Dark) theme. Can you please let me know what is missing here from my end?

main.dart:
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FlutterStatusbarcolor.setStatusBarWhiteForeground(true);

  await Firebase.initializeApp();
  await ThemeManager.initialise();

  runApp(MultiProvider(
    providers: [
      // Provider needed by app
    ],
    child: MyApp(),
  ));
}

class MyApp extends StatelessWidget {
  MyApp();

  @override
  Widget build(BuildContext context) {
    return ThemeBuilder(
      defaultThemeMode: ThemeMode.system,
      darkTheme: darkTheme,
      lightTheme: lightTheme,
      statusBarColorBuilder: (theme) => theme.accentColor,
      themes: getThemes(),
      builder: (context, regularTheme, darkTheme, themeMode) {
        return LayoutBuilder(
            //return LayoutBuilder
            builder: (context, constraints) {
          return OrientationBuilder(
              //return OrientationBuilder
              builder: (context, orientation) {
            //initialize SizerUtil()
            SizerUtil().init(constraints, orientation);

            return ProgressDialog(
              orientation: ProgressOrientation.vertical,
              loadingText: "Please wait...",
              backgroundColor: Theme.of(context).backgroundColor,
              child: MaterialApp(
                title: "My App",
                theme: regularTheme,
                darkTheme: darkTheme,
                themeMode: themeMode,
                home: SplashScreen(),
              ),
            );
          });
        });
      },
    );
  }
}
```

setting_page.dart: 
```
// Calling this method when user selected any of theme from list of theme
void _updateSelectedThemeMode(ThemeMode selectedThemeMode) async {
    // Just gave it a try but no luck
    // getThemeManager(context).toggleDarkLightTheme();

    getThemeManager(context).setThemeMode(selectedThemeMode);
  }
```

@FilledStacks Guys do you have any idea what's going wrong here. I cross-verified implementation on [your blog](https://www.filledstacks.com/post/multiple-themes-in-flutter-dark-and-light-theme-flutter-stacked/) as well but no luck and unable to figure out exact source of issue.

Ref: https://github.com/FilledStacks/stacked/issues/158#issuecomment-761813982

**Comment by bipinvaylu** [comment]
Ref: https://github.com/FilledStacks/stacked/issues/158#issuecomment-761967152

> 1. What do you want to happen?
- As per given details on pub.dev and checkout examples, I believe package should manage to save last selected theme mode when i set it using `getThemeManager(context).setThemeMode(selectedThemeMode)` method call.
> 2. What is happening at the moment?
- Right now, Seems like this package is not storing last selected theme mode. So always get System/Light theme mode which is my Android device theme as well.

themes.dart
```
List<ThemeData> getThemes() {
  return [lightTheme, darkTheme];
}
```
Let me know if you need anything else from me. I am having 2 themes only. Light and Dark.

**Comment by bipinvaylu** [comment]
Ref: https://github.com/FilledStacks/stacked/issues/158#issuecomment-774396900
 
```
main.dart: where I am reading persisted theme
```
ThemeService _themeService = ThemeService.getInstance();
ThemeMode _themeMode = _themeService.isDarkMode? ThemeMode.dark : ThemeMode.light;

return ThemeBuilder(
          defaultThemeMode: _themeMode,
          darkTheme: darkTheme,
          lightTheme: lightTheme,
          ....);
```
- Getting _themeService null in main.dart only. 

settings_page.dart: where i am persisting theme selection
```
ThemeService _themeService = ThemeService.getInstance();
_themeService.toggleDarkLightTheme();
_themeService.setThemeMode(_themeService.isDarkMode? ThemeManagerMode.dark : ThemeManagerMode.light);
```

I am not sure how to locator would make difference here and had not used locator before. It would be great if you can help me out with bit more details or code sample. Thanks.

**Comment by FilledStacks** [comment]
@bipinvaylu This is built specifically to work with stacked, hence it's in the stacked package. I can't guarantee the reliability of it outside of stacked given that it's built to work with an IoC container like get_it that allows you to register singletons for usage throughout the app. 

The functionality for this isn't that much so you can easily duplicate it. Add shared preferences to your app, store the theme value in a boolean in there, read that when the app starts and use that instead. The same in settings, you can simply update the bool value on the preferences to the one that it's been changed too and then use that.
