### ISSUE TITLE
How to access view model in initState

### ISSUE THREAD

**Issue by Reprevise** [Stacked-Org/stacked#219]
I have a page controller stored in my view model but I can't call on it to animate to a page until it attaches to a `PageView`. I figured I'd use the `addPostFrameCallback` to be able to call my view model, but there's no way of accessing it. I saw there was a `key` field in the `ViewModelBuilder` widget so I thought of attaching a key to it to access its state. I found out however that its state is private. Is there any way that I can wait for my widget to load completely so that I can call `PageController#animateToPage`?

**Comment by FilledStacks** [comment]
@Reprevise you can construct your ViewModel locally in the Stateful widget state object and pass that to the viewmodel builder.

```dart
class StateWidget extends State<>{
final _model = MyViewModel();

Widget build(context) {
 return ViewModelBuilder.reactive(
  viewModelBuilder: () => _model,
  ...
  );
}
}
```

Then it'll be available during the init call
