### ISSUE TITLE
is there a property change notifier?

### ISSUE THREAD

**Issue by anhartasman** [Stacked-Org/stacked#221]
if i have two ViewModelWidgets, widget A listen for property name, widget B listen for property email, if name get changed, i just want to rebuild widget A, if email get changed, i just want to rebuild widget B, how to do that?

sorry my english is not good

**Comment by FilledStacks** [comment]
@anhartasman there's no way to define partial rebuilds like that at the moment. That functionality will be worked on if we can find a way to do that.
