### ISSUE TITLE
I can't  use useTextEditingController() in HookViewModelWidget

### ISSUE THREAD

**Issue by ahmedalmubarak** [Stacked-Org/stacked#222]
**error show to me is** ==> The method 'useTextEditingController' isn't defined for the type '_StringForm'.
Try correcting the name to the name of an existing method, or defining a method named 'useTextEditingController'.
I import stacked_hooks.dart but also doesn't work !

**Comment by FilledStacks** [comment]
That function is only available in flutter_hooks. So you need to add that to your project
