### ISSUE TITLE
MaybePop

### ISSUE THREAD

**Issue by Coderessurect** [Stacked-Org/stacked#223]
@FilledStacks sir how to utilize mabyePop with NavigationService present in stacked services

**Comment by FilledStacks** [comment]
@Coderessurect Are you asking me what `maybePop` is for?

**Comment by Coderessurect** [comment]
How to use it via navigation service in built in stacked services

**Comment by FilledStacks** [comment]
@Coderessurect you call it when needed. Then it'll either pop or not pop.
