### ISSUE TITLE
Make dialog title/content optional

### ISSUE THREAD

**Issue by Reprevise** [Stacked-Org/stacked#227]
This is a regression and a breaking change that completely broke our app in an upgrade that was supposed to be "non-breaking".

**Comment by FilledStacks** [comment]
@Reprevise shit, hopefully it didn't revert. Let me check that out.

**Comment by FilledStacks** [comment]
This should be fixed in 0.7.2 let me know if there's still a problem. I don't know what happened. No history in the logs of changing it.
