### ISSUE TITLE
Title cannot be null in SnackbarService

### ISSUE THREAD

**Issue by yusufhnf** [Stacked-Org/stacked#231]
I make my own custom snack bar. But I cannot call the custom snack bar without a title.
The snack bar will be shown if I add a title when I call the Snackbar.

**Comment by FilledStacks** [comment]
@yusufhnf you should be able to do that. If it's custom you can simply ignore it

**Comment by yusufhnf** [comment]
if I ignore it, the snackbar can't show and give me an error like this:
`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/widgets/text.dart': Failed assertion: line 370 pos 10: 'data != null': A non-null String must be provided to a Text widget.`

**Comment by FilledStacks** [comment]
@yusufhnf then don't set it in your custom UI? Can you put your custom UI below please

**Comment by yusufhnf** [comment]
> @yusufhnf then don't set it in your custom UI? Can you put your custom UI below please

`snackBarService.registerCustomSnackbarConfig(
    variant: SnackbarType.successTop,
    config: SnackbarConfig(
      borderRadius: 10.0,
      backgroundColor: Colors.green,
      messageColor: Colors.white,
      margin: AppStyle.standarScreenPaddingAll,
    ),
  );`

**Comment by FilledStacks** [comment]
And the code you use to call it

**Comment by FilledStacks** [comment]
If there's still a problem with this please post the code requested and we can discuss and I'll re-open the issue if there's a problem.
