### ISSUE TITLE
Incompatible with code-generators that uses different versions of analyser

### ISSUE THREAD

**Issue by andreikastsiuk** [Stacked-Org/stacked#232]
Hi,
 
 I have faced the next issue:

> Because every version of stacked_generator depends on analyzer ^0.39.2 and floor_generator 0.18.0 depends on analyzer ^0.40.4, stacked_generator is incompatible with floor_generator 0.18.0.
> And because no versions of floor_generator match >0.18.0 <0.19.0, stacked_generator is incompatible with floor_generator ^0.18.0.
> So, because *my_app_name* depends on both floor_generator ^0.18.0 and stacked_generator any, version solving failed.
> pub get failed (1; So, because *my_app_name* depends on both floor_generator ^0.18.0 and stacked_generator any, version solving failed.)

I am trying to use stacked_generator but I am getting the issue above.

To solve it, I have tried to add the next code:

```
dependency_overrides:
  analyzer: ^0.41.2
```

When I try to run:

> flutter pub run build_runner build --delete-conflicting-outputs

I always get the next issue: 

>  Failed assertion: boolean expression must not be null

As you see, I would like to use Floor (https://pub.dev/packages/floor) as ORM.

stacked_generator and Floor use different versions of analyzer so I am not sure but it might be a reason. I think it could be solved by increased the min version on the analyzer library in stacked_generator. Also, the additional reason could be the support of NullSafety

I am new in Flutter, so I could be totally wrong. Please, could you help me? Thanks a lot!

**Comment by FilledStacks** [comment]
Fixed in stacked_generator 0.2.1
