### ISSUE TITLE
Add Forms support into Stacked

### ISSUE THREAD

**Issue by FilledStacks** [Stacked-Org/stacked#233]
The development for this feature has already started and can be tracked [here](https://github.com/FilledStacks/stacked/tree/feature/form-vm/packages/stacked/example/lib/ui/form). I wanted this issue to serve as a reminder for the feature functionality that we intend to build into the form part of stacked:

- [x] Add FormView annotation to allow the user to define form fields
- [x] Generate the $FormView mixin with the matching controllers, focusNodes and update function to update the `FormViewModel` map as the values change.
- [x] Create the `FormViewModel` functionality in the stacked package
- [ ] Add a delayed validation function call that can be overridden in the implementing FormViewModel class. This function should fire 500ms second after all user typing has stopped. This value should be adjustable on construction
- [ ] Most forms will have a `canSubmit` criteria. We should allow the dev to be able to override this and define their can submit conditions. 

Please leave comments below for any additional functionality you think we need to support. I'd be happy to chat about it and see if it can be added into the first round of improvements.

**Comment by Reprevise** [comment]
You should integrate some custom form widgets such as a date-time picker, file uploader, checkboxes, and more. It's one of the main reasons I love the `reactive_forms` package as well as its ambiguous `FormControl` class. A custom controller that can store any value for all types of fields would make me switch.

**Comment by FilledStacks** [comment]
@Reprevise yes. I had it as a comment in the code to support different types of form controllers. I'm not going to provide any UI for this so I'll have to build it in a way to find a compatible package for the way it should be used. 

Will see what needs to be done to provide flexibility there. I want the devs to still have freedom to use their existing UI / packages to build their forms. I'm just removing the sync between view and viewmodel and the additional boilerplate usually required with setting your view and managing all the controllers.

**Comment by Reprevise** [comment]
@FilledStacks I think a separate package for widgets would be good. I'd really like a date picker or file upload and you'd just provide a controller and a `InputDecoration` and it would set the value.

As a separate package for widgets, devs would still have the ability to customize them if they choose to and it would make it easier for people who don't want to have an `onChanged` callback and having to set the controller value manually.

**Comment by FilledStacks** [comment]
@Reprevise agreed. I can definitely add a "sync" to allow for any controller type to be synced automatically to the viewmodel. The same way we removed it for TextControllers. It should be quite easy actually, if the controller implements the addListener function then we should be able to automatically sync its values into the formValueMap using a dedicated key. Will create a separate ticket for that.
