### ISSUE TITLE
[stacked] What is the point of onModelReady?

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [Stacked-Org/stacked#24]
Taking a look at the implementation of `onModelReady`, I can tell that the following two snippets of code do the exact same thing:

```dart
ViewModelBuilder.reactive(
  viewModelBuilder: () => FooViewModel(),
  onModelReady: (viewModel) => viewModel.init(),
  builder: ..,
)
// does the same as the following more concise snippet:
ViewModelBuilder.reactive(
  viewModelBuilder: () => FooViewModel()..init(),
  builder: ..,
)
```

So what is the point of `onModelReady`, now that you removed the `onPostFrameCallback`?

**Comment by FilledStacks** [comment]
@creativecreatorormaybenot the point of it is to run logic when the model has been constructed, in a readable manner. You'll find most of my decisions will be verbose to make it clear what's happening when reading the code. Not because of a technical requirement.

**Comment by creativecreatorormaybenot** [comment]
@FilledStacks I see. No worries then because I can still use the other way if I prefer it 👍

**Comment by melis-m** [comment]
This might not be directly related to stacked, but what's the point of having a `ViewModel.init()` function that you call from `onModelReady`. Couldn't you achieve the same result by directly putting the content of `init` inside the ViewModel's constructor ?

**Comment by FilledStacks** [comment]
@melis-m construction is blocking. It's the same for some things. But if you want to for instance fetch and set data it would be good not to do it in the constructor.

**Comment by melis-m** [comment]
@FilledStacks but `init` is blocking as well, and it's not as if there's actually any really _blocking_ stuff, like even making an http request is only just launching a future.
I just don't really understand the point of splitting the construction and the initialization part :\
