### ISSUE TITLE
Partial View Rebuild issue.

### ISSUE THREAD

**Issue by Shamik07** [Stacked-Org/stacked#243]
The build function of the main view is also being triggered when an inner view is being rebuilt.

Main view - 

```dart
class PartialBuildsView extends StatelessWidget {
  const PartialBuildsView({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder<PartialBuildsViewModel>.nonReactive(
        builder: (context, model, child) {
          print('PartialBuildsView rebuilt');
          return Scaffold(
            body: Column(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                _TitleAndValue(),
                SizedBox(
                  height: 25,
                ),
                _StringForm(),
              ],
            ),
          );
        },
        viewModelBuilder: () => PartialBuildsViewModel(),
    );
  }
}
```

Inner View 1 - 
```dart
class _StringForm extends HookViewModelWidget<PartialBuildsViewModel> {
  _StringForm({Key key}) : super(key: key, reactive: false);
  @override
  Widget buildViewModelWidget(BuildContext context, PartialBuildsViewModel model,) {
    print('_StringForm rebuilt');
    var text = useTextEditingController();
    return TextField(
      controller: text,
      onChanged: model.updateString,
    );
  }
}`

Inner View 2 -
`class _TitleAndValue extends ViewModelWidget<PartialBuildsViewModel> {
  const _TitleAndValue({Key key}) : super(key: key, reactive: true);
  @override
  Widget build(BuildContext context, PartialBuildsViewModel model) {
    print('_TitleAndValue rebuilt');
    return Column(
      children: [
        Text(
          model.title ?? '',
          style: TextStyle(fontSize: 40),
        )
      ],
    );
  }
}
```

Viewmodel - 
```dart
class PartialBuildsViewModel extends BaseViewModel {
  String _title = "Write something";
  String get title => _title;

  void updateString(String value) {
    if(value.isEmpty){
      _title = "Write something";
    }else{
      _title = value;
    }

    notifyListeners();
  }
}
```

stacked: ^1.9.5

log - 
[ +120 ms] flutter: PartialBuildsView rebuilt
[   +1 ms] flutter: _TitleAndValue rebuilt
[   +1 ms] flutter: _StringForm rebuilt
[+1510 ms] flutter: PartialBuildsView rebuilt
[        ] flutter: _TitleAndValue rebuilt
[        ] flutter: _StringForm rebuilt
[  +27 ms] flutter: PartialBuildsView rebuilt
[   +1 ms] flutter: _TitleAndValue rebuilt
[   +2 ms] flutter: _StringForm rebuilt
[ +138 ms] flutter: PartialBuildsView rebuilt
[   +5 ms] flutter: _TitleAndValue rebuilt
[        ] flutter: _StringForm rebuilt

**Comment by FilledStacks** [comment]
This is probably due to to the latest update to fix an issue for disposing a nonReactive Viewmodel. Will revert and push back up.

**Comment by Shamik07** [comment]
Yup tested it on 1.9.0 and it's working. I also wanted to ask you about this, Don't know if it's normal behavior or a bug, I am trying to build a form with PartialBuild. I have multiple TextFeilds and each time I type in 1 TextFeild, All the other TextFeilds also get rebuilt. Is this supposed to happen? 

Also, should I switch to your form generators instead of using PartialBuilds?

**Comment by FilledStacks** [comment]
@Shamik07 If you're calling notifyListeners then yes.

The two are not mutually exclusive, the can and should be used together if needed.
