### ISSUE TITLE
How to reset error to null in base view model

### ISSUE THREAD

**Issue by githubmin** [Stacked-Org/stacked#246]
hi, can somebody tell me how to reset the error object when using runBusyFuture() in success condition

source code in here  https://github.com/FilledStacks/stacked/blob/master/packages/stacked/lib/src/state_management/base_view_models.dart#L75-L99

```dart
/// Sets the ViewModel to busy, runs the future and then sets it to not busy when complete.
///
/// rethrows [Exception] after setting busy to false for object or class
Future runBusyFuture(Future busyFuture,
    {Object busyObject, bool throwException = false}) async {
_setBusyForModelOrObject(true, busyObject: busyObject);
try {
    var value = await runErrorFuture(busyFuture,
        key: busyObject, throwException: throwException);
    _setBusyForModelOrObject(false, busyObject: busyObject);
    return value;
} catch (e) {
    _setBusyForModelOrObject(false, busyObject: busyObject);
    if (throwException) rethrow;
}
}

Future runErrorFuture(Future future,
    {Object key, bool throwException = false}) async {
try {
    return await future;
} catch (e) {
 --->   _setErrorForModelOrObject(e, key: key);
    onFutureError(e, key);
    if (throwException) rethrow;
    return Future.value();
}
}
```

when cache exception, will call _setErrorForModelOrObject(e: key: key),
but when i recall runBusyFuture(), if this time, no exception occurred, could we need to reset the error to null?
i did not found where to reset this error, can some body help me ?

**Comment by githubmin** [comment]
Now, in my code now in below

```dart
static final String objectRefreshBook = 'refreshBook';

  Future<void> refreshBook() async {
    if (!hasBook) return;
    if (busy(objectRefreshBook)) return;

-->    setErrorForObject(objectRefreshBook, null);
    await runBusyFuture(
      Future(() async {
        final newBook = await _bookService.fetchBook(_book);
        await _bookService.updateBook(newBook);
        _book = newBook;
      }),
      busyObject: objectRefreshBook,
    );

    if (error(objectRefreshBook) != null) {
      _snackbarService.showSnackbar(message: error(objectRefreshBook).toString());
    }
  }
```

i need to call setErrorForObject(key, null); to reset error before runBusyFuture()

is this api designed using like so? or could we merge this reset error in base view model?

**Comment by FilledStacks** [comment]
You can add it [in here](https://github.com/FilledStacks/stacked/blob/a55b8b56486d88c1c8cd8c0b9113b25a8b5167e6/packages/stacked/lib/src/state_management/base_view_models.dart#L91) and make a PR. Or I'll add that, probably end of this weeks and push a release out for it after it's been tested.
