### ISSUE TITLE
[stacked] Const constructors for view model widgets

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [Stacked-Org/stacked#25]
Why be there no `const` constructors for the immutable [`ViewModelWidget` class](https://github.com/FilledStacks/stacked/blob/80bcaaddf51237c0870093a44b634e4a4b1cd590/lib/_viewmodel_widget.dart#L6)?

I feel like https://github.com/FilledStacks/stacked/blob/80bcaaddf51237c0870093a44b634e4a4b1cd590/lib/_viewmodel_widget.dart#L9

Should actually look like this:

```dart
const ViewModelWidget({Key key, this.reactive = true}) : super(key: key);
```

What is the rationale behind that decision?

**Comment by creativecreatorormaybenot** [comment]
If this is not intended, I can create a PR for this 👍🏽  
I wanted to wait before creating any change as #27 should be merged first (I think it is important and landing any other change before this one is tricky).

**Comment by FilledStacks** [comment]
No rationale. I didn't make that choice consciously. You can definitely make a PR for that where it applies.
