### ISSUE TITLE
Please update dependency of stacked ^1.9.5 to the latest version

### ISSUE THREAD

**Issue by jhandaya** [Stacked-Org/stacked#252]
How to reproduce :

1. Open pubspec.yaml
2. add dependency to the latest version of provider
            provider: ^5.0.0
            stacked: ^1.9.5
3. run flutter pub get

you may need to update your project dependency to the latest version

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.1   ##--> 5.0.0
##**********************************************************
##There are some input beside this issue

  observable_ish: ^2.1.4  ## --> 2.1.5
  meta: ^1.1.8     ## --> 1.3.0
  get_it: ^5.0.6    ## --> 6.0.0

**Comment by FilledStacks** [comment]
A PR for this would be great. Otherwise I'll get to this on Thursday probably
