### ISSUE TITLE
Update state of only one HookViewModel Widget

### ISSUE THREAD

**Issue by StankoKostic** [Stacked-Org/stacked#253]
Hello all, and thank you for this amazing package/architecture template. I ran across one issue that I'd like to have a feedback about:

Let's say we have a list of same `HookViewModel` widgets within the `View` that use the same `ViewModel`, but only one needs to update it's state (f.e. we want to use `animationController` or just expand the widget `onTap()`). What would be the best way to deal with this, since `HookViewModel` widgets do not provide us `setState()` option?

The only thing that I can think of is to wrap the `HookViewModel` widget with a `StatefulWidget`.

Thanks in advance!

**Comment by FilledStacks** [comment]
@StankoKostic If you're using the animationController widget you should have the animation controller available in the build function so you can simply call start on it when tapped. that's what I would do. 

I don't think there's any need to wrap it in a stateful widget.

**Comment by StankoKostic** [comment]
@FilledStacks Thank you for the answer! Two questions that might be relevant:

- How do we dispose the controller?
- What do we do in scenarios where we only need one simple setState()?

**Comment by FilledStacks** [comment]
- Hooks dispose themselves internally
- If you **need** setState then you need a stateful widget. Nothing else I would recommend to use.

**Comment by StankoKostic** [comment]
Thanks for the explanation! I guess I will be closing this thread. Though, I think it would be nice to have something like `StatefulHookViewModelWidget` inspired by `StatefulHookWidget` in `flutter_hooks` package - to have the option to internally reset the state for minor needs
