### ISSUE TITLE
stack_themes and new @StackedApp

### ISSUE THREAD

**Issue by hunterdowns** [Stacked-Org/stacked#255]
I used to use:
```
  @lazySingleton
  ThemeService get themeService => ThemeService.getInstance();  //https://www.filledstacks.com/post/multiple-themes-in-flutter-dark-and-light-theme-flutter-stacked/
```
before the new @StackApp version of Stacked.  The below doesn't work
```
@StackedApp(
  routes: [
    MaterialRoute(page: HomeView, initial: true),
  ],
  dependencies: [
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: ThemeService),
  ],
)
class AppSetup {
  /** Serves no purpose besides having an annotation attached to it */
}
```
 as I get a null anytime I use
```
  final ThemeService _themeService = locator<ThemeService>();
```
Am I missing something or is this an issue?

**Comment by FilledStacks** [comment]
Mmmmm, I'd have to add an option to register a function to call instead of constructing the service myself. I'll look into that.

**Comment by FilledStacks** [comment]
You can now pass in 

```dart
    LazySingleton(
      classType: ThemeService,
      resolveUsing: ThemeService.getInstance,
    )
```

The same for Singleton and pass it the static function to use for resolving. This is available in v1.9.7 and generator v0.2.6

**Comment by coruscant187** [comment]
Could this be added inside the documentation of stacked_themes? 
The documentation mentions `locator.registerSingleton(() => ThemeService.getInstance());` to register the service. 
[https://pub.dev/packages/stacked_themes](https://pub.dev/packages/stacked_themes)

**Comment by FilledStacks** [comment]
I've added the tag. It'll be added as we comb through and add docs for the new release.
