### ISSUE TITLE
Re-using ViewModels

### ISSUE THREAD

**Issue by athirlwall-bots** [Stacked-Org/stacked#257]
In the [Stacked documentation](https://pub.dev/packages/stacked), section **How Does It Work**, two of the 'principles to follow during development' are:

- ViewModels for widgets that represent page views are bound to a single View only.
- ViewModels may be re-used if the UI require the same functionality.

Given that we want to re-use a ViewModel for multiple Views, which one of the following is correct?

1. The same instance of a ViewModel can be used for different Views
2. Each View should be bound to a unique instance of the ViewModel

For example, if we have HomeView and AboutUsView, and we want to use ContentViewModel for both, can we use the same instance of ContentViewModel for both Views, or should we have unique instances of ContentViewModel for each View?

**Comment by FilledStacks** [comment]
Number 2 is correct. Each view should always have a unique instance. 

That's a much better way to say both of those sentences in 1 as well. Thanks for the question. I should update the docs.

**Comment by FilledStacks** [comment]
Change 

- ViewModels for widgets that represent page views are bound to a single View only.
- ViewModels may be re-used if the UI require the same functionality.

To
- A widget should always be associated with a unique instance of a ViewModel

**Comment by ghost** [comment]
Looking for a little more advice/support on this. If a viewmodel requires nearly the exact same functionality, what is the issue using the same viewmodel? Is it a performance issue or more-so a poor readability issue?

**Comment by FilledStacks** [comment]
@EricPHassey if it requires the exact same functionality then it's fine to use for a different view as well. For instance we have a widget for image uploading. If you tap it we show the image picker and then you upload. 

That widget has a viewmodel ImagePickerViewModel and we use that viewmodel for three different widgets because there's 3 different UI's for uploading the image throughout the app.
