### ISSUE TITLE
[stacked_firebase_auth] Prevent replay attacks by generating a nonce when signing in with apple

### ISSUE THREAD

**Issue by Reprevise** [Stacked-Org/stacked#261]
The Flutter Firebase Auth [documentation](https://firebase.flutter.dev/docs/auth/social#apple) recommends generating a nonce using the `crypto` to prevent replay attacks using Apple credentials.

**Comment by FilledStacks** [comment]
Thanks for that info. 

This is on the backlog. Will probably start working on this in a week, around when we're making the Single Sign on functionality for the Boxtout series.

**Comment by FilledStacks** [comment]
This hasn't been pushed yet. Which is why I kept this open. Otherwise I'll foget.
