### ISSUE TITLE
Issue running app on release mode in flutter web

### ISSUE THREAD

**Issue by javdhu** [Stacked-Org/stacked#262]
Since upgrading to the latest version of stacked and using only stacked for routing and dependency injection I can't run the app on release mode in flutter web. I've added the error logs obtained from the web console. App works perfectly in debug mode.

`main.dart.js:40167 Uncaught TypeError: Cannot read property 'cy' of null
    at aNJ.a6L (main.dart.js:87425)
    at aNJ.$1$3$instanceName$param1$param2 (main.dart.js:87427)
    at aNJ.$3$instanceName$param1$param2 (main.dart.js:87430)
    at aAv.$1$0 (main.dart.js:112800)
    at Object.buV (main.dart.js:15228)
    at main.dart.js:23709
    at aZ6.a (main.dart.js:3939)
    at aZ6.$2 (main.dart.js:39137)
    at Object.n (main.dart.js:3925)
    at Object.b_m (main.dart.js:23717)`

**Comment by FilledStacks** [comment]
What is `cy` referring too?

**Comment by javdhu** [comment]
It's some variable in the generated dart code. Seems to be related to getIt, as it originates from the function that sets up the locators.

**Comment by FilledStacks** [comment]
I have never used code_gen on web so I don't have any experience or insights there. Sorry about that, will get some soon when we build our web apps.

**Comment by hjue** [comment]
I have the same problem.
The stacked is not support on the web platform.
![image](https://user-images.githubusercontent.com/1135045/111977694-fedb8f80-8b3d-11eb-9b1c-2b7513c08624.png)

I replace the code 
`viewModelBuilder: () => locator<LobbyPageModel>(),`with` viewModelBuilder: () => LobbyPageModel(), ` , the problem is solved. It's related to getIt,but I do not what to do  .

**Comment by BrylleGomez** [comment]
I am currently building a Flutter Web App with Stacked and faced this very same issue. Found the fix [here](https://github.com/FilledStacks/stacked/issues/288) (another currently open issue within this package at the time I am posting this comment). Hope it solves it for everyone. @hjue is somewhat right, it's related to an issue regarding the built-in locator in Stacked, and replacing it with the regular GetIt locator in app.locator.dart fixes it.

**Comment by FilledStacks** [comment]
@BrylleGomez We will work on a fix for this soon.

**Comment by hjue** [comment]
I changed the code `viewModelBuilder: () => locator<LobbyPageModel>() ` to `viewModelBuilder: () => locator.get<LobbyPageModel>()` ，Everything works fine.  


@BrylleGomez @FilledStacks

**Comment by FilledStacks** [comment]
Interesting. I'll keep that around to add into the docs.

**Comment by javdhu** [comment]
> 
> 
> I changed the code `viewModelBuilder: () => locator<LobbyPageModel>() ` to `viewModelBuilder: () => locator.get<LobbyPageModel>()` ，Everything works fine.
> 
> @BrylleGomez @FilledStacks

I can confirm that this fixes the issue.

**Comment by realhackg25** [comment]
you can see that I used locator.get<LoginViewModel>() but still I can not get the app to work in release mode, NOTE that in debug mode works fine @FilledStacks

**Comment by realhackg25** [comment]
And I also have this in my route defined LoginViewModel as dependency so it can be picked by locator `@StackedApp(
  routes: [
    MaterialRoute(page: StartUpView, initial: true),
    MaterialRoute(page: DashboardView),
    MaterialRoute(page: SignUpFormView),
    MaterialRoute(page: BusinessHomeView),
    MaterialRoute(page: LoginView),
  ],
  dependencies: [
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: LoginViewModel)
  ],
)
class AppSetup {
  /** Serves no purpose besides having an annotation attached to it */
}`

**Comment by richard457** [comment]
Also, have the same issue had discussed with @jdaev about this issue in the email we realized that in the current stacked 2.0.4 the issue is not yet solved, your help is appreciated?  @FilledStacks

**Comment by richard457** [comment]
@FilledStacks any support on this?

**Comment by richard457** [comment]
It's wired that on the master branch of flutter works fine!
