### ISSUE TITLE
Wrapping every view with a DialogManager

### ISSUE THREAD

**Issue by sqrg** [Stacked-Org/stacked#269]
I followed and adapted [this Dialog Manager implementation](https://medium.com/flutter-community/manager-your-flutter-dialogs-with-a-dialog-manager-1e862529523a) in a previous Stacked version. I just had to do this for every view in the router:

```
case LoginView.routeName:
        return MaterialPageRoute(builder: (context) => DialogManager(child: LoginView()));
```

The problem now is that the automatic route generator doesn't allow me to do something like that. Is there any way to achieve that? I would need something like this:

```
DebugView: (data) {
      var args = data.getArgs<DebugViewArguments>(
        orElse: () => DebugViewArguments(),
      );
      return MaterialPageRoute<dynamic>(
        builder: (context) => DialogManager(child: DebugView(key: args.key)),
        settings: data,
      );
    },
```

Maybe there's a way while still using the automatic generator?

Thanks

EDIT: [Here](https://github.com/sqrg/flutter_base_project) you can see a basic example of what I'm talking about.

Also, maybe related to #226 ?

**Comment by FilledStacks** [comment]
@sqrg there's a new way to do this that doesn't require the maintenance or wrapping of the DialogManager using the stacked_services. [This video goes over it](https://youtu.be/uuyJHCxxMEY), we don't recommend the approach you're using anymore. 

Let me know if this helps. But you won't be able to use the route generation if you want to use the manager method.

**Comment by sqrg** [comment]
Ok, I'll take a look. Thanks!
