### ISSUE TITLE
anyObjectsBusy is always true in MultipleFutureViewModel

### ISSUE THREAD

**Issue by miquelromero** [Stacked-Org/stacked#270]
Hi,

The `anyObjectsBusy` getter is always true in a `MultipleFutureViewModel`.

I think the issue here is that we always have a true item in the `_busyStates` array (its hash matches the own `MultipleFutureViewModel` hash).

![image](https://user-images.githubusercontent.com/9053887/111610210-61016100-87db-11eb-8f82-310ee409a4e2.png)

In the example in the screenshot, the viewmodel has two futures (`busyStates[1]` and `busyStates[2]`), which are already resolved.
But `_busyStates[0]` will still be true, so `anyObjectsBusy` will also be always true.

I see the `_busyStates` and the `anyObjectBusy`  are not a `MultipleFutureViewModel` specific thing but a `BaseViewModel` feature, maybe what we would need (at least what I would need) is a `anyFuturesBusy` getter in the `MultipleFutureViewModel` instead of relying on `anyObjectBusy`.

Thanks for the project, you are helping us a lot.

**Comment by miquelromero** [comment]
I see the responsible is probably this code in the MultipleFutureViewModel initialization:
```
    // We set busy manually as well because when notify listeners is called to clear error messages the
    // ui is rebuilt and if you expect busy to be true it's not.
    setBusy(true);
```

Anyway, we can always implement a `anyFuturesBusy` ourselves in our viewmodel, so not a big deal.

**Comment by FilledStacks** [comment]
@miquelromero thanks for letting me know about that. It's definitely something to improve.

**Comment by FilledStacks** [comment]
Working on this next

**Comment by FilledStacks** [comment]
this is in the latest version of stacked 2.0.4
