### ISSUE TITLE
Error flutter pub get stacked_generator if using json_serializable

### ISSUE THREAD

**Issue by rio45ka** [Stacked-Org/stacked#275]
Hello, 
First of all, i would say thanks for awesome library.
I'm new for using stacked_generator, before using this im using auto_route.
But when i'm trying to migrate, and using stacked_generator.

Its error like incompatible with json_serializable (source_gen) like this:

"Because no versions of json_serializable match >4.1.0 <5.0.0 and json_serializable 4.1.0 depends on source_gen ^1.0.0, json_serializable ^4.1.0 requires source_gen ^1.0.0.
And because every version of stacked_generator depends on source_gen ^0.9.0, json_serializable ^4.1.0 is incompatible with stacked_generator."

Can you help me?

**Comment by FilledStacks** [comment]
Please check the latest null safe version 0.3.1-nullsafety.3
