### ISSUE TITLE
Error on load ViewModel when migrate to 2.0.0-nullsafety.2

### ISSUE THREAD

**Issue by Spiderbezno** [Stacked-Org/stacked#278]
I migrated from 1.9.7 to 2.0.0-nullsafety.2(with 1.9.7 all is OK) and when I load my ViewModel:
@override
  Widget build(BuildContext context) {
    return ViewModelBuilder<MyPhonePostpaidTabViewModel>.reactive(
      viewModelBuilder: () => MyPhonePostpaidTabViewModel(context),
      fireOnModelReadyOnce: true,
      onModelReady: (MyPhonePostpaidTabViewModel viewModel) {
        viewModel.startView();
      },
      builder: (BuildContext context, MyPhonePostpaidTabViewModel viewModel, Widget child) {
        return Scaffold(
          appBar: AppBar(......

appear this error:

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following ProviderNotFoundException was thrown building
Consumer<MyPhonePostpaidTabViewModel>(dirty):
Error: Could not find the correct Provider<MyPhonePostpaidTabViewModel> above this
Consumer<MyPhonePostpaidTabViewModel> Widget

This happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:

- You added a new provider in your `main.dart` and performed a hot-reload.
  To fix, perform a hot-restart.

- The provider you are trying to read is in a different route.

  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.

- You used a `BuildContext` that is an ancestor of the provider you are trying to read.

  Make sure that Consumer<MyPhonePostpaidTabViewModel> is under your
MultiProvider/Provider<MyPhonePostpaidTabViewModel>.
  This usually happens when you are creating a provider and trying to read it immediately.

  For example, instead of:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // Will throw a ProviderNotFoundError, because `context` is associated
      // to the widget that is the parent of `Provider<Example>`
      child: Text(context.watch<Example>()),
    ),
  }
  ```

  consider using `builder` like so:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // we use `builder` to obtain a new `BuildContext` that has access to the provider
      builder: (context) {
        // No longer throws
        return Text(context.watch<Example>()),
      }
    ),
  }
  ```

If none of these solutions work, consider asking for help on StackOverflow:
https://stackoverflow.com/questions/tagged/flutter

The relevant error-causing widget was:
  Consumer<MyPhonePostpaidTabViewModel>
  file:///Users/prodriguez/.pub-cache/hosted/pub.dartlang.org/stacked-2.0.0-nullsafety.2/lib/src/state_management/view_model_builder.dart:166:14

When the exception was thrown, this was the stack:
#0      Provider._inheritedElementOf (package:provider/src/provider.dart:332:7)
#1      Provider.of (package:provider/src/provider.dart:284:30)
#2      Consumer.buildWithChild (package:provider/src/consumer.dart:182:16)
#3      SingleChildStatelessWidget.build (package:nested/nested.dart:259:41)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4569:28)
#5      SingleChildStatelessElement.build (package:nested/nested.dart:279:18)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#8      StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#11     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:456:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#13     ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#14     _InheritedProviderScopeElement.update (package:provider/src/inherited_provider.dart:477:11)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#18     StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#21     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#23     StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#26     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#28     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2694:33)
#29     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:873:21)
#30     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#31     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#32     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#33     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by FilledStacks** [comment]
Looking into these issues

**Comment by FilledStacks** [comment]
Please check this in stacked 2.0.0
