### ISSUE TITLE
Nested Navigation weird behavior

### ISSUE THREAD

**Issue by kodjosama** [Stacked-Org/stacked#279]
According to stacked [documentation on nested navigation](https://pub.dev/packages/stacked#nested-navigation).

Every time i try to navigate to a nested view like this
```dart
_navigationService.navigateTo(DrawerNavigatorRoutes.homeView, id: 1);
```
 I got an exception: `route id (1) not found`
```dart
Route id (1) not found
```

#### Here is the routes tree: 

- /
- /login-view
- /drawer-navigator
  - /
  - /setting-view
- /tab-navigator
  - /

After many trials, i noticed two things:

- First, i can navigate to the initial route of a nested route by doing 
```dart
_navigationService.navigateTo(Routes.drawerNavigator);
```
or
```dart
_navigationService.navigateTo(Routes.tabNavigator);
```

- And last one,
```dart
_navigationService.navigateTo('${Routes.drawerNavigator}${DrawerNavigatorRoutes.settingView}');
```

With this last one, i can navigate to any route of a nested navigator.

**Can anyone explain this weird behavior?** 😅  😅 

- [ ] update stacked docs

[Link to test repository](https://github.com/kodjosama/flutter-nested-navigation), you can clone and test it.

PS: @FilledStacks You do great work! 🥇  :star_struck: :star_struck: , i want to thank you :satisfied:

**Comment by FilledStacks** [comment]
Did you do this part above the line you're referring to?

```dart
class OtherNavigator extends StatelessWidget {
  ...
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ExtendedNavigator(router: OtherNavigatorRouter(), navigatorKey: StackedService.nestedNavigationKey(1)));
  }
}
```

**Comment by kodjosama** [comment]
Yes

**Below the source code for drawer navigator**

```dart
class DrawerNavigator extends StatelessWidget {
  ...
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ExtendedNavigator(
        router: DrawerNavigatorRouter(),
        navigatorKey: StackedService.nestedNavigationKey(1),
      ),
    );
  }
}
```

**and for tab navigator**

```dart
class TabNavigator extends StatelessWidget {
  ...
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ExtendedNavigator(
        router: TabNavigatorRouter(),
        navigatorKey: StackedService.nestedNavigationKey(2),
      ),
    );
  }
}
```

**Comment by FilledStacks** [comment]
I'll have to look into this. I haven't used nested navigators before. I exposed this directly from the get package.

**Comment by kodjosama** [comment]
Ok, I think I'll create an issue on their repository and update the docs.

**Comment by consciousmayank** [comment]
Any solution the question by @kodjosama @FilledStacks ? I am also facing the similar issue. I have done everything which is mentioned in the docs.

**Comment by FilledStacks** [comment]
@consciousmayank it's because the routes were generated at the route of the app. If you want nested routes for real you need to nest them in the app.dart file. 

```dart
 MaterialRoute(page: SignUpSheetView, 
  children: [
      CupertinoRoute(page: AuthenticationOptionsSheetView, initial: true),
      CupertinoRoute(page: ContinueWithEmailSheetView),
      CupertinoRoute(page: CreatePasswordSheetView),
    ],
),
```

This  way you can only navigate to `SignUpSheetView` and not directly to the `AuthenticationOptionsSheetView` or `ContinueWithEmailSheetView` .
