### ISSUE TITLE
App Architecture 

### ISSUE THREAD

**Issue by vptcnt** [Stacked-Org/stacked#28]
Hello Dane,

I am still trying to discover stacked and how to implement it in a full app.
I have quite easily transposed screens into views/viewmodel, and api into services. Thanks again for the tip about AutomaticKeepAliveClientMixin.

But now, I can't figure out how a view can influence another view. 
For exemple :

If I have a MainView/MainViewModel : a Scaffold with some infos, a DrawerView/DrawerViewModel and a button to log in ...
The Login screen is a LoginView (stacked) with a LoginViewModel.
One the login is successful, how to update the Drawer (to see more options) and the MainView (change the log in button to a logout button)..

Thanks for your advice

Vincent

**Comment by FilledStacks** [comment]
Hi @vptcnt in the readme there's a part for reactivity. Put the data you want to share in a service, make the service reactive, make the value you want to share an rx value then use the reactive viewmodel functionality to react to those service changes.
