### ISSUE TITLE
stacked_themes 0.2.4 - no way to get current theme index with multiple themes

### ISSUE THREAD

**Issue by bbedward** [Stacked-Org/stacked#284]
Hi,

We started to setup multiple themes using stacked_themes and we noticed there's no way to get what the current theme is.

main.dart
```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return ThemeBuilder(
      defaultThemeMode: ThemeMode.system,
      themes: [themeOne, themeTwo, themeThree],
      builder: (context, regularTheme, darkTheme, themeMode) => MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'My App',
        theme: regularTheme,
        darkTheme: darkTheme,
        themeMode: themeMode,
        navigatorKey: StackedService.navigatorKey,
        onGenerateRoute: StackedRouter().onGenerateRoute,
      ),
    );
  }
}
```

We are looking for something like

```
getThemeManager(context).getSelectedTheme()
```

However from reading the documentation and checking the code we couldn't seem to find anything. There is `isDarkMode` but that isn't particularly helpful for multiple themes.

We temporarily worked around this by importing the shared_preferences_service from the package and registering it in our locator like this:

```dart
import 'package:myapp/app/app.locator.dart';
import 'package:stacked/stacked.dart';
import 'package:stacked_themes/src/services/shared_preferences_service.dart';
import 'package:stacked_themes/stacked_themes.dart';

class MyViewModel extends BaseViewModel {
  final SharedPreferencesService _themeSharedPrefs = locator<SharedPreferencesService>();

  int getSelectedTheme() {
    return _themeSharedPrefs.themeIndex;
  }
}
```

Obviously not an ideal solution, either we're missing something or are requesting this to be part of the package.

Thank you for this framework and all you guys are doing for flutter developers!

**Comment by FilledStacks** [comment]
Hey @bbedward this is a good request. 

You can make a PR if you need it soon, otherwise it'll go through our priority list and get worked on as we get some time.
