### ISSUE TITLE
NavigationService.currentRoute always empty

### ISSUE THREAD

**Issue by DirtyNative** [Stacked-Org/stacked#287]
I am using the NavigationService to navigate through my app. I register it via injectable:

`
@singleton
NavigationService get navigationService;
`

and navigate with

`
_navigationService.navigateTo('register');
`

My startup looks like this:

```
MaterialApp(
        navigatorKey: StackedService.navigatorKey,
        onGenerateRoute: generateRoute,
        initialRoute: 'login',
      ),
```

And the generateRoute():

```
Route<dynamic> generateRoute(RouteSettings settings) {
  switch (settings.name) {
    case 'login':
      return MaterialPageRoute(builder: (_) => LoginView());

    case 'register':
      return MaterialPageRoute(builder: (_) => RegisterView());
  }

  return MaterialPageRoute(
    builder: (_) => Scaffold(
      body: Center(
        child: Text('No path for ${settings.name}'),
      ),
    ),
  );
}
```

The problem is, that NavigationService.currentRoute never gets any value, neither does NavigationService.previousRoute. Both are always an empty String

**Comment by e-e** [comment]
@DirtyNative did you find a solution to this?

**Comment by DirtyNative** [comment]
@e-e  Yes, there was an other one facing this issue and it was resolved. Just check the closed tickets

**Comment by e-e** [comment]
For anyone else that finds this, make sure you have an up-to-date version of stacked and see https://pub.dev/packages/stacked_services#route-observation
