### ISSUE TITLE
How to make RxList notify ReactiveViewModel?

### ISSUE THREAD

**Issue by ahmetcj4** [Stacked-Org/stacked#29]
I'm trying to hold a list of items and use it in multiple viewmodels. Currently, I could achieve this by manually notifying view models.

**Comment by ahmetcj4** [comment]
Currently I implement the method below to make the field notify viewmodels. A more correct solution would be implementing RxList version of `ReactiveServiceMixin`

```
notifyChange() {
    var value = _orders.value;
    _orders.value = [];
    _orders.value = value;
}
```

**Comment by FilledStacks** [comment]
Oooooof, that's a big ask. But it'll probably be worth it. If I do that I will most likely get rid of the Observable-ish package and build it into stacked. When I get time I will check if I can do a quick implementation for it with the basic functionality

**Comment by FilledStacks** [comment]
I will start looking at this in about 2 hours. If it's not built into Observable-ish I will the code for it and include it in stacked. Will probably fork Observable-Ish if it's open to use in that way and keep it locally as well.

**Comment by FilledStacks** [comment]
I read this completely wrong haha. I see what you're asking now. There's no common interface for those classes so I'll definitely have to spend some more time on the implementation. I might get this into stacked and rebuild the functionality myself to match the requirements.

**Comment by FilledStacks** [comment]
@ahmetcj4 Update to 1.5.0 and you should have the RxList functionality. To use RxList you change don't wrap your entire list like this.

```
RxList<List<int>>
```
Instead you use RxList as the list type
```
RxList<int>
```
