### ISSUE TITLE
[stacked_themes] Exception (...) _themeManager@929083297' has not been initialized

### ISSUE THREAD

**Issue by sqrg** [Stacked-Org/stacked#290]
I'm trying to implement themes on an app, but I get this error on launch

```
Exception has occurred.
LateError (LateInitializationError: Field '_themeManager@929083297' has not been initialized.)
```

Following [this](https://www.filledstacks.com/post/multiple-themes-in-flutter-dark-and-light-theme-flutter-stacked/), I changed the `main()` to a Future, added the `await ThemeManager.initialise();`, wrapped the MaterialApp with a `ThemeBuilder`, etc.

But when I try to `_themeService.toggleDarkLightTheme();` on a viewmodel, I get the previous exception. Any ideas?

You can see a (non) working example at https://github.com/sqrg/flutter_base_project, and the failing code is in https://github.com/sqrg/flutter_base_project/blob/master/lib/core/viewmodels/debug/debug_viewmodel.dart

**Comment by kodjosama** [comment]
In your project, line [19](https://github.com/sqrg/flutter_base_project/blob/master/lib/app.dart#L19) in app.dart is incorrect.

Replace this line

```dart
LazySingleton(classType: ThemeService),
```

with this

```dart
LazySingleton(classType: ThemeService, resolveUsing: ThemeService.getInstance),
```

Follow the documentation [https://pub.dev/packages/stacked#dependency-registration](https://pub.dev/packages/stacked#dependency-registration) for more details.

**Comment by sqrg** [comment]
Thanks! Now it's working :)
