### ISSUE TITLE
textformfield being set to empty when keyboard is closed

### ISSUE THREAD

**Issue by humayuntanwar** [Stacked-Org/stacked#295]
i m using the stacked architecture with reactive/nonreactive method
everytime i press the back /enter key on the keyboard the text field is set to null
as per my knowledge the textfieldcontroller needs to be used with a statefull class how we can accomplish this with stacked?

```dart
var _inputSurnameController = TextEditingController();
String _inputName;

  return ViewModelBuilder<SignupViewModel>.reactive(
      builder: (context, model, child) {
        return Scaffold()//dummy code

TextFormField(
                      controller: _inputNameController,
                      onChanged: (value) {
                        print(value);
                        _inputName = value;
                        updateButtonState(model);
                      },
                      style: TextStyle(color: AppColors.brandBlue),
                      decoration: InputDecoration(
                        labelText: "Name",
                        labelStyle: TextStyle(color: AppColors.brandDarkGrey),
                        contentPadding: EdgeInsets.fromLTRB(10, 5, 0, 0),
                      ),
                    ),
```

**Comment by FilledStacks** [comment]
I would recommend you use Stacked to generate your `TextEdittingController` for you.

**Comment by Silfalion** [comment]
Sorry just to be sure, you mean with FormView, right?

**Comment by manafire** [comment]
I think he means with form generation as illustrated in https://youtu.be/Y-JawJ4m6Fg

**Comment by Silfalion** [comment]
Yes, that's what I thought, didn't use it before because of not being able to change the controller's value directly(with a dev made keyboard instead of the system's one for example). But didn't give it much time either, will do that. Thank you.
