### ISSUE TITLE
Is there a way to get the context in the viewmodel?

### ISSUE THREAD

**Issue by sqrg** [Stacked-Org/stacked#296]
I would like to use https://pub.dev/packages/another_flushbar from the viewmodel, but it seems that I need access to the context.

I know that there's a snackbar service within stacked_services, but I would like to customize the UI

**Comment by merfire** [comment]
@sqrg You can pass context from View to ViewModel through the constructor.

From your View pass context to the ViewModel constructor:
```dart
viewModelBuilder: () => ExampleViewModel(context),
```

ViewModel:
```dart
BuildContext _context;

ExampleViewModel(BuildContext context){
  _context = context;
}
```

**Comment by FilledStacks** [comment]
@sqrg It goes against the stacked rules to have the BuildContext in the viewmodel. It's supposed to be completely unit testable code that's not reliant on anything from the UI side. 

You can customise the snackbar with the stacked_services. Or if you want to use another flushbar then wrap it in a service as well and use the manager patern that I've shown for the old implementation of the `DialogManager`.
