### ISSUE TITLE
Removed observable_ish, how to migrate?

### ISSUE THREAD

**Issue by binaris-no** [Stacked-Org/stacked#297]
So, I'm using a bunch of RxValue and RxList (mostly in services/managers, and in combination with bunch of ReactiveViewModel's). How to migrate now that observable_ish is removed?
I do tried quickly with a direct dependency on observable_ish 3.0.0, but got a hanging app (without having researched further on where that might originate from).

I suppose the cleanest way to proceed is to remove all Rx*, but how do you wire up things then?

Any examples?

**Comment by binaris-no** [comment]
I suppose this is the main clue?


```
mixin ReactiveServiceMixin {
...

  /// List to the values and react when there are any changes
  void listenToReactiveValues(
      @Deprecated('Prefer to use the notifyListeners call in the service when you want your ViewModel to rebuild. Observable_Ish has been removed')
          List<dynamic> reactiveValues) {
    for (var reactiveValue in reactiveValues) {
      if (reactiveValue is ChangeNotifier) {
        reactiveValue.notifyListeners();
      }
    }
  }

...
}
```

**Comment by FilledStacks** [comment]
@binaris-no i was hoping that there wasn't an excess use of it. The package had to be removed but I might have to implement that in stacked so it's maintained properly. 

Currently the way we do it is the same as in a viewmodel. You update your value then call notifyListeners afterward. 
it's not the prettiest thing at the moment, sorry about that. It's basically manual. 

I'll move the implementation into stacked and will expose the functionality again for you.

**Comment by merfire** [comment]
@binaris-no
Check this [example](https://github.com/FilledStacks/stacked/issues/88#issuecomment-686240887). I think you need also need [this](https://github.com/FilledStacks/stacked/tree/master/packages/stacked#reactive-view-model) to connect Reactive Service with the ViewModel.

**Comment by binaris-no** [comment]
I'm in process of ditching the dependency on Rx objects and manually calling notifyListeners is not an issue, since the wiring and the syntax for the Rx* was somewhat unusual to begin with. The code is even shorter. I expect to know how this works out in a day or so.

**Comment by FilledStacks** [comment]
@binaris-no quickly moved it over for you if you want to use it. It's a bit more verbose. `ReactiveValue` and `ReactiveList` . I wanted to get this started because I think there's some cool boiler plate things we can get working on down the line. Now that this is in there I think we can get an idea of what to do. 

Thanks for filing the issue. I'll close it now.
