### ISSUE TITLE
Issue when generate Navigation after upgrade Flutter v2

### ISSUE THREAD

**Issue by yusufhnf** [Stacked-Org/stacked#299]
I have some problem when generating navigation service with the command:
`flutter pub run build_runner build --delete-conflicting-outputs`

After running that command, I got some error like this:
`[INFO] Generating build script...
[INFO] Generating build script completed, took 354ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 132ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 766ms

[INFO] Running build...
[INFO] Running build completed, took 42ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 82ms

[SEVERE] stacked_generator:stackedRouterGenerator on lib/app/app.dart (cached):
An error `FormatterException` occurred while formatting the generated source for
  `package:zeniora/app/app.dart`
which was output to
  `lib/app/app.router.dart`.
This may indicate an issue in the generator, the input source code, or in the
source formatter.
Could not format because the source could not be parsed:

line 382, column 13 of .: Methods must have an explicit list of parameters.
    ╷
382 │ final String* ujianID;
    │             ^
    ╵
line 327, column 12 of .: A function body must be provided.
    ╷
327 │ final Key* key;
    │            ^^^
    ╵
line 355, column 13 of .: Operator declarations must be preceded by the keyword 'operator'.
    ╷
355 │ final String* ujianID;
    │             ^
    ╵
line 346, column 13 of .: Methods must have an explicit list of parameters.
    ╷
346 │ final String* title;
    │             ^
    ╵
line 288, column 12 of .: A function body must be provided.
    ╷
288 │ final Key* key;
    │            ^^^
    ╵
line 297, column 7 of .: Expected to find ';'.
    ╷
297 │ final String* ujianID;
    │       ^^^^^^
    ╵
line 295, column 12 of .: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
    ╷
295 │ final Key* key;
    │            ^^^
    ╵
line 296, column 7 of .: Expected to find ';'.
    ╷
296 │ final String* sesiID;
    │       ^^^^^^
    ╵
line 337, column 13 of .: Operator declarations must be preceded by the keyword 'operator'.
    ╷
337 │ final String* ujianUserID;
    │             ^
    ╵
line 319, column 10 of .: Operator declarations must be preceded by the keyword 'operator'.
    ╷
319 │ final Key* key;
    │          ^
    ╵
(213 more errors...)
[SEVERE] Failed after 138ms
pub finished with exit code 1`

**For additional information**

- stacked_generator: ^0.3.1-nullsafety.3
- auto_route_generator: ^1.0.2
- injectable_generator: ^1.2.2
- build_runner:
- stacked: ^2.0.0
- stacked_services: ^0.7.3

app.dart code:
`import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
import 'package:zeniora/screens/analisis_screen.dart';
import 'package:zeniora/screens/forgotpassword_screen.dart';
import 'package:zeniora/screens/home_screen/detail_bacaan_screen.dart';
import 'package:zeniora/screens/home_screen/detail_forum_screen.dart';
import 'package:zeniora/screens/home_screen/home_screen.dart';
import 'package:zeniora/screens/home_screen/list_pertanyaan_screen.dart';
import 'package:zeniora/screens/home_screen/new_question_screen.dart';
import 'package:zeniora/screens/home_screen/search_screen.dart';
import 'package:zeniora/screens/landing_screen.dart';
import 'package:zeniora/screens/leaderboard_screen.dart';
import 'package:zeniora/screens/login_screen.dart';
import 'package:zeniora/screens/notification_screen.dart';
import 'package:zeniora/screens/privacy_screen.dart';
import 'package:zeniora/screens/profile_screen/bonus_referal_screen.dart';
import 'package:zeniora/screens/profile_screen/choose_avatar_screen.dart';
import 'package:zeniora/screens/profile_screen/edit_profile_screen.dart';
import 'package:zeniora/screens/profile_screen/kode_promo_screen.dart';
import 'package:zeniora/screens/profile_screen/profile_screen.dart';
import 'package:zeniora/screens/profile_screen/referal_screen.dart';
import 'package:zeniora/screens/quiz_screen.dart';
import 'package:zeniora/screens/register_screen/register_screen.dart';
import 'package:zeniora/screens/splash_screen.dart';
import 'package:zeniora/screens/statistik_screen.dart';
import 'package:zeniora/screens/top_up_screen/checkout_screen.dart';
import 'package:zeniora/screens/top_up_screen/get_premium_screen.dart';
import 'package:zeniora/screens/top_up_screen/riwayat_pembelian_screen.dart';
import 'package:zeniora/screens/top_up_screen/top_up_dashboard_screen.dart';
import 'package:zeniora/screens/webview_screen.dart';
import 'package:zeniora/screens/zenito_screen/zenito_dashboard_screen.dart';
import 'package:zeniora/screens/zenito_screen/zenito_detail_screen.dart';
import 'package:zeniora/screens/zenito_screen/zenito_instruksi_screen.dart';
import 'package:zeniora/screens/zenito_screen/zenito_pilih_passinggrade_screen.dart';
import 'package:zeniora/screens/zenito_screen/zenito_pilih_sesi_screen.dart';
import 'package:zeniora/screens/zenito_screen/zenito_result_screen.dart';

@StackedApp(
  routes: [
    MaterialRoute(page: SplashScreen, initial: true),
    MaterialRoute(page: AnalisisScreen),
    MaterialRoute(page: ForgotPasswordScreen),
    MaterialRoute(page: HomeScreen),
    MaterialRoute(page: LeaderBoardScreen),
    MaterialRoute(page: LoginScreen),
    MaterialRoute(page: NotificationScreen),
    MaterialRoute(page: QuizScreen),
    MaterialRoute(page: RegisterScreen),
    MaterialRoute(page: StatistikScreen),
    MaterialRoute(page: LandingScreen),
    MaterialRoute(page: BonusReferalScreen),
    MaterialRoute(page: EditProfileScreen),
    MaterialRoute(page: KodePromoScreen),
    MaterialRoute(page: ProfileScreen),
    MaterialRoute(page: ReferalScreen),
    MaterialRoute(page: TopupDashboardScreen),
    MaterialRoute(page: RiwayatPembelianScreen),
    MaterialRoute(page: CheckoutScreen),
    MaterialRoute(page: ZenitoDashboardScreen),
    MaterialRoute(page: ZenitoDetailScreen),
    MaterialRoute(page: ZenitoPilihPasingGradeScreen),
    MaterialRoute(page: SearchScreen),
    MaterialRoute(page: ZenitoResultScreen),
    MaterialRoute(page: ZenitoPilihSesiScreen),
    MaterialRoute(page: WebViewScreen),
    MaterialRoute(page: GetPremiumScreen),
    MaterialRoute(page: ZenitoInstruksiScreen),
    MaterialRoute(page: ChooseAvatarScreen),
    MaterialRoute(page: DetailBacaanScreen),
    MaterialRoute(page: DetailForumScreen),
    MaterialRoute(page: NewQuestionScreen),
    MaterialRoute(page: ListPertanyaanScreen),
    MaterialRoute(page: PrivacyScreen)
  ],
  dependencies: [
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: SnackbarService),
    LazySingleton(classType: BottomSheetService),
  ],
)
class AppSetup {
  /** Serves no purpose besides having an annotation attached to it */
}
`

**Comment by FilledStacks** [comment]
Hey,

This means you're trying to generate null-safe code but the file the StackedApp is defined in is not null safe. Check it's not marked with //@dart=2.9 and make sure your min sdk version is 2.12.0

**Comment by FilledStacks** [comment]
Did you try the changes I suggested?

**Comment by yusufhnf** [comment]
> Did you try the changes I suggested?

Wait, Let me try. For the version of package in puspec.yaml are true?

**Comment by yusufhnf** [comment]
Solved when I change min sdk version number. Thank you.
