### ISSUE TITLE
The ViewModel variable name is inconsistent

### ISSUE THREAD

**Issue by Moseco** [Stacked-Org/stacked#301]
The ViewModel variable name is inconsistent in the stacked package. 

`ViewModelBuilder` uses just `model`. For example:

```dart
return ViewModelBuilder<HomeViewModel>.reactive(
    builder: (context, model, child) => Scaffold() 
);
```

While the `ViewModelWidget` uses `viewModel`. For example: 

```dart
class Widget extends ViewModelWidget<HomeViewModel> {
  @override
  Widget build(BuildContext context, HomeViewModel viewModel) {
    return Container();
  }
}
```

@FilledStacks I can create a PR to make it consistent, would you have a preference for which variable name to use? I think I prefer just `model` and it seems like you do as well looking at the readme.

**Comment by FilledStacks** [comment]
@Moseco that would be great. Thanks for picking that up. I think we should use `viewModel`.
