### ISSUE TITLE
[stacked_generator] duplicated import in app.router.dart

### ISSUE THREAD

**Issue by ecerroni** [Stacked-Org/stacked#312]
I am getting `material.dart` imported twice, one from a relative path:

```
import 'package:flutter/material.dart';
import 'package:stacked/stacked.dart';

import '../../flutter/material.dart';
```

This causes the following error:
```
The name 'MaterialPageRoute' is defined in the libraries 'package:/flutter/src/material/page.dart (via package:/flutter/material.dart)' and 'package:flutter/src/material/page.dart (via package:flutter/material.dart)'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.
```

Setup:
**stacked_generator version: 0.3.2**

**Comment by FilledStacks** [comment]
that's strange. haven't seen that before. Will look into it.

**Comment by ecerroni** [comment]
That is strange indeed. I thought the same while I was wondering if it could be related to my setup although I am not doing anything special in it :thinking:

**Comment by FilledStacks** [comment]
@ecerroni will get that worked on today.

**Comment by FilledStacks** [comment]
@ecerroni we can't reproduce this issue on our side.

**Comment by ecerroni** [comment]
Then it's probably something on my side. If I eventually get any clue that exposes it as an actual bug not related to my setup I'll reopen the issue 👍 

Thanks for having looked into it.

**Comment by nickbug** [comment]
hi @FilledStacks  @ecerroni i have same problem, do u find the solution?

i find something interesting between project name and problem

| Project Name  |  Error |
|-----------------|--------|
|flutter_app1    |   yes |
|flutterapp1 | yes |
|flutters | yes |
|app1 | no |
|flutteapp1 | no|
|fluttes | no|

I have no idea what happened ......

Setup:
  stacked: 1.9.8
  stacked_services: 0.7.3
  build_runner: 1.12.2
  stacked_generator: 0.2.7
