### ISSUE TITLE
Stacked_services clearStackAndShow

### ISSUE THREAD

**Issue by YoussefGheith** [Stacked-Org/stacked#32]
Hi 
First of all thank u for this awesome package .
 Second 
 I’m getting this error when I’m  using clearStackAndShow method to navigate .

`Unhandled Exception: Bad state: Future already completed`

method pushNamedAndRemoveUntil works fine though .
Using Version ^0.2.2  .

**Comment by FilledStacks** [comment]
Mmmmm, thanks for mentioning. I'll check it out when I get a chance.

**Comment by akifarhan** [comment]
Hi, i also getting somewhat similar error from the clearStackAndShow.

`Unhandled Exception: Bad state: No element`

Version ^0.2.1

**Comment by surveshoeb** [comment]
@FilledStacks still having this exception in Ver 0.3.1
In my scenario, I'm trying to route to next page with an argument.

**Comment by FilledStacks** [comment]
@surveshoeb I've posted an update for your problem. @akifarhan I don't see that functionality.

**Comment by FilledStacks** [comment]
@akifarhan try v 0.3.2+1

I was doing a replace after clearing the entire stack so there was no element to replace which gave the bad state exception. i now use the built in get function

**Comment by surveshoeb** [comment]
@FilledStacks It's not fixed yet. I have upgraded the package to **0.3.1+1**.

**Error**

> E/flutter ( 1007): #0      ListMixin.lastWhere (dart:collection/list.dart:163:5)
E/flutter ( 1007): #1      NavigatorState.popUntil (package:flutter/src/widgets/navigator.dart:3621:32)
E/flutter ( 1007): #2      NavigationService._clearBackstackCompletely (package:stacked_services/src/navigation_service.dart:177:31)
E/flutter ( 1007): #3      NavigationService.clearStackAndShow (package:stacked_services/src/navigation_service.dart:150:5)

`replaceWith()` works fine but if I have to clear stack and move to next page I need to use `clearStackAndShow()`

**Comment by FilledStacks** [comment]
@surveshoeb  Try 0.3.2+1

**Comment by FilledStacks** [comment]
I'm using it in my project and it's working fine

**Comment by surveshoeb** [comment]
Fixed! You can close this issue. Liked your speedy response.

**Comment by FilledStacks** [comment]
@YoussefGheith Can I close this issue?

**Comment by YoussefGheith** [comment]
i will

thank you!
