### ISSUE TITLE
Get.off warning in NavigationService when using replaceWithTransition

### ISSUE THREAD

**Issue by JayPerfetto** [Stacked-Org/stacked#322]
[GETX] WARNING, consider using: "Get.off(() => Page())" instead of "Get.off(Page())".

could be fixed by a minor change:
```
    return Get.off(
      () => page,
```

**Comment by FilledStacks** [comment]
In the latest version this should be fixed

**Comment by hurbes** [comment]
It is fixed in release 0.8.3
