### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by ParadiseFallen** [Stacked-Org/stacked#324]
Navigation is strange cuz u navigating from vm to view. In normall MVVM u will never navigate to view. U navigating to another view model and resolver on top level create view for view model

**Comment by ParadiseFallen** [comment]
but for some reason in stacked when u navigating u use view as target and not view model

**Comment by FilledStacks** [comment]
Yes that's correct. We had to build it according to the Flutter navigation functionality that exists and the best way to do that was to use the named routing. You don't actually navigate to the view. You're giving flutter a name for the route to resolve and then it constructs your view for you through the onGenerateRoute function.
