### ISSUE TITLE
Why does _DataProviderElement not mark the widget as dirty?

### ISSUE THREAD

**Issue by ricksecretin** [Stacked-Org/stacked#327]
After going a bit through the source code of Stacked I found the following difference in the following class between StatelessWidget and ViewModelWidget.

    class _DataProviderElement<T> extends ComponentElement {
      ...

      @override
      void update(ViewModelWidget newWidget) {
        super.update(newWidget);
        assert(widget == newWidget);
        rebuild();
      }
    }

     class StatelessElement extends ComponentElement {
       ...

      @override
      void update(StatelessWidget newWidget) {
        super.update(newWidget);
        assert(widget == newWidget);
        _dirty = true; <--- this is marked as dirty
        rebuild();
      }
    }

I am wondering why this is the case and if it's correct.

Thanks,

Rick

**Comment by FilledStacks** [comment]
@ricksecretin we don't use that value internally as we only want to build once and then rebuild ourselves using `notifyListeners`. I also think that at the time of building stacked that value was not being set to _dirty. 

Maybe it should be added.

**Comment by FilledStacks** [comment]
If you can make a PR of this I can keep this issue open. Otherwise I will close it.
