### ISSUE TITLE
Stacked_services - Compiler Error - Dependency on get

### ISSUE THREAD

**Issue by giiyms** [Stacked-Org/stacked#33]
Hello, 

Looks like dependency on get is outdated for anything 

> Because my_app depends on stacked_services any which depends on get ^1.17.3, get ^1.17.3 is required.

Getting error from compiler:

> Launching lib\main.dart on Android SDK built for x86 in debug mode...
> 
> Compiler message:
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
>   void install(OverlayEntry insertionPoint) {
>        ^
> /C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
>   void install() {
>        ^
> 
> Compiler message:
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/snackbar/snack_route.dart:279:8: Error: The method 'SnackRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
>   void install(OverlayEntry insertionPoint) {
>        ^
> /C:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
>   void install() {
>        ^
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/routes/default_route.dart:242:9: Error: No named parameter with the name 'animation'.
>         animation: animation,
>         ^^^^^^^^^
> /C:/flutter/packages/flutter/lib/src/cupertino/route.dart:436:3: Context: Found this candidate, but the arguments don't match.
>   CupertinoFullscreenDialogTransition({
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/snackbar/snack_route.dart:289:18: Error: Too many positional arguments: 0 allowed, but 1 found.
> Try removing the extra positional arguments.
>     super.install(insertionPoint);
>                  ^
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/routes/default_route.dart:242:9: Error: No named parameter with the name 'animation'.
>         animation: animation,
>         ^^^^^^^^^
> /C:/flutter/packages/flutter/lib/src/cupertino/route.dart:436:3: Context: Found this candidate, but the arguments don't match.
>   CupertinoFullscreenDialogTransition({
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/get-1.17.3/lib/src/snackbar/snack_route.dart:289:18: Error: Too many positional arguments: 0 allowed, but 1 found.
> Try removing the extra positional arguments.
>     super.install(insertionPoint);
>                  ^
> Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
> build failed.
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildDebug'.
> > Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 23s
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)

This is version:
[√] Flutter (Channel dev, 1.18.0-9.0.pre, on Microsoft Windows [Version 10.0.18362.778], locale en-US)

Any ideas how to get around this?

**Comment by FilledStacks** [comment]
If you're on a branch other than stable you need to override the get package version in your code to point to the one required. [2.0.9-dev ](https://pub.dev/packages/get/versions/2.0.9-dev)

**Comment by elhe26** [comment]
This PR: #35 resolves the errors.

@giiyms please verify.

**Comment by giiyms** [comment]
Yes it works.
