### ISSUE TITLE
[stacked_services] 0.8.3 currentRoute doesn't work for nested routes

### ISSUE THREAD

**Issue by bbedward** [Stacked-Org/stacked#331]
Relevant to #218, currentRoute still doesn't work as expected for nested routes.

Having routes such as:

```dart
  MaterialRoute(page: LoginView, initial: true),
  MaterialRoute(
    page: DrawerNavigatorView,
    children: [
      CustomRoute(page: HomeView, initial: true),
      CustomRoute(page: ReportsView),
      CustomRoute(page: TeamView),
      CustomRoute(page: SettingsView),
      CustomRoute(page: SupportView),
    ],
  ),
```

When on one of the nested routes, e.g. `HomeView`, `ReportsView`, `TeamView` the `currentRoute` is always `/drawer-navigator-view`. In our case at least it would be desired to get information about the current nested route as well.

**Comment by hurbes** [comment]
Please try passing `StackedService.routeObserver` into your `ExtendedNavigator` 's `observers`

**Comment by bbedward** [comment]
@hurbes I'm not really sure what you mean, use it somewhere other than the MaterialApp?

**Comment by hurbes** [comment]
You are using `ExtendedNavigator` for those nested routes, right? Try passing the `StackedService.routeObserver` in its `observers` like this
```dart
ExtendedNavigator<HomeViewRouter>(
      router: HomeViewRouter(),
      initialRoute: Routes.streamCounterView,
      observers: [StackedService.routeObserver],
      navigatorKey: StackedService.nestedNavigationKey(1),
 );
  ```

**Comment by bbedward** [comment]
Ah yes, that works. Thank you
