### ISSUE TITLE
setupLocator always returns void 

### ISSUE THREAD

**Issue by sanalkv** [Stacked-Org/stacked#333]
I'm not able to use await for setupLocator. I would like the setupLocator to return a future<void> if there is any class type that requires resolving the future. 

instead of `  locator.registerLazySingleton(() => SharedPreferenceService.getInstance());`, it should be 
`  locator.registerLazySingleton(() async=> await SharedPreferenceService.getInstance());`

**Comment by hurbes** [comment]
Use `Presolve` for registering async instance and make sure `getInstance` has Future return type

```dart
 Presolve(
      classType: LocalStorageService,
      presolveUsing: LocalStorageService.getInstance,
    )
 ```

**Comment by sanalkv** [comment]
I'm using `presolve`. `getInstance` returns `static Future<SharedPreferenceService> getInstance()`

**Comment by sanalkv** [comment]
@FilledStacks

**Comment by sanalkv** [comment]
@kodjosama

**Comment by kodjosama** [comment]
share a snippet code of the app.dart file

**Comment by FilledStacks** [comment]
Using this

```dart
  Presolve(
    classType: CloudLoggingService,
    presolveUsing: CloudLoggingService.getInstance,
  ),
```

Will generate this

```dart
Future setupLocator() async {
  final sharedPreferencesService = await SharedPreferencesService.getInstance();
  locator.registerSingleton(sharedPreferencesService);
}
```

so it's a Future you can await. We use this exact functionality
