### ISSUE TITLE
[stacked] [stacked_generator] How can we pass data to singleton or lazy singleton or factory

### ISSUE THREAD

**Issue by kodjosama** [Stacked-Org/stacked#334]
How can I pass parameters to a singleton or lazy singleton or factory?

According to get_it documentation and as defined in stacked sources codes

https://github.com/FilledStacks/stacked/blob/f3ec5b5121e0ee9ba527eca4db5af6d6ad8e34b4/packages/stacked/lib/src/code_generation/stacked_locator.dart#L97

we can pass params.

But I didn't find a way to implement that.

#### Code

In _order_list_viewmodel.dart_

```dart
class OrderListViewModel extends BaseViewModel {
    final String? sellerId;

    OrderListViewModel(this.sellerId);

    // ...
}
```

In _app.dart_

```dart
@StackedApp(
    dependencies: [
        const Singleton(classType: OrderListViewModel),
    ]
)
```

**Comment by sanalkv** [comment]
I believe you shouldn't be using a viewmodel as a service.

**Comment by kodjosama** [comment]
Declaring a view model as a singleton makes its function onModelReady gets called only once. it's useful when using BottomNavigationBar.

Links to docs https://pub.dev/packages/stacked#call-onmodelready-only-once

**Comment by sanalkv** [comment]
You can call onModelReady only once using a Boolean parameter present in
the viewmodel builder itself. fireOnModelReadyOnce to true. This will fire
the onModelReady call only once during the lifecycle of the ViewModel.

**Comment by FilledStacks** [comment]
@kodjosama that's something that we should provide you with. I will get that worked on.

@sanalkv it's easier setting up the singleton pattern through get_it. Less code to maintain. We use it in production that way as well.

**Comment by sanalkv** [comment]
Ya, i thought he mentioned about creating viewmodel as singleton and using it inside another view model.

**Comment by kodjosama** [comment]
> Ya, i thought he mentioned about creating viewmodel as singleton and using it inside another view model.

It was not what I'm trying to do 😃 

@FilledStacks I'm trying to understand how the get_it source generator works https://github.com/FilledStacks/stacked/tree/master/packages/stacked_generator/lib/src/generators/getit

I'll try to develop that feature if not yet implemented

**Comment by calvintam236** [comment]
I wonder the same. Please update us when it is ready for testing. Thanks!

**Comment by FilledStacks** [comment]
We should probably tackle this feature at some point @hurbes

**Comment by eb-so** [comment]
@FilledStacks we implemented passing parameters to the factory service, Should we close this?

**Comment by eb-so** [comment]
@FilledStacks  Didn't we fix that by adding the `FactoryWithParam` class?
