### ISSUE TITLE
runBusyFuture return type is always dynamic

### ISSUE THREAD

**Issue by sanalkv** [Stacked-Org/stacked#338]
Is there a way to set the return type of `runBusyFuture` ?. Currently its `Future<dynamic>`.

**Comment by kodjosama** [comment]
You need to cast the result to the desired type.

```dart
final result = await runBusyFuture(...) as CustomType;
```

Ex

- if the future returns an int

```dart
final result = await runBusyFuture(...) as int;
```

- if the future returns a nullable int

```dart
final result = await runBusyFuture(...) as int?;
```

**Comment by sanalkv** [comment]
Thanks for the reply @kodjosama .
