### ISSUE TITLE
ViewModelBuilder keeps triggering future for Desktop/Mobile views

### ISSUE THREAD

**Issue by ghost** [Stacked-Org/stacked#339]
I'm using the same ViewModel for both the Mobile and Desktop view. I also use responsive builder.

When I go to a view, the future runs fine and as expected, however when I change the screen layout and it triggers a different screensize, the future runs again triggering more/new data to load. 

I even set:
`      initialiseSpecialViewModelsOnce: true,
      disposeViewModel: false,`

in both the mobile and desktop viewodelbuilder. 

It's quite slow (as you can imagine) to have to trigger more new data to come in even when all the data is right there.

I'm sure I'm doing something wrong, just not sure what it could/should be. Should I save the data in a local variable once I get it and check to see if it has data first, if not run the future again? I was under the impression the two flags above would prevent it from running again though.

**Comment by FilledStacks** [comment]
The ViewModel for multiple layouts should only be supplied once and not within every layout. This means the layouts will most likely only use the `ViewModelWidget` class. What that means is when the mobile or desktop layout is built the Main view isn't rebuilt but just the layout that's displayed. 

Does that make sense? i show the setup in the flutter web series.
