### ISSUE TITLE
How to pass data from one viewmodel to other model?

### ISSUE THREAD

**Issue by joshiprashanthd** [Stacked-Org/stacked#344]
App has two screens, one to get inputs from user and other to process those inputs and fetch data from server based on those. 

Right now, what I am doing is to keep state of the input in viewmodel
```dart
class ScreenOneViewModel extends BaseViewModel {
    final Language language;
    final Gender gender;
    ...
    // set methods
    ...
    void navigateToScreenTwo() => _navService.navigateTo(Routes.screenTwoView, arguments: 
        ScreenTwoViewArguments(language: language, gender: gender),
    )
}
```

And in screen two I get those arguments and pass them to `init` function of the `ScreenTwoViewModel` to initialize properties in viewmodel. 

```dart
class ScreenTwoViewModel extends BaseViewModel {

    late final Language language;
    late final Gender gender;

    void init(Language lang, Gender gen) {
        langauge = lang;
        gender = gen;
    }

    // process those inputs
}
```

```dart
class ScreenTwoView extends StatelessWidget {
    ...
    final Langauge langauge;
    final Gender gender;

    Widget build(context) {
        return ViewModelBuilder<ScreenTwoViewModel>.reactive(
            onModelReady: (viewModel) => viewModel.init(language, gender),
            ...
        )
    }
}
```

In this right way to pass arguments between two view models?

**Comment by surveshoeb** [comment]
Hi @joshiprashanthd, you need to create your own service using `lazySingleton` annotation which is present in the `injectable` package.

For a more detailed description go through https://www.filledstacks.com/post/services-in-code-and-how-to-use-them-in-flutter/

**Comment by FilledStacks** [comment]
@joshiprashanthd you would simply pass it to the viewmodel on construction from the view. The routing will pass the arguments to the view, then you can pass it into the ViewModel

**Comment by joshiprashanthd** [comment]
Yeah I did exactly the same. I was just curious about other ways to do this.
