### ISSUE TITLE
[ViewModelWidget] [Mockito] | widget is not rebuilt after tester.pump()

### ISSUE THREAD

**Issue by Kp0c** [Stacked-Org/stacked#345]
Hi,

I have a small issue trying to test ViewModelWidget with mocked ViewModel via mockito. Unfortunately, build is not called on every pump.
setup:
widget:
```
class EmailSection extends ViewModelWidget<AuthViewModel> {
  EmailSection() {
    print('ctor');
  }

  @override
  Widget build(BuildContext context, AuthViewModel model) {
    print('build');
    return Container();
}
}
```
test file:
```
Future<void> createWidget(WidgetTester tester, AuthViewModel model) async {
  await tester.pumpWidget(ViewModelBuilder<AuthViewModel>.nonReactive(
    viewModelBuilder: () => model,
    builder: (context, model, _) => MaterialApp(
      home: EmailSection(),
    ),
  ));

  await tester.pump();
}
@GenerateMocks([AuthViewModel])
void main() {
  var authViewModel = MockAuthViewModel();

  setUp(() {
    resetMockitoState();
    authViewModel = MockAuthViewModel();

    when(authViewModel.isBusy).thenReturn(false);
    when(authViewModel.isLogin).thenReturn(true);
    when(authViewModel.username).thenReturn('username');
    when(authViewModel.email).thenReturn('test@test.com');
    when(authViewModel.password).thenReturn('12345678');
  });

  testWidgets('test', (WidgetTester tester) async {
    await createWidget(tester, authViewModel);
    await createWidget(tester, authViewModel);
    await createWidget(tester, authViewModel);
    await createWidget(tester, authViewModel);
    await createWidget(tester, authViewModel);

    final widgetFinder = find.byType(EmailSection);

    expect(widgetFinder, findsOneWidget);
  });
}

```

In this case, I'll have only one 'build' in the console, but several 'ctor'.

if I'll add a unique ValueKey to createWidget, it will work:
```
var q = 0;
Future<void> createWidget(WidgetTester tester, AuthViewModel model) async {
  await tester.pumpWidget(ViewModelBuilder<AuthViewModel>.nonReactive(
    viewModelBuilder: () => model,
    key: ValueKey(q++),
    builder: (context, model, _) => MaterialApp(
      home: EmailSection(),
    ),
  ));

  await tester.pump();
}
```

After this change, I have 5 'build' in the console. But I feel that I'm doing something wrong. Could you please suggest how to omit adding ValueKey during test?

**Comment by FilledStacks** [comment]
@Kp0c you're not doing something wrong. Sometimes flutter cannot determine if a widget has changed and doesn't swap it out in the element tree. The way to fix that is to supply unique keys. You'll see this in development as well when you have a list view that you update dynamically. The list item won't update regardless of calling setstate because the list view builder determines it hasn't changed. The way we fix that is by adding a unique key for each item. 

So what you're doing is fine. I don't have any UI tests (like this) but I don't see anything wrong with your implementation.

**Comment by Kp0c** [comment]
Thank you for the response. I thought that this elements-optimization thing is a root cause, but felt weird doing that ValueKey hack. But if someone much more experienced in Flutter says that it is fine, then I'll close that 😸
