### ISSUE TITLE
Slow performance navigating to Nested route

### ISSUE THREAD

**Issue by bbedward** [Stacked-Org/stacked#346]
There is quite a bit of delay when using the NavigationService to navigate to a route that uses an ExtendedNavigator, at least the first time you navigate to the route. Subsequent times don't have an issue.

You  can see this in the [example](https://github.com/kodjosama/flutter-nested-navigation) provided by  @kodjosama in #279 

Invoking `_navigationService.navigateTo(Routes.tabNavigator);` has a pretty significant delay before the new route is added to the stack,  even in release mode.

**Comment by FilledStacks** [comment]
We haven't experienced this, such strange behaviour. Could you maybe give us a sample where it happens?
