### ISSUE TITLE
[stacked_generator] [new feature] Request to enable build profiles to correctly setup dependencies in @StackedApp

### ISSUE THREAD

**Issue by leccles1** [Stacked-Org/stacked#347]
Hi, 

So I recently upgraded my app to make use of the latest features added by stacked_generator, in favour of having less boilerplate for setup. And I gotta admit, I like how clean the setup is.

One big feature I am missing is the ability to define dependency build profiles/environments for abstract classes. Luckily, it's easy enough to use classType & asType properties in isolation for specific services. 

Would it be possible / is it on the roadmap to add the ability to specify build environments to automatically handle correctly assigning the classType & asType properties of dependencies within the StackedApp decorator?

And use the corresponding dependencies based on,  for example a parameter passed to ``` setupLocator(); ```

```
enum env {
  dev,
  production
}
void main() {
  final log = getLogger('MyApp');
  log.v("Initialising app");
  setupLocator(env.prod);
  runApp(MyApp());
}
```

Previously when directly using injectable, I would use decorators such as ```@Environment('dev')``` to automatically assign mock or concrete implementations for services, as the ```locator.config.dart``` would be regenerated based on mentioned decorators, to map abstract classes to their specified build versions etc.

Thanks!

**Comment by FilledStacks** [comment]
@leccles1 this is a great request. I can have one of the internal devs look at it to see what it would take to add this functionality.

**Comment by FilledStacks** [comment]
Support for this added by [this PR](https://github.com/FilledStacks/stacked/pull/360). I will push a new release shortly.
