### ISSUE TITLE
[stacked_service] showSnackbar has empty space if title is not given 

### ISSUE THREAD

**Issue by alanchan-dev** [Stacked-Org/stacked#350]
stacked_service: 0.8.5

If I don't give the title, there is an empty space at the snackbar, which isn't there on older version.
Can the empty space be removed when there is no title passed?

`_snackbarService.showSnackbar(
        message:
            'message content here');`

Thank you.

**Comment by FilledStacks** [comment]
@DogeeeXD It can probably be removed. I'll see if we have a dev free to tackle that.

**Comment by FilledStacks** [comment]
Fixed in 0.8.6 will push release later today

**Comment by alanchan-dev** [comment]
Thank you very much!
