### ISSUE TITLE
[stacked_generator] [forms] Add support for passing initial value for `FormTextField`

### ISSUE THREAD

**Issue by saileshbro** [Stacked-Org/stacked#361]
Hey @FilledStacks, is it possible to extend this package to include the initial value to be passed from `FormTextField`? We cannot assign the `initialValue` and `controller` at the same time to the `TextFormField` as it gives an error.
---
Proposed changes
```dart
@FormView(
  fields: [
    FormTextField(
      name: 'email',
      initialValue: 'saileshbro@gmail.com',
      isPassword: false,
    ),
  ],
)
```

I know its not the best use case to give initial value to the email field but its just an example.

**Comment by FilledStacks** [comment]
Fixed in #362 will be pushed in 0.4.2
