### ISSUE TITLE
environment sdk version issue 

### ISSUE THREAD

**Issue by shreyaDere** [Stacked-Org/stacked#366]
when i make sdk version to sdk: ">=2.2.0 <3.0.0" it showing this error 

 Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.12 or higher.
    {String? environment, _i2.EnvironmentFilter? environmentFilter}
if i change version to sdk: ">=2.12.0 <3.0.0"
it showing error to the router file

pubspec.yaml

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  carousel_slider: ^3.0.0
  flutter_switch: ^0.3.1
  get_it: null
  google_fonts: ^2.0.0
  injectable: null
  intl: ^0.17.0
  logger: ^1.0.0
  stacked: null
  stacked_hooks: null
  stacked_services: null

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: null
  build_runner: null
  # built_value_generator: null
  injectable_generator: null

please help me to solve this issue.

**Comment by FilledStacks** [comment]
after going to dart 2.12 run flutter pub upgrade then generate your code again

**Comment by shreyaDere** [comment]
if a do so then then it given error in main.dart for following two lines .because I could not access router.gr  code into the main.
i could not found onGenerateRoute in genrated file.

These two lines:
 initialRoute: router.Routes.SplashScreenViewRoute,
onGenerateRoute: router.Router().onGenerateRoute,

**Comment by FilledStacks** [comment]
Flutter has a new router in their own framework. You can give the generated router an alias when you import and it'll be fine.
