### ISSUE TITLE
Null check operator used on a null value Stacked_Locator

### ISSUE THREAD

**Issue by Some1Somewhere** [Stacked-Org/stacked#367]
Getting this error while running the application. 
Error coming at this line
`locator.registerLazySingleton(() => NavigationService());`

Issue seems to be that 
`bool _canRegister(Set<String>? registerFor) {
    return _environmentFilter!.canRegister(registerFor ?? {});
  }`
  
  Am I missing something or what is the issue. Unable to figure it out.
  
  Please help me solve this issue.
  
  Stacktrace
  `[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
#0      StackedLocator._canRegister (package:stacked/src/code_generation/stacked_locator.dart:45:30)
#1      StackedLocator.registerLazySingleton (package:stacked/src/code_generation/stacked_locator.dart:302:9)
#2      setupLocator (package:example/core/app/app.locator.dart:19:11)
#3      main (package:example/main.dart:18:3)`
  
  Stacked Version
  `
  stacked: ^2.1.3
  stacked_services: ^0.8.6`
  
  Flutter Doctor Output : 
  ` [✓] Flutter (Channel stable, 2.0.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 2.0.6 at /Users/dhruvshetty/flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 4A507864-885D-41C1-BD58-0CF76290084F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.212`

**Comment by FilledStacks** [comment]
can you check on the latest version of the stacked_generator please. 0.4.5 and re-run the build_runner

**Comment by SalimBrd** [comment]
@FilledStacks Hi, the 0.4.5 release solved both this issue (I had the exact same problem as the author) and the issue #364.
Thank you for your support.

**Comment by Some1Somewhere** [comment]
Thank you!

**Comment by MDSADABWASIM** [comment]
I'm getting the same issue, but not in main app it's working fine on app side.
Getting this issue on test side, while I'm trying to replicate new TDD article. I am in latest version of Stacked, Stacked services and stacked generator

```
Null check operator used on a null value
StackedLocator._canRegister
package:stacked/…/code_generation/stacked_locator.dart:45
StackedLocator.registerSingleton
package:stacked/…/code_generation/stacked_locator.dart:211
getAndRegisterNavigationService
test\helpers\test_helpers.dart:16
registerServices
test\helpers\test_helpers.dart:28
```

**Comment by ParasPaladiya** [comment]
Object' is from 'dart:core'.
        instance: instance,

**Comment by ParasPaladiya** [comment]
the parameter type 'T?'.
 - 'Object' is from 'dart:core'.
        instance: instance,

**Comment by FilledStacks** [comment]
@ParasPaladiya  That's due to out dated packages. We don't use the stacked_core package anymore. 

Make sure all stacked related packages are on the latest and you've run `flutter pub upgrade`
