### ISSUE TITLE
Future<T?> unnecessarily forces nullable type

### ISSUE THREAD

**Issue by dmitry-fbm** [Stacked-Org/stacked#369]
It must be up to application to decide whether return type is nullable or not. Recent change in 35e860a7debebd36aa71b17c454ebcd46b3d338e (issue #338) breaks a lot of code forcing nullable where it cannot be and correspondingly, need for unnecessary typecast. For instance, this is used to be (and has to be) valid code:

![2021-05-14_003932](https://user-images.githubusercontent.com/72771850/118191212-e8bac300-b44c-11eb-8f59-02cfe2925767.png)

Therefore the return type has to be `Future<T>`, which covers both nullable and non-nullable types, depending on context.

**Comment by FilledStacks** [comment]
I'll make an update now and push that.

**Comment by FilledStacks** [comment]
Pushed in 2.1.4

**Comment by sanalkv** [comment]
The following error is happening when api call returned with error `Unhandled Exception: type 'Null' is not a subtype of type 'AddGrowCycleSensorResponse' in type cast
`
