### ISSUE TITLE
Issue in reactive Service and model.

### ISSUE THREAD

**Issue by richard457** [Stacked-Org/stacked#371]
I have the following code
`
```
import 'package:flipper_services/keypad_service.dart';
import 'package:test/test.dart';
import '../helpers/test_helpers.dart';
import 'package:flipper_models/view_models/business_home_viewmodel.dart';
import 'package:flipper_models/models/order_mock.dart';
```
`
```
BusinessHomeViewModel _getModel() => BusinessHomeViewModel();`
void main() {
  group('Test When sellign a product', () {
    late KeyPadService keypadService;
    late BusinessHomeViewModel model;
    setUp(() {
      registerServices();
      keypadService = getAndRegisterKeyPadServiceUnmocked();
      model = _getModel();
    });
    tearDown(() => unregisterServices());

    test('can set amount', () async {
      model.setAmount(amount: 300.0);
      expect(keypadService.amountTotal, 300.0);
    });
    test('should increase quantity', () async {
      model.increaseQty();
      expect(keypadService.quantity, 1);
    });
```
   ```
 test('should decrease quantity', () async {
      model.decreaseQty();
      expect(keypadService.quantity, 0);
    });
  });
}
```
`
When I run each test independently it works fine and the service can update as I assume, the problem comes when I run the code as a whole for testing, it seems like stacked does not like to update to different property at the same time here **quantity** and **amountTotal** please help me understand what is going on here.

**Comment by FilledStacks** [comment]
@richard457 

1. Those are not unit tests, I only have valuable experience in writing unit tests. What you're writing there makes each unit dependent on something else, so negates the definition of a unit test. 
2. If you want to write a unit test each unit has to test a single unit of work, only 1, in complete isolation.
3. To fix your problem. Construct the model in each test and remove it from the global scope. Unit testing is not a place for shared code besides your setup functions. That should be done in your code base.
