### ISSUE TITLE
Setting a reactive service dynamically after the view model init doesn't listen to the reactive service

### ISSUE THREAD

**Issue by naamapps** [Stacked-Org/stacked#372]
Hey!
I have a widget that accepts a factory service as a property, then I pass it to the viewmodel so it would react to changes inside the service.

This is not working however, The viewmodel doesn't know I have set the service after the initialization so it doesn't listen to changes.

Example - Here if I call notifyListeners inside the lateService, the viewmodel won't rebuild.
```
class ExampleViewModel extends ReactiveViewModel {
  LateService lateService; 
    
  ExampleViewModel(this.lateService);

  @override
  List<ReactiveServiceMixin> get reactiveServices =>
      [lateService];
}
```

It would be great if the viewmodel had a function to add (and remove) reactive services at runtime after initialization of the viewmodel.
Something like:

```
abstract class ReactiveViewModel extends BaseViewModel {
    void addReactiveService(ReactiveServiceMixin service) {
      _reactiveServices.add(service);
      service.addListener(_indicateChange);
    }
    
    void removeReactiveService(ReactiveServiceMixin service) {
      _reactiveServices.remove(service);
      service.removeListener(_indicateChange);
    }
    ....
}
```

Thanks!

**Comment by FilledStacks** [comment]
That's something we can probably add when we get some time.

**Comment by FilledStacks** [comment]
@naamapps given that the Viewmodel is not accessible anywhere you can really call it to add services this functionality would be mute. Services shouldn't be used in the view and the view is the only place you have access to the viewmodel. I'm going to close this issue. If you think it's still required please provide an example of how you think it should work.

**Comment by naamapps** [comment]
@FilledStacks The viewmodel has access to itself. So after initialization or some other logic, then the viewmodel itself could add a reactive service.
This is useful if you don't know the reactive service at compile time (like a pool manager that gives you a service from a pool), so it will work like this:
```
class PostViewModel extends DynamicViewModel {
  final PoolManager<String, PostService> _poolManager = locator();
  late PostService _postService;
  final String _postId;

  PostListItemViewModel(this._postId) {
    _postService = _poolManager.get(key: _postId);
    addReactiveService(_postService);
  }
}
```

I hope this is clearer and the use case is relatable.
Thanks

**Comment by FilledStacks** [comment]
I've actually never seen that, I guess it makes sense if you want to register a service at runtime as well? I've never seen the requirement to do this which is why it's a strange request for me. If you make a PR I can check merge it in if it passes review.
