### ISSUE TITLE
Not able to register Snackbar Service

### ISSUE THREAD

**Issue by souravgopal25** [Stacked-Org/stacked#378]
![](https://user-images.githubusercontent.com/27691870/118659595-161bbe00-b80b-11eb-877a-8a5c933a281e.PNG)

![](https://user-images.githubusercontent.com/27691870/118659668-26339d80-b80b-11eb-927c-58e60c0cc0ce.PNG)

**Comment by MDSADABWASIM** [comment]
You are using the latest version of stacked services, if your codebase is null safe use the latest version of all stacked related libraries, otherwise, try to downgrade your stacked_services version.

**Comment by souravgopal25** [comment]
![image](https://user-images.githubusercontent.com/27691870/119977595-449d5400-bfd6-11eb-843f-b34bf14f6d60.png) what does "9*+-." this means before the class Snackbar Service

**Comment by FilledStacks** [comment]
I have no idea. I've never seen that.
