### ISSUE TITLE
ViewModelBuilder createNewModelOnInsert not working

### ISSUE THREAD

**Issue by Solidara** [Stacked-Org/stacked#381]
Triggered by a menu item I was trying to load a new body widget into a reactive scaffold and body view with

> onModelReady: (model) => model.initialise(jsonMap),

Problem is, that this initialise  by default is triggered only once. So the new page isn't loaded into the existing scaffold body.

I tried to insert 

> createNewModelOnInsert: true,

As I understood from the documentation this should force the creation of a new model. But there was no change. The initialise method still is not called again.

As a workaround I had to add a unique Key value to the new version of the view each time I load a new page. Then everything is working fine.

(Stacked version was 2.0.4)

**Comment by FilledStacks** [comment]
Yes you are correct. But it's on condition of Flutter calling the init state in their lifecycle. So if they don't pick up that the item has changed init state won't be called again. And we use init state to rebuild models and insert. 

Your approach is the correct one. Which is to use a unique key to tell Flutter that the key has changed and they should do a total rebuild.

**Comment by JaidynBluesky** [comment]
Thank you! This is also what you should do if you are using the IndexTrackingViewModel and your Views do not initialise when you switch tabs.
