### ISSUE TITLE
Set form values from view model.

### ISSUE THREAD

**Issue by RodolfoSilva** [Stacked-Org/stacked#382]
Hi @FilledStacks, great work with the FormView decorator :D.

I've a question:

Right now It's possible to retrieve data from forms in the view model. But I've not see any way to set the form data from the view model?

For example: one app with a logic to retrieve data from the server to allow the user to edit the form data.

How can I do that?

I see in the generated `*.form.dart` does have in the extension the `get` operation, but does not have the `set` operation.

**Comment by FilledStacks** [comment]
@RodolfoSilva good question. All you have to do is set the controller values after the data has been fetched. I would do that with a callback function from the ViewModel. When the controller updates the maps automatically sync so you don't have to set the values in the maps directly.

**Comment by RodolfoSilva** [comment]
Thanks @FilledStacks 

So, I will need a callback in my widget view and when I receive the data from the server I will call this model callback. 
Right? Because the model does not have direct access to the controllers.

Something like this:

View:
```dart
@FormView(fields: [
  FormTextField(name: 'name'),
  FormTextField(name: 'price'),
])
class ProductView extends StatelessWidget {
  const ProductView({Key? key}) : super(key: key);

  onReset(Map<String, String> data) {
    nameController.value = data['name'];
    priceController.value = data['price'];
  }

  @override
  Widget build(BuildContext context) {
    SizeConfig().init(context);
    return ViewModelBuilder<ProductViewModel>.reactive(
      onModelReady: (viewModel) {
        listenToFormUpdated(viewModel);
        model.listenToFormReset(this.onReset);
        model.initialise();
      },
      ...
    );
  }
}
```

Model
```dart
class LoginViewModel extends FormViewModel {
  void Function? _onReset;
  listenToFormReset(void Function onReset) {
    _onReset = onReset;
  }

  resetForm(Map<String, String> data) {
    if (_onReset == null) {
      return;
    }

    _onReset(data);
  }

  initialise() async {
    final data = await loadFromTheServer();
    resetForm(data);
  }
}
```
If not, could you give me an example?

**Comment by FilledStacks** [comment]
@RodolfoSilva yes. That is exactly the solution. You can even move that function out of the build function into the class. Also I have a suggestion that has nothing to do with the solution just to reduce some code. I would update 

```dart
resetForm(Map<String, String> data) {
    if (_onReset == null) {
      return;
    }

    _onReset(data);
  }
```
to

```dart
resetForm(Map<String, String> data) {
    _onReset?.call(data);
  }
```

**Comment by RodolfoSilva** [comment]
Nice, thanks :D @FilledStacks

**Comment by FilledStacks** [comment]
@RodolfoSilva you can now use `[formName]Value = 'My value'` from version 0.9.1+1 and it will update the controller value as well as the internal map + run all validation checks.
