### ISSUE TITLE
[stacked_generator] [forms] Add support for passing custom controller for `FormTextField`

### ISSUE THREAD

**Issue by RodolfoSilva** [Stacked-Org/stacked#384]
Sometimes, standard controllers are not enough.
It would be nice if we can specify a custom controller for the fields. 
I personally use a custom controller to add mask to the inputted text.(https://pub.dev/packages/extended_masked_text)
But right now I cant use this with the Stacked Form.

I will try to implement this and send a PR.

**Comment by FilledStacks** [comment]
@RodolfoSilva that is something that I would really like to have. If you find the time please send a PR and I'll review. I'll label is as waiting for PR for now. Will check in again in a few days.
