### ISSUE TITLE
How to navigate with arguments and have these arguments in the ViewModel

### ISSUE THREAD

**Issue by jeremylcarter** [Stacked-Org/stacked#386]
Hi,

I would like to know the best strategy to navigate with arguments and have these arguments in the ViewModel. Is there a chat forum for these kinds of questions as they arent "issues".

Thanks again for your hard work.

**Comment by FilledStacks** [comment]
@jeremylcarter thanks for reaching out. 

At the moment there's no built in functionality for that. We simply pass it to the ViewModel on construction. Since the view navigation params is generated it's just an additional view lines of code for the ViewModel. 

So when the ViewModelBuilder creates your viewmodel you can pass it through the constructor there.

**Comment by FilledStacks** [comment]
Also, I'm fine with the issues as questions. There should be clearer communication about things like this. The readme is so big. We're going to create a stacked docs website soon to cover everything. There's a lot that I've never even spoken about in the package that's very useful.

I'll tag as documentation and we'll close it once it's been explained in the documentation.

**Comment by corporate-cas** [comment]
Hello FilledStacks!
William, your ardent follower here. I think the above is something I don't quite understand so pardon my request for further clarification.

So, I need to send a Firestore DocumentSnapshot from a listView screen to a details screen. I have created a constructor on the details screen expecting the information:

```
...
  final DocumentSnapshot documentSnapshot;

  const ProductDetailsView({Key? key, required this.documentSnapshot})
      : super(key: key);
...
```
I pass the documentSnapshot in my navigation function:

```
  goToDetails(DocumentSnapshot documentSnapshot) {
    _navigationService!.navigateTo((Routes.productDetailsView),
        arguments: documentSnapshot);
  }

```
But I receive the following error:
The following assertion was thrown while handling a gesture:
Expected [ProductDetailsViewArguments],  found [_JsonQueryDocumentSnapshot]

Please any suggestions here?
