### ISSUE TITLE
MultipleFutureViewModel future functions with params

### ISSUE THREAD

**Issue by andreierdoss** [Stacked-Org/stacked#387]
I was looking to use the MultipleFutureViewModel but I was not able to add future functions that require params. Is it possible to do it with the current implementation or does it require such a feature to be added?

**Comment by FilledStacks** [comment]
@andreierdoss When the future is constructed you supply the parameters. The same way you do with the single future viewmodel.

```dart

class HomeViewModel extends FutureViewModel<Feed> {

String feedIdentity;
HomeViewModel(this.feedIdentity);

@override
Future<Feed> futureToRun() => _feedService.getFeedForIdentity(feedIdentity); // Passing parameter to future

}

```


```

**Comment by andreierdoss** [comment]
@FilledStacks thank you for the example. I was looking to use the MultipleFutureViewModel, which requires this override:


```
@override
  Map<String, Future Function()> get futuresMap => {
     _currentScoreFuture: _databaseService.getScore(scoreId), // this shows an error
    _selectedCompetitorsFuture: _databaseService.getCompetitors // this works fine, without a param
  }
```

```
@override
  Map<String, Future Function(int id)> get futuresMap => { // this says that it's no longer override because of the param
     _currentScoreFuture: _databaseService.getScore(scoreId),
    _selectedCompetitorsFuture: _databaseService.getCompetitors // shows an issue due to the missing param
  }
```

**Comment by FilledStacks** [comment]
I can't remember the exact implementation. Can you make the futuresMap have a value of Future only? Or does it have to be a function that returns a Future?
