### ISSUE TITLE
How to update change in all ViewModels when a ViewModel has made a change in a Service's property

### ISSUE THREAD

**Issue by AlanTso** [Stacked-Org/stacked#388]
Hi Dane,

I need to update a change in BaseModel when a ViewModel changes a property in a service class. Here is the summary of my code.

  class BaseModel extends ChangeNotifier {  
    final AuthenticationService _authenticationService =
    locator<AuthenticationService>();  

    AppUser get currentUser => _authenticationService.currentUser;  
  }

  class AuthenticationService {
    final FirebaseAuth _firebaseAuth = FirebaseAuth.instance;
    final FirestoreService _firestoreService = locator<FirestoreService>();
  
    AppUser _currentUser;
    AppUser get currentUser => _currentUser;
  
  updateUser(AppUser user) {
      _currentUser = user;
    }  
  }

  class UserProfileViewModel extends BaseModel {
  final AuthenticationService _authenticationService = locator<AuthenticationService>();
  
  Future updateUser() async{    
      AppUser user = AppUser(many properties);    
      await _authenticationService.updateUser(user);    
      notifyListeners();
    }  
  }

When I call UserProfileViewModel.updateUser(), the _currentUser in AuthenticationService change sucessfully, however the currentUser in BaseModel doesn't synchronize the update.

What I have tried: I have tried observable_ish package, however, when I implement the ReactiveServiceMixin in my AuthenticationService and wrap the _currentUser in an RxValue, I can't set the initial value resulting in always prompt an error message. Here is what I tried: (RxValue \<AppUser> _currentUser = RxValue \<AppUser> (initial: ???);)
Also, other functions in AuthenticationService which pass _currentUser as an argument, get error message too. Like this: await _firestoreService.createUser(_currentUser);

Looking forward to your support!
Thank you.

**Comment by AlanTso** [comment]
Hi Dane,

It's strange, It even doesn't work with int value.
![image](https://user-images.githubusercontent.com/37435112/119487235-b3d33800-bd8b-11eb-8520-b394e320f6dd.png)

**Comment by FilledStacks** [comment]
@AlanTso I think the constructor has changed to take positional arguments. You can press f12 on it to see it's definition. 

Also we don't use observable_ish anymore. There's a new `ReactiveValue` class in the stacked package that you can use with the same functionality.
