### ISSUE TITLE
Null check operator used on a null value: at view_model_builder.dart:164:14

### ISSUE THREAD

**Issue by rocketman7** [Stacked-Org/stacked#389]
Hi team,
I was migrating my project to flutter 2.2.0 and I got stuck on view model builder of stacked.
The error message is saying

======================

The following _CastError was thrown building Consumer<VoteSelectViewModel>(dirty,
dependencies:
[_InheritedProviderScope<VoteSelectViewModel>]):
Null check operator used on a null value

The relevant error-causing widget was:
  Consumer<VoteSelectViewModel>
  file:///Users/Mac/SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/stacked-2.1.6/lib/src/state_management/view_model_builder.dart:164:14

========================

I'm not sure if the error coming from Stacked or my code. But I guess there were similar errors on stacked while migrating to Flutter 2.2.0.

Could you kindly check on this?

Thanks,

**Comment by FilledStacks** [comment]
Hey, I don't know what to check here.  can you post the code that's causing the issue.
