### ISSUE TITLE
Explain how to perform Auth Guard / Startup logic in a Web app using nested nav

### ISSUE THREAD

**Issue by JayPerfetto** [Stacked-Org/stacked#391]
Can someone please explain how to perform auth guarding / nested navigation in a web app?

I am stuck on the following situation:

I have an app with login / user sessions.
I want to redirect all unknown routes to a 404
I want to redirect all unauthenticated users to the login page
I want to redirect all authenticated users to a startup / initialization page, then to the Home Page
The Home page has a BottomNavBar with 3 items
       => I would expect each item to show a route in the URL bar of /home/page1, /home/page2, and /home/page3

**Comment by JayPerfetto** [comment]
It's far too much code to post, but I ended up implementing this package and combining their Auth example + bottom nav examples, and not using the stacked navigation service / routers: 

https://pub.dev/packages/beamer
https://pub.dev/packages/beamer#authentication-bloc
https://pub.dev/packages/beamer#bottom-navigation-multiple-beamers

**Comment by FilledStacks** [comment]
@JayPerfetto thanks for the details! We'll probably wrap something else for web on our side given that we'd want to use navigator 2.0 for everything. We are building a mobile / web app at the moment. Web only starts later on so at the moment we're not seeing the nav issues with stacked services. We'll soon tackle those. At the moment I would recommend not using stacked services for web apps. It's built with the mobile functionality only in mind.
