### ISSUE TITLE
Update stacked_themes dependency on rxdart 0.26 to 0.27

### ISSUE THREAD

**Issue by PushkarGarg02** [Stacked-Org/stacked#393]
Because stacked_themes >=0.2.4 depends on rxdart ^0.26.0 and geoflutterfire 3.0.0-nullsafety.4 depends on rxdart ^0.27.0, stacked_themes >=0.2.4 is incompatible with geoflutterfire 3.0.0-nullsafety.4.
So, because app depends on both geoflutterfire 3.0.0-nullsafety.4 and stacked_themes 0.3.1, version solving failed.
pub get failed (1; So, because app depends on both geoflutterfire 3.0.0-nullsafety.4 and stacked_themes 0.3.1, version solving failed.)

**Comment by FilledStacks** [comment]
@PushkarGarg02 I'll assign this internally and see if anyone can get time to make a PR to update the package.

**Comment by FilledStacks** [comment]
fixed in 0.3.3
