### ISSUE TITLE
ReactiveServiceMixin is not listening for ChangeNotifier changes

### ISSUE THREAD

**Issue by daniilsv** [Stacked-Org/stacked#395]
**stacked\lib\src\state_management\reactive_service_mixin.dart**
_void listenToReactiveValues(List<dynamic> reactiveValues)_

What's now

```
else if (reactiveValue is ChangeNotifier) {
  reactiveValue.notifyListeners();
}
```

What seems to be
```
else if (reactiveValue is ChangeNotifier) {
  reactiveValue.addListener(notifyListeners);
}
```

'cause there is no clue to call _notifyListeners_ on ChangeNotifier in Service constructor and we should listen for updates

**Comment by FilledStacks** [comment]
Will merge the PR when the other updates are done that was requested.
