### ISSUE TITLE
Can't build a dropdown list dynamically because the constructor for StaticDropdownItem is constant

### ISSUE THREAD

**Issue by kayzkenny** [Stacked-Org/stacked#397]
For example we may want to build a dropdown list from a list of countries. 
```
const countries = <String>["Mordor", "Wakanda"];

final countriesDropdownlist = countries
    .map((countryName) =>
        StaticDropdownItem(title: countryName, value: countryName))
    .toList();

@FormView(fields: [
  FormDropdownField(name: 'country', items: countriesDropdownlist),
])
```

If we try to do this we get the following warnings.

Arguments of a constant creation must be constant expressions.
Try making the argument a valid constant, or use 'new' to call the constructor.dartconst_with_non_constant_argument
The values in a const list literal must be constants.
Try removing the keyword 'const' from the list literal.dartnon_constant_list_element
Invalid constant value.dart(invalid_constant)

Please remove the const keyword from the StaticDropdownItem class constructor

**Comment by kayzkenny** [comment]
@hurbes could you give an example on how to build a dropdown list dynamically using a @FormView. Thanks

**Comment by FilledStacks** [comment]
@kayzkenny you can't do that in this package. We haven't built that functionality. We'll need some work to get it working properly.

**Comment by kayzkenny** [comment]
@FilledStacks thanks. I would like to contribute in anyway. Do you have any good first issues? How far along are you with a documentation website (i would really like to help with that)

**Comment by FilledStacks** [comment]
@kayzkenny I'm going to tackle splitting up the readme into separate sections today and will use a docs generator to create a basic website. There's a lot I have to write, I don't know if you know the entirety of stacked and how to use it so I think it's best suited for me to write.

**Comment by kayzkenny** [comment]
Ok, looking forward to it.

**Comment by dougclarknc** [comment]
is there a way users can bump requests?
