### ISSUE TITLE
Stacked with responsive builder

### ISSUE THREAD

**Issue by kanityi** [Stacked-Org/stacked#4]
Hi, I'm Trying to implement a very basic app, but it doesn’t carry over the state (from portrait to landscape) or vice-versa , Or there's something I'm missing
My snip code : 

**HomeView**
```
class HomeView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder<HomeViewModel>.reactive(
      viewModelBuilder: () => HomeViewModel(),
      onModelReady: (model) => model.initialise(),
      builder: (context, model, child) => ScreenTypeLayout.builder(
        mobile: (context) => OrientationLayoutBuilder(
          portrait: (context) => HomeMobilePortrait(),
          landscape: (context) => HomeMobileLandscape(),
        ),
      ),
    );
  }
}
```
**Portrait**
```
class HomeMobilePortrait extends ViewModelWidget<HomeViewModel> {
  @override
  Widget build(BuildContext context, HomeViewModel model) {
    return Scaffold(
      body: Container(
        child: Text(model.title),
        alignment: Alignment.center,
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => model.updateTitle(),
      ),
    );
  }
}
```
**Landscape**
```
class HomeMobileLandscape extends ViewModelWidget<HomeViewModel> {
  @override
  Widget build(BuildContext context, HomeViewModel model) {
    return Scaffold(
      body: Container(
        alignment: Alignment.center,
        child: Text(
          model.title,
          style: TextStyle(color: Colors.purple),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => model.updateTitle(),
      ),
    );
  }
}
```

**Comment by FilledStacks** [comment]
ViewModelWidget requires a type to extract the provided value.

```
class HomeMobileLandscape extends ViewModelWidget<HomeViewModel> {
}

**Comment by kanityi** [comment]
I did it like that,  I do not know why it was not showing on that, check here on this pic:
![15876284998264067868043722648558](https://user-images.githubusercontent.com/31445207/80073774-8e507b00-8548-11ea-9756-597d6849b590.jpg)

**Comment by FilledStacks** [comment]
So what's the problem? I need more info than it's not working. What are you doing, what are you expecting to happen, what is it doing at the moment, what other things are you using.

**Comment by kanityi** [comment]
It doesn't carry over the state from portrait to landscape or vice versa , if I have 6 on portrait when I change the orientation it start to "initialize"

That is my problem

**Comment by FilledStacks** [comment]
Try and use the nonReactive constructor for the HomeView. You don't want the top view to rebuild since nothing depends on the model state there.

**Comment by kanityi** [comment]
Thanks very much man, it worked

**Comment by kanityi** [comment]
These packages are the best, with few lines I have covered 90% of responsive and state management code. Thanks guys.

**Comment by FilledStacks** [comment]
@kanityi Awesome! That wast the goal :) We'll be adding more functionality into stacked and the responsive builder as we us it in production and see what else is required. 

Thanks for using it, much appreciated.
