### ISSUE TITLE
Get NavigationService's currentRoute arguments

### ISSUE THREAD

**Issue by e-e** [Stacked-Org/stacked#400]
I saw that somewhat recently an update was made to define a navigation observer in order to successfully retrieve `navigationService.currentRoute`. If that route included arguments, is there any way to retrieve those arguments from NavigationService?

**Comment by hurbes** [comment]
`Get` already provides the functionality. We can sure expose that. We'll assign this internally.

**Comment by FilledStacks** [comment]
Added. This will be released later today.

**Comment by FilledStacks** [comment]
Released in 0.8.7
