### ISSUE TITLE
stacked_localisation null-safety migration?

### ISSUE THREAD

**Issue by calvintam236** [Stacked-Org/stacked#401]
Looks like `stacked_localisation` has not updated for null safety (for flutter v2.0+) at https://pub.dev/packages/stacked_localisation.

Any plan updating this and maybe release as preview instead of stable?

PS: discontinued flag is bad for search in pub.dev.

**Comment by Hannnes1** [comment]
I think it's marked as discontinued because it is not supposed to show up while they are working on it. See #126

**Comment by calvintam236** [comment]
Since the last update on pub.dev is 8/20/20, I don’t think anyone is working on it?

Null-safety should be a priority now since Flutter v2.2+ requires it.

**Comment by FilledStacks** [comment]
@calvintam236 it's marked as discontinued and has been since the second day it was released. I realised I had an incomplete implementation and abandoned the package for that reason. 

We don't have the resources to dedicate to this project since we have no more projects that require localisation.
