### ISSUE TITLE
stacked_themes incompatible with CupertinoApp (ThemeData)

### ISSUE THREAD

**Issue by calvintam236** [Stacked-Org/stacked#405]
The code hardcoded for `ThemeData`, which is from `material` library. It is not compatible with other packages that does not based on it, such as `CupertinoApp`.

For example, `CupertinoApp` uses `CupertinoThemeData` and there is no direct themes switching. Cupertino uses [`CupertinoDynamicColor`](https://api.flutter.dev/flutter/cupertino/CupertinoDynamicColor-class.html) to determine color between light and dark mode.

There should be a way to pass through a different type for `ThemeData` in `ThemeBuilder` and `ThemeManager`. Maybe you can create a generic `ThemeData` for this package and generate a `ThemeData`/ `CupertinoThemeData` for app’s `theme`.

**Comment by hurbes** [comment]
It's not our priority at the moment, we are currently focusing on other functional issues that might be in the app. We'll update it in the future.

**Comment by calvintam236** [comment]
That’s alright. Now I can remove this package from my pubspec since it is useless to me at the moment.

Please just add to `stacked_themes`’s readme saying `CupertinoApp` is not supported (only `MaterialApp` and `ThemeData` based on `material` works).
