### ISSUE TITLE
How can we listen for life cycle callbacks in ViewModel?

### ISSUE THREAD

**Issue by Dhruv-Garg79** [Stacked-Org/stacked#409]
I want to refresh data when onResume() life cycle method is called. wanted to know if this is possible to do from ViewModel?

**Comment by hurbes** [comment]
Related to issue #413 

https://github.com/FilledStacks/stacked/issues/413#issuecomment-861176804
Create a LifeCycleService that has a single Stream on it that emits the LifeCycleState (an enum that has all the states). Then in the ViewModels that are listening and alive, I would listen to that and handle the state in there. I the LifeCycleManager you can add the states onto the stream before doing anything else.

Any ViewModel that's listening and still alive will react to it.

**Comment by jossephalvarez** [comment]
You can see my solution here -> https://github.com/FilledStacks/stacked/issues/413#issuecomment-863145587

**Comment by Dhruv-Garg79** [comment]
Thanks, got the solution!
