### ISSUE TITLE
Stacked generator not complying to the original class

### ISSUE THREAD

**Issue by Silfalion** [Stacked-Org/stacked#411]
![image](https://user-images.githubusercontent.com/23188369/121787030-a2779180-cbbb-11eb-98be-aa376646716b.png)
![image](https://user-images.githubusercontent.com/23188369/121787034-ad322680-cbbb-11eb-9b79-62096861ce95.png)

The first picture shows the generator app_router.dart and the second the original class. Despite there not being any errors with it, the generated route still shows the arguments without their default values. Is it a bug or a mistake on my part please?

**Comment by hurbes** [comment]
That's strange. haven't seen that before. Will look into it.

**Comment by Silfalion** [comment]
Thank you.

**Comment by FilledStacks** [comment]
Will look at this issue today

**Comment by FilledStacks** [comment]
Seems to be a problem relating to [this issue](https://github.com/dart-lang/sdk/issues/46284)

**Comment by Silfalion** [comment]
So the only solution for now would be to initialize in the body of the constructor in the meantime it's resolved.

**Comment by FilledStacks** [comment]
I guess that's a workaround. I'd like to be able to fix it I just have no idea to debug and figure out what's happening.

**Comment by FilledStacks** [comment]
@Silfalion can you check if 0.4.9 works for you?

**Comment by akifarhan** [comment]
It works now for me

**Comment by Silfalion** [comment]
@FilledStacks so sorry for the late reply, didn't notice the notification. Yes, it works now, thank you so much. However there is another issue with the generation that doesnt add a custom made transition builder class to the generated app_router. Should I open an another issue or post the details here?

**Comment by FilledStacks** [comment]
@Silfalion you can add another issue for that please. I'll close this one.
