### ISSUE TITLE
pub.dev readme for stacked_services is out of date

### ISSUE THREAD

**Issue by bsneider** [Stacked-Org/stacked#415]
its missing an s 

"New way:

```
service.registerCustomDialogBuilder(variant: Dialog.basic, builder: (context, request, completer) => Dialog(...))
Take note of the third parameter in the builder function that you can call to complete the builder instead of using the dialog service directly. You can simply call
```"
on registerCustomDialogBuilder**s**

also 
`final builders = {
    DialogType.basic: (context, sheetRequest, completer) =>
        _BasicDialog(request: sheetRequest, completer: completer),
    DialogType.form:  (context, sheetRequest, completer) =>
        _FormDialog(request: sheetRequest, completer: completer),
  };`

should be 
`  final builders = {
    DialogType.Basic: (context, sheetRequest, completer) =>
        _BasicDialog(request: sheetRequest, completer: completer),
    DialogType.Form:  (context, sheetRequest, completer) =>
        _FormDialog(request: sheetRequest, completer: completer),
  };`

**Comment by bsneider** [comment]
also the rest of the example is not null-safe
`
class _BasicDialog extends StatelessWidget {
  final DialogRequest request;
  final Function(DialogResponse) completer;
  const _BasicDialog({Key key, this.request, this.completer}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Dialog(
      child: /* Build your dialog UI here */
    );
  }
}

class _FormDialog extends StatelessWidget {
  final DialogRequest request;
  final Function(DialogResponse) completer;
  const _FormDialog({Key key, this.request, this.completer}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Dialog(
      child: /* Build your dialog UI here */
    );
  }
}`

**Comment by hurbes** [comment]
Yes, It's been a while since it's updated. We'll update it in the next release.
