### ISSUE TITLE
Using stack_logger with stack_crashlytics

### ISSUE THREAD

**Issue by skytect** [Stacked-Org/stacked#416]
According to `README.md` in `stack_crashlytics`, to integrate `CrashlyticsService` into our logger we can use:
> ```dart
> Logger(
> ...
>     output: MultipleLoggerOutput([
>     ...
>     CrashlyticsOutput(),
>     ]),
> );
> ```

However, this doesn't seem to be able to work with `StackedLogger` in
```dart
@StackedApp(
  routes: [
    ...
  ],
  dependencies: [
    LazySingleton(classType: CrashlyticsService),
    ...
  ],
  logger: StackedLogger(), // only has the single parameter String logHelperName
)
class App {}
```

Is there a way to generate `app.logger.dart` such that the `MultipleLoggerOutput()` in the `getLogger()` function can have the additional `CrashlyticsOutput()`? Maybe by adding a parameter in `StackedLogger()` that takes a list of other `LogOutput`s?

**Comment by FilledStacks** [comment]
Released in stacked 2.1.9
Released in stacked_generator 0.4.8
