### ISSUE TITLE
_key was called on null

### ISSUE THREAD

**Issue by LoveAndroDev** [Stacked-Org/stacked#42]
hi Dane

the navigatorKey that i am getting from Navigation services i am getting this error
![error](https://user-images.githubusercontent.com/55128544/82112796-26b7d500-976e-11ea-98de-e8c06ba780ee.PNG)

**Comment by FilledStacks** [comment]
update to 1.5.1 it's fixed.

**Comment by LoveAndroDev** [comment]
Thanks
