### ISSUE TITLE
readme about FutureViewModel is outdated

### ISSUE THREAD

**Issue by calvintam236** [Stacked-Org/stacked#420]
https://github.com/FilledStacks/stacked/blob/master/packages/stacked/README.md#futureviewmodel

Still using deprecated `get future` in the example. It has been replaced by `futureToRun()`.

**Comment by hurbes** [comment]
We'll update the documentation in the next release.
Related to issue #415

**Comment by calvintam236** [comment]
@FilledStacks this is not related to #415, and it is still not fixed at `master`.
