### ISSUE TITLE
outdated stacked_services example

### ISSUE THREAD

**Issue by calvintam236** [Stacked-Org/stacked#423]
https://github.com/FilledStacks/stacked/blob/master/packages/stacked_services/example/pubspec.yaml

The example is not even using `stacked` (looks like pre-stacked).

**Comment by hurbes** [comment]
Related to issue #415 and #420

**Comment by calvintam236** [comment]
This is regarding to the whole example folder, not just readme. Documentation needs to be updated as well.

**Comment by surajmandalcell** [comment]
@calvintam236  I think the example of the stacked service is supposed to show you how to use the services and not how to use it with stacked(which I've read and is already well documented).

**Comment by calvintam236** [comment]
> @calvintam236 I think the example of the stacked service is supposed to show you how to use the services and not how to use it with stacked(which I've read and is already well documented).

`stacked_services` is designed to use with `stacked` but there is no `stacked` dependency used in the example. Do you see the problem?

**Comment by FilledStacks** [comment]
@calvintam236 Single responsibility applies everywhere I'm involved. 

The example for a package will only show how to use the package. That is because stacked services works very well with BLoC and Redux as well.
