### ISSUE TITLE
Replace `dart:io` for `universal_io` for better cross-platform support

### ISSUE THREAD

**Issue by calvintam236** [Stacked-Org/stacked#426]
I notice some of the packages are still using `dart:io`. Since `stacked` will support web (on the roadmap), this should be replaced by [`universal_io`](https://pub.dev/packages/universal_io) for its cross-platform support (web included) since `dart:io` has no support on web.

`universal_io` has identical API as `dart:io` so the conversion should be quick and easy.

**Comment by FilledStacks** [comment]
@hurbes can you run through the packages and update this for us?

**Comment by FilledStacks** [comment]
released in latest versions
