### ISSUE TITLE
Analytics-friendly route names

### ISSUE THREAD

**Issue by manafire** [Stacked-Org/stacked#428]
Looks like Firebase Analytics has made great strides in making screenName (and screenClass) more marketer-friendly but the current route annotations are somewhat rigid in that they're only path-based.  As far as I can tell, the only way to set the screenName ([following the FilledStacks tutorial](https://www.filledstacks.com/post/firebase-analytics-and-metrics-in-flutter/)) is through the [path] parameter, but that has some limitations:

```dart
// app.dart - route annotations
// #1. 
// routes break runtime ([navigateTo]) if they have spaces in them
CupertinoRoute(page: CreateAccountView, path: 'Create Account'),
CupertinoRoute(page: ForgotPasswordView, path: 'Forgot Password'),

// #2. 
// [initial] doesn't seem to matter unless [path] is also set to '/'.  
// Setting it to anything else requires "home: StartupView()" to be set on MaterialApp.
MaterialRoute(page: StartupView, initial: true, path: 'Startup')

// main.dart
MaterialApp(
      title: 'Compound',
      navigatorKey: StackedService.navigatorKey,
      onGenerateRoute: StackedRouter().onGenerateRoute,
      navigatorObservers: [
        locator<AnalyticsService>().getAnalyticsObserver(),
      ],
      // required only if "initial" path != '/'
      home: StartupView(), 
      ...
    );
```

Ideally, routes would have both a path as well as a screenName.  Whether could be declared explicitly and/or implicitly on the actual View (say, for dynamic screen names like "Product XYZ" - see #226).  There's the foundations of a workable way [here](https://stackoverflow.com/a/55831114/805003), but it only works for Stateful widgets.

Anyway, I suppose this might be considered a feature request, but I wanted to flag this as it will undoubtedly become more problematic for folks in the future as analytics becomes increasingly less developer-centric.

**Comment by FilledStacks** [comment]
Thanks @manafire for the details. We're also pretty analytics centric. Well our clients are and this hasn't been a problem yet. But it's a good thing to keep note of and add in. We could add an additional parameter for `ViewName` and use that in the analytics observer instead of the path. 

Will see where I can fit this in when high priority issues are dealt with.

**Comment by FilledStacks** [comment]
We now have a viewname parameter that can be different. This should bypass the original issue.
