### ISSUE TITLE
Access model in onDispose

### ISSUE THREAD

**Issue by Hannnes1** [Stacked-Org/stacked#429]
When using onModelReady inside ViewModelBuilder, you have access to the model within the callback. It seems like that is not possible when using onDispose. Is that on purpose? It seems like the only change that needs to be done in the source code is to add T to the following line in the source code:

```dart
  final Function()? onDispose;
```

like so:

```dart
  final Function(T)? onDispose;
```

**Comment by FilledStacks** [comment]
@Hannnes1 that is on purpose. You have an override for dispose in the viewmodel where you can dispose anything related to your business logic. 

The onDispose callback is to dispose anything you have in the state of your view.

**Comment by Hannnes1** [comment]
Ah, okay. Thanks!
