### ISSUE TITLE
get null when Pass argument 

### ISSUE THREAD

**Issue by tazik561** [Stacked-Org/stacked#434]
Hi, 
I wondered that on `[replaceWithTransition](https://github.com/FilledStacks/stacked/blob/master/packages/stacked_services/lib/src/navigation_service.dart)` in NavigationService why you  didn't add argument prop? 
I changed it to this :
```
   Future<dynamic> navigateWithTransition(Widget page,
      {bool opaque,
      @required String transition,
      Duration duration,
      bool popGesture,
      int id,
      dynamic arguments}) {
    return Get.to(() => page,
        transition: _getTransitionOrDefault(transition),
        duration: duration ?? Get.defaultTransitionDuration,
        popGesture: popGesture ?? Get.isPopGestureEnable,
        opaque: opaque ?? Get.isOpaqueRouteDefault,
        id: id,
        arguments: arguments);
  }
```

and when I pass a dummy string :
```
await _navigatorService.navigateWithTransition(
      PersonalInfoDegreePage(
        userProfileModel: userProfileModel,
      ),
      transition: NavigationTransition.RightToLeft.name,
      arguments: "dummy test",
    );
```

In `PersonalInfoDegreePage` I got null ? `print(getIt<NavigatorService>().currentArguments);`

**Comment by FilledStacks** [comment]
`currentArguments` are only stored when you use named routing since it goes through a router. 

If you're using this view you can just pass the argument into the constructor of the View you're navigating too if you need it in that view.

**Comment by tazik561** [comment]
> `currentArguments` are only stored when you use named routing since it goes through a router.
> 
> If you're using this view you can just pass the argument into the constructor of the View you're navigating too if you need it in that view.

Thanks, but I changed your repository and I added arguments to your `navigateWithTransition` method , I could send argument. 
Yes by constructor it is possible.
