### ISSUE TITLE
[stacked_generator] passing `dispose` at `@StackedApp`

### ISSUE THREAD

**Issue by calvintam236** [Stacked-Org/stacked#441]
https://github.com/FilledStacks/stacked/blob/a368ebcbc7ab9f54ce4d799885f55ef0c998702f/packages/stacked_generator/lib/src/generators/getit/stacked_locator_generator.dart#L58

https://github.com/FilledStacks/stacked/blob/ce14a15bb1e0cec863e7f51a2700e80c6d240009/packages/stacked/lib/src/code_generation/stacked_locator.dart#L219

By reviewing at the generator code, I don’t see a way I can pass the dispose function at `@StackedApp` (`app.dart`) even the main function support this param. Looks like a bug to me.

**Comment by FilledStacks** [comment]
That's not how a bug is defined. That's just a missing feature. A bug is if something you intend to happen is not happening. This isn't a high priority at the moment but we'll add it to our list and get to it a bit later if there's nothing else above it. 

You're welcome to make a PR and fix it up, I'll review and merge if it's ready to go in .

**Comment by calvintam236** [comment]
Well, if you create a service that you cannot dispose (no way to pass this param to generator, and it is not recommended to commit/edit the generated file; hence, no way to call it), and this service will eventually cause Dart process to hang (memory leak or overflow). This is not really a missing feature (a feature = an enhancement) as this is fixing what is missing.

**Comment by FilledStacks** [comment]
This has not been a priority with any of the other projects using Stacked and will be closed.
