### ISSUE TITLE
[stacked_generator] import relative material.dart

### ISSUE THREAD

**Issue by nickbug** [Stacked-Org/stacked#443]
Triggering conditions:

1.  when project name start with **flutter** (like: flutter_app1, flutterapp2)
2. anyone page use the parameter:
     ```
     class Page1 extends StatelessWidget{
        const Page1({Key key, this.username}) : super(key: key);
     }
      ```

After flutter pub run build_runner build, the **app.router.dart** file:

```
import 'package:flutter/material.dart';
import 'package:stacked/stacked.dart';

import '../../flutter/material.dart';
import '../ui/page1.dart';
```

I found the reason, because the code use the **startsWith**, in this case

targetFilePath = flutter_app1/app/app.dart
package = flutter
path = flutter/material.dart
return= ../../fluterr/material.dart

https://github.com/FilledStacks/stacked/blob/a368ebcbc7ab9f54ce4d799885f55ef0c998702f/packages/stacked_generator/lib/import_resolver.dart#L20-L27

**Comment by josephmangmang** [comment]
Same issue here

**Comment by FilledStacks** [comment]
Aaaaaah, nice catch. I find is strange than an app will start with flutter since it's built in flutter but this should be fixed. @nickbug if you have time and can do a PR then I'll review and merge. Otherwise I'll pass it to @hurbes on the internal team and he'll take a look when he gets some time.
