### ISSUE TITLE
CustomRoute missing reverseTransitionDuration param

### ISSUE THREAD

**Issue by josephmangmang** [Stacked-Org/stacked#448]
<img width="558" alt="Screen Shot 2021-07-12 at 10 28 06 PM" src="https://user-images.githubusercontent.com/7690158/125304788-71c47c80-e360-11eb-9b7f-8a27c654fb45.png">
Is there a way to define reverseTransitionDuration for CustomRoute?

**Comment by FilledStacks** [comment]
Hey, I don't think there's a way to do this now. We don't have a parameter for it.
