### ISSUE TITLE
RouteGuards are never reached

### ISSUE THREAD

**Issue by jeanboreta** [Stacked-Org/stacked#449]
Hi!

First of all, awesome package! But I am having issues implementing RouteGuards.

Following the documentation example, here is my main.dart:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Disco',
      navigatorKey: StackedService.navigatorKey,
      onGenerateRoute: StackedRouter().onGenerateRoute,
      theme: ThemeData(
        appBarTheme: AppBarTheme(color: Colors.white),
        fontFamily: 'Rubik',
        primarySwatch: MaterialColor(0xFF3E9FC9, primaryColor),
        textTheme: Theme.of(context).textTheme.apply(
              fontFamily: 'Rubik',
              bodyColor: Color.fromRGBO(23, 40, 56, 1),
              displayColor: Color.fromRGBO(23, 40, 56, 1),
            ),
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
    );
  }
}
```

Here is my route with its guard:

```dart
AdaptiveRoute(
  page: AuthenticationView,
  name: 'Authentication',
  guards: [SignedOutOnlyGuard],
)
```

Here is the generated RouteDef inside app.router.dart:

```dart
RouteDef(Routes.Authentication,
        page: AuthenticationView, guards: [SignedOutOnlyGuard])
```

And finally, here is my RouteGuard

```dart
class SignedOutOnlyGuard extends RouteGuard {
  final AuthUseCase _auth = GetIt.instance<AuthUseCase>();

  @override
  Future<bool> canNavigate(
    ExtendedNavigatorState<RouterBase?> navigator,
    String routeName,
    Object? arguments,
  ) async {
    switch (_auth.state) {
      case AuthState.LOADING:
        navigator.replace(Routes.SplashScreen);
        return false;
      case AuthState.ERROR:
        await _auth.signOut();
        return true;
      case AuthState.AUTHENTICATED:
        navigator.replace(Routes.Feed);
        return false;
      default:
        return false;
    }
  }
}
```

The problem is that this canNavigate method is never called and the user can navigate to it regardless of the guard's logic. Are there any other steps that I am missing? The documentation doesn't mentioned guards

I am using stacked: 2.2.2

**Comment by FilledStacks** [comment]
@jeanboreta I've never used route guards in Flutter. The functionality is probably a remnant of the fork from auto_route back when we forked it. 

I wouldn't be able to help you with the problem. @hurbes did we have any issue with guards before and do you know if it works?

**Comment by hurbes** [comment]
@FilledStacks We are not using route guards in any of our projects, I'll check it out and try to reproduce it.

**Comment by jeanboreta** [comment]
Thank you for the quick replies.

If you don't ever use guards, do you use a more efficient way to prevent users navigating to unwanted routes?

**Comment by FilledStacks** [comment]
@jeanboreta we use general control flow and checks in our business logic. We build only mobile apps for clients so we control where everything heads. We're doing a web app later this year so at that point we might need route guards. For now we can just purely control where a user can go with basic logic guarding.

**Comment by ThangD** [comment]
@FilledStacks How about this issue? I'm also using this feature on the web but **Guards** are never reached. Thanks.

@jeanboreta Did you find a solution?

**Comment by FilledStacks** [comment]
@ThangD we haven't properly used stacked on web yet so this might not be supported.

**Comment by jcwasher** [comment]
@ThangD @jeanboreta I came up with a decent workaround for this. You can take advantage of the `onGenerateRoute` function to redirect when necessary. I'll modify the example in the stacked documentation to illustrate.

```
import 'package:stacked_services/stacked_services.dart';
import 'app/app.router.dart';

...

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      // If you've added the stacked_services package then set the navigatorKey, otherwise set
      // your own navigator key
      navigatorKey: StackedService.navigatorKey,
      // Construct the StackedRouter and set the onGenerateRoute function
      onGenerateRoute: (settings) => StackedRouter().onGenerateRoute(
        _guardedSettings(settings),
      ),
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
    );
  }
}
```

Where `_guardedSettings` does something like this:

```
RouteSettings _guardedSettings(RouteSettings settings) {
  final path = settings.name;
  final signedIn = yourAuthStateProvider.signedIn;

  // if you want a path to always be allowed place before your route guards
  if (path == Routes.purchaseProduct) return settings;

  // auth route guard implementation
  if (!signedIn && path != Routes.signIn) {
    return RouteSettings(name: Routes.signIn);
  }

  // no route guards violated, return the settings for the desired route
  return settings;
}
```

**Comment by FilledStacks** [comment]
@jcwasher We'll be looking at guarded routes soon.

**Comment by VittorioParagallo** [comment]
Noooo such a pity that you removed, it is so useful! are you planning to implement route guard in the future?

**Comment by Chappie74** [comment]
I would like to know the same thing. Using stacked web I need guards on my routes for Authenticated Only. @FilledStacks

**Comment by ferrarafer** [comment]
@Chappie74 we need to add it to the documentation but we already support guards.

app.dart
```
        CustomRoute(
          page: UserProfileView,
          path: 'profile',
          guards: [AuthGuard],
        ),

```

auth_guard.dart
```
 class AuthGuard extends StackedRouteGuard {
  @override
  Future<void> onNavigation(resolver, router) async {
    final _userService = locator<UserService>();

    if (!_userService.hasFirebaseUser) {
      router.push(const UnknownViewRoute());
      return;
    }

    resolver.next(true);
  }
}

```

**Comment by Chappie74** [comment]
Thanks @ferrarafer I eventually did figure it out my scanning through the code. Definitely needed in the docs.

**Comment by nguyenle0608** [comment]
> @Chappie74 we need to add it to the documentation but we already support guards.
> 
> app.dart
> 
> ```
>         CustomRoute(
>           page: UserProfileView,
>           path: 'profile',
>           guards: [AuthGuard],
>         ),
> ```
> 
> auth_guard.dart
> 
> ```
>  class AuthGuard extends StackedRouteGuard {
>   @override
>   Future<void> onNavigation(resolver, router) async {
>     final _userService = locator<UserService>();
> 
>     if (!_userService.hasFirebaseUser) {
>       router.push(const UnknownViewRoute());
>       return;
>     }
> 
>     resolver.next(true);
>   }
> }
> ```

Hi @ferrarafer, I tried the above solution but didn't find it working. It seems to me that the generator does not process the guard field
