### ISSUE TITLE
How can i change message font weight from snackbar service?

### ISSUE THREAD

**Issue by ziqq** [Stacked-Org/stacked#451]
Hi bro! Can u add opportunity change  font weight from snackbar message. Plz.

**Comment by FilledStacks** [comment]
hi hi. If you add it and make a PR I'll review and see if it can be merged in. @ziqq

**Comment by akifarhan** [comment]
Hi, would it better for it to be in `SnackbarConfig` or something like the `registerCustomMainButtonBuilder`?

**Comment by FilledStacks** [comment]
@akifarhan probably the snackbar config
