### ISSUE TITLE
Adding FilePicker as a service

### ISSUE THREAD

**Issue by Hannnes1** [Stacked-Org/stacked#457]
To be able to use [FilePicker](https://pub.dev/packages/file_picker), I need to use `FilePicker.platform`. The problem is that that returns an instance of the `FilePickerIO` class, and not the type. Is there a way to do this with the stacked locator, or will I have to use get_it directly?

I have tried to use a `LazySingleton` with `asType`, but that doesn't work either, as that needs the type. The best solution I have right now is to import `FilePickerIO` directly from the packages `src` folder. But that isn't really ideal since ["Code under lib/src is considered private"](https://dart.dev/guides/libraries/create-library-packages#what-makes-a-library-package).

**Comment by FilledStacks** [comment]
Hey, just wrap the package in a service and register your service as a dependency with the stacked app.

**Comment by Hannnes1** [comment]
Thanks, didn't think about that...
