### ISSUE TITLE
Pop Back...

### ISSUE THREAD

**Issue by PeerLabs** [Stacked-Org/stacked#46]
I'm trying to implement the equivalent of `Navigator.pop(context)` in this architecture's Navigation Service.

the scenario is i have transitioned from ViewA to ViewB and that works fine... the transition is great ...

In ViewB i have a button to go back ... and in my onTapped I call a function on the model something like `Future navigateBack() async {}` ...

In this function if i do ... `await _navigationService.navigateTo(Routes.viewA);` ... it works but the transition is not great and looks wonky.

if I do `await _navigationService.navigateWithTransition(HomeView(), transition: "leftToRight",);` it works, the transition is better but not really the same as if I had to do `Navigator.pop(context) `

is there another call that i need to use?

Also note in the video you emulate on Android, which has a hardware back button which we don't have on iOS...

The transition i am after on iOS is the same as if I had to swipe the page to the right... which behaves like `Navigator.pop(context);`

**Comment by PeerLabs** [comment]
So I solved this issue with passing my context from my view to the model and then executing `Navigator.of(context).pop();` there... 

The question is shouldn't this functionality be supported by the Navigation Service out the box? I would argue that going back is a navigation route!

**Comment by FilledStacks** [comment]
@PeerLabs this [is supported in the stacked services](https://github.com/FilledStacks/stacked/blob/293b091484e96764976b876999f83fcaccfdc3ec/packages/stacked_services/lib/src/navigation_service.dart#L117).  If you're using get you don't need the context.

**Comment by surveshoeb** [comment]
@PeerLabs you need to pass current page route in the `back({dynamic result})`


**Example**

> locator<NavigationService>().back(result: Routes.profileViewRoute);

or

> _navigationService.back(result:` Routes.profileViewRoute);
