### ISSUE TITLE
Userootnavigator issue

### ISSUE THREAD

**Issue by Silfalion** [Stacked-Org/stacked#468]
Is it possible to check this pull request potentially urgently as get latest update may have broken the stacked services packages:

https://github.com/FilledStacks/stacked/pull/467

**Comment by Silfalion** [comment]
for anyone facing this, as a temporary fix, add this line:

`  get: "<=4.1.3"`

to your pubspec.yaml

**Comment by FilledStacks** [comment]
@Silfalion this has been fixed in the latest stacked services.
