### ISSUE TITLE
Stacked generator Build Error after upgrade to version 0.5.0 and above

### ISSUE THREAD

**Issue by Abhis33** [Stacked-Org/stacked#469]
![canvas](https://user-images.githubusercontent.com/36435796/126411768-7f921eb2-dbbf-4596-865f-ef24a519a390.png)

![canvas2](https://user-images.githubusercontent.com/36435796/126411804-ea764b21-f676-4f00-8224-7ce3de94ec8e.png)

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[!] Android Studio (version 4.1.0)
    X Unable to find bundled Java version.
[!] Android Studio
    X android-studio-dir = C:\Program Files\Android\Android Studio"
    X Android Studio not found at C:\Program Files\Android\Android Studio"
[√] VS Code (version 1.58.2)
[√] Connected device (2 available)

**Comment by FilledStacks** [comment]
Makes sure you're on the latest stacked version since the factory param is on the latest. Please run `flutter pub outdated` to see which dependencies are out of date
