### ISSUE TITLE
stacked_service Dialog is not showing

### ISSUE THREAD

**Issue by LoveAndroDev** [Stacked-Org/stacked#47]

**Comment by FilledStacks** [comment]
Stacked services uses get. Make sure you set the navigation key for the app equal to the Get.key value. The key is exposed on all services that require it to work, you only have to set it for one service. Which we usually do for the navigation service

**Comment by LoveAndroDev** [comment]
You talking about navigatorkey: locator<NavigationService>.navigatorKey ?

**Comment by LoveAndroDev** [comment]
Yes i had already provided that because i am using navigation service which is working but dialog are not working

**Comment by LoveAndroDev** [comment]
issue solved thanks

**Comment by humayuntanwar** [comment]
how was this solved, please share @LoveAndroDev

**Comment by FilledStacks** [comment]
@humayuntanwar make sure you set the key on the navigator  in the main file
