### ISSUE TITLE
doc: Add table of content to the documentation

### ISSUE THREAD

**Issue by pruthvi145** [Stacked-Org/stacked#471]
Since the documentation is quite big, It is good if there is a **Table of Content** at the top.

**Comment by FilledStacks** [comment]
@pruthvi145 that would be good. I'm busy creating a dedicated website for the docs so we'll be putting our time in there for the docs instead of updating the current readme docs. I'm hoping to get it done over the next few weeks.

**Comment by FilledStacks** [comment]
We will be implementing a new stacked docs website very soon which will contain this.
