### ISSUE TITLE
Listening only to partial changes (in the ViewModel)

### ISSUE THREAD

**Issue by daehan-lim** [Stacked-Org/stacked#472]
Is it possible to add something like the "select" method from the provider package? This is the method's documentation "Watch a value of type T exposed from a provider, and only listen partially to changes. By using select, instead of watching the entire object, the listener will rebuild only if the value returned by selector changes. When a provider emits an update, it will call synchronously all selector."
I don't see a way to do that in stacked. Even if I  use "reactive" only in the child widgets that need to react to ViewModel changes, whenever I call notifyListeners all of those widgets will be rebuilt. Is there no way to make the widgets listen only to the changes I want like the "select" method of provider?

**Comment by Afsal102** [comment]
@daehan-lim  yes its possible but u have to install provider because stacked doesn't have any widgets to do that, with provider u can accomplish the , i have tried it works like charm

**Comment by FilledStacks** [comment]
@daehan-lim at the moment it's not possible. We will probably add that as a new builder type. 

**Feature:** Add a new `PartialViewModelBuilder` that uses `select` from the Provider to rebuild only when certain properties are changed.

**Comment by ifredom** [comment]
> @daehan-lim yes its possible but u have to install provider because stacked doesn't have any widgets to do that, with provider u can accomplish the , i have tried it works like charm

Thank you very much for any examples you can see

**Comment by HarryCarter1995** [comment]
Is anyone using this package and also making use of providers Selector? I am also looking for partial rebuilds of specific widgets and wondering if using Selector with this package is ok?
