### ISSUE TITLE
AsyncSingleton not supported in @StackedApp

### ISSUE THREAD

**Issue by davidjadczyk** [Stacked-Org/stacked#475]
I use ObjectBox as my Database and I can retrieve the initial Instance with an async Function ` await openStore()` . But the Singleton Types in the dependency List do not support async Factory methods. My Repositories depend on the Store Singleton, sothat I also needed to register them outside of the `@StackedApp` in a separate method like this:
```
setupLocatorAdditions() async {
  appLocator.registerSingletonAsync<Store>(() async => await openStore(),
      signalsReady: false);

  appLocator.registerSingletonWithDependencies(() => WorkoutRepository(),
      dependsOn: [Store]);
}
```
would be great if this will be possible in the `dependencies: []` of the `@StackedApp`
```
dependencies: [
      LazySingleton(classType: NavigationService),
      // Something like 
     // SingletonAsync(type: Store, future: openStore / asyncFunction: () => await openStore() )
     // and a dependsOn Iterable Attribute to Sync the Dependency Registration
     // Singleton(type: WorkoutRepository, dependsOn: [Store])
    ])
```

**Comment by hurbes** [comment]
You can use presolves for this.
```dart
 Presolve(
     classType: SharedPreferencesService,
     presolveUsing: SharedPreferencesService.getInstance,
  ),
  ```

**Comment by davidjadczyk** [comment]
@hurbes  but the `openStore()` is not a static class function and the stacked generator always creates something like `Store.openStore()` which doesn't exist.

**Comment by FilledStacks** [comment]
@DJ2695 since you're wrapping open box as your DatabaseService create a static getInstance method in your database service and presolve that.

**Comment by davidjadczyk** [comment]
got it now. Worked with `static Future<Store> getInstance() async => await openStore();` in a DatabaseService class and the Presolve 

```
Presolve(
          classType: DatabaseService,
          asType: Store,
          presolveUsing: DatabaseService.getInstance)
```
thank you both of you @hurbes and @FilledStacks
