### ISSUE TITLE
stackedArchitecture with Beamer 

### ISSUE THREAD

**Issue by abdulahadfolio** [Stacked-Org/stacked#478]
https://github.com/slovnicki/beamer so I was wondering is it possible to integrate beamer with stacked architecture since it wraps around the navigator 2.0 ?

**Comment by FilledStacks** [comment]
@abdulahadfolio Hey, i got it working and then couldn't figure out how to abstract the navigation into a service that's injectable through the locator. 

I'll spend some more time to figure it out when I get some time.

**Comment by abdulahadfolio** [comment]
@FilledStacks just wondering why is this closed do we have an implementation for web?
