### ISSUE TITLE
Conditionally pause stream subscription

### ISSUE THREAD

**Issue by scullabyte** [Stacked-Org/stacked#48]
Currently the `streamsSubscriptions` map has `@visibleForTesting` attached to it, which doesn't let me conditionally pause a stream.

i.e.- I want to add this to stream1.onData:
```
if(condition){ 
	streamsSubscriptions['timer'].resume 
}else{ 
	streamsSubscriptions['timer'].pause; 
}
```

If there's a way to do this another way let me know.

**Comment by FilledStacks** [comment]
@scullabyte Mmmmmm. Would it be fine if I expose a Pause and resume dedicated function? I don't feel comfortable exposing the subscriptions.

Better yet I can create a getter function that returns the subscription for the key passed in?

**Comment by FilledStacks** [comment]
1.5.3 adds `getSubscriptionForKey` function to use
