### ISSUE TITLE
stacked_theme: example folder

### ISSUE THREAD

**Issue by djkloop** [Stacked-Org/stacked#485]
### env
![image](https://user-images.githubusercontent.com/21050914/128485856-96b1ba93-2c55-48b8-add8-a43d3c0192a3.png)

### info
![image](https://user-images.githubusercontent.com/21050914/128485747-51091415-2fd5-4754-8d40-cdbaa403203d.png)

### link
[flutter theme-data-accent-properties](https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties)

**Comment by FilledStacks** [comment]
Are you asking for anything @djkloop
