### ISSUE TITLE
Route id (1) not found

### ISSUE THREAD

**Issue by itsarvinddev** [Stacked-Org/stacked#487]
`_navigationService.navigateTo(
                                    PageModuleRoutes.homeView,
                                    id: 1,)`

I'm getting this error when navigate to new screen
Unhandled Exception: Route id (1) not found

**Comment by hurbes** [comment]
You have to pass the `StackedService.nestedNavigationKey(1)` into your Navigator's `navigatorKey`.

**Comment by FilledStacks** [comment]
@rvndsngwn you happy with the answer above?

**Comment by itsarvinddev** [comment]
`ExtendedNavigator(router: PageModuleRouter(), navigatorKey: StackedService.nestedNavigationKey(1))` I passed the`navigatorKey` already! but the error is still.
@FilledStacks and @hurbes

**Comment by FilledStacks** [comment]
@rvndsngwn Please provide an example it'll be easier to help. We know that should work because there's only 1 issue for it, meaning it works for us and everyone else. There might be something you're missing. A reproducible example will help to solve it.

**Comment by itsarvinddev** [comment]
for now I'm using AutoRouter. I appreciate and thank you for your support, @FilledStacks
