### ISSUE TITLE
setState() or markNeedsBuild() called during build flutter occuring when using future builder 

### ISSUE THREAD

**Issue by LoveAndroDev** [Stacked-Org/stacked#49]
Hi Dane,

So whenever i try to use futurebuilder inside my class where my ViewModelBuilder is reactive i am getting the following error my model class extending ReactiveViewModel

setState() or markNeedsBuild() called during build flutter

**Comment by FilledStacks** [comment]
Future builder is a class for managing state and so is ViewModelBuilder. One of them is asking the UI to rebuild while the other is already rebuilding the UI

**Comment by LoveAndroDev** [comment]
Please provide any solution

**Comment by LoveAndroDev** [comment]
So what I am trying to achieve is paging in my gridview like load more product after every 10 item from API but future builder calling constantly please give me some solution for that

Thanks

**Comment by FilledStacks** [comment]
To remove the error you have to put the call that's causing it to happen on an post frame callback. 

Comment out the calls you think that's causing it and once you find the call causing it you can put it on a post frame callback.

```dart
SchedulerBinding.instance
          .addPostFrameCallback((_) => yourCallHere());
```

**Comment by LoveAndroDev** [comment]
Thanks for answer but
.
.
So where we pass future to future builder that is the is problem causing so what i had done rather then directly calling api call through model i had created one instance of future initilize it inside onModelReady call different method in model which update my future instance and pass that instance to future of future builder.
I do no it is correct or not but it worked for me.

thanks.

**Comment by FilledStacks** [comment]
@LoveAndroDev sounds very complicated. My paging usually happens in my service and the ViewModel just gets an updated version of the list and calls notifyListeners. You can check out[ this infinte scroll tutorial ](https://youtu.be/rr7d3SuhLiU?t=9) or my [paginated data tutorial](https://youtu.be/1chV50D5BVU) it'll give you an idea of how simple it should be using stacked.

**Comment by LoveAndroDev** [comment]
i want to create paging for grid does that work ?

**Comment by FilledStacks** [comment]
@LoveAndroDev the way the data is displayed should have nothing to do with the logic for paging. That's all done in the business logic, the UI just shows the list / grid / cards you want. So you can show it howevery you want to show it.

**Comment by LoveAndroDev** [comment]
Yes i had used your way it worked pretty well thanks man✌✌✌✌
