### ISSUE TITLE
stacked services package has issue with easy localization package ?

### ISSUE THREAD

**Issue by codes-zain** [Stacked-Org/stacked#490]
Hi everyone 
I have issue with stacked services package 
when I import stacked services package and easy localization package in same file 
I can't use tr() method and I got the following error :
A member named 'tr' is defined in extensions 'StringTranslateExtension' and 'Trans' and neither is more specific.
Try using an extension override to specify the extension you want to to be chosen.

my code : 

import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:sooq/app/app.locator.dart';
import 'package:stacked_services/stacked_services.dart';

import 'app/app.router.dart';

void main() async{
  WidgetsFlutterBinding.ensureInitialized();
  setupLocator();
  await EasyLocalization.ensureInitialized();

  runApp(
    EasyLocalization(
        supportedLocales: [Locale('ar'), Locale('en')],
        path: 'resources/langs',
        fallbackLocale: Locale('ar'),
        startLocale: Locale('ar'),
        child: MyApp()
    ),
  );
 // runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'title'.tr(),
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      navigatorKey: StackedService.navigatorKey,
      onGenerateRoute: StackedRouter().onGenerateRoute,
    );
  }
}

![locale](https://user-images.githubusercontent.com/57390988/129086541-2c83fc20-e0b0-4b61-8947-8d813d3ac362.JPG)
o be chosen.

**Comment by FilledStacks** [comment]
Import one using an alias

**Comment by codes-zain** [comment]
> Import one using an alias

I used an alias before I post this, but it not solve the problem.
the problem only appear when I import stacked_services package and easy_localization in same file
and  give me error only when I use .tr() method

**Comment by FilledStacks** [comment]
What does the error say?

**Comment by FilledStacks** [comment]
We don't have those extensions in our code `StringTranslateExtension` or `Trans`
