### ISSUE TITLE
Stacked services NavigationService.clearTillFirstAndShow throws error

### ISSUE THREAD

**Issue by surveshoeb** [Stacked-Org/stacked#50]
Attempting to navigate to next page using `locator<NavigationService>().clearTillFirstAndShow(Routes.appBaseViewRoute);` but it throws error on `popUntil()` 

**Error**
`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type '(dynamic) => dynamic' is not a subtype of type '(Route<dynamic>) => bool' of 'predicate'`

**Comment by FilledStacks** [comment]
Added a type to the predicate parameter and double checked that it's working. Update to 0.3.1+1 and see if it solves the problem.

**Comment by surveshoeb** [comment]
Fixed. Closing the issue.
