### ISSUE TITLE
Reaction on reactive value change

### ISSUE THREAD

**Issue by surajmandalcell** [Stacked-Org/stacked#500]
Currently, we are already using reactiveServiceMixin to listen to ViewModel from the service. Whenever we update value from the service, the ViewModel changes but the issue is that it does not have any custom callbacks for onUpdate or just to perform updates on specific reactive values.

This is how it is handled in getx with workers, is there something similar available in stacked?

```dart
ever(_authService.phoneAuthState, (authState) async {
      switch (authState) {
        case AuthState.failed:
          setBusy(false);
          log.e('OTP verification failed');
          Get.snackbar('Error', 'OTP verification failed');
          break;
        case AuthState.verified:
          log.d('OTP verification successful');
          await _loginCall();
          Get.snackbar('Success', 'OTP verification successful');
          break;
        case AuthState.autoRetrievalTimeOut:
          log.d('OTP timed out');
          break;
        case AuthState.codeSent:
          setBusy(false);
          log.d('OTP sent to $phoneNumber');
          break;
      }
    });
```

**Comment by kodjosama** [comment]
In your view model, create a function, let say _initialize_

```dart
void initialize() {
    // if phoneAuthState is a ReactiveValue variable
    _authService.phoneAuthState.listen((value) {
        // do your stuff here ...
    });
}
```

In the widget, call the _onModelReady_ function.

```dart
return ViewModelBuilder<YourViewModel>.reactive(
    // etc.
    viewModelBuilder: () => YourViewModel(),
    onModelReady: (YourViewModel viewModel) {
        WidgetsBinding.instance!.addPostFrameCallback(() => viewModel.initialize());
    },
);
```

I think this should solve the problem.

**Comment by hurbes** [comment]
@surajmandalcell  As the answer stated above you can listen for the ReactiveValue changes and use it as a stream with the stream view model and perform your callbacks `onData`. Let us know this answers your query.

**Comment by kodjosama** [comment]
Sorry but there is an issue with the previous code :disappointed:

```dart
_authService.phoneAuthState.listen((value) {
    print('changes happen');
    // do your stuff here ...
});
```

Calling the `listen` function on the phoneAuthState got called when the view model has instantiated the first-time event if there are no changes.

The correct way

```dart
_authService.phoneAuthState.onChange.listen((Change change) {
    if (change.old != change.neu) {
        print('changes happen');
        // do your stuff here ...
    }
});
```

**Comment by FilledStacks** [comment]
I'm closing this. If there's any additional queries please comment below.
