### ISSUE TITLE
Running a function before initial render happens

### ISSUE THREAD

**Issue by sadikcoban** [Stacked-Org/stacked#502]
Hi, I am trying to run a function (such as initState in stateful widgets) inside my view before the first render happens. When I use onModalReady callback for this purpose, what I see is this callback runs after the first render on the screen which results in some weird situation for my purpose. Is there any way to get this done with stacked package?

**Comment by gresnick** [comment]
@sadikcoban  - have you tried asking your question to the community in the [FIlledStacks Slack workspace](https://filledstacks.slack.com/archives/CJJG5E32P)?

**Comment by FilledStacks** [comment]
@sadikcoban onModelReady runs before the first render. It's called in the `init` function of the `ViewModelBuilder`

**Comment by FilledStacks** [comment]
What's your situation, what do you expect to happen and what's currently happening?
