### ISSUE TITLE
Listening to reactive values does not update ViewModel after upgrading to null-safety

### ISSUE THREAD

**Issue by StankoKostic** [Stacked-Org/stacked#503]
Greetings Stacked team,

After updating Flutter and packages I am encountering the issue of reactive values not working properly. I am using `ReactiveServiceMixin` and `observable_ish`. Use case is updating the amount of tabs in the bottom navigation bar after triggering a switch on one of the menu pages.

Here is the code to the relevant `BottomNavigationService`:

```dart
import 'package:observable_ish/observable_ish.dart';
import 'package:stacked/stacked.dart';

class BottomNavigationService with ReactiveServiceMixin {
  RxValue<int> _numberOfTabs = RxValue(4);
  RxValue<int> _currentTab = RxValue(0);

  int get numberOfTabs => _numberOfTabs.value;
  int get currentTab => _currentTab.value;

  BottomNavigationService() {
    listenToReactiveValues([_numberOfTabs, _currentTab]);
  }

  void changeNumberOfTabs(int tabs) {
    _numberOfTabs.value = tabs;
  }

  void changeTab(int tab) {
    _currentTab.value = tab;
  }
}
```

Relevant parts of the `BottomNavigationViewModel`:

```dart
class BottomNavigationViewModel extends IndexTrackingViewModel
```
```dart
 @override
  List<ReactiveServiceMixin> get reactiveServices =>
      [langService, _bottomNavigationService];

  int get numberOfTabs => _bottomNavigationService.numberOfTabs;
```
In the relevant page, I am calling:
```dart
_bottomNavigationService.changeNumberOfTabs(5);
```

Important notes: 
- BottomNavigationView is built with `reactive ViewModel builder`
- This was all working properly before the update

Thanks.

**Comment by StankoKostic** [comment]
I managed to solve issue in my case by making the following changes in my code:

In `BottomNavigationService`:
```dart
RxValue<int> get numberOfTabs => _numberOfTabs;
RxValue<int> get currentTab => _currentTab;
```

In `BottomNavigationViewModel`:
```dart
BottomNavigationViewModel() {
    _bottomNavigationService.numberOfTabs.listen((value) {
      setIndex(currentIndex);
    });
}
```

However, this solution seems a bit 'hacky' in my opinion. After breakpointing and testing, I figured that `listenToReactiveValues()` method from `ReactiveServiceMixin` is not working properly.

Hope there will be some update on this issue.

**Comment by AbdullahChauhan** [comment]
@StankoKostic Hello!

If you're using stacked version: `2.1.3` or onwards, you don't need to use `observable_ish` package anymore with stacked. The latest we get now is "ReactiveValue" excluding RxValue (part of `observable_ish` package).
So this should be working fine as per the updates: `ReactiveValue<int> _numberOfTabs = ReactiveValue(4);`

Do checkout the [docs](https://pub.dev/packages/stacked).

**Comment by StankoKostic** [comment]
Thank you very much @AbdullahChauhan. Seems that I've missed that part of the updated docs. Thank you!
Will try it out, and close the issue if all is fine
