### ISSUE TITLE
[stacked]Add Object for the key in multiple stream viewmodel

### ISSUE THREAD

**Issue by Afsal102** [Stacked-Org/stacked#504]
Adding a specific type of object to the onStreamData => [key] 
To integrate it with unions...
**Sample**
```

onStreamData<Union>(Union key, dynamic data){
	key.when(
			key1:(){
				//do some tasks
		},
	);
}


```
sample is used with **freezed** unions.
(T extends Object) any Type of object

**Comment by FilledStacks** [comment]
Are you asking how to do this or are you asking for a new feature?

**Comment by Afsal102** [comment]
A new feature. I stumbled upon this and found this solution.
Its works great with `unions` also eliminates `if` conditions.
I could make a PR if u would like

**Comment by Eimen2018** [comment]
Hey @Afsal102  Yeah sure you can make a PR we will review it.

**Comment by Afsal102** [comment]
@Eimen2018 sure! am quite busy i will try to make a pr by start of `May` 😄

**Comment by Afsal102** [comment]
@Eimen2018 created a PR 😄

**Comment by Eimen2018** [comment]
@Afsal102  Thanks for the PR
