### ISSUE TITLE
NavigationService with auto_route 2.4.0

### ISSUE THREAD

**Issue by corentinc-old** [Stacked-Org/stacked#505]
Hi ! 

Does stacked_services compatible with auto_route 2.4.0 ?

auto_route 2.4.0 doesn't generate a onGenerateRoute() method. 
So, I don't know how to use your NavigationService anymore.

Could you give me some example of how to do it with the last version of auto_route ? 

My root widget :
![image](https://user-images.githubusercontent.com/6071822/134315677-155390a4-f0d7-41ff-8a11-5b839de4ba6e.png)

Example of use : 
![image](https://user-images.githubusercontent.com/6071822/134316034-135b695c-2f43-4b11-bd6d-6a3f1914b685.png)

Example of stacktrace : 
![image](https://user-images.githubusercontent.com/6071822/134315937-b51f6e20-bc84-481e-aba2-35db874bfbc4.png)

Thanks.

**Comment by mrseth01** [comment]
@corentinc 

I finally got it working. The only difference I see between my code and yours is the delegate:

```dart
routerDelegate: AutoRouterDelegate(
        _routerService.router,
        // Provide an AutoRouteObserver instance
        navigatorObservers: () => [
          AutoRouteObserver(),
          StackedService.routeObserver,
          FirebaseAnalyticsObserver(
            analytics: FirebaseAnalytics(),
          ),
        ],
      ),
```

**Comment by FilledStacks** [comment]
@mrseth01 that's awesome! It's actually not compatible which is why we built the previous version of auto route into the stacked generator. 

I'f possible I'd like to see an example of your setup. I don't see how our system can work with Navigator 2.0 without major updates to the way the internals of the navigation service works.

**Comment by look1n** [comment]
@corentinc awesome job, can you please share your experience integrating latest auto_route library with stacked?

**Comment by look1n** [comment]
@mrseth01 awesome job, can you please share your experience integrating latest auto_route library with stacked?
