### ISSUE TITLE
Documentation for MultipleStreamViewModel

### ISSUE THREAD

**Issue by ad-on-is** [Stacked-Org/stacked#51]
Man, can you read minds?! :-D I just switchted my project-architecture to stacked, which clearly represents the architecture, I was searching for and works very well. And 2 days ago, I was working on a problem, where I thought, "hmmm.. That's something where a MultipleStreamViewModel would come in handy" ... and ... boom, the next day - there it is!

Unfortunatelly, there's no documentation providing how to set it up. Could you provide some in the README?

Cheers!

**Comment by FilledStacks** [comment]
@ad-on-is hehe, I think we'll all require the same things at some point. I did forget to add it into the readme. Silly mistake, I'll move the code over from example to the readme. You can see an [example here](https://github.com/FilledStacks/stacked/blob/master/packages/stacked/example/lib/ui/multiple_streams_example/multiple_streams_example_viewmodel.dart). 

There's also [a set of tests](https://github.com/FilledStacks/stacked/blob/89f2a6e88265aa5044879818c6290d0f283f5618/packages/stacked/test/streamviewmodel_test.dart#L153) that show you what you can assume to be true when using the viewmodel. I think the test names are documented well so it should serve as some form of documentation. I'll only be able to add it in the readme late afternoon Sunday after releasing the new video.

**Comment by ad-on-is** [comment]
Aah, great... example looks good so far, thanks! Keep up the good work 👍

**Comment by FilledStacks** [comment]
I added the basic documentation for the Multiple Stream ViewModel into the Readme for the stacked package.

**Comment by aula2030** [comment]
Hi! Thanks @ad-on-is, @FilledStacks 

I was having trouble trying to implement MultipleStreamViewModel. I was trying to retrieve stream data using model.streamsMap[model.myKey].data and was not working :sweat_smile: It was retrieving the StreamData but I couldn't access the data itself.

Reading the doc it is not clear how to use it from views. In the end, I found this closed issue :smile:. So thank you!

A link to the example could be easily added to the README. I could make a PR for that, if you want.

Congratulations for the good work! It is helping me a lot :+1:
