### ISSUE TITLE
stacked_themes update provider to latest 6.0.1

### ISSUE THREAD

**Issue by azazadev** [Stacked-Org/stacked#511]
- it is possible to upgrade provider to 6.0.1
and please also remove or integrate the package flutter_statusbarcolor_ns ( https://github.com/FilledStacks/stacked/issues/501 )

**Comment by azazadev** [comment]
any update please ?

**Comment by FilledStacks** [comment]
@azazadev the package we're using is not being updated. When they update we'll bump our version too.

**Comment by FilledStacks** [comment]
Duplicate of #501
