### ISSUE TITLE
Navigator gets stuck when swiping to go back while displaying Snackbar in iOS

### ISSUE THREAD

**Issue by rjgpereira** [Stacked-Org/stacked#512]
Hi Stacked team! 

When trying to make use of "swipe to go back" feature on iOS, the snackbar interferes with the Navigator's pop.

Example code:

```dart
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:stacked_services/stacked_services.dart';

void main() {
  runApp(MyApp());
}

final locator = GetIt.instance;

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    locator.registerSingleton<SnackbarService>(SnackbarService());
    setupSnackbarUi();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: StackedService.navigatorKey,
      home: MyHomePage(),
    );
  }

  void setupSnackbarUi() {
    final service = locator<SnackbarService>();
    service.registerSnackbarConfig(SnackbarConfig(backgroundColor: Colors.grey));
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Screen 1"),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (context) => SecondPage(),
              ),
            );
          },
          child: Text("Navigate to Screen 2"),
        ),
      ),
    );
  }
}

class SecondPage extends StatefulWidget {
  SecondPage({Key? key}) : super(key: key);

  @override
  _SecondPageState createState() => _SecondPageState();
}

class _SecondPageState extends State<SecondPage> {
  final _snackbarService = locator<SnackbarService>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Screen 2"),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            _snackbarService.showSnackbar(title: 'Title', message: 'This is a snack bar',  duration: Duration(seconds: 4));
          },
          child: Text("Show Snackbar"),
        ),
      ),
    );
  }
}

```

Steps to reproduce:
1. Navigate to the second screen;
2. Tap the button;
3. (while the snackbar is showing) drag from the left edge of the screen to pop the navigation stack;

Result:

The animation is interrupted, the navigator get's stuck and the topmost page is not popped, as displayed bellow.

![Simulator Screen Shot - iPhone 13 - 2021-10-07 at 09 35 11](https://user-images.githubusercontent.com/8735329/136349946-8b2dcc4d-9e78-4bdf-b3a3-388e939ee908.png)

**Comment by FilledStacks** [comment]
Stange! Thank you for you detailed report. We'll definitely take a look at this internally and see if we can fix this.

**Comment by ashlog** [comment]
Any updates on this?

**Comment by hurbes** [comment]
@ashlog This is from `getx` navigator issue. There's still an open issue related to this one. 
[App freeze on transition in iOS when Get.snackbar is open and swipe right gesture executed](https://github.com/jonataslaw/getx/issues/773)

**Comment by jonataslaw** [comment]
Just to let you know, this has been fixed in the latest version.
I hope I haven't broken any features since the snackbar was rewritten from scratch, but now the snackbar uses the overlay api, not the navigation one, so there's no chance of that happening.

**Comment by hurbes** [comment]
@jonataslaw Thanks
@ashlog version 0.8.16 is released with updated `getx` dependency.

**Comment by Natan-hub** [comment]
I have this same problem using the another_flushbar package that when you swipe and the screen gets stuck and it was said to have been fixed, using the flutter documentation I saw that it doesn't crash but when swiping the snack bar ends up going to the previous screen too and it does not close. Is there no way to close it?

**Comment by KoenVestjens** [comment]
@Natan-hub Did you manage to fix/find a solution? I have the same issue using another_flushbar.

**Comment by Natan-hub** [comment]
> @Natan-hubVocê conseguiu consertar/encontrar uma solução? Tenho o mesmo problema ao usar another_flushbar.

unfortunately no, I ended up changing the package, now if I swipe the flush bar remains on the screen but at least it doesn't lock it

**Comment by KoenVestjens** [comment]
@Natan-hub FYI, I found out you also can use `blockBackgroundInteraction`.
