### ISSUE TITLE
Error: Required named parameter 'vsync' must be provided.

### ISSUE THREAD

**Issue by puhpavel** [Stacked-Org/stacked#521]
Recently my flutter app stop to compile because of stacked package, the whole log:

`Waiting for connection from debug service on Chrome...
../../.pub-cache/hosted/pub.dartlang.org/stacked-2.2.7/lib/src/state_management/skeleton_loader.dart:103:29: Error: Required named parameter 'vsync' must be provided.
              ? AnimatedSize(
                            ^
../../fvm/versions/stable/packages/flutter/lib/src/widgets/animated_size.dart:56:9: Context: Found this candidate, but the arguments don't match.
  const AnimatedSize({
        ^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/stacked-2.2.7/lib/src/state_management/skeleton_loader.dart:98:26: Error: Required named parameter 'vsync' must be provided.
      child: AnimatedSize(
                         ^
../../fvm/versions/stable/packages/flutter/lib/src/widgets/animated_size.dart:56:9: Context: Found this candidate, but the arguments don't match.
  const AnimatedSize({
        ^^^^^^^^^^^^
Failed to compile application.`

**Comment by hunterdowns** [comment]
Saw the same issue.  I was using Flutter 2.2.3.  Upgraded to 2.5.3...Fixed it

**Comment by arslan9380** [comment]
I'm facing the same issue. please suggest a solution except upgraded to flutter?

**Comment by vetri654vel** [comment]
**For Hot Fix**
open the pub-cache/hosted/pub.dartlang.org/stacked-2.2.7/lib/src/state_management/skeleton_loader.dart
**And Replace this Function (Just add the Parameter it Required)**

 ```
 return IgnorePointer(
      ignoring: widget.loading,
      child: AnimatedSize(
	  vsync: this,
          duration: const Duration(milliseconds: 250),
          curve: Curves.easeOut,
          // We only want to show this if the widget is loading OR if the widget is busy with the transition.
          child: widget.loading || _transitionToNewWidget
              ? AnimatedSize(
			  vsync: this,
                  duration: Duration(milliseconds: 450),
                  curve: Curves.easeOut,
                  child: ShaderMask(
                    child: CustomPaint(
                      child: widget.child,
                      foregroundPainter: RectangleFillPainter(),
                    ),
                    blendMode: BlendMode.srcATop,
                    shaderCallback: (rect) {
                      return LinearGradient(colors: [
                        animationOne.value!,
                        animationTwo.value!,
                      ]).createShader(rect);
                    },
                  ),
                )
              : widget.child),
    );
```

**Comment by hurbes** [comment]
Hey, I think you're using an older version on flutter cause the `vsync` field in the AnimatedSize widget is deprecated after  flutter`v2.2.0-10.1.pre` and it's not a required field anymore so it shouldn't be a problem.
