### ISSUE TITLE
Support for Provider 6.0.0

### ISSUE THREAD

**Issue by JaidynBluesky** [Stacked-Org/stacked#524]
I am using the latest (2.2.7) version of Stacked in our app, but there is a version of another package containing a potentially critical fix that requires provider ^6.0.0. Currently stacked 2.2.7 only supports ^5.0.0.

Will this dependency be updated soon?

Cheers.

**Comment by jeremylcarter** [comment]
Have you tried, in the iterrim seeing if you can pin provider to version 5 using dependency overrides.

https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by JaidynBluesky** [comment]
> Have you tried, in the iterrim seeing if you can pin provider to version 5 using dependency overrides.
> 
> https://dart.dev/tools/pub/dependencies#dependency-overrides

Yeah, this seemed to work in the meantime. Thanks for the suggestion.
