### ISSUE TITLE
[Question] Is riverpod integration planned?

### ISSUE THREAD

**Issue by bgervan** [Stacked-Org/stacked#527]
Is it planned to create/change to riverpod instead of Provider?

**Comment by look1n** [comment]
+1
Is it possible to use Riverpod with current implementation?

**Comment by FilledStacks** [comment]
@bgervan no. Unless it provides a clear set of advantages over using provider we will not move from provider to riverpod. If you have any please share them, based on what I looked at, it does the exact same things as provider with a new syntax
