### ISSUE TITLE
[stacked_services] Add 'Duration' property in SnackbarConfig

### ISSUE THREAD

**Issue by Tankerch** [Stacked-Org/stacked#528]
`version: stacked_services: 0.8.15`

To change the duration value for how long the snackbar appears, I have to pass the `Duration` value to all `showCustomSnackBar` methods. The default value of 1 second is too fast for me to use in my project and changing it in every method is very repetitive.

Therefore, wouldn't it be better if `Duration` added in SnackbarConfig?

Old way:
``` dart
  // At register phase
  _snackbarService.registerCustomSnackbarConfig(
      variant: SnackbarVariant.Info,
      config: SnackbarConfig(
        backgroundColor: VoilaColor.Black,
        textColor: VoilaColor.White,
      ));

 // call custom snackbar
 _snackbarService.showCustomSnackBar(variant: SnackbarVariant.Info, message: err.message, duration: Duration(seconds: 3)); 

// Need to pass Duration(seconds: 3) to each showCustomSnackBar
```

New way:
``` dart
  // At register phase
  _snackbarService.registerCustomSnackbarConfig(
      variant: SnackbarVariant.Info,
      config: SnackbarConfig(
        backgroundColor: VoilaColor.Black,
        textColor: VoilaColor.White,
        duration: Duration(seconds: 3)
      ));

 // call custom snackbar
 _snackbarService.showCustomSnackBar(variant: SnackbarVariant.Info, message: err.message);

// Now, all snackbars that use variant: SnackbarVariant.Info appear for 3 seconds
```

**Comment by yaikuro** [comment]
+1 Please add this feature. 
Right now the duration of the snackbar is way too fast. It's even worse if you add animationDuration, the snackbar won't even show up properly cause the duration is counted along with the animation duration.

**Comment by FilledStacks** [comment]
If one of you can make a PR for it then I'd be happy to merge it

**Comment by vishhmakasana** [comment]
@FilledStacks I have created PR for this please have a look on it. @Tankerch @yaikuro

**Comment by FilledStacks** [comment]
PR has been merged by @vishhmakasana
