### ISSUE TITLE
Disposing in the view model

### ISSUE THREAD

**Issue by kansson** [Stacked-Org/stacked#53]
Image a view model which has  a `TextEditingController` to get the text from a `TextField` in the view. This controller can be initialized with the help of `ViewModelBuilder.onModelReady` but how would it be disposed correctly?

**Comment by pgudivadaDiligent** [comment]
viewModel should not access to the `TextEditController`.  view should be passing the value to the viewModel.  This [might](https://www.filledstacks.com/post/flutter-state-management-with-stacked/#viewmodelwidgets-for-children-that-inherit-the-viewmodel) help.

**Comment by kansson** [comment]
Yes that would solve my problem, thanks.
