### ISSUE TITLE
Question: Can I use Stacked packages to create a flutter package?

### ISSUE THREAD

**Issue by bdairy** [Stacked-Org/stacked#531]
Hi there,

I have a package delivery for a client.. package includes main widget,, and sub views with more than one service,, I am stacked addicted now a days,, my wonder, can I use stacked & stacked services to create a package??

Regards.

**Comment by FilledStacks** [comment]
@bdairy yes, you absolutely can. 

I use stacked to create our other packages or internal package as well.

**Comment by bdairy** [comment]
@FilledStacks  I built the package,, was working like charm :D then.  figured out that the client project is using onGenerateRoute,,,  my question how to avoid setting the navigatorKey for the package... is there away around it?? and still using the navigation service?

**Comment by FilledStacks** [comment]
@bdairy the navigation services uses a NavigatorKey. As long as you provide the navigation key to is it'll interact with that navigator. The key doesn't have to be linked to a router using onGenerate route, although it's built specifically for named routing.

**Comment by bdairy** [comment]
@FilledStacks  thanks for the reply,, I guess if I want to use the navigation service then there is no other way but to use the navigator key..my question what if I created the package,, and the target project uses its own navigator key for some reason,, is there any way around it,, ? again I am a big fan :)
