### ISSUE TITLE
[Question] FormViewModel Validation for Individual Form Fields

### ISSUE THREAD

**Issue by ghost** [Stacked-Org/stacked#532]
### Discussed in https://github.com/FilledStacks/stacked/discussions/530

<div type='discussions-op-text'>

<sup>Originally posted by **serpv357** November 17, 2021</sup>
I am learning Stacked Architecture and working with the form generator. I see that in the FormViewModel class there is a single showValidation property and a single validationMessage property, which means that you can only have one validation message showing using setValidationMessage "out of the box". What would be the best way to have validation for each individual form field displaying under each field?

Edit: What seems to work is something like this but let me know what I should be doing.

Edit 2: I also have the use case where I want one (or more) of the FormTextFields to be readonly, and set that as a result of a calculation relying on the other fields, like in a calculator app, but it seems that the automatically generated stuff does not have a setter. Edit 3: oh, looks like the answer to this is here: https://github.com/FilledStacks/stacked/issues/382

```
class AgePayFormViewModel extends FormViewModel {
  final _navigationService = locator<NavigationService>();

  bool _showValidationAge = false;
  bool get showValidationAge => _showValidationAge;

  String? _validationMessageAge;
  String? get validationMessageAge => _validationMessageAge;

  void setValidationMessageAge(String? value) {
    _validationMessageAge = value;
    _showValidationAge = _validationMessageAge?.isNotEmpty ?? false;
  }

  @override
  void setData(Map<String, dynamic> data) {
    setValidationMessageAge(null);
    super.setData(data);
  }

  @override
  void setFormStatus() {
    // do validation for each field

    if (ageValue?.isEmpty ?? false) {
      // set validation message for age
      setValidationMessageAge("Enter an age");
    }
  }

  // If the dev doesn't want realtime validation then they can
  // simply validate in the function that they'll use to submit the
  // data to the backend or db.

  Future? saveData() {
    // here we can run custom functionality to save to our api
  }

  Future? navigateSomewhere() {
    // possible navigation
  }
}

```</div>

**Comment by FilledStacks** [comment]
@serpv357 this functionality is not supported out of the box. Most likely if we can update the validation message to be a map that is generated using the same key as the controller form value map then you'd have the option built in. 

Unfortunately I have not had time to improve stacked functionality but if you want to you can make a PR and I can review it and get the functionality into the package.

**Comment by FilledStacks** [comment]
This is going into planning

**Comment by ghost** [comment]
Hello @FilledStacks, any progress on this? 
I might have a PR ready in a few days if still needed! 👀😄

**Comment by FilledStacks** [comment]
Awesome! @Gerfaut I will check it out later today and review
