### ISSUE TITLE
StackedLogger logs information in release mode

### ISSUE THREAD

**Issue by TobiCrackIT** [Stacked-Org/stacked#541]
StackedLogger logs info even in release mode. There appears to be no other way to stop this except modifying the app.logger.dart file

**Comment by FilledStacks** [comment]
@TobiCrackIT provision for this will be added. The reason is logs in production is because if you have a remote logger like google cloud logging you want the session to be logged for remote debugging. But we can probably allow for console logs to be turned off in production.

**Comment by FilledStacks** [comment]
I've added this to the Stacked Issue clearance project

**Comment by TobiCrackIT** [comment]
Thanks @FilledStacks

**Comment by FilledStacks** [comment]
This is fixed in version 0.5.7 of generator + 2.2.8 of stacked
