### ISSUE TITLE
BottomSheet custom widget 

### ISSUE THREAD

**Issue by matszafraniec** [Stacked-Org/stacked#543]
Hello,

I would like to ask, how we can use custom widget in BottomSheetService predefined showBottomSheet and showCustomSheet? Something similar to Get.bottomSheet(), where first property is Widget. In mentioned methods I can see only title and description properties, no way to pass there custom widget like presented below:

<img src="https://user-images.githubusercontent.com/31272038/145587218-a9fa699a-0629-4a9a-b616-876c2b76d41c.png" width="250" height="500">

**Comment by isaacadariku** [comment]
@matszafraniec go through [this](https://www.filledstacks.com/post/bottom-sheets-in-flutter-through-stacked-services/) you will see how to  use the custom bottomsheet

**Comment by Ruslanbek0809** [comment]
It is not mentioned in docs but there is a way to pass custom data. To pass custom data use property called `data` in here like this:

```
Future showCustomBottomSheet() async {
  var sheetResponse = await _bottomSheetService.showCustomSheet(
    variant: BottomSheetType.floating,
    title: 'This is a floating bottom sheet',
    description:
        'This sheet is a custom built bottom sheet UI that allows you to show it from any service or viewmodel.',
    mainButtonTitle: 'Awesome!',
    secondaryButtonTitle: 'This is cool',
    data: 'Your data to pass. Could be custom model or anything. Here it is String'
  );
```

And you will pass this using `sheetRequest.data` like this:

```
void setupBottomSheetUi() {
  final bottomSheetService = locator<BottomSheetService>();

  final builders = {
    BottomSheetType.floating: (context, sheetRequest, completer) =>
        _FloatingBoxBottomSheet(
       request: sheetRequest, 
       completer: completer,
       myData: sheetRequest.data ) // You pass it here 
  };

  bottomSheetService.setCustomSheetBuilders(builders);
}
```

This is your `_FloatingBoxBottomSheet` StatelessWidget :

```
class _FloatingBoxBottomSheet extends StatelessWidget {
  final SheetRequest request;
  final Function(SheetResponse) completer;
  final String myData;
  const _FloatingBoxBottomSheet({
    Key key,
    this.request,
    this.completer,
    this.myData,
  }) : super(key: key);
```

**Comment by FilledStacks** [comment]
@matszafraniec does the above answer your question?

**Comment by matszafraniec** [comment]
> @matszafraniec does the above answer your question?

Yes. Thank you so much @Ruslanbek0809
