### ISSUE TITLE
Refresh FutureViewModel data

### ISSUE THREAD

**Issue by shayant98** [Stacked-Org/stacked#544]
Is there a way to update data that's recieved from a future in the viewmodel, AFTER it's been build. let's say a pull to refresh to update the base set with new data. any advice is welcome

**Comment by shayant98** [comment]
class HomeViewModel extends FutureViewModel<List<Workorder>> {
  final _log = getLogger("HomeViewModel");
  final NavigationService _navigationService = locator<NavigationService>();
  final BottomSheetService _bottomSheetService = locator<BottomSheetService>();
  final SnackbarService _snackbarService = locator<SnackbarService>();
  final UserService _userService = locator<UserService>();
  final WorkorderService _workorderService = locator<WorkorderService>();

  User? _user;
  User? get user => _user;

  Workorder? _activeWorkorder;
  Workorder? get activeWorkorder => _activeWorkorder;

  void init() {
    _user = _userService.currentUser;
    _activeWorkorder = _workorderService.activeWorkorder;
  }

  final List<MenuItem> _menu = [
    MenuItem(
      "Workorder Management",
      Routes.workordersView,
      const Icon(FontAwesomeIcons.accusoft),
    ),
    MenuItem(
      "Device Lookup",
      Routes.deviceLookupView,
      const Icon(FontAwesomeIcons.accusoft),
    ),
    MenuItem(
      "device Manuals",
      Routes.deviceManualsView,
      const Icon(FontAwesomeIcons.accusoft),
    ),
  ];

  List<MenuItem> get menu => _menu;

  void navigateTo(String route, {args}) {
    if ((route == Routes.deviceLookupView || route == Routes.deviceManualsView) && activeWorkorder == null) {
      _bottomSheetService.showBottomSheet(title: "No Active Workorder", description: "To view devices, please select an active workorder");
      return;
    } else if (route == Routes.detailsView) {
      _navigationService.navigateTo(route, arguments: DetailsViewArguments(id: 1));
    }
    _navigationService.navigateTo(route);
  }

  void navigateToDetails(id) {
    _navigationService.navigateTo(Routes.detailsView, arguments: DetailsViewArguments(id: 1));
  }

  updateWorkorderStatus(Workorder workorder) {
    if (workorder.status == WorkorderStatus.RGS && _activeWorkorder != null) {
      _snackbarService.showSnackbar(title: "Error", message: "Incident - ${activeWorkorder!.customer.name} not resolved");
      return;
    }

    _activeWorkorder = _workorderService.setWorkorderStatus(workorder);
    data!.removeWhere((workorder) => workorder.id == _activeWorkorder!.id);
    if (activeWorkorder!.status == WorkorderStatus.executed) {
      _snackbarService.showSnackbar(message: "Incident - ${activeWorkorder!.customer.name} successfully resolved");
      _activeWorkorder = null;
    }
    notifyListeners();
  }

  @override
  Future<List<Workorder>> futureToRun() {
    return _workorderService.getTodayWorkorders(take: 2);
  }

  refreshData() async {
    await runBusyFuture(_workorderService.getTodayWorkorders());
    notifySourceChanged();
  }
}


this is the viewmodel in question. the refreshdata is called when i pull but i get a build error

**Comment by Ruslanbek0809** [comment]
Hi. I know it is late but you can use stacked package's built-in `initialise()` method. It triggers `onModelReady` again. 

In your `View` you can use it like this: 

```
onRefresh: () async {
   await model.initialise(); // This reinitializes whole View
   _refreshController.refreshCompleted();
    }
```

In your `ViewModel` it is used like this: `initialise();`

Also check this [link](https://filledstacks.slack.com/archives/CJY4SV5KQ/p1639457439405400)

**Comment by FilledStacks** [comment]
@shayant98 does the above answer your question?

**Comment by shayant98** [comment]
Yes it does, thanks @Ruslanbek0809
