### ISSUE TITLE
AnimatedSize required vsync must be provided

### ISSUE THREAD

**Issue by Mumunt** [Stacked-Org/stacked#546]
I use this package with version `stacked: ^2.2.7+1.` But, i found an error when compiling.

`../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/stacked-2.2.7+1/lib/src/state_management/skeleton_loader.dart:103:29: Error: Required named parameter 'vsync' must be provided.
              ? AnimatedSize(
                            ^
../../tools/flutter/packages/flutter/lib/src/widgets/animated_size.dart:56:9: Context: Found this candidate, but the arguments don't match.
  const AnimatedSize({
        ^^^^^^^^^^^^
../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/stacked-2.2.7+1/lib/src/state_management/skeleton_loader.dart:98:26: Error: Required named parameter 'vsync' must be provided.
      child: AnimatedSize(
                         ^
../../tools/flutter/packages/flutter/lib/src/widgets/animated_size.dart:56:9: Context: Found this candidate, but the arguments don't match.
  const AnimatedSize({
        ^^^^^^^^^^^^
Failed to compile application.
`

this is my sdk version `sdk: ">=2.12.0 <3.0.0"`.
i run this project in chrome as web app.

**Comment by zorro-ftw** [comment]
Had the same problem while developing a mobile app.

I found that issue begins in version 2.2.7 of this package.

The solution I found (for now) was  updating `stacked: ^2.2.7` to `stacked: 2.2.5` in pubspec.yaml. Be noted that this will make your app to use only 2.2.5 version of stacked package and it would not keep updating itself.

**Message for developers of this package:**

Problem seems to be in "..src/state_management/skeleton_loader.dart" in line 103 where a required parameter named "vsync" is not provided for AnimatedSize widget. Can you include this issue's fix for newer versions?

Thanks,
Best regards.

**Comment by FilledStacks** [comment]
@zorro-ftw yes, this can definitely be added. Thanks for taking the time to find the issue. Will add this to our issue clearance project and start working on this as soon as there's time.
