### ISSUE TITLE
scoket-io-client  implementation

### ISSUE THREAD

**Issue by kururu-abdo** [Stacked-Org/stacked#547]
i  wanna use **socket-io-client** lib alongside **stacked**
what  is  the  good  way to do so?

**Comment by FilledStacks** [comment]
The same way as you would use a normal stream. Add it to your service, consume it where you need it in the viewmodel or a different service. Stacked doesn't dictate how things should be used. So however you were going to use it you should. 

It's basically the same as a stream or will be converted into one so just use it that way.
