### ISSUE TITLE
use  FutureViewModel  print error log

### ISSUE THREAD

**Issue by tablebird** [Stacked-Org/stacked#552]
Use FutureViewModel to request the network to throw an exception and print the following log: 

`E/flutter (20956): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type
E/flutter (20956): #0      _FutureListener.handleError (dart:async/future_impl.dart:194:7)
E/flutter (20956): #1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
E/flutter (20956): #2      Future._propagateToListeners (dart:async/future_impl.dart:800:13)
E/flutter (20956): #3      Future._completeError (dart:async/future_impl.dart:610:5)
E/flutter (20956): #4      _completeOnAsyncError (dart:async-patch/async_patch.dart:274:13)
E/flutter (20956): #5      BaseViewModel.runBusyFuture (package:stacked/src/state_management/base_view_models.dart)
E/flutter (20956): <asynchronous suspension>`

**Comment by FilledStacks** [comment]
Hey, I don't know what you're asking. 

Is there something that you need help with?

**Comment by rcsousa14** [comment]
I got the same error using FutureViewModel.
<img width="810" alt="error" src="https://user-images.githubusercontent.com/31862300/150132076-7f63960e-4cfe-4165-9e9e-1e3775a7d197.PNG">

**Comment by rcsousa14** [comment]
I would elaborate more but I just trying to make a regular http request on a service and getting the data on the view model

**Comment by rcsousa14** [comment]
I got the same error and the stack trace says the error is on the baseviewmodel.
<img width="808" alt="error" src="https://user-images.githubusercontent.com/31862300/150132519-989b9e21-3038-4164-b64e-549d5951c28e.PNG">

**Comment by Turbo0x03** [comment]
The problem appears when you try to use the FutureViewModel implementation

A workaround is to use the BaseViewModel 

```
return ViewModelBuilder<HomeViewModel>.reactive(
  fireOnModelReadyOnce: true,
  onModelReady: (model) =>
      model.getDataFuture(),
  builder: (context, model, child) =>Scaffold(),
  viewModelBuilder: () => HomeViewModel(),
);
```

And

```
Future getDataFuture() async {
  try {
    final result = await runBusyFuture(YOUR_FUTURE,
        throwException: true);
    setBusy(false);
  } catch (e) {
    setError(e);
    log.e(e.toString());
  }
}
```

**Comment by rcsousa14** [comment]
I figure it out. @tablebird check how you are sending the data. In my case I have a model and I was sending the wrong data on it. example on my the data from API was a int but my model said it was string.

**Comment by Turbo0x03** [comment]
@rcsousa14 indeed that is the problem, but the catch should, in theory, catch that error and send it to your UI with setError(), but it doesn't do that, for example, if there is anything wrong coming back, we should be able to throw an exception and then catch that in our models.

**Comment by FilledStacks** [comment]
This is fixed in latest stacked release
