### ISSUE TITLE
Add custom UI to dialogservice.

### ISSUE THREAD

**Issue by sanalkv** [Stacked-Org/stacked#56]
i have noticed that there is no option to add a custom UI for dialogservice, hope the feature is in development.

**Comment by FilledStacks** [comment]
@sanalkv yes. This is currently a feature required for us in production as well so I'll be taking what we've done in production and moving it in here on Sunday. I'll rename this to remind myself and then let you know when it's done.

**Comment by sanalkv** [comment]
sure, waiting for it.

**Comment by YazeedAlKhalaf** [comment]
Any updates?

**Comment by FilledStacks** [comment]
@YazeedAlKhalaf I've come up with the way to do it, but haven't written any code. I'm working on my own stuff all day today so I'll probably get to it later on today. I hope I can finish it up today.

**Comment by FilledStacks** [comment]
@sanalkv @YazeedAlKhalaf This has been added into 0.4.0. Please read the [Custom dialog section on the readme](https://pub.dev/packages/stacked_services#custom-dialog-ui)

**Comment by sanalkv** [comment]
Sure, Thanks alot.

**Comment by YazeedAlKhalaf** [comment]
Sure, Thanks a lot.
