### ISSUE TITLE
This is not an issue. I'd like to support you.

### ISSUE THREAD

**Issue by gscottschulz** [Stacked-Org/stacked#560]
Hi Dane,
I was wondering if you've ever thought of enabling people to pay you with BAT tokens? I use the Brave web browser and get a decent amount of BAT tokens every month. I'd be willing to pay you using them. I use your stuff for work and personal use and I love your YouTube channel. Please consider this so I can help!

https://publishers.basicattentiontoken.org/

Keep up the AMAZING work!!

**Comment by hetthummar** [comment]
We shouldn't be writing this thing here but I agree with you @gscottschulz
I am also using a brave browser for the past 6 months and I think I have a decent amount of **BAT coin** which I like to give to you for your amazing work. 
I discovered your channel very early on when I just started to learn flutter and it helped me a lot. 
Thank you for your amazing work.

**Comment by gscottschulz** [comment]
I'm closing this since it's not an issue and also https://www.filledstacks.com and filledstack's youtube channel are now Brave verified creators. Thanks @FilledStacks !
