### ISSUE TITLE
navigator 2.0 support.

### ISSUE THREAD

**Issue by richard457** [Stacked-Org/stacked#563]

**Comment by Reprevise** [comment]
I would love to see navigator 2.0 support.

**Comment by FilledStacks** [comment]
Hey, we currently don't use navigator 2.0 and doesn't look appealing to use either given how it mixes state and UI functionality. 

I will reasses to see if there's better ways to manage it yet then come back to this.

**Comment by FilledStacks** [comment]
This issue might be revisited when we do a full web support sweep for Stacked. Right now it's low priority compared to the [cli updates ](https://stacked.filledstacks.com/docs/getting-started/how-it-works)
