### ISSUE TITLE
How to reset when user logout

### ISSUE THREAD

**Issue by hetthummar** [Stacked-Org/stacked#564]
I am using this architecture for the past six months and I love it.
The only question I have is how can I reset all view models of the app when users log out.

All the ViewModel are singleton so when the user logs out and another user logs in the data of the previous user are still loaded in all the ViewModel. 
I face the problem continuously whenever are try to implement a bottom navigation bar with a persistent page.

**Comment by paul-ube** [comment]
What I did here was to unregister the `LazySingleton` when the user logs out. It might be a little dirty, considering this architecture.

```
 if (locator.isRegistered<MyLazySingleton>()) {
      locator.unregister<MyLazySingleton>();
      locator.registerLazySingleton(
        () => MyLazySingleton(),
      );
    }
```

I am also looking for a solution to this.

**Comment by hetthummar** [comment]
Hey, @paul-ube Here is what I am currently doing not so sure that we should do this in the production app.

I created one function resetLocator() and put it into CustomBaseview and whenever a user logs I am calling this function.

```
resetLocator() async{
    await locator.reset(dispose: true);
    setupLocator();
    setupSnackBarUi();
    setUpBototmSheet();
    setupDialogUi();
  }
```

**Comment by FilledStacks** [comment]
Does this answer your question?

**Comment by hetthummar** [comment]
> Does this answer your question?

Sorry for the late reply.
Is there any better solution? then doing this

```
resetLocator() async{
    await locator.reset(dispose: true);
    setupLocator();
    setupSnackBarUi();
    setUpBototmSheet();
    setupDialogUi();
  }
```
