### ISSUE TITLE
flutter web screen resize view model widget will rebuild

### ISSUE THREAD

**Issue by yamamz** [Stacked-Org/stacked#566]
Screen resize in flutter web viewmodelwidget gets rebuild

**Comment by yamamz** [comment]
when you have iframe on viewmodelwidget the screen flickers when resizing the screen using this widget `HtmlElementView `

**Comment by yamamz** [comment]
without stacked the build method does not rebuild when resizing the screen

**Comment by FilledStacks** [comment]
@yamamz we don't focus on web at the moment but will keep this issue here for when we get full time devs.
