### ISSUE TITLE
The titleText property in registerCustomSnackbarConfig not reflecting on the Snackbar title

### ISSUE THREAD

**Issue by iamelio** [Stacked-Org/stacked#569]
Adding text to the `titleText` property of `registerCustomSnackbarConfig()` does not reflect any change in the snackbar on the UI.

I went through the source code and noticed that only `title` is passed in from `showCustomSnackBar` in the `ViewModel` and it is `null` when `title` isn't defined, while ideally the `titleText` from `registerCustomSnackBarConfig` should be referenced if `title` is not specified in `showCustomSnackBar` before pointing to null if both values aren't specified.

This is a small issue and I will push a PR that contains fixes for this.

**Comment by FilledStacks** [comment]
Did you push this PR?

**Comment by iamelio** [comment]
Yeah, I did.  :)

It's part of #571.
Thanks!

**Comment by Eimen2018** [comment]
@thecokerdavid Thank you for the PR
