### ISSUE TITLE
Wrap required provider functionality in Stacked Specific implementations and Hide dependencies

### ISSUE THREAD

**Issue by VictorUvarov** [Stacked-Org/stacked#57]
We can currently use provider just by importing stacked.

- This is only possible if you import the full `import 'package:provider/provider.dart';
`. VSCode won't auto import it.
- A user could just start using provider features like (ChangeNotifierProvider) and avoid stacked. (Idk why).

**Comment by FilledStacks** [comment]
@VictorUvarov I've actually been wanting to allow users to use provider through stacked but I don't know how. Is it possible now? Especially when building responsive UI and you want to provide data models to multiple layouts using a basic Provider and the ViewModelWidget.

**Comment by VictorUvarov** [comment]
@FilledStacks  It only works if you use `import 'package:provider/provider.dart';`. Since stacked imports provider that import will resolve because it finds the dependency in stacked. You can just type `ChangeNotifierProvider` and expect VSCode to auto import. I assumed you wanted to wrap provider and hide it. I'm not sure how you can export an import in a dart package.

**Comment by FilledStacks** [comment]
@VictorUvarov I would like to expose at least the provider class so the user can provide some kind of value. Or maybe I should write my own wrapper for that as well just to keep everything as Stacked? Let me think about that, it's a good point you're bringing up. What do you think? 

Write wrappers for the functionality in stacked and hide provider details?

**Comment by VictorUvarov** [comment]
I would lean towards writing wrappers. Bloc library wraps provider also.

**Comment by FilledStacks** [comment]
@VictorUvarov wrappers it is the. I'll rename this issue and label it so I can work on it on Sunday

**Comment by YazeedAlKhalaf** [comment]
Any updates?

**Comment by FilledStacks** [comment]
Oh yah, @VictorUvarov I can't actually see provider through this package. Did dart maybe update the scope? If I'm in a project with only stacked I get no exposed provider parts. 

@YazeedAlKhalaf based on the reply to victor above I didn't do anything to hide provider package.

**Comment by VictorUvarov** [comment]
@FilledStacks Oh I must have had a project with provider already in my dependencies. Never mind I guess.
