### ISSUE TITLE
Unhandled Exception: type 'bool' is not a subtype of type 'StackedRoute<dynamic>?' of 'result'

### ISSUE THREAD

**Issue by AlastairOZ** [Stacked-Org/stacked#572]
I just updated to the latest version of Flutter,
Now when I used Stacked Navigation service, specifically the 'navigator.back'  function I get an error

  Future navigateBackOne() async {
    JobActivityItemChangedModel _results = JobActivityItemChangedModel(deleteitem: false, saveitem: false ,item: _itemoriginal);
   _navigationService.back(result: _results);
  }

I tried replacing my _results model with any value (I tried bool, list, string)  produces error "Unhandled Exception: type 'bool' is not a subtype of type 'StackedRoute<dynamic>?' of 'result''

Anyone seen this?

**Comment by AlastairOZ** [comment]
Dane, 
I have identified the issue:

StackedRouterGenerator needs to be modified so the MaterialPageRoute does not have a type 

eg:


      return MaterialPageRoute<StackedRoute<dynamic>>(
        builder: (context) => const NextView(),
        settings: data,
      )

needs to be:
 
     return MaterialPageRoute<dynamic>(
        builder: (context) => const NextView(),
        settings: data,
      )

However when I used build runner, it will overwrite any manual changes. 

With thanks
Alastair

**Comment by Eimen2018** [comment]
Hey @AlastairOZ are you still having this issue?

**Comment by AlastairOZ** [comment]
Good afternoon,
I think that the problem was resolved a few days after I raised the issue.
Thanks for reaching out. From memory, this problem was triggered by a
flutter update.

Alastair

**Comment by Eimen2018** [comment]
Awesome 🎉
