### ISSUE TITLE
how to use stacked with showcaseview?

### ISSUE THREAD

**Issue by vontdeux** [Stacked-Org/stacked#573]
Hi, @FilledStacks, is it possible to use stacked with showcaseview https://pub.dev/packages/showcaseview ?

what i've tried, I used onModelReady 
`onModelReady: (model) => model.init(context),`

and inside init, i called startShowCase 
``` 
void init(BuildContext context) {
    //delay a little bit
    Future.delayed(const Duration(milliseconds: 500), () {
      startShowCase(context);
    });
  }
```

but it doesn't seems to be working.

**Comment by FilledStacks** [comment]
Hey @vontdeux , are you still having this problem? Were there any errors?

**Comment by ziqq** [comment]
Hi! @vontdeux U need to use
```
onModelReady: (model) => WidgetsBinding.instance?.addPostFrameCallback((_) async {
  await init();
  startShowCase(context);
});
```

**Comment by ziqq** [comment]
My solution is't work. Because [showcaseview](https://pub.dev/packages/showcaseview) used GlobalKey, which is't uses from StatelessWidget. We need to use StatefullWidget which contradicts methodology **stacked**.

**Comment by FilledStacks** [comment]
@ziqq We use stateful widgets all the time. It doesn't contradict Stacked. Only hard rules stacked has is, no UI code in the ViewModel.

**Comment by ziqq** [comment]
> @ziqq We use stateful widgets all the time. It doesn't contradict Stacked. Only hard rules stacked has is, no UI code in the ViewModel.

OK it's very good info. I don't use UI in ViewModels :) 

@FilledStacks Thx bro 👍
