### ISSUE TITLE
dart analyze issue when generating docs

### ISSUE THREAD

**Issue by Henriquedn** [Stacked-Org/stacked#576]
To generate app docs, the code has to pass the **dart analyze** command.
Running **dart analyze** produces these 2 info issue related to stacked. 

<img width="1223" alt="Screenshot 2022-03-09 at 11 40 59" src="https://user-images.githubusercontent.com/4680937/157404505-1d2c044f-b121-4416-aa7a-6fdfae2fc114.png">

**Comment by Eimen2018** [comment]
I have also seen that We will look into this soon

**Comment by eb-so** [comment]
@Henriquedn I think this issue fixed we also add it to our github actions

**Comment by Henriquedn** [comment]
> 

Confirmed Issue fixed

**Comment by Henriquedn** [comment]
> 



> @Henriquedn I think this issue fixed we also add it to our github actions

Thank you @eb-so. confirmed issue is fixed.
