### ISSUE TITLE
Object/factory with  type SharedPreferencesService is not registered inside GetIt. 

### ISSUE THREAD

**Issue by devtrex007** [Stacked-Org/stacked#577]
I am getting this error when I try to run my app.

```
The following assertion was thrown building MyApp:
Object/factory with  type SharedPreferencesService is not registered inside GetIt. 
(Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
Did you forget to register it?)
'package:get_it/get_it_impl.dart':
package:get_it/get_it_impl.dart:1
Failed assertion: line 372 pos 7: 'instanceFactory != null'

```

I am using SharedPreferences package in some places. without registering it in the locator dependency

My app.dart file

```
@StackedApp(
  routes: [
    MaterialRoute(page: StartupView, initial: true),
    MaterialRoute(page: OnboardingView),
    MaterialRoute(page: LoginView),
  ],
  
  dependencies: [
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: BottomSheetService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: SnackbarService),
    LazySingleton(classType: MobileAuth),
    LazySingleton(classType: PushNotificationService),
    LazySingleton(classType: ThemeService),
    Singleton(classType: FirebaseAuthenticationService),

    LazySingleton(classType: GraphQLService),
    LazySingleton(classType: AccountService),
  ],
)

class AppSetup {
  /** Serves no purpose besides having an annotation attached to it */
}
```
I also try to add SharedPreferences like this, but it doesn't work,
also i try this as well [SharedPreferences](https://github.com/FilledStacks/stacked/issues/332)

```
dependencies: [
    ...
    Presolve(classType: SharedPreferences , presolveUsing: SharedPreferences.getInstance),
  ],
```

**Comment by saihormkham-nobody** [comment]
I have the same issue.

By any chance did you use ThemeBuilder? I comment on it and it works.
My version is stacked_themes 0.3.8+1

**Comment by devtrex007** [comment]
oh man, it worked, 

But I really need ThemeBuilder let me know if you find any solution with ThemeBuilder. 
thank you so much

**Comment by vincentderidder** [comment]
Did you initialise your ThemeManager?
Add `await ThemeManager.initialise();` in you `main()` function

**Comment by egin10** [comment]
How to call SharedPreferences in ViewModel?
Because I still got a problem when I call the locator in ViewModel.

> The following assertion was thrown building MyApp:
> Object/factory with  type SharedPreferencesService is not registered inside GetIt. 
> (Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
> Did you forget to register it?)
> 'package:get_it/get_it_impl.dart':
> package:get_it/get_it_impl.dart:1
> Failed assertion: line 372 pos 7: 'instanceFactory != null'

Thank you.
