### ISSUE TITLE
Adding of HookViewModelBuilderWidget

### ISSUE THREAD

**Issue by sbatezat** [Stacked-Org/stacked#579]
Hi,

I'm new to stacked so I may say something wrong...
I'm using ViewModelBuilderWidget when I don't need hook.
When I need it, I would like to have the same kind of syntax but unfortnately, there is no HookViewModelBuilderWidget class available.

Does it make sense to add it to the stacked_hooks package?

**Comment by Eimen2018** [comment]
Hey @sbatezat What would be the purpose of HookViewModelBuilderWidget ?
