### ISSUE TITLE
Complete Stacked Services Readme

### ISSUE THREAD

**Issue by FilledStacks** [Stacked-Org/stacked#58]
Add the proper documentation for each of the Stacked Services that are provided into the readme. This should contain the reason they exist, the best way to make use of them and go through all the features that they provide.

**Comment by YazeedAlKhalaf** [comment]
I have made documentation for the `NavigationService` and `SnackbarService`

I will do a pull request today, hope you like it 😊💙

**Comment by YazeedAlKhalaf** [comment]
#90 This pull request solves the issue 😊
