### ISSUE TITLE
Follow recommended linter rules

### ISSUE THREAD

**Issue by zuboje** [Stacked-Org/stacked#580]
This is a feature request.

Many use LINT for their coding and have a set of rules, while the generator cannot really follow everyone's wishes (we would hope so), at least it should follow standard lint rules that are recommended by flutter/dart, One of them is "[unused_import](https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=unused_import#unused_import)" in the current code app.router.dart fails to follow this principle:

```
Analyzing FlutterDemo...                                          

   info - Unused import: 'package:stacked/stacked_annotations.dart' - lib\app\app.router.dart:11:8 - unused_import
```

Additionally, it would be nice if we could provide some "config" for the generator on how to generate code. For example, in my application, we use lefthook for pre-commit and staging, but we also try to avoid using relative imports, while for some this may not be a big deal, multiple developers working on a code may not use identical IDE or identical setup for the IDE. Because of that, we use "avoid_relative_lib_imports". We have seen issues, where a user would import a class and IDE, and it would write import like this:

`import 'file://c:/users/xyz/repos/mobileapp/lib/class.dart';`

This was done with Android Studio, code would be committed like this and it would then generate failures during build times or on any other machine. We tend to use all packages to be `import 'package:flutterdemo/class.dart';`, because of that we have a lint rule to error out but generated packages are not following this. While I do not expect this to be built I suggest providing some lint options down the road. When I get a chance I will try to contribute to your code but at the moment I don't have enough time.

**Comment by eb-so** [comment]
@zuboje The first issue has been solved in this [PR](https://github.com/FilledStacks/stacked/pull/654)
