### ISSUE TITLE
How to handle similar HookViewModelWidgets in different contexts

### ISSUE THREAD

**Issue by StankoKostic** [Stacked-Org/stacked#581]
Hello Stacked team. I am working on a big project, so I am trying to find the optimal solution for this problem without too much of a copy+pasted code.

My question is how to handle Widgets that are naturally `HookViewModelWidgets`, but in different context. Since the new context (different page) is using a different `ViewModel` (but visually looks almost the same), what is the best way to approach it?

One way would be to create a duplicated `HookViewModelWidget`, just with a different `ViewModel`, the other would be to pass the old ViewModel as a constructor parameter. 

There is also an option of passing all the needed values as parameters, and convert the widget to a regular Stateless/Stateful widget. 

Otherwise, I get:

```
Error: Could not find the correct Provider<SelectedBotViewModel> above this PeriodButtons Widget

This happens because you used a `BuildContext` that does not include the provider
```

Thanks!

**Comment by Eimen2018** [comment]
Hey @StankoKostic would you mind sharing some code to look at to understand your question/request better

**Comment by StankoKostic** [comment]
Hello @Eimen2018. Thank you for your response, and sorry for the late answer. I am also sorry that I cannot share the majority of the code, because of NDA, but I will try my best explaining what is the main issue here.

I have the view called `SelectedBotView` that is building `SelectedBotViewModel`:

```dart
return CupertinoScaffold(
      body: ViewModelBuilder<SelectedBotViewModel>.reactive(
        viewModelBuilder: () => SelectedBotViewModel(),
        disposeViewModel: false,
```

This page contains a `HookViewModelWidget` called `PeriodButtons()`:

```dart
class PeriodButtons extends HookViewModelWidget<SelectedBotViewModel>
```

that is reactive, and is manipulating `SelectedBotViewModel` state on certain action. However, when I navigate to the next screen `GraphExplanationView`, there should be a widget that is the exact replicate of the mentioned `PeriodButtons()`, behaving the and looking the same way. However, since it's a new page, it has a different context, hence - different ViewModel. 

What is the best way to create this Widget? One way would be to take parameters instead of `HookViewModelWidget`, but again, it manipulates state of the ViewModel used in another widgets as well. I could keep the values used for this widget in a Service, but that would end up having a lot of copy pasted code for two different widgets that are practically the same. I am curious what is the lesser evil here, or is there another better answer. 

Thank you in advance for the answer!

Best regards,
Stanko

**Comment by Eimen2018** [comment]
@StankoKostic What if you make it `class PeriodButtons<T> extends HookViewModelWidget<T>` and when you call it pass the closest ViewModel `PeriodButtons<SelectedBotViewModel>()` and `PeriodButtons<GraphExplanationViewModel>()`. since I think you don't want the code duplication on both viewmodel you can create a mixin move the periodbuttons method code in there and extend the viewmodels like `SelectedBotViewModel extends BaseViewModel with PeriodButtonMixin`

**Comment by StankoKostic** [comment]
Thanks @Eimen2018 for the elaborate answer, I ended up using `Mixins` for the widget. I like the idea of having a generics passed to the `HookViewModelWidget`, will probably try it our sometimes soon. Will close this issue as resolved.
