### ISSUE TITLE
stackedServices custom dialog UI (AlertDialog) with ability to pass in function to execute

### ISSUE THREAD

**Issue by zuboje** [Stacked-Org/stacked#583]
Currently, there is the ability to create custom dialogs that when awaited will wait for user input and then complete. But there is a scenario where the dialog should not take user input but rather inform the user of what is happening like Alert Dialog. Currently, in stacked, I can use AlertDialog for my custom dialog but if the dialog is awaited it will never close (because it is an alert dialog, does not take any input). For example, in my current app AlertDialog is used when the mobile app is interacting with the server (loading, downloading data, sending data, etc.) this informs the user of the current action, prevents the user from going around the app (no ability to dismiss) and when the function completes it either presents the user with error or success in form of snackbar and then the action moves forward (navigates, updates UI, etc.).

The current workaround is the following:

```
// ignore: unawaited_futures
    _dialogService.showCustomDialog(
        variant: DialogType.loading, description: 'Loading...');
    bool hasError = false;
    HttpResult result;
    try {
      bool connected = await isConnectedToInternet();
      if (connected) {
        result = await someBusyfutureTalkingToTheServer();
      }
    } on Exception catch (e) {
      hasError = true;
    } finally {
      _dialogService
          // ignore: always_specify_types
          .completeDialog(DialogResponse(confirmed: true, data: false));
    }
    // Now that everything completes
    updateUI();
```

preferred way of dealing with alertDialog would be something like this:

```
var result = await _dialogService.showCustomDialog(
        variant: DialogType.loading, description: 'Loading...', runFunction: someBusyfutureTalkingToTheServer());

if(result.hasError){
  showsnackbarwitherror('something went wrong');
} else {
  showsnackbarwithsuccess('something went wrong');
  updateUI();
}
```

At this moment I am not sure if I am missing something in current CustomDialogUI setup or simply what I am asking does not exist, but functionality to use AlertDialog and pass function to run would definitely benefit some users. I am not sure how others handle "loading" when communicating with server but we relay on AlertDialog.

**Comment by FilledStacks** [comment]
Hey, we're handling loading by giving the dialog UI it s own viewmodel and treating it like a normal view (which is it because it's inserted in the navigation stack). 

So you can write it exactly as you would a normal view. That in addition to returning the expected result from the dialog in the response has covered all the scenarios we've encountered.

**Comment by zuboje** [comment]
Makes sense but how would my completer run in a ViewModel and return value? In the examples shown it runs onTap or some sort of user interaction, if I for example create ViewModel for my loading dialog I would run completer as part of onModelReady, or ideally I would pass it to futureToRun in a FutureViewModel

```
@override
  Future<T> futureToRun() async => await completer(DialogResponse());
```

Does this mean that my completer will automatically close the view once run as a part of onModelReady and get DialogResponse? Do you have any samples to help me out I am a bit lost

**Comment by zuboje** [comment]
I figured it out, thanks for the advice! I send the function as my "data" parameter and my viewmodel takes a function in the constructor, does some work in try/catch (if an exception shows up I can complete dialog) and it is executing this with onModelReady. If you have any other suggestion how to make this more efficient I would be more than happy to hear that, otherwise this solves my problem :)

**Comment by zuboje** [comment]
If anyone in the future is interested in similar those is how I do it:

View:

```

class LoadingDialogView extends StatelessWidget {
  // ignore: always_specify_types
  final DialogRequest request;
  // ignore: always_specify_types
  final Function(DialogResponse) completer;

  const LoadingDialogView({
    required this.request,
    required this.completer,
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder<LoadingDialogViewModel>.reactive(
      viewModelBuilder: () => LoadingDialogViewModel(request.data),
      // ignore: always_specify_types
      onModelReady: (LoadingDialogViewModel viewmodel) async =>
          // ignore: always_specify_types
          completer(DialogResponse(data: await viewmodel.runProcess())),
      builder: (BuildContext context, LoadingDialogViewModel viewModel,
              Widget? child) =>
          AlertDialog(
        backgroundColor: Colors.grey,
        shape: const RoundedRectangleBorder(
          borderRadius: BorderRadius.all(
            Radius.circular(15),
          ),
        ),
        content: Row(
          children: <Widget>[
            const CircularProgressIndicator(
              valueColor: AlwaysStoppedAnimation<Color>(Colors.green),
            ),
            Expanded(
              child: Container(
                margin: const EdgeInsets.only(left: 22, right: 5),
                child: Text(
                  request.description!,
                  textAlign: TextAlign.left,
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

ViewModel:

```
class LoadingDialogViewModel extends BaseViewModel {
  // ignore: always_specify_types
  Future process;
  LoadingDialogViewModel(this.process);

  // ignore: always_specify_types
  Future runProcess() async {
    try {
      return await process;
    } catch (error) {
      return CustomDialogException(error);
    }
  }
```

and once this custom dialog is registered this is how it is called:

```
var results = await _dialogService.showCustomDialog(
            variant: DialogType.loading,
            description: 'Connecting to ${device.name}',
            data: _service.callSomeFunction(param);
}
```

Results could be exception or actual data so you need to actually look at what type is returned since it is dynamic. Any feedback or suggestion on adjusting this is welcome
