### ISSUE TITLE
Add instanceName to get_it generator

### ISSUE THREAD

**Issue by zuboje** [Stacked-Org/stacked#584]
The current stacked generator does now allow multiple instances of the same class for a singleton. get_it package has optional parameter "instanceName" that can be passed for multiple singleton instances of the same class:

```
locator.registerLazySingleton(() => MyClass(), instanceName: 'mysetup1');
locator.registerLazySingleton(() => MyClass(), instanceName: 'mysetup2');
```

This allows for greater flexibility. It would be great if stacked annotation would allow an optional parameter to pass the instance name.

**Comment by FilledStacks** [comment]
You think you can add this through a PR?

**Comment by zuboje** [comment]
Certainly I can

**Comment by zuboje** [comment]
I just created PR https://github.com/FilledStacks/stacked/pull/586 but I have no ability to test because I never wrote plugins and I tried using the path in pubspec.yaml and it generates issue for me because I have to changed stacked package for annotation and stacked_generator package. If you give me some quick tip how I can test both at the same time locally I will be more than happy to debug/troublshoot, current code is more like a guess

**Comment by calvintam236** [comment]
I just encountered the same issue. I want to reuse the same service with a different `getInstance` (the library has multiple constructors and method calls do not change).

@FilledStacks It looks like #586 did not merge, and I don't see any code/docs changes regarding this in `master`?

**Comment by FilledStacks** [comment]
This is in the latest generator.

**Comment by calvintam236** [comment]
> This is in the latest generator.

I found the code now, but the readme does not mention the usage of this.

**Comment by FilledStacks** [comment]
Yes, the readme has not been kept up to date, I'll spend some time in the future updating all the docs for Stacked.
