### ISSUE TITLE
Arguments in NavigationService

### ISSUE THREAD

**Issue by eyeoftime** [Stacked-Org/stacked#59]
When using the NavigationService to navigate to a new view, how do you access the navigation arguments in the ViewModel of the new View, I can't see anything in the NavigationService class that gives access to the passed arguments?

**Comment by jahir9991** [comment]
same here !! till now i just complete it with service (no argument). its worked but still need better approach.

**Comment by FilledStacks** [comment]
@eyeoftime you pass your arguments through the view and then through the constructor of the ViewModel. This improves testability as well. 

```dart

class ArgumentsView extends StatelessWidget {
  final MyModel myData;
  final int id;
 const ArgumentsView({Key key, this.myData, this.id}) : super(key: key);

 @override
 Widget build(BuildContext context) {
   return ViewModelBuilder<ArgumentsViewModel>.reactive(
     builder: (context, model, child) => Scaffold(),
     viewModelBuilder: () => ArgumentsViewModel(id: id, myData: myData),
   );
 }
}
```

When navigating using the service you'll do

```dart
_navigationService.navigateTo(
    Routes.argumentsViewRoute, 
    arguments: ArgumentsViewArguments(
        id: 4, 
        myData: MyModel(
          data: {
             'data': 9
          }
     )
);
```

the ViewArguments class is automatically generated for you so as you add or remove arguments from your view it gets regenerated and update through auto_route. You don't have to type any boilerplate code.

**Comment by jahir9991** [comment]
solved it , come here to share and here you r already posted 🍡

**Comment by eyeoftime** [comment]
Thank you @FilledStacks this makes sense now. I'm pretty new to Flutter, but the Stacked architecture is really getting me up and running quickly.

**Comment by FilledStacks** [comment]
@jahir9991 haha beat you to it!! Thanks for coming back to share. 

@eyeoftime I'm very happy to hear that stacked is helping you through the learning process.

**Comment by jahir9991** [comment]
really loved it bro .
you done an amazing job !!
<3 <3
