### ISSUE TITLE
NavigationService.currentRoute returns an empty string.

### ISSUE THREAD

**Issue by djoshua21** [Stacked-Org/stacked#598]
`final _navigationService = locator<NavigationService>();`
`print(_navigationService.currentRoute); // Returns Empty String`

I navigated the route using `_navigationService.clearStackAndShow(Routes.homeView);`

but when I try to check the current route then it shows nothing.

**Comment by djoshua21** [comment]
I discovered a work around by calling `ModalRoute.of(context)?.settings.name` in the view to get the current route.

**Comment by ferrarafer** [comment]
Is working for me, can you share more code or try to log the `currentRoute` from a viewmodel on stacked example application?

**Comment by dimzeta** [comment]
Resolved thanks to this issue: https://github.com/FilledStacks/stacked/issues/287

You have to add a route observer: https://pub.dev/packages/stacked_services#route-observation
