### ISSUE TITLE
Null Aware Operators in Flutter 3.0 (Stacked themes)

### ISSUE THREAD

**Issue by godspeed0310** [Stacked-Org/stacked#606]
: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
../…/src/theme_manager.dart:123
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../CodeRepository/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
            SchedulerBinding.instance?.window.platformBrightness;
                             ^
: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
../…/src/theme_manager.dart:221
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../CodeRepository/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
          SchedulerBinding.instance!.window.platformBrightness;
                           ^

**Comment by vikt0r40** [comment]
Same, we need 3.0.0 support

**Comment by godspeed0310** [comment]
Fixed with Commit # e6bb94ac498b095816c3b7720d25737a511f5b2e

**Comment by vikt0r40** [comment]
When 2.3.7 will be released or can I somehow get it in pre-release ?
