### ISSUE TITLE
Once you have called dispose() on a Model, it can no longer be used.

### ISSUE THREAD

**Issue by Rayv1** [Stacked-Org/stacked#61]
Hi,

i migrated to this package from your ArchitectureV3 and now facing the following issue;

I have  a onModelReady Function with an await Future. Inside this future i call setBusy to true at start, another await Future in the Mid and than setBusy to false at End. When i for e.g. navigate Back before the Future returns, the last setBusy cause the error, that the Model no longer can be used.
The Workaround is to create a mounted variable suggested by Remi, but as we now have many Models, i wonder how to do it without having this boilerplate variable.

Example:
```
ViewModelBuilder<Model>.reactive(
        onModelReady: (model) async {
          await model.someFuture(parmeter: parameter);
        },
        viewModelBuilder: () => Model(),
        builder: (context, model, child) {
          return [....]
        });
```

```
class Model extends BaseViewModel {
setbusy(true);
Future.delayed(Duration(seconds: 5)).then((value) => setBusy(false));
}
```

Iam doing something wrong?

**Comment by Rayv1** [comment]
duplicate of https://github.com/FilledStacks/stacked/issues/36

**Comment by ferrarafer** [comment]
You should not await on onModelReady, is just to trigger actions that need to start as soon as posibble but do not wait for them to finish.
