### ISSUE TITLE
Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null

### ISSUE THREAD

**Issue by dmitry-fbm** [Stacked-Org/stacked#615]
In flutter 3.x `WidgetsBinding` isn't nullable anymore, causing multiple warnings during build:
```
flutter/.pub-cache/hosted/pub.dartlang.org/stacked_services-0.8.22+1/lib/src/snackbar/snackbar_service.dart
:233:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('flutter/packages/flutter/lib/src/w
idgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((_) async {
                     ^
/
```

**Comment by Hannnes1** [comment]
It seems like this was fixed by https://github.com/FilledStacks/stacked/commit/dcdef88c4af7c7d1da1aadc404d2fa1e2f4c9f0c. It just hasn't been published to pub.dev yet.

**Comment by djoshua21** [comment]
I really hope it get's fixed really soon because this is seriously disturbing my workflow.

**Comment by 404shades** [comment]
@FilledStacks Any update on this?

**Comment by FilledStacks** [comment]
@djoshua21 and @404shades It's fixed not published. 

It's only a waring so shouldn't be a blocker. But we can probably get this published. I'll chat to the team and see if we can push an update today.
