### ISSUE TITLE
Navigation service unable to capture arguments from clearStackAndShow()

### ISSUE THREAD

**Issue by surveshoeb** [Stacked-Org/stacked#63]
I'm trying to navigate to next view by clearing all the view from the stack and passing a single argument but not able to capture in the next view.

**Code for navigating to next page**
```
locator<NavigationService>().clearStackAndShow(
              Routes.profileViewRoute,
              arguments: ProfileViewArguments(fromLoginView: true));
```

**Constructor on Profile View**
```
ProfileView({this.fromLoginView});
```

**router.g.dart Code for Profile View**

```
case Routes.profileViewRoute:
        if (hasInvalidArgs<ProfileViewArguments>(args)) {
          return misTypedArgsRoute<ProfileViewArguments>(args);
        }
        final typedArgs =
            args as ProfileViewArguments ?? ProfileViewArguments();
        return MaterialPageRoute<dynamic>(
          builder: (context) =>
              ProfileView(fromLoginView: typedArgs.fromLoginView),
          settings: settings,
        );
```

Expected value on ProfileView of fromLoginView is **true** but when it is passed via clearStackAndShow() it get **false**

**Note:** It work with clearTillFirstAndShow() but not with clearStackAndShow()

**Comment by FilledStacks** [comment]
Thanks for the detailed report. Update to 0.3.4 and it should work now.

**Comment by surveshoeb** [comment]
Thanks for update it's working now.
