### ISSUE TITLE
Multiple instances of form on same page doesn't work

### ISSUE THREAD

**Issue by gscottschulz** [Stacked-Org/stacked#643]
Hi FilledStacks,
I have a unique UI need for multiple instances of the same form on a page. I think the declaration of the `Map<String, TextEditingController>`, `Map<String, FocusNode>` and `Map<String, String? Function(String?)?>` need to be moved inside the mixin and not outside.

In the form generator, these lines https://github.com/FilledStacks/stacked/blob/6d09110ce0c7366fc4e317b050131184652639ec/packages/stacked_generator/lib/src/generators/forms/form_generator_util.dart#L21-L23 need to be moved before this line https://github.com/FilledStacks/stacked/blob/6d09110ce0c7366fc4e317b050131184652639ec/packages/stacked_generator/lib/src/generators/forms/form_generator_util.dart#L32

Thanks for all the hard work!

**Comment by gscottschulz** [comment]
To Clarify, by "doesn't work", I mean I have multiple issues I'm seeing

1. When any form widget is disposed and therefore all the `TextEditingControllers`, `FocusNodes`, etc. are also disposed, every other instance of that form widget is broken because they're all referencing the same objects in the `Maps` I mentioned in my first post.

2. For the same reasoning as issue 1 (the single instance referencing), the text values are also all screwed up.

Each instance of the form needs to have it's own instances of certain objects to function correctly.

**Comment by FilledStacks** [comment]
@gscottschulz that functionality only fires if expose is called? Does that mean you call expose even if the view is not being changed? 

I don't really know what you're asking. If you can paste an example of the form output you want so that I can see how that would help this use case.
