### ISSUE TITLE
NavigationService.navigateTo() arguments property has suddenly changed to a map

### ISSUE THREAD

**Issue by KPatel91** [Stacked-Org/stacked#656]
The `navigateTo` function has changed from
` return G.Get.toNamed<T?>(
      routeName,
      arguments: arguments,
      id: id,
      preventDuplicates: preventDuplicates,
      parameters: parameters,
    );`

to 

`return G.Get.toNamed<T?>(
      routeName,
      arguments: {'arguments': arguments, 'transition': transition},
      id: id,
      preventDuplicates: preventDuplicates,
      parameters: parameters,
    );` 

The `arguments` property is now sending a map rather than the traditional object itself, but this hasn't been documented anywhere?

This has changed from 0.8.25 -> 0.8.26 so just wondering if this was accidental or not?

**Comment by Eimen2018** [comment]
Hey Hey @KPatel91 it is not accidental we added that in order to be able to accept custom transition since `get` doesn't allow as to pass any more arguments. argument is parsed the same nothing change just the ability to have transitions now. Did it affect you some how?

**Comment by chetanchoudhary08** [comment]
how do you initialise any variables in viewmodel from router arguments?

**Comment by andreierdoss** [comment]
@Eimen2018 this is how my code changed:

from:
`final arguments = settings.arguments;`
`if (arguments != null && arguments is List) {`
    `squadId = arguments.first as int;`
    `sport = arguments.last as String;`
`}`

to:
`final arguments = settings.arguments;`
`if (arguments != null && arguments is Map && arguments['arguments'] != null) {`
    `List args = arguments['arguments'];`
    `squadId = args.first as int;`
    `sport = args.last as String;`
` }`

I agree with @KPatel91 that this breaking change should be documented somewhere.
