### ISSUE TITLE
Dependencies Registration with Generic Type

### ISSUE THREAD

**Issue by rahmanpsg** [Stacked-Org/stacked#657]
I have class service with generic type : 

`class Service<T> {}`

How to register this class to dependencies with the generic type?

**Comment by eb-so** [comment]
@rahmanpsg Just like any other service for example `LazySingleton(classType: Service)`

**Comment by rahmanpsg** [comment]
@eb-so Thanks for your feedback. But with that, i have error if get the instance with this 
`locator<Service<Model>>()`

the only way i found is to register each type:
`LazySingleton(classType: Service<ModelOne>)`
`LazySingleton(classType: Service<ModelTwo>)`

and i found this question [https://github.com/fluttercommunity/get_it/issues/48](url)
doesn't seem to be able to register the service class with a generic type.

Thanks.

**Comment by eb-so** [comment]
@rahmanpsg Glad that you found the answer.
