### ISSUE TITLE
Method Not Found on Flutter 3.0.2

### ISSUE THREAD

**Issue by elvisgn** [Stacked-Org/stacked#669]
Hi,
On upgrading to flutter 3.0.x, I upgraded my stacked_services package to 0.8.26. I'm getting the below error on build.

> ../../flutter/.pub-cache/hosted/pub.dartlang.org/stacked_services-0.8.26/lib/src/snackbar/snackbar_service.dart:239:10: Error: Method not found: 'ambiguate'.
>       sc.ambiguate(WidgetsBinding.instance)!.addPostFrameCallback((_) async {

Is there a workaround ? How can I install an older version of the package? pub get keeps getting 0.8.26.

**Comment by Eimen2018** [comment]
please update all stacked packages and see if the error occurs
