### ISSUE TITLE
Add Method for setting a message for Object to BaseViewModel

### ISSUE THREAD

**Issue by Henriquedn** [Stacked-Org/stacked#671]
Similar to the method for **setErrorForObject()**, it would be great to have a method that sets a message for object **setMessageForObject()** for use when no error occurred and probably need to show a message from api in addition to the data.

Use case, then you have a wrapper for all responses  like below:
```
{
    "success": true,
    "responseCode":200,
    "message": "This message to be displayed in a text view when no error occured",
    "data":  {...}
}
```

**Comment by Eimen2018** [comment]
stacked 2.3.13

**Comment by Henriquedn** [comment]
> stacked 2.3.13

@Eimen2018 is it possible for this to be added to stacked: ^3.0.1

**Comment by FilledStacks** [comment]
@Henriquedn it's in all versions moving up from 2.3.13
