### ISSUE TITLE
not creating new Viewmodel

### ISSUE THREAD

**Issue by hetthummar** [Stacked-Org/stacked#676]
### **What I am trying to achieve?**

On the main screen of the application, I am showing a list of patients. when the user clicks on any of the patients I am navigating the user to the patient screen which has TabBarView. TabBarview has five pages and all of them have API calls.
now I don't want to do API calls every time the user changes its tab. so I am setting these values which is working fine.

```
fireOnModelReadyOnce: true,
createNewModelOnInsert: false,
initialiseSpecialViewModelsOnce: true,
disposeViewModel: false
```

but when user go back to main screen and click on any other patient then the patient screen displays the old data.
basically, no API calls because "fireOnModelReadyOnce: true" and I am doing API calls from the function which is called from the onModelReady callback.

But I don't want this behavior.
I want to keep patient data cached when switching between tabs but it should be refreshed when the user clicks on another patient (standard behavior, nothing new)

### **Steps I took to solve this issue**

1. I thought this issue is occurring because flutter is not identifying that a new widget is inserted so I tried passing the key to ViewModelBuilder and also tried passing the key to the entire screen with the super constructor but nothing worked.

2. I tried passing the below value

```
fireOnModelReadyOnce: false,
createNewModelOnInsert: true,
initialiseSpecialViewModelsOnce: false,
disposeViewModel: true
```
The above value leads to another error

> A ViewModel was used after being disposed

which is weird because "createNewModelOnInsert: true" should create new viewModel.

I am using the latest version of stacked package.
> stacked: ^2.3.12

I don't know if it is the default behavior for stacked or if I am doing something wrong. anyways I want to implement the scenario that I mentioned above.

I am sharing very basic code snippets without any unnecessary details which I am using.

```
    return ViewModelBuilder<PatientVitalsViewModel>.reactive(
      onModelReady: (PatientVitalsViewModel model) async {
        print("ON MODEL READY");
        model.initVitalsPagingController();
      },
      fireOnModelReadyOnce: false,
      createNewModelOnInsert: true,
      initialiseSpecialViewModelsOnce: false,
      disposeViewModel: true,
      onDispose: (PatientVitalsViewModel model) {
        print("DISPOSED");
        model.disposeControllers();
      },
      builder: (context, model, child) {
        return Container();
      },
      viewModelBuilder: () => locator<PatientVitalsViewModel>(),
    );
```

**Comment by Eimen2018** [comment]
@hetthummar Why don't you call initialise method manually to refresh the screen when ever you want refreshing?

**Comment by hetthummar** [comment]
@Eimen2018  Thanks for your reply. I don't understand Can you share the basic code.

**Comment by FilledStacks** [comment]
Was this issue resolved?

**Comment by hetthummar** [comment]
Yes, Thanks for the reply
