### ISSUE TITLE
Confirmation Dialog Actions are navigating back

### ISSUE THREAD

**Issue by Melak12** [Stacked-Org/stacked#683]
After upgrading to the latest version of stacked_service v 0.9.1, the action buttons of confirmation dialogs are not working properly. Both the cancel ("No") and "Yes" buttons are just navigating back rather than dismissing and confirming true. I wonder if anyone has faced the same issue?

**Comment by eb-so** [comment]
@Melak12 I don't recall changing any thing in the latest version of stacked_services, can you post a snippet of code so we can help you

**Comment by Melak12** [comment]
Hi @eb-so, please find the snippet below. 
==== confirmation dialog ====
```
Future<bool> showConfirmationDialog({
  String title = 'Confirmation',
  String description = 'Do you want to continue?',
  String confirmationTitle = "Yes",
  String cancelTitle = "No",
}) async {
  final _dialogService = coreLocator<DialogService>();

  var response = await _dialogService.showConfirmationDialog(
    title: title,
    description: description,
    confirmationTitle: confirmationTitle,
    dialogPlatform: DialogPlatform.Material,
    cancelTitle: cancelTitle,
  );

  return response?.confirmed ?? false;
}
```

========= main.dart========================
```
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
      systemNavigationBarColor: Colors.grey[200],
      systemNavigationBarIconBrightness: Brightness.dark,
      systemNavigationBarDividerColor: kcWhite,
    ));
    return ConnectionNotifier(
      child: MaterialApp(
        title: 'Sheger',
        theme: AppTheme.passengerTheme,
        localizationsDelegates: context.localizationDelegates,
        supportedLocales: context.supportedLocales,
        locale: context.locale,
        debugShowCheckedModeBanner: false,
        home: const AnnotatedRegion<SystemUiOverlayStyle>(
          value: SystemUiOverlayStyle(
            systemNavigationBarColor: kcBackground,
            systemNavigationBarDividerColor: kcBackground,
            statusBarBrightness: Brightness.light,
            systemNavigationBarIconBrightness: Brightness.dark,
          ),
          child: StartupView(),
        ),
        onGenerateRoute: StackedRouter().onGenerateRoute,
        navigatorKey: StackedService.navigatorKey,
      ),
    );
  }
}
```

================ Using the confirmation dialog ========
```
Future<bool> onBackClick() async {
    bool confirm = await showConfirmationDialog(
        title: "Exit", description: "Do you want to Exit?");
    return confirm;
  }
```

When using showConfirmationDialog, the action buttons always navigate back if the view is not at the top level. If it is on the top-level page such as a home page, the action buttons don't respond at all.

**Comment by eb-so** [comment]
@Melak12 What is a top level page?
The ConfirmationDialog should return either true or false which doesn't relate to the navigation state or the pages order.

My guess that there is a problem somewhere else in your code.

the snippet above doesn't show the issue I need you to create a new project with a minimal code to reproduce the issue see this [issue](https://github.com/FilledStacks/stacked/issues/690) for reference
