### ISSUE TITLE
stacked_themes Issue

### ISSUE THREAD

**Issue by santhisagar** [Stacked-Org/stacked#693]
Package: stacked_themes-0.3.8+1

environment:
  sdk: ">=2.17.5 <3.0.0"

Error:
../../Dev/flutter/.pub-cache/hosted/pub.dartlang.org/stacked_themes-0.3.8+1/lib/src/theme_manager.dart:123:30: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Dev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
            SchedulerBinding.instance?.window.platformBrightness;
                             ^

**Comment by eb-so** [comment]
@santhisagar Try `flutter clean`

**Comment by mugikhan** [comment]
@FilledStacks I have the same warning. Please can you update the stacked_themes package?

**Comment by eb-so** [comment]
@mugikhan published stacked_themes 0.3.9
