### ISSUE TITLE
Whey do NavigationService.replaceWith() and NavigationService.navigateTo() handle arguments differently?

### ISSUE THREAD

**Issue by andreierdoss** [Stacked-Org/stacked#694]
As this [issue](https://github.com/FilledStacks/stacked/issues/656) mentioned it, NavigationService.navigateTo()'s way of handling arguments has changed to a Map, but NavigationService.replaceWith() has remained using a List.

This difference has caused a bug in the code, when calling the route from the two different methods.

Here are I am calling the methods with arguments.
```
_navigationService.replaceWith(
    Router.scoringViewRoute,
        arguments: [
            squadId,
            selectedSport,
        ],
);

_navigationService.navigateTo(
    Router.scoringViewRoute,
        arguments: [
            squad.id,
            squad.sport,
        ],
);
```
Here I'm processing the arguments depending if they are a Map or List. This is not ideal.
```
final arguments = settings.arguments;
int squadId = 0;
String sport = '';
if (arguments != null) {
    if (arguments is List) {
        squadId = arguments.first as int;
        sport = arguments.last as String;
    } else if (arguments is Map && arguments['arguments'] != null && arguments['arguments'] is List) {
        List args = arguments['arguments'];
        squadId = args.first as int;
        sport = args.last as String;
    }
}
```

**Comment by FilledStacks** [comment]
I assume you create and maintain your own router and do not use the generator?

**Comment by Eimen2018** [comment]
@andreierdoss I think stacked_services "0.9.3" would solve your issue
