### ISSUE TITLE
Using riverpod instead of provider under the hood

### ISSUE THREAD

**Issue by OmkarDabade** [Stacked-Org/stacked#696]
Hello everyone,
I was planning to use stacked package for my future projects and i was going through documentation
I saw that under the hood provider is being used
I have this doubt that
What if riverpod is used under the hood instead of provider
Riverpod solves some problems of the provider, The author also agrees to this.

I feel riverpod will be a good transition
What do you guys say ?

**Comment by eb-so** [comment]
Hey @OmkarDabade If there is not any particular issue with the current implementation we won't spend time migrating provider to riverpod, If you have a specific issue you want to talk about please don't hesitate to open a new issue
