### ISSUE TITLE
Widget / Integration Testing

### ISSUE THREAD

**Issue by jromanski** [Stacked-Org/stacked#699]
In my project I use Stacked Architecture. In Unit Testing it works perfectly fine but when it comes to Widget/Integration Testing I am getting an error right at the start.

My code:

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:my_project/ui/start_up/startup_viewmodel.dart';

void main() {
  testWidgets(
    "Simple widget test",
    (WidgetTester tester) async {
      await tester.pumpWidget(StartUpView());
    },
  );
}
```
The error that I get:

```dart
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building StartUpView:
Object/factory with  type AuthService is not registered inside GetIt.
(Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
Did you forget to register it?)
'package:get_it/get_it_impl.dart':
Failed assertion: line 372 pos 7: 'instanceFactory != null'

The relevant error-causing widget was:
  StartUpView
  StartUpView:file:path/my_project/lib/app/app.router.dart:87:37
```

From the error log I see that it is actually the **AuthService** which is causing the problem. The class is registered as a **LazySingleton** in *app.dart* and I realized that the program really crashes in *startup_viewmodel.dart*:
```dart
final _authService = locator<AuthService>();
final _navigationService = locator<NavigationService>();
```
(Switching this to lines cause to replace **AuthService** with **NavigationService** in error message). 

Suggestions about *get_it* didn't help me much because in all of the files "get_it" didn't comes once (even in my *pubspec.yaml*). I also tried solutions from [this thread](https://stackoverflow.com/questions/62548585/how-to-use-get-it-flutter-dependency-injection-in-the-widget-test) but it didn't resolve the issue.

The *app.router.dart* is a generated code based on *app.dart*. In its 87. line there is:

```dart
StartUpView: (data) {
  return MaterialPageRoute<dynamic>(
    builder: (context) => const StartUpView(),
    settings: data,
  );
},
```

Lastly I tried using *integration_test_driver* and running test through *flutter test* command with no improvement.

So the simple question is...

How to Widget Test using Stacked Architecture?
-----------------------------------------------------
Any help would be greatly appreciated.

**Comment by eb-so** [comment]
Hey @jromanski you can check out the [stacked example](https://github.com/FilledStacks/stacked/blob/master/packages/stacked/example/integration_test/app_test.dart) integration test
