### ISSUE TITLE
StreamViewModel get data based on a parameter?

### ISSUE THREAD

**Issue by thedigitalpro** [Stacked-Org/stacked#7]
Hi. Absolutely loving the latest update but have a question regarding StreamViewModel. 

Please could you advise how I can listen to a stream based on a provided parameter? It appears the get stream is called before providing any opportunity to pass in a parameter. I have tried the constructor to no avail.

`return ViewModelBuilder<EventViewModel>.reactive(
    disposeViewModel: false,
    viewModelBuilder: () => EventViewModel(_eventId),
    builder: (context, model, child) =>`

`@override
  Stream<List<EventCategory>> get stream => _database.eventsCategory(_eventId);`

Thank you.

**Comment by FilledStacks** [comment]
@thedigitalpro New version pushed. Try out 1.2.2, the subscription is now moved till after the construction so passing through the constructor should work. Thanks for letting me know.

**Comment by thedigitalpro** [comment]
> @thedigitalpro New version pushed. Try out 1.2.2, the subscription is now moved till after the construction so passing through the constructor should work. Thanks for letting me know.

Thank you so much Dane for such a quick response. This is fantastic and works a treat! Such a great solution you are coming up with here.
