### ISSUE TITLE
Using GoRouter and want to register navigation service using GetIt

### ISSUE THREAD

**Issue by timfong888** [Stacked-Org/stacked#701]
I am using GoRouter which doesn't have a global `navigationKey`.  Normally I would register a service with Get It, but cannot associate the navigationKey with the MaterialApp.router() -- it doesn't recognize it.

The reason I need to register a navigationKey with the service locator pattern and implement with Get It is because I have a listener() which sits within main().

Events can come at any time, and most often will come when the app hasn't been installed yet.  The listener will pick up events from clicking on the link to open or download the app.  At that point, the app needs to redirect to a specific Widget (LandingPageWidget) which is a named Route.

However, when I set MaterialApp.router() to GetMaterialApp.router(), I still get an error because the listener gets called from main before reaching the Widget.

Unhandled Exception: You are trying to use contextless navigation without
      a GetMaterialApp or Get.key.
      If you are testing your app, you can use:
      [Get.testMode = true], or if you are running your app on
      a physical device or emulator, you must exchange your [MaterialApp]
      for a [GetMaterialApp].
      
#0      GetNavigation.global (package:get/get_navigation/src/extension_navigation.dart:1094:7)
#1      GetNavigation.to (package:get/get_navigation/src/extension_navigation.dart:522:12)
#2      registerListeners.<anonymous closure> (package:assembly/main.dart:68:9)
#3      Invites.setOnReferralDataReceivedListener.<anonymous closure> (package:getsocial_flutter_sdk/invites.dart:74:15)
#4      NativeBridge.registerListener.<anonymous closure> (package:getsocial_flutter_sdk/src/native_bridge.dart:44:37)

**Comment by eb-so** [comment]
@timfong888 GoRouter doesn't support context-less navigations so It doesn't make sense to register the service cause you can't use it in the viewmodel or service anyway, However you can provide the trigger class to `refreshListenable` see the [documentation](refreshListenable)
