### ISSUE TITLE
Using Stacked in StatefulWidget/how to work with override methods from StatefulWidget

### ISSUE THREAD

**Issue by danPyk** [Stacked-Org/stacked#704]
I'm just discoverd this interesting package and I have some doubts.
For example I would like to work with camera package (https://pub.dev/packages/camera). It requires from me to chceck if widget is `mounted`, so I need to use StatefulWidget and initState(). How flow should looks like, if I wouldn't like to place logic inside initState, but in viewModel?

**Comment by eb-so** [comment]
@danPyk  You don't have to use `initState` you can put all the initialisation logic in one function and use a `FutureBuilder`

``` javascript
  Future<CameraController?> initializeCameraController(
      TakePictureViewModel model) async {
    final camera = await model.getRearCamera();

    if (camera == null) return Future.error('Couldn\t get the rear camera');

    cameraController = CameraController(
      // Get a specific camera from the list of available cameras.
      camera,
      // Define the resolution to use.
      ResolutionPreset.high,
    );

    // Next, initialize the controller. This returns a Future.
    await cameraController!.initialize();

    return cameraController;
  }
```

``` javascript
      FutureBuilder<CameraController?>(
              future: initializeCameraController(model),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.done &&
                    snapshot.hasData) {
                  // If the Future is complete, display the preview.
                  return SizedBox.expand(child: CameraPreview(snapshot.data!));
                } else {
                  // Otherwise, display a loading indicator.
                  return const Center(child: CircularProgressIndicator());
                }
              },
            )
```

**Comment by danPyk** [comment]
Shame on me, that I didn't figure out this solution, thank you.

Edit: Second thought: am I uderstand right - I need to dispose CameraController at some point, but in fact I dont, because field disposeViewModel taking handle of this?

**Comment by eb-so** [comment]
No shame in any question, I had to spend a couple of hours to wrap my head around this issue 😄 .

I didn't paste the full code here is how to dispose it or you can use the `onDispose` from the ViewModelBuilder
``` javascript
  @override
  void dispose() {
    // Dispose of the controller when the widget is disposed.
    cameraController?.dispose();
    super.dispose();
  }
