### ISSUE TITLE
Systyem UI icon birghtness not changing with theme

### ISSUE THREAD

**Issue by imprisonedmind** [Stacked-Org/stacked#705]
Hi There, 

My assumption is that System UI icon brightness would change when my theme changes but it does not appear to be happening. 

If that is not the case please let me know, can write some manual detection but would prefer not to. 

Thanks :)

**Comment by FilledStacks** [comment]
Have you been able to solve this? 

We've had a few issues, outside of stacked with the system brightness not following some code on certain platforms. .ie. iOS needs different code than Android to change the system brightness.

**Comment by imprisonedmind** [comment]
Main.dart
```
statusBarColorBuilder: (theme) => theme?.colorScheme.onSurface,
navigationBarColorBuilder: (theme) => theme?.colorScheme.onSurface,
```
Dark Mode:
```
onSurface: Colors.black.withOpacity(0.001),
```

Light Mode:
```
onSurface: Colors.white.withOpacity(0.001),
```

I did this roughly pretty soon after asking this comment, Cannot remember exactly why I did it this way.

I also removed any reference to:
```
SystemChrome.setSystemUIOverlayStyle
```

**Comment by FilledStacks** [comment]
Yeah, the Flutter Theme stuff is confusing sometimes. I've had to do similar things just to get the system tray icons to be the way that I want it to be on certain views.
