### ISSUE TITLE
Stacked generator [Prerelease: 0.8.0-beta.0] generate functions parameter as dynamic

### ISSUE THREAD

**Issue by isaacadariku** [Stacked-Org/stacked#706]
# Example
Using the stacked/example as a demo

1. Add `ValueSetter` callback and type it with `Clashable`
2. Add a getter function `Clashable Function(String name)? clashableGetter`

both to the view parameter for `ExampleFormView`
```
class ExampleFormView extends StatelessWidget with $ExampleFormView {
  final Clashable clashableOne;
  final ValueSetter<Clashable>? onClashableOneSetter;
  final Clashable Function(String name)? clashableGetter;
  ExampleFormView(
      {Key? key,
      required this.clashableOne,
      this.onClashableOneSetter,
      this.clashableGetter})
      : super(key: key);
```

Also for `StreamCounterView` we add our predefine typedef as `ClashableCallback`

```
typedef ClashableCallback = void Function(Clashable clashable);

class StreamCounterView extends StatelessWidget {
  final Clashable clashableTwo;
  final ClashableCallback? onClashableTwoChanged;
  const StreamCounterView(
      {Key? key, required this.clashableTwo, this.onClashableTwoChanged})
      : super(key: key);
```

# Result 
`stacked/packages/stacked/example/lib/app/app.router.dart`
![Screenshot 2022-07-27 at 22 56 58](https://user-images.githubusercontent.com/46024202/181379606-4008a538-e943-467f-8004-83d5c52aa06c.png)

From the result above it fails to attached the alias to the type for functions

**Comment by eb-so** [comment]
@isaacadariku Try  0.8.0-beta.3

**Comment by ziqq** [comment]
Ooo i have this same issue.
