### ISSUE TITLE
How to change index of bottom bar when navigating in children

### ISSUE THREAD

**Issue by furkansoylemez** [Stacked-Org/stacked#716]
Hi, 
I have a HostScreen and it has 2 children nested route in it. I have bottom bar in HostScreen and also have an ExtendedNavigator.When one of the bottom bar buttons clicked im handling navigation like your bottom_bar_example. So my question is, when navigating by clicking bottom bar is ok but if i want navigate from its children how can i animate the bottom bar also? I mean when navigate from ScreenA to ScreenB by clicking bottom bar how can i return ScreenB to ScreenA without clicking bottom bar?

For now, i registered HostScreenViewModel as a singleton. When navigating inside without clicking bottom bar, getting HostScreenViewModel thanks to get_it and updating index. Is there any solid way or this way is enough for this situation?

Finally, thanks for the package :)

**Comment by Eimen2018** [comment]
@furkansoylemez Are you trying to navigate back? in that case you can provide the Id on _navigationService.back and it will go back on the nested route 

`_navigationService.back(id: [yourExtendedNavigatorId]);`

**Comment by furkansoylemez** [comment]
@Eimen2018 Not only I want to go back, but I also want the bottom bar to react when I navigate without pressing the bottom bar button.
