### ISSUE TITLE
[stacked_services] [snackbar] The SnackbarConfig.textColor not working as intended

### ISSUE THREAD

**Issue by dvagala** [Stacked-Org/stacked#717]
I believe that the `SnackbarConfig.textColor` should define the color for all the text in a snackbar, unless otherwise specified explicitly in `titleColor`, `messageColor`, `mainButtonTextColor`.

**Steps to reproduce**
```
final snackbarService = locator<SnackbarService>();

snackbarService.registerSnackbarConfig(SnackbarConfig(
  textColor: Colors.red,
));

snackbarService.showSnackbar(
  message: 'The message',
  title: 'The title',
);
```

**Actual results**
Snackbar's title and message are not red.

**Expected results**
Snackbar's title and message are red.

**Comment by Eimen2018** [comment]
Thank you for the PR
