### ISSUE TITLE
Remove boilerplate when using Presolve

### ISSUE THREAD

**Issue by dvagala** [Stacked-Org/stacked#728]
Each service that needs to be asynchronously initialized during the registration needs to have this boilerplate:
```
  static NativeCommunicatorService? _initializedInstance;
  static Future<NativeCommunicatorService> getInitializedInstance() async {
    if (_initializedInstance == null) {
      _initializedInstance = NativeCommunicatorService();
      await _initializedInstance!.init();
    }
    return _initializedInstance!;
  }

  Future<void> init() async {
   ...
  }
```

I would suggest adding some abstract class `InitializableDependency` and each service would need to override the init(). It would be used like this:
```
class NativeCommunicatorService implements InitializableDependency {
  @override
  Future<void> init() async {
    ...
  }
}
```

It would be registered like this:
```
@StackedApp(dependencies: [
  InitializableSingleton(classType: NativeCommunicatorService),
])
class App {}
```

The generated code in `app.locator.dart` would look like this:
```
  final nativeCommunicatorService = NativeCommunicatorService();
  await nativeCommunicatorService.init();
  locator.registerSingleton(nativeCommunicatorService);
```

When generating the code we can even check if `NativeCommunicatorService` is indeed a subtype of InitializableDependency without reflection using this [little trick](https://stackoverflow.com/a/69114947/8558193)

What do you guys think? Can I implement it this way?

**Comment by FilledStacks** [comment]
That is a good idea @dvagala I like it. 

Please implement and we can merge it into the code. Things to consider when creating a PR. 
- Please branch off the beta branch since that will be master soon
- Add your changes to the change log
- Write some notes on how to test the work
- Update the example project to include this example with the generated code

**Comment by dvagala** [comment]
@FilledStacks alright, I will come back to this In a few weeks, currently don't have time

**Comment by ferrarafer** [comment]
Feature was added to the package, I'm closing this.
