### ISSUE TITLE
Issue with release version !Important

### ISSUE THREAD

**Issue by 404shades** [Stacked-Org/stacked#73]
```dart
Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

```dart
final response = dialogService.showConfirmationDialog(
          title: "Thanks!",
          description:
              "descriptionn.");
      response.then((value) {
        navigationService.back();
      });
```

**Comment by FilledStacks** [comment]
You're not awaiting that call where you're setting response. Is there a reason for that?

**Comment by 404shades** [comment]
I am using then to resolve Future. I am not using await because I don't want to stuck until user presses something.

**Comment by FilledStacks** [comment]
That's not how await works. it's the opposite. it continues execution of the calling function until the value is ready and asynchronously executes the rest of that function. You can't resolve await using then. you're actually just storing the future aren't you? hove over that result and see what type it's being cast to.

**Comment by 404shades** [comment]
Thanks!
