### ISSUE TITLE
[stacked_services] [snackbar] Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by mugikhan** [Stacked-Org/stacked#730]
Steps to reproduce.

Call show custom snackbar.
_snackbarService.showCustomSnackBar(
    variant: SnackbarType.error,
    message: exception.message,
    duration: const Duration(seconds: 2),
);

The exception occurs on the following line in the snackbar_controller class.
```
 Line 91: _overlayState = Overlay.of(Get.overlayContext!);
 ```

```
Unhandled Exception: Null check operator used on a null value
#0      SnackbarController._configureOverlay (package:get/get_navigation/src/snackbar/snackbar_controller.dart:91:50)
#1      SnackbarController._show (package:get/get_navigation/src/snackbar/snackbar_controller.dart:331:5)
#2      GetQueue._check (package:get/get_utils/src/queue/get_queue.dart:42:47)
#3      GetQueue.add (package:get/get_utils/src/queue/get_queue.dart:29:5)
#4      _SnackBarQueue._addJob (package:get/get_navigation/src/snackbar/snackbar_controller.dart:357:31)
#5      SnackbarController.show (package:get/get_navigation/src/snackbar/snackbar_controller.dart:63:27)
#6      ExtensionSnackbar.showSnackbar (package:get/get_navigation/src/extension_navigation.dart:366:16)
#7      GetSnackBar.show (package:get/get_navigation/src/snackbar/snackbar.dart:288:16)
#8      SnackbarService.showCustomSnackBar.<anonymous closure> (package:stacked_services/src/snackbar/snackbar_service.dart:216:37)
```

**Comment by FilledStacks** [comment]
@mugikhan could you give an example that we can use to reproduce this then we'll fix it up.

**Comment by FilledStacks** [comment]
I'm confirming if this happens in the stacked example now.

**Comment by FilledStacks** [comment]
Used the same code as above with a single update of the variant. I have to change the variant to `blueAndYellow` because I don't have an error variant registered. This code:

```dart
   _snackbarService.showCustomSnackBar(
                variant: SnackbarType.blueAndYellow,
                message: 'exception.message',
                duration: const Duration(seconds: 2),
              );
```

Produces the image below

![screenie](https://user-images.githubusercontent.com/3592170/188914151-fa5d9214-ad73-46da-9e92-b7f268346763.jpg)

**Comment by FilledStacks** [comment]
Can you post the code that registers your error variant @mugikhan

**Comment by mugikhan** [comment]
@FilledStacks 
```
service.registerCustomSnackbarConfig(
    variant: SnackbarType.error,
    config: SnackbarConfig(
      snackPosition: SnackPosition.TOP,
      backgroundColor: ColorPalette.error,
      textColor: ColorPalette.onError,
      borderRadius: 1,
      dismissDirection: DismissDirection.up,
    ),
  );
  Shows it using this
  
  _snackbarService.showCustomSnackBar(
variant: SnackbarType.error,
message: exception.message,
duration: const Duration(seconds: 2),
);
```

**Comment by mugikhan** [comment]
This is my main app class. I am using auto_route directly as I need route guards and stacked doesn't cater for it. If I need stacked navigation key I will register my own service to show snackbars I guess. @FilledStacks 

```
class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  final _appRouter = GetIt.I<AppRouter>();

  @override
  Widget build(BuildContext context) {
    return ThemeBuilder(
      defaultThemeMode: ThemeMode.light,
      statusBarColorBuilder: (theme) => Colors.transparent,
      lightTheme: lightTheme,
      darkTheme: darkTheme,
      builder: (context, regularTheme, darkTheme, themeMode) {
        return MaterialApp.router(
          title: 'Transylvania',
          routerDelegate: _appRouter.delegate(),
          routeInformationParser: _appRouter.defaultRouteParser(),
          theme: regularTheme,
          darkTheme: darkTheme?.copyWith(
            pageTransitionsTheme: const PageTransitionsTheme(
              builders: {
                TargetPlatform.iOS: NoShadowCupertinoPageTransitionsBuilder(),
                TargetPlatform.android: FadeUpwardsPageTransitionsBuilder(),
              },
            ),
          ),
          themeMode: themeMode,
          localizationsDelegates: const [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: const [Locale('en', '')],
        );
      },
    );
  }
}
```

**Comment by FilledStacks** [comment]
@mugikhan when you supply your router delegate I think you have access to the nav key in there. I know there are some stacked users that use auto route with the latest version of stacked.

Closing this issue as it's not a bug

**Comment by mugikhan** [comment]
> @FilledStacks 

<img width="443" alt="Screenshot 2022-09-11 at 11 33 44" src="https://user-images.githubusercontent.com/20798643/189520844-1ec77071-c6f1-443a-9357-a8a02c393d12.png">

This is all I have access to. How can I use this to add the navigator key?

**Comment by FilledStacks** [comment]
Mmmmmm, maybe not in the auto router delegate. I don't know how to access it there.

**Comment by mugikhan** [comment]
@FilledStacks 
```
Just an update tried to use GetX directly with the GetMaterialApp and showing a snackbar using Get.snackbar(...)
```
This also errored out with the same error so I guess I'll wait until that package is updated.

**Comment by FilledStacks** [comment]
Thanks for the update @mugikhan

**Comment by mugikhan** [comment]
Yes I can. I will do so a little later tonight. I’ve been on leave and didn’t have access to my laptop. I think the problem is that I’m not using the stacked navigator key and generate route. I need route guards so I am using auto router directly.

Regards,

Mughees Khan
________________________________
