### ISSUE TITLE
Navigation transition doesn't work as expected

### ISSUE THREAD

**Issue by WinXaito** [Stacked-Org/stacked#732]
Hi,

I don't know if I do something wrong or if this is a bug.

after the method `setupLocator()`, I use the following code for defining default transition:

```dart
locator<NavigationService>().config(
  defaultDurationTransition: const Duration(milliseconds: 4000), // volontary high for see the difference
  defaultTransitionStyle: Transition.leftToRight,
);
```

If I do `navigation.navigateToView(MachinesView());`, that's work as expected, I have my long transition. But if I do `navigation.navigateTo(Routes.machinesView);`, that doesn't work. I have a `zoomIn` transition.

I tried to add that: `CustomRoute(page: LoadingView, transitionsBuilder: TransitionsBuilders.slideLeft, durationInMilliseconds: 8000),` in my `@StackedApp`, but that doesn't change anything.

I use the library `fluent_ui` with Flutter 3.3

- stacked: ^3.0.0
- stacked_service: ^0.9.5

Edit: if I do `navigation.navigateToMachinesView()`, or `navigation.navigateToMachinesView(transition: ((p0, p1, p2, p3) => HorizontalSlidePageTransition(child: p3, animation: p1)));`, that **doesn't work** too.

Edit: `navigation.replaceWithTransition(MachinesView(), transitionStyle: Transition.upToDown);` works. As I can see, when I use `Routes.xxx` that doesn't work, and if I build the page myself, that work.

**Comment by FilledStacks** [comment]
Hey @WinXaito can you try supplying the `transition` as described [here in the docs](https://stacked.filledstacks.com/docs/feature-guides/Navigation/custom-navigation). It needs to be statically supplied so we can generate the correct code for it. 

See the example in the docs linked and let me know if it works or not.

**Comment by WinXaito** [comment]
That work fine, thank you !

But, there is a reason that when we do:

```dart
locator<NavigationService>().config(
  defaultDurationTransition: const Duration(milliseconds: 4000), // volontary high for see the difference
  defaultTransitionStyle: Transition.leftToRight,
);
```

A `_nav.navigateToView(..)` use the default transition, but `_nav.navigateTo(Routes.yyy)` not ?

**Comment by FilledStacks** [comment]
@WinXaito yes, the reason is that it has never been implemented properly. I inherited a lot of the code from auto_route 0.6.9, before they swapped to navigator 2.0 and it never worked. I should remove it from the library to avoid confusion.

**Comment by FilledStacks** [comment]
@WinXaito I'll close the issue. Happy to help. 😄

**Comment by coruscant187** [comment]
> Hey @WinXaito can you try supplying the `transition` as described [here in the docs](https://stacked.filledstacks.com/docs/feature-guides/Navigation/custom-navigation). It needs to be statically supplied so we can generate the correct code for it.
> 
> See the example in the docs linked and let me know if it works or not.

@FilledStacks Where can I find the newest documentation for [this](https://stacked.filledstacks.com/docs/feature-guides/Navigation/custom-navigation)? The page cannot be found currently.
