### ISSUE TITLE
[stacked_generator] Failed generate with Query Param

### ISSUE THREAD

**Issue by ziqq** [Stacked-Org/stacked#733]
I try to generate routes with query param and i catch this error.

![image](https://user-images.githubusercontent.com/20646071/190156902-9c8d6933-36bc-4376-acf3-ca46a5e0cd76.png)
![image](https://user-images.githubusercontent.com/20646071/190156999-bc48ae4d-e2ec-4413-aa1d-021bdff8c616.png)

And generator forgeted to import my models from app.dart

![image](https://user-images.githubusercontent.com/20646071/190158328-c498cce8-57b4-4e4c-88d5-e103286cae94.png)

**Comment by FilledStacks** [comment]
Hey, what is `QueryParam`? It's not something we built for. You can remove that. It's not required.

**Comment by maciekczwa** [comment]
It worked correctly with previous version. It is especially needed if using web version. That way data can be passed in the url to take user directly to correct screen by id.

For example I'm using this to pass the page identifier and title
https://localhost/app/#/page/72?title=PageTitle

The route was defined by:
`MaterialRoute(page: GenericPageView, path: "/page/:pageId")`
And the view constructor:
` GenericPageView({Key? key, @PathParam('pageId') required this.pageId, @QueryParam('title') this.pageTitle, this.siblingPagesData})`

**Comment by FilledStacks** [comment]
I see, I see. I've never used that, it's also not in our example app which is why it's broken. I'll work on this as soon as I get a chance.

**Comment by FilledStacks** [comment]
@maciekczwa can you give me a full example of what's supposed to be generated please. It'll make the fix easier. In your example above why is `title` not in the `path` property? Or is that just because this is pseudo code?

**Comment by maciekczwa** [comment]
I wanted title to be named. If I remember good there was a problem with special characters (like spaces, national characters) in path parameters, when you use QueryParam they are getting url encoded.
The GenericPageView contains some additional parameters which can be passed outside of the url.

Generated working code:
```
class Routes {
  static const String _genericPageView = '/page/:pageId';
  static String genericPageView({@required dynamic pageId}) => '/page/$pageId';
  static const all = <String>{
    _genericPageView,
  };
}

class StackedRouter extends RouterBase {
  @override
  List<RouteDef> get routes => _routes;
  final _routes = <RouteDef>[
    RouteDef(Routes._genericPageView, page: GenericPageView),
  ];
  @override
  Map<Type, StackedRouteFactory> get pagesMap => _pagesMap;
  final _pagesMap = <Type, StackedRouteFactory>{
    GenericPageView: (data) {
      var args = data.getArgs<GenericPageViewArguments>(
        orElse: () => GenericPageViewArguments(),
      );
      return MaterialPageRoute<dynamic>(
        builder: (context) => GenericPageView(
          key: args.key,
          pageId: data.pathParams['pageId'].getInt(),
          pageTitle: data.queryParams['title'].optString(),
          siblingPagesData: args.siblingPagesData,
        ),
        settings: data,
      );
    },
  };
}

/// ************************************************************************
/// Arguments holder classes
/// *************************************************************************

/// GenericPageView arguments holder class
class GenericPageViewArguments {
  final Key? key;
  final SiblingPagesData? siblingPagesData;
  GenericPageViewArguments({this.key, this.siblingPagesData});
}
```
Target view class:
```
class GenericPageView extends StatelessWidget {
  final int pageId;
  final String? pageTitle;
  final SiblingPagesData? siblingPagesData;

  GenericPageView({Key? key, @PathParam('pageId') required this.pageId, @QueryParam('title') this.pageTitle, this.siblingPagesData})
      : super(key: key);
}
```

App:
```
@StackedApp(
  routes: [
    MaterialRoute(page: GenericPageView, path: "/page/:pageId")
  ])
```

**Comment by FilledStacks** [comment]
Awesome, thanks. I'll see where that code went. It was most likely removed during our refactor. 

I'll find an older version and then I'll merge it back in at some point.

**Comment by ziqq** [comment]
@FilledStacks, I wont to ask U. Can u fix **var** to **final**. Because my linters swear at it.

![image](https://user-images.githubusercontent.com/20646071/190973994-8d8249ba-ba8e-4f8a-a044-ac574f3a359e.png)

**Comment by Edamijueda** [comment]
Yes you should. Since you are not reassigning it.

**Comment by FilledStacks** [comment]
@ziqq if I get some time I can. It's a small fix, you can probably find the place and make a PR for it then I'll merge it in.

**Comment by ziqq** [comment]
@FilledStacks. Strange, I ran the generator and got what I was supposed to do without changing the source code. Magic, I don't think so. The only thing I did was update a couple of dependencies.

But generator forgot import my models.

![image](https://user-images.githubusercontent.com/20646071/191187394-b51ed75f-28d8-4842-97b9-a17d4439a2b1.png)

And i catch this same error

![image](https://user-images.githubusercontent.com/20646071/191187528-71f0316e-a256-4240-adc6-9e4586992667.png)

![image](https://user-images.githubusercontent.com/20646071/213125815-ee2b36ed-1394-4983-9e8f-76f6148c316e.png)

![image](https://user-images.githubusercontent.com/20646071/213126027-18b6d29c-50d2-4278-80c4-aedc724813e5.png)

**Comment by ziqq** [comment]
Hello @FilledStacks i try upgraded to 8.0.1 and this isue not fixed.

**Comment by ziqq** [comment]
Still need to add model imports

![image](https://user-images.githubusercontent.com/20646071/203909149-3adff3b0-04bf-4507-85ed-e8001c68dbc1.png)

And this line from above so that my linter does not swear
> // ignore_for_file: no_leading_underscores_for_library_prefixes, prefer_relative_imports, avoid_annotating_with_dynamic, avoid_dynamic_calls

**Comment by FilledStacks** [comment]
Where should that be added?

**Comment by ziqq** [comment]
> Where should that be added?

app.router on top. And in old version i have my models imports but i don't find it in new version.

![image](https://user-images.githubusercontent.com/20646071/203963941-01caec83-6a03-4801-bc9d-2754540bb448.png)

**Comment by FilledStacks** [comment]
I see, add it in, make a PR and I'll publish it.

**Comment by ziqq** [comment]
I can't add PR becouse i didn't has time. Plz make fix and update package.

**Comment by FilledStacks** [comment]
The same here. We'll look at it sometime in this week, maybe next week.

**Comment by FilledStacks** [comment]
This works when using the latest template for stacked --template=web when creating with the cli. 

We are adding documentation in the coming weeks that will show how to migrate to using the v2 Flutter navigator in stacked.
