### ISSUE TITLE
stacked_generator compatibility with freezed version 2.1.1

### ISSUE THREAD

**Issue by godspeed0310** [Stacked-Org/stacked#734]
Because stacked_generator >=0.8.0-beta.6 depends on analyzer ^4.6.0 and freezed >=2.1.1 depends on analyzer ^5.0.0, stacked_generator >=0.8.0-beta.6 is incompatible with freezed >=2.1.1.

**Comment by godspeed0310** [comment]
Issue fixed with stacked_generator 0.8.0

**Comment by godspeed0310** [comment]
This is fixed by rolling back the freezed version to 2.1.0+1 but there's no fix for 2.1.1

**Comment by FilledStacks** [comment]
Fixed in 0.8.0+1
