### ISSUE TITLE
Code gen failing: flutter pub run build_runner build --delete-conflicting-outputs

### ISSUE THREAD

**Issue by ikennaumeh** [Stacked-Org/stacked#735]
I'm unable to run my code gen.

![stacked ---](https://user-images.githubusercontent.com/54285609/192494474-0055f13c-ce10-44cb-b7fd-3702bf13c910.png)

**Comment by Edamijueda** [comment]
What task are you trying to accomplish that made you run the command?

**Comment by ikennaumeh** [comment]
Setting up the app basically and I added a view, then ran the command.

**Comment by Edamijueda** [comment]
Did you add the view that using the Stacked_CLI? If yes, then you should update your stacked_generator package to the  latest version.

**Comment by FilledStacks** [comment]
What version of the stacked and the stacked_generator are you using?

**Comment by ikennaumeh** [comment]
Fixed. Just had to upgrade the versions.
