### ISSUE TITLE
Real Partial Rebuilds

### ISSUE THREAD

**Issue by FilledStacks** [Stacked-Org/stacked#74]
Currently we have the ability to separate widgets with their own viewmodels which allows you to rebuild only certain widgets within the widget tree. In addition to that I think it would be great if we can rebuild a ViewModelWidget ONLY if the state that it's using has updated. This will make it so that not all the ViewModelWidgets that's marked as reactive is rebuilt when notifyListeners is called. 

I will be looking at the Selector functionality in Provider to see if that will allow me to create a solution to provide this functionality. I will most likely only be able to look at it the 25th of June and the 28th of June. 

If anyone reading this would like to jump on this functionality before then feel free to contact me on Slack and we can discuss solutions to get the ball rolling for a PR.

**Comment by Edorin9** [comment]
I've been using stacked, but I've never used Provider actually. Looking at the provider docs, it looks like Selector is the way to go. I'd really like to see this capability in this package.

**Comment by seekcx** [comment]
Is there any progress on this feature?

**Comment by FilledStacks** [comment]
@seekcx No. There has not been a need for this in any of the apps we built so it never became a priority. I don't know when I'll look at this.

**Comment by FilledStacks** [comment]
This has not become a requirement after multiple client projects. I will close this repo until we experience a problem with the functionality not being available.
