### ISSUE TITLE
[stacked_generator] Not import both classes with same name from two different libraries

### ISSUE THREAD

**Issue by elceka** [Stacked-Org/stacked#740]
Hi,
i have two classes with same name, but under different paths and libraries of the same package.
When i importing both in file app.dart, then i set keyword (import with AS) to one of them (or for both of them, the result is same) and after success generate procedure, file app.router.dart contain only one imported class of them.
Please, what i make a wrong?

**Comment by FilledStacks** [comment]
Hi @elceka the new version of stacked and stacked_generator solves. Please try with latest generator version. We had the same bug and fixed it.

**Comment by elceka** [comment]
Hi @FilledStacks , thank you for your time and answer.
Now, it is working, with latest version of stacked_generator, but only partially, now it is trouble with navigation methods names, prefixed with 'navigateToCLASSNAME'.
Generator generate two methods of the same name.
In the file app.dart i have set names of all routes classes, is it possible use that names on generated navigation methods names?

**Comment by FilledStacks** [comment]
It's concerning that you would have two views with the same name that does two different things.
- If it has the same functionality refactor into one view
- If it doesn't name it something else

Having conflicting file names (in dart) causes maintenance issues for the team. Could you elaborate on why you have that setup. Maybe there's something we can do about that instead.

**Comment by elceka** [comment]
I have a multiple different packages (modules of my stacked app) and inside this packages i use sometimes same library (class) names. All modules solves different tasks, show different content, but both haves same hierarchy (list view, item view, ...) but with different appearance. I'm trying use the same naming convention across all packages (for simplicity).
I think, this isn't nothing special, i can rename those libraries, but, i think, this way is not the right way, for this we have dart's keyword of libraries importing functionality.
For example, how can i solve this navigation issue with package from a another owner?

Packages tree example:

- module_1
  - lib
    - src
      - views
        - screens
          - item.dart
          - list.dart
          - main.dart
- module_2
  - lib
    - src
      - views
        - screens
          - item.dart
          - list.dart
          - main.dart
- app
  - lib
    - src
      - views
        - screens
          - ...

**Comment by FilledStacks** [comment]
@elceka I see. It's a tradeoff we sometimes have to make. Simplicity or Maintainability. In this case, or in any generator based solution you wouldn't be able to generate routes with different names for the same views since it would be the same name. 

What you can do is to add a name to the routes using the name property . 

```dart
CupertinoRoute(page: HomeView, name: 'homeViewArtistApp'),
CupertinoRoute(page: HomeView, name: 'homeViewHostApp'),
```

That should generate the routes using those names as well as the route paths to be used for navigation.

**Comment by elceka** [comment]
Hi @FilledStacks,
I've used the name attribute on the route class constructor, but as i wrote in the second comment above, generator generate two navigation methods with the same name, as you can see in the example below (in the navigator extension).

app.dart
```dart
import 'package:ex_app/src/views/screens/protocols_list_screen.dart';
import 'package:ex_app/src/module_admin/views/screens/protocols_list_screen.dart' as module_admin;

@StackedApp(routes: [
  MaterialRoute(page: ProtocolsListScreen, name: 'moduleTechnicianProtocolsListScreen', path: '/module-technician/protocols'),
  MaterialRoute(page: module_admin.ProtocolsListScreen, name: 'moduleAdminProtocolsListScreen', path: '/module-admin/protocols')
])
class AppSetup {}
```

app.router.dart
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// StackedRouterGenerator
// **************************************************************************

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter/material.dart' as _i21;
import 'package:flutter/material.dart';
import 'package:ex_app/src/module_admin/views/screens/protocols_list_screen.dart' as _i20;
import 'package:ex_app/src/views/screens/protocols_list_screen.dart' as _i11;
import 'package:stacked/stacked.dart' as _i1;
import 'package:stacked_services/stacked_services.dart' as _i26;

class Routes {
  static const moduleTechnicianProtocolsListScreen = '/module-technician/protocols';
  static const moduleAdminProtocolsListScreen = '/module-admin/protocols';

  static const all = <String>{
    moduleTechnicianProtocolsListScreen,
    moduleAdminProtocolsListScreen,
  };
}

class StackedRouter extends _i1.RouterBase {
  final _routes = <_i1.RouteDef>[
    _i1.RouteDef(
      Routes.moduleTechnicianProtocolsListScreen,
      page: _i11.ProtocolsListScreen,
    ),
    _i1.RouteDef(
      Routes.moduleAdminProtocolsListScreen,
      page: _i20.ProtocolsListScreen,
    ),
  ];

  final _pagesMap = <Type, _i1.StackedRouteFactory>{
    _i11.ProtocolsListScreen: (data) {
      return MaterialPageRoute<dynamic>(
        builder: (context) => const _i11.ProtocolsListScreen(),
        settings: data,
      );
    },
    _i20.ProtocolsListScreen: (data) {
      return MaterialPageRoute<dynamic>(
        builder: (context) => const _i20.ProtocolsListScreen(),
        settings: data,
      );
    },
  };

  @override
  List<_i1.RouteDef> get routes => _routes;
  @override
  Map<Type, _i1.StackedRouteFactory> get pagesMap => _pagesMap;
}

extension NavigatorStateExtension on _i26.NavigationService {
  Future<dynamic> navigateToProtocolsListScreen([
    int? routerId,
    bool preventDuplicates = true,
    Map<String, String>? parameters,
    Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)?
        transition,
  ]) async {
    return navigateTo<dynamic>(Routes.moduleTechnicianProtocolsListScreen,
        id: routerId,
        preventDuplicates: preventDuplicates,
        parameters: parameters,
        transition: transition);
  }

  Future<dynamic> navigateToProtocolsListScreen([
    int? routerId,
    bool preventDuplicates = true,
    Map<String, String>? parameters,
    Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)?
        transition,
  ]) async {
    return navigateTo<dynamic>(Routes.moduleAdminProtocolsListScreen,
        id: routerId,
        preventDuplicates: preventDuplicates,
        parameters: parameters,
        transition: transition);
  }
}
```

**Comment by FilledStacks** [comment]
Aaaaaahh @elceka I see, 

There's probably a bug in the NavigatorExtensions generator function and it's not using the Route.name and maybe using the class name directly. I'll only be able to look at that on Monday. I'm busy moving today and this weekend.

**Comment by elceka** [comment]
Bump

**Comment by FilledStacks** [comment]
@elceka I haven't had time to check this out. Let me get the dev that updated this code to see if he can make a fix for it.

**Comment by FilledStacks** [comment]
@eb-so says he'll tackle this issue soon soon 👀 👀 👀 👀

**Comment by eb-so** [comment]
@elceka @FilledStacks 👀
