### ISSUE TITLE
runBusyFuture() doesn't reliably set error property on ViewModel in error case. Stacked version 3.0.0

### ISSUE THREAD

**Issue by JohnnyRainbow81** [Stacked-Org/stacked#741]
Hi,
The runBusyFuture()-method doesn't seem to reliably set the setError/modelError-properties when the Future throws an error. 

Solely the _errorStates-Map will receive an Exception/Error-entry, but neither setError() nor modelError properties are updated.

My example:

` List<Subscription>? list =
        await runBusyFuture<List<Subscription>?>(_userService.getSubscriptions(), busyObject: subscriptions);`

I use stacked 3.0.0. 

<img width="521" alt="Bildschirmfoto 2022-10-17 um 11 49 25" src="https://user-images.githubusercontent.com/23189088/196146908-870e8d8c-55bf-4d8c-b7d7-a8776ea4296d.png">

[edit] 
This seems to be a wanted scenario when you have a busyObject. Because then you also have to check for error individually with 

`if(viewModel.error(busyObject)) ... // show error in UI `

Wouldn't it be better if the `hasError` also gets set to `true` when we have **any** error ?

**Comment by FilledStacks** [comment]
Hey @JohnnyRainbow81 I think it would be a good move to ensure `hasError` also returns true in that case. Do you think you can create a PR to implement this functionality for us?

**Comment by JohnnyRainbow81** [comment]
Hi! Thanks for your great work btw, I love stacked so far :)

How would this work for you?

From
```
// Returns the error existence status of the ViewModel
  bool get hasError => error(this) != null;

  // Returns the error status of the ViewModel
  dynamic get modelError => error(this);
```

to
 ```
// Returns the error existence status of the ViewModel
  bool get hasError => error(this) != null;

  // Returns the error existence status of any error that was caught by the Viewmodel
  bool get hasAnyError => _errorStates.entries.isNotEmpty && _errorStates.entries.any((element) => element.value != null);

  // Returns recently added error to the ViewModel
  dynamic get currentError => _errorStates.entries.last.value;

  // Returns the error status of the ViewModel
  dynamic get modelError => error(this);
```

**Comment by FilledStacks** [comment]
Thank you. I'm excited to keep pushing updates. I have been very focused on my startup but now that we can push forward on sales with the product I have some time to create content and improve stacked again. 

The only concern here is `currentError` . I don't think it's guaranteed that the value property on a map is ordered by LIFO. But I didn't do any research on it. If it is ordered in that way then I'm happy with the code you want to write.

**Comment by JohnnyRainbow81** [comment]
Good point. I did some research and it isn't said that `Map<K,V>` doesn't guarantee to return the last element when you call map.entries.last, but `LinkedHashMap<K,V>` does! 
That would involve to change the _errorStates-` Map` to `LinkedMap`.
Like this:

  ```
LinkedHashMap<int, dynamic> _errorStates = LinkedHashMap<int, dynamic>();
  dynamic error(Object object) => _errorStates[object.hashCode];

  /// Returns the error existence status of the ViewModel
  bool get hasError => error(this) != null;

  /// Returns the error existence status of any error that was caught by the Viewmodel
  bool get hasAnyError => _errorStates.entries.isNotEmpty && _errorStates.entries.any((element) => element.value != null);

  /// Returns recently added error to the ViewModel
  dynamic get currentError => _errorStates.entries.last.value;

  /// Returns the error status of the ViewModel
  dynamic get modelError => error(this);
```

I am in no way a senior dev, so I can only hope that this approach kinda suits OK. Just sayin :)

Wish you much luck with your startup! 🚀

**Comment by FilledStacks** [comment]
That change should be fine. Given that the _errorStates map is not used externally the type of it doesn't really matter. 

I'm happy using a LinkedHashMap

**Comment by FilledStacks** [comment]
PR in progrss in #750 waiting on final review changes before merging.

**Comment by FilledStacks** [comment]
The PR went stale. I'll leave it open and will attempt to merge it in on my next working session
