### ISSUE TITLE
Snackbar isn't shown if it is followed by navigationService.back();

### ISSUE THREAD

**Issue by godspeed0310** [Stacked-Org/stacked#742]
Here's the minimal code for the same

`saveChanges() {
    log('Profile Updated');
    _snackbarService.showSnackbar(
      message: 'Changes saved',
      duration: const Duration(seconds: 2),
    );
    _navigationService.back();
  }`

**Comment by FilledStacks** [comment]
Yes, that makes sense. The back call will dismiss the navbar. 

Turn the calls around. Navigate back first then show the snackbar.

Or a better solution would be, show the snackbar when the navigation completes in the viewmodel that's calling the function.

**Comment by godspeed0310** [comment]
Okay got it, closing the issue then. Thanks for the clarification 👍
