### ISSUE TITLE
Call controllers from ViewModel

### ISSUE THREAD

**Issue by JulienDev** [Stacked-Org/stacked#744]
Hello folks,

I really appreciate the ViewModel architecture, however, each time I need to call a controller function from the ViewModel I can't find any correct solution. For example, sometimes I need to start an animation from the controller, or sometimes, I want to display the next PageView page. I know some people already asked how to do that, I read the answers but I didn't find any concrete examples. Could you please share a piece of code with me? :)

Thanks

**Comment by FilledStacks** [comment]
Hey @JulienDev ,

The best way to do this is to use a callback function. I have a solution in mind to build this into the package which I haven't started working on yet. 

But the way I do it now is to register a callback function and then call it when it's required. 

```dart
...
onModelReady: (model) => model.registerAnimationCallback(() => controller.forward())
```

**Comment by JulienDev** [comment]
Thank you! That's great news for the future of the library!
