### ISSUE TITLE
[stacked_generator] Missing prefix of enum default value in app.router.dart

### ISSUE THREAD

**Issue by cvphat** [Stacked-Org/stacked#745]
I have a view with default value is an enum in constructor like this:

```dart
class CameraView extends StatelessWidget {
  final List<CameraMode> cameraModes;
  final bool allowSwitchCamera;
  const CameraView({
    super.key,
    this.cameraModes = const [
      CameraMode.image,
      CameraMode.video,
    ],
    this.allowSwitchCamera = false,
  });
}
```
app.router.dart
![image](https://user-images.githubusercontent.com/50006020/197726502-4ea13be6-c5dd-440a-a2d5-5e3c986942b3.png)

**Comment by FilledStacks** [comment]
Hi there, thanks for filing an issue. We have fixed this before. Can you confirm the version of the stacked_generator that you're currently using in your pubspec.yaml?

**Comment by cvphat** [comment]
> Hi there, thanks for filing an issue. We have fixed this before. Can you confirm the version of the stacked_generator that you're currently using in your pubspec.yaml?

I am using `^0.8.0+1`

**Comment by FilledStacks** [comment]
Aaaah, I see. The default value as a list of enums is what breaks it. Normal enums work. When I get some time I'll fix this up. I might only get time in the next few days.

**Comment by ScottAtRedHawk** [comment]
Hi @eb-so , this is also an issue with importing prefixes on routes with type parameters. The import and prefix are at the top of the `app.router.dart` file but not put with the classes. After every build runner build command, I have to manually fix the prefixes.

Thanks!

`app.dart`
```dart
@StackedApp(
  routes: [
    AdaptiveRoute(page: StartupView, initial: true),
    CustomRoute(
      page: LoginView,
      transitionsBuilder: TransitionsBuilders.slideTop,
      durationInMilliseconds: 300,
    ),
    AdaptiveRoute<Customer>(page: CustomerSelectionView),
    AdaptiveRoute<CategoryType>(page: CategorySelectionView),
  ],
  dependencies: [
    // stacked services
    LazySingleton(classType: NavigationService),
  ],
  logger: StackedLogger(),
)
class App {
  // This class has no purpose besides housing the annotation that generates
  // the required functionality.
}
```

<img width="677" alt="image" src="https://user-images.githubusercontent.com/26330264/201151546-bf2fa3cc-3de6-4504-a2a4-3ae6cbda8530.png">

**Comment by FilledStacks** [comment]
Please confirm it works on 0.8.1-beta.3 @cvphat  then I'll promote to stable.

**Comment by cvphat** [comment]
@FilledStacks , It does not work. I also tried to run `flutter clean` and `flutter pub get` again.

**Comment by eb-so** [comment]
@cvphat I used this [example](https://github.com/FilledStacks/stacked/blob/master/packages/stacked/example/lib/ui/home/home_view.dart) to repreduce the bug

**Comment by cvphat** [comment]
The route method is also not correct after I upgrade to `0.8.1-beta.3` 
![image](https://user-images.githubusercontent.com/50006020/201628490-1945c1c1-f864-456c-b0d9-d598634296cd.png)
As image, the class name of view has not been capitalized the first character

**Comment by eb-so** [comment]
I didn't change that but you can create a separate issue for it

**Comment by cvphat** [comment]
@eb-so , I created a new repo to reproduce and added some code to generate router. The bug is still happening. Please help to see this https://github.com/cvphat/stacked_issue
![image](https://user-images.githubusercontent.com/50006020/201638638-fadbbabd-bd44-474c-b887-4992e62c265e.png)
I do not know why your example code work well :cry:

**Comment by eb-so** [comment]
@cvphat I found the issue, I'll fix it quickly
