### ISSUE TITLE
Stacked_hooks useTextEditingController(): the method 'useTextEditingController' isn't defined for the type 'LoginDialog'. (Documentation)

### ISSUE THREAD

**Issue by Kyrie-Jin** [Stacked-Org/stacked#746]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/63819693/197755991-71d37c81-f4c2-4be9-8c0b-433cdd0d583b.png">

<img width="910" alt="image" src="https://user-images.githubusercontent.com/63819693/197756046-4abb7a4a-a985-46e5-8c09-2a5dc718661f.png">

<img width="199" alt="image" src="https://user-images.githubusercontent.com/63819693/197756198-a661bbb9-08e7-401a-8d8f-0d659a05c565.png">

I cannot figure it out, thank you in advance!

**Comment by FilledStacks** [comment]
That function only exists in flutter_hooks. Install it then you can use it.
