### ISSUE TITLE
Problem with a View pushing the same View

### ISSUE THREAD

**Issue by vptcnt** [Stacked-Org/stacked#752]
Hello,
I would like to used Stacked to get articles from Wordpress.

I display the list of articles correctly via a ListingView calling a controller ListingViewModel.
I can click on an item in the list and display the content of the article via an ArticleView using a controller ArticleViewModel.
This articles are get by IDs

Inside the article, there are links to other  articles, but the article are get a Slug.

And I would like to push the same page to load the new article.

To do something like this:

ListingView > ArticleView (article A by Id) > ArticleView (article B by Slug)> ArticleView (article C)

My problem is if there is a notifylisteners called in ArticleView (article B), I have a error :

The following assertion was thrown while dispatching notifications for ArticleViewModel:
This _InheritedeProviderScope<ArticleViewModel?> Widget cannot be marked as needing to build because the framework is already in the process of building. [...]

What would be the best solution to implement a View pushing the same View ?

Vincent

**Comment by FilledStacks** [comment]
@vptcnt when performing the navigation you can pass in `preventDuplicates` and set it to false. Then we won't block duplicate entries in the stack.
