### ISSUE TITLE
[stacked_generator] Dialog generator ignore stacked configuration

### ISSUE THREAD

**Issue by elceka** [Stacked-Org/stacked#754]
Generated file for the stacked dialogs not reflex to the stacked configuration defined in the stacked.config.json file.
In the generated dialog file is imported incorrect locator dart file, it is imported default name of it, not the name defined in the stacked configuration file.
Trouble is in the implementation in the file dialog_class_generator_helper.dart, as can you see, import is firmly defined at the line 23 of the code: https://github.com/FilledStacks/stacked/blob/8fd219037003c562f99c5bfffc78293ed8d1623f/packages/stacked_generator/lib/src/generators/dialogs/generate/dialog_class_generator_helper.dart#L23

Content of the file stacked.config.json:
```json
{
  "views_path" : "lib/src/ui",
  "services_path" : "lib/src/services",
  "stacked_app_path" : "lib/module.dart",
  "locator_name" : "locator"
}
```

Example of the file module.dart:
```dart
@StackedApp(dialogs: [
  StackedDialog(classType: LoginDialogCupertino),
])
class ModuleCore implements BaseModule {}
```

Part of the generated file module.dialog.dart:
```dart
import 'package:stacked_services/stacked_services.dart';

import 'app.locator.dart';
...
```

How can look right generated part of the file module.dialog.dart:
```dart
import 'package:stacked_services/stacked_services.dart';

import 'module.locator.dart';
...
}
```

**Comment by FilledStacks** [comment]
Hey, those two packages are separate. Which is why they won't work together. 

It's a good thing you picked up on. 

Most likely we'll have to read the stacked.config in the generator as well. That's a new feature that will have to be built. 

Thanks for taking the time to write out the details.

**Comment by elceka** [comment]
OK, thank you.

**Comment by FilledStacks** [comment]
This feature will not be added to the upcoming improvements. 

### Reason
1. Generators get access to the location of the current path that contains the annotation in question. We don't have access to all the files with the current generator implementation. 
2. We don't know which use cases this applies too
3. We don't have many users looking for this functionality
