### ISSUE TITLE
NavigationService - Nested Navigation

### ISSUE THREAD

**Issue by ParthaGudivada** [Stacked-Org/stacked#76]
I was looking to leverage the NavigationService of the stacked_services for the nested navigators.  However I couldn't find anything to that reference.  Maybe there is a way to do that with the current package.  

 If it does not exist,  can something in the following lines
```flutter
Future<dynamic> navigateToInGlobalKey(
      GlobalKey<NavigatorState> navStateKey, String routeName,
      {dynamic arguments}) {
    return navStateKey.currentState.pushNamed(routeName, arguments: arguments);
}
```
will do that.  Any thoughts ?

**Comment by FilledStacks** [comment]
Mmmmmm, I haven't looked at multiple navigators for it yet. There's definitely nothing that exists for it right now. That might work, i'd have to test it first. I don't want any ui code in the viewmodels so there's can't be a reference of the key on the api of the navigation service.

**Comment by ParthaGudivada** [comment]
Agreed.  ViewModel(VM) should not have access to the key.  Underlying package `get` suggests to use `nestedKey`.  However it is not exposed via NavigationService.    What would be your recommendation if I need to use multiple navigators.

**Comment by sanalkv** [comment]
I just found out that get package nested navigation is not exposed via NavigationService, this is a must include feature. My app is completely depended on navigation service, but now to use nested navigation, i will have to import get package  separately. I hope you can add this feature to your navigation service ASAP. Thanks in advance :) . @FilledStacks

**Comment by FilledStacks** [comment]
@sanalkv @ParthaGudivada Done. Exposed get `nestedNavigationKey` on the `NavigationService` in 0.4.4

**Comment by sanalkv** [comment]
Hey, you forgot to pass id parameter for each functions like navigateTo, replaceWith etc. Without mentioning the id, the Get package will use the default key for navigating, the nested key wont have an impact.

you have to make changes to each function like the below code.

`  Future<dynamic> navigateTo(String routeName, {dynamic arguments,int id}) {
    return Get.toNamed(routeName, arguments: arguments,id: id);
 '}`

@FilledStacks

**Comment by FilledStacks** [comment]
@sanalkv my bad. I don't use nested navigation so i just updated based on what's in the readme for get. Added id in 0.4.4+1

**Comment by sanalkv** [comment]
Thanks mate, that was quick. Code working fine now.
