### ISSUE TITLE
Update Get Started to explain the generated Code

### ISSUE THREAD

**Issue by FilledStacks** [Stacked-Org/stacked#760]
At the moment the Get Started section of the documentation lacks an explanation of the output of the cli. 

Since we have some counter code in the generated code we should go over explaining how the view and viewmodel works by using the generated code as an example.

**Comment by ferrarafer** [comment]
In Review ✅ 

Documentation: https://github.com/FilledStacks/stacked-docs/pull/19

**Comment by FilledStacks** [comment]
Review complete. Moving on to the next PR now.
