### ISSUE TITLE
Build a basic Todo App

### ISSUE THREAD

**Issue by FilledStacks** [Stacked-Org/stacked#761]
As apart of the documentation we want the user to create a basic Todo application. This will cover:
- Form functionality to enter the text
- View / ViewModel interaction
- Service creation and dependency injection
- Service creation for wrapping a package (like SharedPreferences)

**Comment by ferrarafer** [comment]
In Review :white_check_mark:

App: https://github.com/ferrarafer/stacked_todos
Documentation: https://github.com/FilledStacks/stacked-docs/pull/20

@FilledStacks Let me know if you want to move the repo to Filledstacks domain.

**Comment by FilledStacks** [comment]
Going into review now.
