### ISSUE TITLE
Reactive Services

### ISSUE THREAD

**Issue by ferrarafer** [Stacked-Org/stacked#764]
Explain how to share data between two viewmodels using services and make them react to the change of those values.

**Comment by ziqq** [comment]
An error occurred while updating the UI with a reactive service in a new implementation such as ListenableServiceMixin. Please check that it works properly.

**Comment by FilledStacks** [comment]
@ziqq we have checked. It seems to work properly. If you have a repo that reproduces your issue we can take a look at it.

**Comment by richard457** [comment]
This code inside ReactiveViewModel view model ```@override
  List<ReactiveServiceMixin> get reactiveServices =>
      [keypad, app, productService, settingService];``` is deprecated the question I believe was how to migrate to suggestion.

**Comment by ziqq** [comment]
> This code inside ReactiveViewModel view model `@override List<ReactiveServiceMixin> get reactiveServices => [keypad, app, productService, settingService];` is deprecated the question I believe was how to migrate to suggestion.

```dart
List<ListenableServiceMixin> get listenableServices => [_sameService, _otherSameService];
```

**Comment by FilledStacks** [comment]
@richard457 let me know if the above works.

**Comment by araujocarlosm** [comment]
Hi @FilledStacks 

I'm using ListenableServiceMixin in my new Services, but I can't achieve that ReactiveValues are fired when I set a new value to them.

Service:

```
@lazySingleton
class DemoService with ListenableServiceMixin {
  final loaderValue = ReactiveValue(false);

  DemoService() {
    listenToReactiveValues([loaderValue]);
  }
}
```

ViewModel:

```
class DemoViewModel extends ReactiveViewModel {
  final _service = locator<DemoService>();

  @override
  List<ListenableServiceMixin> get listenableServices => [_service];
}
```

When 'listenToReactiveValues' evaluates the ReactiveValue, it doesn't applies in no one cases

![Captura de pantalla 2023-02-14 a la(s) 1 32 28 p m](https://user-images.githubusercontent.com/15207044/218826621-adf60d22-a598-4b3b-b5cc-85a9b3e6274c.png)


Let me know if I'm wrong, I'll appreciate it.

**Comment by FilledStacks** [comment]
Hi @araujocarlosm I'm hoping to remove the ReactiveValues completely from the codebase as it's not useful to us and caused more issues than it solved. 

In terms of what you've done, can you provide the type you want to it and see if that helps. `ReactiveValue<bool>(false)`.

We have slowly been moving away from it so it might have broken completely. 

What we do is call `notifyListeners` in the service when we want viewmodels listening to it to rebuild. This way we control exactly when the rebuild happens.

**Comment by araujocarlosm** [comment]
> Hi @araujocarlosm I'm hoping to remove the ReactiveValues completely from the codebase as it's not useful to us and caused more issues than it solved.
> 
> In terms of what you've done, can you provide the type you want to it and see if that helps. `ReactiveValue<bool>(false)`.
> 
> We have slowly been moving away from it so it might have broken completely.
> 
> What we do is call `notifyListeners` in the service when we want viewmodels listening to it to rebuild. This way we control exactly when the rebuild happens.

Thanks for your feedback, doesn't work in my case, but it's ok, I'll use notifyListeners() if needed.

**Comment by FilledStacks** [comment]
Duplicate of #265 . We'll be adding proper ReactiveService -> ListenableService documentation
