### ISSUE TITLE
Retry button

### ISSUE THREAD

**Issue by Andreigr0** [Stacked-Org/stacked#77]
How to implement Retry button functionality?

I've tried like so, but nothing happens. There is a stack trace of the exception in console and no print `There should be an error`
```dart
class FutureExampleViewModel extends FutureViewModel<String> {
  @override
  Future<String> get future => getDataFromServer();

  Future<String> getDataFromServer() async {
    await Future.delayed(const Duration(seconds: 3));
    throw Exception('This is an error');
  }

  @override
  void onError(error) {
    print('There should be an error');
  }

  @override
  Future<String> futureToRun() {
    return future;
  }
}

class FutureExampleView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder<FutureExampleViewModel>.reactive(
      viewModelBuilder: () => FutureExampleViewModel(),
      builder: (context, model, child) {
        Widget body;

        if (model.hasError) {
          body = Text('Error ${model.error}');
        } else if (model.isBusy) {
          body = CircularProgressIndicator();
        } else {
          body = Text('Success');
        }

        return Scaffold(
          appBar: AppBar(
            title: const Text('Future Example'),
          ),
          body: Center(child: body),
          floatingActionButton: FloatingActionButton(
            onPressed: () async {
              await model.getDataFromServer();
            },
          ),
        );
      },
    );
  }
}
```

**Comment by FilledStacks** [comment]
I simply call model.initialise again for a future viewmodel and it runs everything that i put in there.

**Comment by Andreigr0** [comment]
Okay, how to start FutureViewModel only by triggering something like button click when I send login data and not automatically?
And how to show dialog or snackbar by some event like BlocListener?

**Comment by FilledStacks** [comment]
`FutureViewModel` is for a `ViewModel` that's dependent on the data to be returned before the view can be used that's why it's stored in the data property. You don't need to use a FutureViewModel for a normal future. You can simple use a `BaseViewModel` and call your future in a normal function that returns a future and that's marked async.

**Comment by Andreigr0** [comment]
So, is there an analog of the BlocListener?

**Comment by FilledStacks** [comment]
@Andreigr0 Excuse my ignorance, i don't know what that sentence means.

**Comment by Andreigr0** [comment]
@FilledStacks it allows to perform some actions triggered by some events. For example, when user successfully logged in, it may show a snackbar or move to another page

**Comment by FilledStacks** [comment]
@Andreigr0 I've never required that in production so it's most likely not built into production. when I want to do that I listen to the event stream and just call snackbarService.show() or navigationService.navigateTo() where i listen to the event. 

Never had to to anything special for that functionality to work.
