### ISSUE TITLE
Form hasValue check not good enough

### ISSUE THREAD

**Issue by FilledStacks** [Stacked-Org/stacked#773]
Rignt now the check to see if the user has entered any text into a text field is

```dart
bool get hasServiceName => this.formValueMap.containsKey(ServiceNameValueKey);
```

This is not good enough as the value can still be empty and return true. This needs to be updated to something that also checks if the string is empty.

**Comment by ferrarafer** [comment]
@FilledStacks This issue can be closed, right?

**Comment by FilledStacks** [comment]
Yes
