### ISSUE TITLE
Share view model betweeen several views and share data?

### ISSUE THREAD

**Issue by ktkanishka** [Stacked-Org/stacked#779]
Thank you for the great package. I'm using this package in one of my project and currectly having issue with passing data between screen. I'm using same view model for 2 screens.

screen 1 : email and code
viewmodel1: navigate to screen 2

screen 2: need screen 1 email
viewmodel1: using same view model (viewmodel1) and trying to get/access email (variable) set in screen 1.

I used but with no luck. 
// When the disposeViewModel is set to false the ViewModel will
// not be disposed during the normal life cycle of a widget.
disposeViewModel: false,

// Tell the ViewModelBuilder to only fire the initialise function once
initialiseSpecialViewModelsOnce: true,

Any advice on achieving this without using 2 view models? If you need more information please let me know.  Thanks in advance.

**Comment by FilledStacks** [comment]
Hey, you're very welcome :) 

1. You shouldn't use the same viewmodel for two different screens unless they have the exact same state requirements. 

2. To pass data to a view you pass it when you navigate using the ViewArguments that's generated for you

3. To share data between viewmodel you put it in a service then both has access to the same data

**Comment by ktkanishka** [comment]
Thank you @FilledStacks for quick reply and support for the community.
