### ISSUE TITLE
Ideal method for including streamed lists in stacked architecture?

### ISSUE THREAD

**Issue by Quesajo17** [Stacked-Org/stacked#780]
I'm a little confused on how to handle elements of a ViewModel that come from `Stream<List<T>>`. Example would be returning data from a Firestore `SnapshotListener`.

Many of my views show lists of documents from Firebase, and my common implementation using the stacked package is like so:

(For an example of how this would look in a task to-do app):
I have a widget that shows a list of all my incomplete tasks (coming from firebase):

1. `MyTaskPageViewModel` is a ViewModel for a page that shows my tasks in a to-do list app. 
2. I have a stream in a Firebase Service that is a snapshot listener subscribed to a query of all my incomplete tasks (so it should update anytime I complete or add new tasks).
3. Within the ViewModel, I have another stream that transforms that Firebase stream into a list of `List<TaskViewModel>`
4. The page view is a ViewModelBuilder widget, with a StreamBuilder that listens to the Stream within the ViewModel, and returns a list of individual task views (which are each comprised of a `ViewModelBuilder` tied to the individual `TaskViewModel`).

I stumbled upon this package because it seemed most similar to what I was used to in SwiftUI, where I would create @ObservableObject ViewModels and most of the state management came for free with that.

This process has worked so far, but it seems like duplicative work to have the `Stream` within the `ViewModel`, since both would publish changes to the appropriate widgets.

Is this an ideal way to be handling ViewModels that are getting other data from Streams, or am I missing some other method that would be more ideal under this architecture?

**Comment by FilledStacks** [comment]
Hi, yes there is. I use the [StreamViewModel](https://pub.dev/packages/stacked#streamviewmodel) in those cases. 

Data will be stored in a typed value called `data` and the UI will rebuild when a new value is emitted. It will also unsubscribe automatically and dispose of the stream subscription when the widget/view is removed from the widget tree.

**Comment by Quesajo17** [comment]
Thank you @FilledStacks. And just to confirm, there's no issue with those streams being initialized inside my regular ViewModel is there? (It seems to work fine, but I just want to make sure there aren't any performance issues/considerations with that).

Thanks,
Charlie

**Comment by FilledStacks** [comment]
@Quesajo17 no, there's no issue with that. I use the MultiStreamViewModel with maaaaany streams 😄  and it works perfectly fine at very high framerates. 

Happy I could help. I'll close this issue.
