### ISSUE TITLE
Implementing a route aware widget

### ISSUE THREAD

**Issue by coruscant187** [Stacked-Org/stacked#790]
I am facing a problem with navigation. My goal is to set variables of widgets based on the current route from the `NavigationService`. 

I am using a `ListView` with `ListTile` elements, where a `ListTile` should be enabled if the current route is a specific route. 

Current View:
```dart
enum NavigationItems {
  projects,
  tasks,
}

class NavigationDrawerView extends StatefulWidget {
  const NavigationDrawerView({super.key});

  @override
  NavigationDrawerViewState createState() => NavigationDrawerViewState();
}

class NavigationDrawerViewState extends State<NavigationDrawerView> {
  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder<NavigationDrawerViewModel>.reactive(
        viewModelBuilder: () => NavigationDrawerViewModel(),
        builder: (context, viewModel, child) {
          return ListView(
            children: [
              ListTile(
                title: const Text('Projects'),
                onTap: () async {
                  viewModel.handleNavigation(NavigationItems.projects.index);
                },
                selected: viewModel.currentRoute == ContentBaseViewRoutes.projectView,
              ),
              ListTile(
                title: const Text('Tasks'),
                onTap: () async {
                  viewModel.handleNavigation(NavigationItems.tasks.index);
                },
                selected: viewModel.currentRoute == ContentBaseViewRoutes.taskView,
              ),
            ],
          );
        });
  }
}
```
Current ViewModel:
```dart
class NavigationDrawerViewModel extends BaseViewModel {
  final NavigationService _navigationService = locator<NavigationService>();

  String get currentRoute => _navigationService.currentRoute;

  void handleNavigation(int index) {
    if (index == NavigationItems.projects.index) {
      navigateToProjects();
    }
    if (index == NavigationItems.tasks.index) {
      navigateToTasks();
    }
  }

  navigateToProjects() {
    notifyListeners();
    _navigationService.navigateTo(
      ContentBaseViewRoutes.projectView,
      id: contentNavigationId,
    );
  }

  navigateToTasks() {
    notifyListeners();
    _navigationService.navigateTo(
      ContentBaseViewRoutes.taskView,
      id: contentNavigationId,
    );
  }
}
```
I have added the route observer to the `MaterialApp` and `ExtendedNavigator` as mentioned in the documentation. [https://pub.dev/packages/stacked_services#route-observation](https://pub.dev/packages/stacked_services#route-observation)
```dart
MaterialApp(
  home: const SplashScreenView(),
  navigatorKey: StackedService.navigatorKey,
  onGenerateRoute: StackedRouter().onGenerateRoute,
  navigatorObservers: [StackedService.routeObserver],
),

ExtendedNavigator(
  navigatorKey: StackedService.nestedNavigationKey(contentNavigationId),
  initialRoute: ContentBaseViewRoutes.projectView,
  router: ContentBaseViewRouter(),
  observers: [StackedService.routeObserver],
),
```

This only works if the `ListTile` elements are tapped directly. But as soon as for example navigationService.back() is called or if a different View is called onto the navigation stack from another ViewModel, then the current route is not updated.

The [Flutter documentation](https://api.flutter.dev/flutter/widgets/RouteObserver-class.html) has an example where they implement the `RouteAware` class in a widget's state and subscribe it to the `RouteObserver`:
```dart
// Register the RouteObserver as a navigation observer.
final RouteObserver<ModalRoute<void>> routeObserver = RouteObserver<ModalRoute<void>>();
void main() {
  runApp(MaterialApp(
    home: Container(),
    navigatorObservers: <RouteObserver<ModalRoute<void>>>[ routeObserver ],
  ));
}

class RouteAwareWidget extends StatefulWidget {
  const RouteAwareWidget({super.key});

  @override
  State<RouteAwareWidget> createState() => RouteAwareWidgetState();
}

// Implement RouteAware in a widget's state and subscribe it to the RouteObserver.
class RouteAwareWidgetState extends State<RouteAwareWidget> with RouteAware {

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    routeObserver.subscribe(this, ModalRoute.of(context)!);
  }

  @override
  void dispose() {
    routeObserver.unsubscribe(this);
    super.dispose();
  }

  @override
  void didPush() {
    // Route was pushed onto navigator and is now topmost route.
  }

  @override
  void didPopNext() {
    // Covering route was popped off the navigator.
  }

  @override
  Widget build(BuildContext context) => Container();

}
```

How can this be realized with the `StackedService.routeObserver` so that I can subscribe to value changes of the `routeObserver` and let the `ListTile` be updated when for example `navigationService.back()` is called?

**Comment by FilledStacks** [comment]
Hey, this is working as expected. 

I think the problem is that your view is not being rebuilt when you tap the back navigation key. To fix this you have to call `notifyListeners` after you navigate. 

All navigations in Flutter are Future's so you can simply await them and they will complete once replaced or removed from the stack (back tapped). Change your code to:

```dart
  Future<void> navigateToProjects() async {
   await _navigationService.navigateTo(
      ContentBaseViewRoutes.projectView,
      id: contentNavigationId,
    );
    notifyListeners();
  }

   Future<void> navigateToTasks() async {
    await _navigationService.navigateTo(
      ContentBaseViewRoutes.taskView,
      id: contentNavigationId,
    );
    notifyListeners();
  }
```

**Comment by coruscant187** [comment]
Thank you. 

The navigation items now change accordingly after refactoring my code to your solution. But this only works when navigating from the ViewModel `NavigationDrawerViewModel`. 

I have another ViewModel `WindowBarViewModel` which calls the following method: 
```dart
navigateBack() {
    _navigationService.back(
        id: contentNavigationId,
    );
}
```

I want to update the UI components of `NavigationDrawerView` after navigating back through calling this method.

How can I trigger `notifyListeners()` inside the ViewModel `WindowBarViewModel` for the ViewModel `NavigationDrawerViewModel`? Is this even intended to be done this way with Stacked, or do I need a Service for this?

Happy New Year!

**Comment by coruscant187** [comment]
I have managed to solve my issue by building a service `CurrentRouteService` and extending the two mentioned ViewModels with `ReactiveViewModel` according to the [documentation](https://pub.dev/packages/stacked#reactivity).

Modified `NavigationDrawerViewModel`:
```dart
class NavigationDrawerViewModel extends ReactiveViewModel {
  final NavigationService _navigationService = locator<NavigationService>();
  final _currentRouteService = locator<CurrentRouteService>();
  
  @override
  List<ReactiveServiceMixin> get reactiveServices => [_currentRouteService];

  String get currentRoute => _currentRouteService.currentRoute;

  navigateToProjects() {
    _navigationService.navigateTo(
      ContentBaseViewRoutes.projectView,
      id: contentNavigationId,
    );
    _currentRouteService.setCurrentRoute(ContentBaseViewRoutes.projectView);
  }

  navigateToTasks() {
    _navigationService.navigateTo(
      ContentBaseViewRoutes.taskView,
      id: contentNavigationId,
    );
    _currentRouteService.setCurrentRoute(ContentBaseViewRoutes.taskView);
  }
}
```

Modified `WindowBarViewModel `:
```dart
class WindowBarViewModel  extends ReactiveViewModel {
  final NavigationService _navigationService = locator<NavigationService>();
  final _currentRouteService = locator<CurrentRouteService>();

  @override
  List<ReactiveServiceMixin> get reactiveServices => [_currentRouteService];

  String get currentRoute => _currentRouteService.currentRoute;

  navigateBack() {
    _navigationService.back(
      id: contentNavigationId,
    );
    _currentRouteService.setCurrentRoute(_navigationService.currentRoute);
  }
}
```

New `CurrentRouteService`:
```dart
import 'package:stacked/stacked.dart';

class CurrentRouteService with ReactiveServiceMixin {
  String _currentRoute = "";

  String get currentRoute => _currentRoute;

  void setCurrentRoute(String route) {
    _currentRoute = route;
    notifyListeners();
  }
}
```

Now every time navigating through routes the method `_currentRouteService.setCurrentRoute()` is called. 
This works, but I am not quite sure if this is the intended way of solving the issue.

**Comment by FilledStacks** [comment]
That is a solution we would use as well. 

In our code, because we always know when we navigate, meaning, we write the code for the navigation, we can always await that call and notify the listeners when the navigation is complete. 

In the case where you don't have the navigation call for some reason then using a reactive service work. This brings up the point that we could probably just make the navigation service a reactive service and notify listeners when the route changes.

**Comment by coruscant187** [comment]
Thank you. Making the navigation service a reactive service and notifying listeners when the route changes would definitely help in my use case.
