### ISSUE TITLE
A few nice things to have

### ISSUE THREAD

**Issue by jalvespinto** [Stacked-Org/stacked#792]
I am just starting to use stacked and I am really enjoying it. tks for doing that! Previously I was using code I got from [https://github.com/Kavantix/hn_state_example.git](url), which has a similar approach, and I think there are a few good things there that seems easy to implement here. I say 'seems' because I am kinda new to programming and so I might be missing some stuff. 
For example, the view model builder has some optional params like `loaderBuilder, errorBuilder, showLoader, showError` that simply reflects on the build method, but it makes it easier to deal with those situations:
```
  @override
  Widget build(BuildContext context) {
    _model.refreshProvided(context);
    return (widget.showLoader ?? false || widget.showError ?? false)
        ? AnimatedSwitcher(
            duration: const Duration(milliseconds: 330),
            child: _model.isLoading && (widget.showLoader ?? false)
                ? widget.loaderBuilder?.call(context) ??
                    const Center(
                      child: CircularProgressIndicator(),
                    )
                : _model.hasError && (widget.showError ?? false)
                    ? widget.errorBuilder?.call(context, _model) ??
                        ConnectionErrorIndicator(model: _model)
                    : widget.builder(context, _model, widget.child),
          )
        : widget.builder(context, _model, widget.child);
  }

class ConnectionErrorIndicator extends StatelessWidget {
  final BaseModel model;
  final double topPadding;

  const ConnectionErrorIndicator({
    Key key,
    @required this.model,
    this.topPadding = 24,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          SizedBox(height: topPadding),
          const Icon(Icons.error),
          const SizedBox(height: 16),
          Text(
            Strings.of(context).errors.failedLoading,
            textAlign: TextAlign.center,
          ),
          ElevatedButton(
            onPressed: model.retryLoading,
            child: Text(Strings.of(context).errors.tryAgain),
          ),
        ],
      ),
    );
  }
}
```
Also, as you can see from about, the base model that extends changenotifer has a `retryLoading` method:
```
abstract class BaseModel extends ChangeNotifier implements Providable {
  bool _isLoading = false;
  bool get isLoading => _isLoading;

  bool _hasError = false;
  bool get hasError => _hasError;

  VoidCallback _retryCallback;

  var _isDisposed = false;

  bool startLoading() {
    if (isLoading || hasError) return false;
    _isLoading = true;
    notifyListeners();
    return true;
  }

  void doneLoading() {
    assert(isLoading);
    _isLoading = false;
    notifyListeners();
  }

  void loadingFailed(VoidCallback retryCallback) {
    assert(isLoading);
    _retryCallback = retryCallback;
    _isLoading = false;
    _hasError = false;
    notifyListeners();
  }

  void retryLoading() {
    if (!hasError || _retryCallback == null) return;
    _hasError = false;
    _retryCallback();
    _retryCallback = null;
    notifyListeners();
  }

  @override
  @mustCallSuper
  void notifyListeners() {
    if (_isDisposed) return;
    super.notifyListeners();
  }

  @override
  @mustCallSuper
  void dispose() {
    _isDisposed = true;
    super.dispose();
  }

  @override
  void refreshProvided(BuildContext context) {}

  bool get usesAppLifecycle => false;

  void didChangeAppLifecycleState(AppLifecycleState state) {}
}
```

**Comment by FilledStacks** [comment]
@jalvespinto Thank you very much for using stacked. I really appreciate it. Do you mind if I ask you where you work with Stacked or if you're an individual free lancer. I want to get an accurate list of the active Stacked users to I can setup some private chats for us. 

In terms of the feature, We have also thought about this. It's definitely a feature we'd want to add.

We're trying to ensure that the implementation applies to more than 1 scenario. Right now with the implementation above you swap out the entire UI for new UI that shows loading. This means, for example, you can't do simple things like only set a button to a loading state and gray out the text on screen while that's happening. 

We are thinking about this, I will keep this open as a feature request and we'll continue the discussion here when we finish some of the docs and choose some new features to work on.

**Comment by jalvespinto** [comment]
I am using stacked on a personal project. I wouldn't use those features all the time, but since it is a optional parameter it seemed something nice to have and easy to implement. Like the retry. And like I said I don't have much experience, I got into coding about an year ago, but let me know if I can help in any way.

**Comment by FilledStacks** [comment]
## Feature

- We want to provide a built-in way for Stacked users to render loading / busy states in the UI
- We want to provide a built-in way for Stacked users to render error states in the UI

## Research
- [ ] Look at how Svelte does this
- [ ] Look at how Next.js does this
- [ ] Look at how VueJs does this

If either of the patterns used in those frameworks is a better fit. Update the requirements below to match or include that implementation. Else we can use the requirements below to guide our API design. 

## Requirements 
- We want to be able to use loading states as a part of the larger render view
- We want to be able to use error states as a part of the larger render view
- The loading UI should be built and rendered based on the ViewModel properties
- The error UI should be built and rendered based on the ViewModel properties

**Comment by FilledStacks** [comment]
This turned out not to be too important
