### ISSUE TITLE
[stacked_services] showSnackbar does not use same SnackbarConfig fields as showCustomSnackBar

### ISSUE THREAD

**Issue by TrentStarky** [Stacked-Org/stacked#798]
When using a default snack bar via the showSnackbar method the following SnackbarConfig values are not used: 
- icon
- maxWidth
- padding
- borderRadius
- borderColor
- borderWidth
- leftBarIndicatorColor
- boxShadows
- backgroundGradient
- dismissDirection
- showProgressIndicator
- progressIndicatorController
- progressIndicatorBackgroundColor
- progressIndicatorValueColor
- snackStyle
- forwardAnimationCurve
- reverseAnimationCurve
- animationDuration
- overlayBlur
- overlayColor
- userInputForm

It would be nice to be able to set these values using SnackbarConfig and have them apply to the basic showSnackbar without having to create a custom snack bar.

**Comment by FilledStacks** [comment]
Merging this in when it's ready
