### ISSUE TITLE
Order changelogs by latest

### ISSUE THREAD

**Issue by chimon2000** [Stacked-Org/stacked#8]
Generally, it's considered a best practice to organize changelogs [latest first](https://keepachangelog.com/en/1.0.0/).  

Most changelogs in pub read most recent first, however stacked reads in reverse.

This means that if you're subscribing to pub changes via an RSS reader, or just viewing the changes on pub.dev, you will always have to scroll to see the latest version.

![Screenshot_20200426-104830~2](https://user-images.githubusercontent.com/6907797/80311214-63666100-87ac-11ea-8663-d7f18f2e9017.jpg)

**Comment by FilledStacks** [comment]
Good observation. I'll update that a bit later when I get some time.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by FilledStacks** [comment]
Donezo. I'm not that great when it comes to things like this but now I know.
