### ISSUE TITLE
Stacked Services - issue with navigateToView

### ISSUE THREAD

**Issue by elhe26** [Stacked-Org/stacked#80]
This function will give us an error:

```dart
 /// Pushes [view] onto the navigation stack
  Future<dynamic> navigateToView(Widget view, {dynamic arguments}) {
    return Get.to(view, arguments: arguments);
  }
```

`Get.to` function doesn't support arguments anymore.

**Comment by FilledStacks** [comment]
@elhe26 in v2.13.1 It's still available. I what version are you using?

**Comment by elhe26** [comment]
Sorry. My fork has `Get: 2.5.2` for stacked_services. Updating to catch up.
