### ISSUE TITLE
Stacked Cli - update create app template - dialogs/bottomsheets to make use of @StackedApp

### ISSUE THREAD

**Issue by rsenthilkumar6** [Stacked-Org/stacked#804]
When creating a flutter project with stacked cli - the dialogs & bottomsheets are not configured via @StackedApp - instead they are present inside ui/setup 

`@StackedApp(
  dialogs: [
    // @stacked-dialog
    StackedDialog(classType: InfoAlertDialog),
  ],
  bottomsheets: [
    // @stacked-bottomsheet
    StackedBottomsheet(classType: NoticeSheet),
  ],`

**Comment by FilledStacks** [comment]
@ferrarafer has this functionality been merged in yet? 

If so please close.

**Comment by ferrarafer** [comment]
Not yet, is the next improvement on bottom sheets and dialogs that I want to do today.

**Comment by ferrarafer** [comment]
Feature added 🚀
