### ISSUE TITLE
CupertinoNavigationBarBackButton fires error when used with NavigationService

### ISSUE THREAD

**Issue by bryan-vh** [Stacked-Org/stacked#821]
I have an app created like so:

```
@StackedApp(routes: [
  CupertinoRoute(page: AppView, initial: true),
  CupertinoRoute(page: PhoneNumberView),
  CupertinoRoute(page: VerificationCodeView),
])
class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MediaQuery.fromWindow(
      child: CupertinoApp(
        useInheritedMediaQuery: true,
        theme: const CupertinoThemeData(),
        navigatorObservers: [StackedService.routeObserver],
        navigatorKey: StackedService.navigatorKey,
        initialRoute: Routes.appView,
        onGenerateRoute: StackedRouter().onGenerateRoute,
      ),
    );
  }
}
```

And a view that contains a navigator bar created like this: 

```
return ViewModelBuilder<AuthenticationViewModel>.nonReactive(
      viewModelBuilder: () => getIt.get<AuthenticationViewModel>(),
      builder: (context, model, child) => CupertinoPageScaffold(
        navigationBar: CupertinoNavigationBar(
          backgroundColor: CupertinoColors.systemBackground,
          border: null,
          padding: const EdgeInsetsDirectional.all(0),
          leading: CupertinoNavigationBarBackButton(
            color: CupertinoColors.label,
            // if I add this it works, but would prefer it work by default rather than using a custom widget
            // onPressed: () => Navigator.pop(context),
          ),
        ),
        child: ...
```

Yet when I try to navigate back / pop with a `CupertinoNavigationBarBackButton`, it throws this error: 

```
CupertinoNavigationBarBackButton should only be used in routes that can be popped
'package:flutter/src/cupertino/nav_bar.dart':
package:flutter/…/cupertino/nav_bar.dart:1
Failed assertion: line 1336 pos 9: 'currentRoute?.canPop ?? false'
```

I understand that if I attach a custom action to the back button it will no longer throw this error and perhaps that's the easiest fix, but I am wondering if there is anything that can be done to get this to work by default without throwing an error. I though adding the navigatorObserver in my app would resolve the issue, but that didn't seem to work.

**Comment by FilledStacks** [comment]
Hi, Thank you for the detailed issue. I appreciate it. 

Very interesting, I actually have never used that back button before. I always call either `.pop` or NavigationService.back depending on what my ViewModel inherited. 

I'll leave this open and we'll tend to it when some higher-priority items are completed. 

@ferrarafer you have any idea why this could be happening or why it's not picking up that there is a route to pop?

**Comment by ynnob** [comment]
@bryan-vh and @FilledStacks 
This error is not related to Stacked. See [Flutter #89888](https://github.com/flutter/flutter/issues/89888)
Your only option is to completly avoid setting the `CupertinoNavigationBarBackButton` or the page on the stack before the CuppertinoScaffold has to be a material Scaffold. Then you can also use the custom back button.

**Comment by FilledStacks** [comment]
Thanks @ynnob you're awesome. Closing this because it's a [Flutter issue](https://github.com/flutter/flutter/issues/89888)
