### ISSUE TITLE
ViewModelBuilder initializes FutureViewModel two times if onModelReady is specified

### ISSUE THREAD

**Issue by ynnob** [Stacked-Org/stacked#824]
Hey i am not sure if this is intended behavior but i just got stuck on this.
I noticed that my FutureViewModel calls the async method that is defined for futureToRun() two times. The reason was that i still had `onModelReady: (viewModel) => viewModel.initialise(),` in my ViewModelBuilder. Even if i set `fireOnModelReadyOnce: true` the ViewModel initializes two times.

As soon as i removed `onModelReady` the ViewModel gets initialized one time as expected. It was not clear to me that i can't use the combination of onModelReady and FutureViewModel.

I was using the following code:

**View**
```
class SkizzeView extends StatelessWidget {
  final String pkSchadensskizze;
  const SkizzeView({Key? key, required this.id}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder<SkizzeViewModel>.reactive(
        viewModelBuilder: () => SkizzeViewModel(pkSchadensskizze),
        onModelReady: (viewModel) => viewModel.initialise(),
        fireOnModelReadyOnce: true,
        builder: (context, viewModel, child) {
          return Scaffold(
              floatingActionButton: FloatingActionButton(
                child: Text(viewModel.counter.toString()),
                onPressed: () {},
              ),
              body: (viewModel.isBusy) ? const LoadingIndicator() : const Sheet());
        });
  }
}
```

**ViewModel**
```
class SkizzeViewModel extends FutureViewModel<void> {
  @override
  Future initialise() {
    return super.initialise();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Future<void> futureToRun() => load(id);

  Future<void> load(String id) async {}
}
```

**Comment by FilledStacks** [comment]
Hey, yes. That's intended. 

The `FutureViewModel` will automatically execute `futureToRun`. What you can do is change the name of the function you want to call in `onViewModelReady` and not use the initialise function. The initialise will be executed automatically.

**Comment by ynnob** [comment]
Ok. Thanks!
