### ISSUE TITLE
'stacked' is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by YassineJaaouan** [Stacked-Org/stacked#829]
After running this command "dart pub global activate stacked_cli" I add the path to the environment variables but he still not recognized the 'stacked' keyword.

![stackedCli](https://user-images.githubusercontent.com/45876688/212535350-ad5fe7bd-129d-4a5a-8fdd-ae9291c3c136.jpeg)

**Comment by FilledStacks** [comment]
Hi @YassineJaaouan 

Do you use powershell, gitbash or command line ?

**Comment by YassineJaaouan** [comment]
Hi @FilledStacks 
I use command line.

**Comment by FilledStacks** [comment]
I will check this out on Windows later today @YassineJaaouan

**Comment by ziqq** [comment]
I have this same issue

![image](https://user-images.githubusercontent.com/20646071/212683003-1c97a82e-b8d6-4e9e-a90b-98a822fd35ee.png)


Why cli installs on error path?

![image](https://user-images.githubusercontent.com/20646071/212683142-c17df33b-3297-4218-8cb9-d4f28442e9a8.png)

**Comment by ynnob** [comment]
@ziqq The path in the error message is not part of your PATH system enviroment vars.
Tbh i habe never seen such a messed up bin path but at some point your dart got told to use that as the installation folder. You should try and reinstall dart.

@YassineJaaouan did you restart the entire cmd/visual studio (not using window reload) or restart your pc? The path seems correct. For me it's working as it should.

**Comment by YassineJaaouan** [comment]
@ynnob I try both of them. I restart my pc and I restart the entire cmd but I still have the same problem.

**Comment by ynnob** [comment]
> dart pub global activate stacked_cli

Where did you add the variable? I just checked on my system and i have set the user enviroment variable path, not the system enviroment. And stacked is instantly recognized in cmd.

**Comment by YassineJaaouan** [comment]
Nice!
Can you please explain more to me and if you have any screen shots may you share them with me.
Thank you a lot.

**Comment by FilledStacks** [comment]
@ziqq yours was installed in `....\Local\Pub\Cache\bin\bin\bin` as it shows in your output. Add that to your path variable and see if it's recogized

**Comment by YassineJaaouan** [comment]
@FilledStacks what about me ! I still have the same problem

**Comment by acbasco** [comment]
@FilledStacks I have a different issue. I installed the cli using git bash then I updated the environment path.
The stacked command is not recognized when I use Git Bash but it works on Windows command prompt.

Using Git Bash
![image](https://user-images.githubusercontent.com/89009668/213118483-009df17c-005a-425a-98d1-4fc50450b39e.png)

Using Windows Command Prompt
![image](https://user-images.githubusercontent.com/89009668/213118620-6f0c551b-8b49-4aaa-a7ba-77a5c33b0226.png)

**Comment by YassineLOGAWIN** [comment]
@acbasco I have the same issue.

**Comment by ynnob** [comment]
@acbasco @YassineLOGAWIN 
You can't use commands in a bash like that. In this case you need to specify the extension if you want to use git bash:
`stacked.bat` will work if your path is set correctly!

![melos](https://user-images.githubusercontent.com/34171562/213175293-abea68bb-fd92-4c02-972c-3198d06c1891.png)

see: https://stackoverflow.com/questions/10681101/git-bash-doesnt-see-my-path

There are some ways do work around this but you should figure that out for yourself.

**Comment by YassineLOGAWIN** [comment]
@ynnob Thank you for sharing it works fine for me when I used stacked.bat, but still need to be fixed.

**Comment by ynnob** [comment]
> @ynnob Thank you for sharing it works fine for me when I used stacked.bat, but still need to be fixed.

No problem. 

He can't fix that. That's the way the bash works and since the bash is not native to windows you need to to create an alias for the bash yourself. Then you can use it like you would in a command prompt.

**Comment by YassineLOGAWIN** [comment]
@ynnob Thank you a lot but I would like to know if I was in the case of @YassineJaaouan how can I fix it, because I see that all the steps are correct but he still have the same problem.

**Comment by FilledStacks** [comment]
@ynnob thank you for providing solutions to these questions. Windows does make things difficult sometimes. But we can't do anything besides have some trouble shooting guides that people can follow to try debug their situation.


@YassineJaaouan We've tried to reproduce. Because stacked is installed by dart, into windows, we don't have any control over where, how and with which alias it gets installed. 

I will keep this open and if I find instructions that you can follow I will post it here. It works on the windows machines that we have tested on, so it's a bit hard to debug right now.

**Comment by YassineJaaouan** [comment]
@FilledStacks Thanks a lot for your response and I will be waiting for your return. By the way, I try to deactivated and reactivated but I still have the same issue also I try to execute  the file directly and it crushed automatically.

**Comment by ynnob** [comment]
> @FilledStacks Thanks a lot for your response and I will be waiting for your return. By the way, I try to deactivated and reactivated but I still have the same issue also I try to execute  the file directly and it crushed automatically. 

Do other cli packages work? I get the feeling that your path is not configured correctly.

Can you try to install the dart package 'melos' for example and check if you can access that command?

**Comment by YassineJaaouan** [comment]
@ynnob good idea, I will check it and return with answer soon. Thank you @ynnob for your time I really appreciated.

**Comment by FilledStacks** [comment]
@ynnob thanks for being so involved! I appreciate it. Good to see others on the project as we're trying to grow.

**Comment by KingCosmic** [comment]
Just ran into this same issue attempting to get started with stacked, looking at my pub cache it seems `stacked.bat` doesn't exist in the folder, there is something similar labeled `st_cli.bat` which I thought was perhaps a misnamed version? but running it didn't seem to alleviate my issues. My second attempt was to install it on a terminal in admin mode but I got the same results, any ever fix this??

**Comment by FilledStacks** [comment]
@KingCosmic we don't control the install location. You'll have to check where your package was installed. The terminal will output the install location for you.

**Comment by ferrarafer** [comment]
Is anyone still having this problem? If not, we will proceed to close the thread as it does not seem to be a bug in the package.
