### ISSUE TITLE
Updating data of parent viewmodel when its child's viewmodel data is changed

### ISSUE THREAD

**Issue by MickelAngel0** [Stacked-Org/stacked#83]
I have 2 widgets, widget A with its own view model which only displays the data and to modify the data I have another page(or widget B) with its own view model.
What I want is when data is changed in widget B then the same changed data should reflect in previous page(or widget A).
The data is quite big so I'm using map function for this.
I tried to do the same task with RxValue from observable_ish pacakage as your video suggests but it doesn't work. This package also has RxMap function but it was not working.
I searched a lil bit and found that the reactive mixin function doesn't have any event notifier for RxMap or RxSet.
Can you please update it so as to support RxMap or RxSet.
Or please help me with other widget builders.

Objective:
- I have 2 separate widgets with there own viewmodels 
- when data is changed in widget B it should reflect the same in widget A but this widgets are not built on same view 
- widget A will be stacked in navigation route stack when widget B is active
- RxMap is not working currently so I want alternative for it or please update the code so that RxMap also works

If possible can you please provide a simple code using map object.i know this type of example is already available in your videos but as my data is quite big I can't use RxValue as shown in videos
So please if possible give a simple example with 2 widgets with there individual viewmodels and sync data between this widgets

**Comment by FilledStacks** [comment]
I give a simple example in my videos [Using a service](https://youtu.be/hEy_36LPcgQ?t=702). You can also simply call notifyListeners in your service and if the viewmodel passes it in as one of the reactive services it will rebuilt that viewmodels ui.

**Comment by MickelAngel0** [comment]
> I give a simple example in my videos [Using a service](https://youtu.be/hEy_36LPcgQ?t=702). You can also simply call notifyListeners in your service and if the viewmodel passes it in as one of the reactive services it will rebuilt that viewmodels ui.

I have seen all your videos n yes it does work
But it does not work for map objects 
RxMap object

**Comment by MickelAngel0** [comment]
> > I give a simple example in my videos [Using a service](https://youtu.be/hEy_36LPcgQ?t=702). You can also simply call notifyListeners in your service and if the viewmodel passes it in as one of the reactive services it will rebuilt that viewmodels ui.
> 
> I have seen all your videos n yes it does work
> But it does not work for map objects 
> RxMap object
> 
> 

And my actual problem is 
When I'm navigating back to previous view then I'm not geting the data 

What I want is child viewmodel should edit the data and this edited data should be displayed in parent view when I'm navigating back
So please help

**Comment by FilledStacks** [comment]
Yep RxMap is just a normal map in the observable_ish library. Only RxValue and List works. You can simply call notifyListeners in the service after changing your map. that should work as well. Make sure you're on the latest version that functionality was added recently.

**Comment by MickelAngel0** [comment]
> Yep RxMap is just a normal map in the observable_ish library. Only RxValue and List works. You can simply call notifyListeners in the service after changing your map. that should work as well. Make sure you're on the latest version that functionality was added recently.

i tried this but still its not working.
this is the link to my github https://github.com/MickelAngel0/Dart.git
can you please go through it and please help me where im going wrong
Please Help
Thank you

**Comment by FilledStacks** [comment]
You're not passing in the reactive service to any of the viewmodels? Did you watch the video I linked because I show how to do it in there.
