### ISSUE TITLE
Old docs link is broken

### ISSUE THREAD

**Issue by JaidynBluesky** [Stacked-Org/stacked#830]
https://github.com/FilledStacks/stacked/blob/master/README_old.md doesn't appear to be linked correctly, leads to a 404 page.

**Comment by FilledStacks** [comment]
Thanks for the heads up @JaidynBluesky let me fix that.

**Comment by FilledStacks** [comment]
@JaidynBluesky updated and working. Thanks for filing an issue 🤝

**Comment by JaidynBluesky** [comment]
Appears to be broken again.

https://github.com/FilledStacks/stacked/blob/master/packages/stacked/README_old.md
