### ISSUE TITLE
[stacked_cli] error when deleting service 

### ISSUE THREAD

**Issue by JeetChhatrala** [Stacked-Org/stacked#833]
modification are not getting removed from `app.dart` file when using stacked cli to delete service

**Comment by FilledStacks** [comment]
Interesting. Are you using windows or Mac?

**Comment by JeetChhatrala** [comment]
I am on Ubuntu 22.04 using stacked_cli 1.1.6

**Comment by JeetChhatrala** [comment]
![image](https://user-images.githubusercontent.com/75415216/213514272-942db9aa-578c-45ab-b6e7-1e8aaacf9fd9.png)

in this image i create test service using cli and also trying to delete it using cli

creating and deleting works for view, just failing on service.

**Comment by FilledStacks** [comment]
I see. Thanks for the details @JeetChhatrala we'll look at this in the week
