### ISSUE TITLE
How can I have nested locators?

### ISSUE THREAD

**Issue by jalvespinto** [Stacked-Org/stacked#838]
Is it possible to reach the state below using the generator?
```
  locator.registerLazySingleton(() => ComparablesRepository());
  locator.registerFactoryParam<ComparableProduct, Product?, dynamic>(
      (param1, param2) =>
          ComparableProduct(param1, locator<ComparablesRepository>()));
```

**Comment by FilledStacks** [comment]
Mmmmmmm, I don't think so @jalvespinto 

We don't have the notion os scoped locators at the moment so it's all registered in the same place.

**Comment by FilledStacks** [comment]
Closing because this is not supported.
