### ISSUE TITLE
[stacked_cli] Respect Opt-out/Opt-in for Google Analytics

### ISSUE THREAD

**Issue by ynnob** [Stacked-Org/stacked#839]
Hey!

Since you are using the `usage`-Package for Google Analytics you should follow the Opt-out/Opt-in convention like stated in the documentation:

### When do we send analytics data?

```
You can use this library in an opt-in manner or an opt-out one. It defaults to opt-out - 
data will be sent to Google Analytics unless the user explicitly opts-out. 
The mode can be adjusted by changing the value of the Analytics.analyticsOpt field.

Opt-out In opt-out mode, if the user does not explicitly opt-out 
of collecting analytics, the usage library will send usage data.

Opt-in In opt-in mode, no data will be sent until the user explicitly opt-in to collection. 
This includes screen views, events, timing information, and exceptions.
```

I think it is ok to use it as an opt-out but i would like to see a setting, maybe in your config file to deactivate it. I would not use the cli in a company enviroment atm.

**Comment by FilledStacks** [comment]
dooooope! I will review and merge soon @ferrarafer
