### ISSUE TITLE
Passing down view model to child widgets?

### ISSUE THREAD

**Issue by bryan-vh** [Stacked-Org/stacked#845]
I've been really enjoying using this library so far, but I have one question about how to properly handle reusing a view model in private child widgets of a parent widget. In this case, I have the following:

```
class NameView extends StackedView<OnboardingViewModel> {
  const NameView({super.key});

  @override
  Widget builder(BuildContext context, OnboardingViewModel viewModel, Widget? child) {
    return child: Column(
        children: [
          Text("What's your name?")
          const Spacer(),
          _FirstNameTextField(),
          const SizedBox(height: 16),
          _LastNameTextField(),
        ],
      );
  }
}

class _FirstNameTextField extends ViewModelWidget<OnboardingViewModel> {
  @override
  Widget build(BuildContext context, OnboardingViewModel viewModel) {
    return TextField(
      onChanged: (value) => viewModel.setFirstName(firstName: value),
      ),
    );
  }
}

class _LastNameTextField extends ViewModelWidget<OnboardingViewModel> {
  @override
  Widget build(BuildContext context, OnboardingViewModel viewModel) {
    return TextField(
      onChanged: (value) => viewModel.setLastName(lastName: value),
      ),
    );
  }
}

```

What I'm struggling with is trying to determine how to let the child widgets (_FirstNameTextField and _LastNameTextField) receive the correct view model and update it without having to create a standalone view model for each of these widgets (which would be a lot of extra boilerplate). I don't know if this is the proper way to do it as the new docs (and old docs) don't specify clearly on how to pass down the view model. Any help / guidance would be really helpful as I seem to be getting stuck on the appropriate way to do this.

**Comment by FilledStacks** [comment]
@bryan-vh that is the way that we do it and recommend to do it.  

If you don't want the boilerplate and want to use a pure stateless widget you can use `getParentViewModel< OnboardingViewModel>` and it'll return the model which you can use as you please. 

Sorry about the lack of documentation, I'm busy doing videos for the channel and struggling to get to the docs for Stacked. trying to get back into the video production is proving time consuming :D
