### ISSUE TITLE
Error: No named parameter with the name 'vsync'.

### ISSUE THREAD

**Issue by Khaled-mohamed-dev** [Stacked-Org/stacked#855]
: Error: No named parameter with the name 'vsync'.
../…/ui/skeleton_loader.dart:106
                  vsync: this,
                  ^^^^^

I'm using flutter latest update with stacked, and I'm getting this error that stops the app from opening.
I had to comment out this line 
 vsync: this, in ../…/ui/skeleton_loader.dart:106
 
 for it to work.

**Comment by FilledStacks** [comment]
@Khaled-mohamed-dev interesting. Thank you. We will take a look.

**Comment by csandovalgt** [comment]
any news about this error? I'm able to reproduce it

**Comment by FilledStacks** [comment]
That's great @csandovalgt can you please generate a stacked project, reproduce it and share the repo with us. We can't reproduce on our side. That would help a lot in fixing this.

**Comment by Al-Krause-ex** [comment]
I have the same problem.

### Errors:
_pub.dev/stacked-3.2.0/lib/src/view_models/ui/skeleton_loader.dart:106:19: Error: No named parameter with the name 'vsync'.
                  vsync: this,
                  ^^^^^_
_lib/src/widgets/animated_size.dart:28:9: Context: Found this candidate, but the arguments don't match.
  const AnimatedSize({
        ^^^^^^^^^^^^_

### My code:
**lib/core/app/routes.dart**
`import 'package:stacked/stacked_annotations.dart';
import 'package:todos_frontend/presentation/show_todos/show_todos_view.dart';

@StackedApp(routes: [
  AdaptiveRoute(page: ShowTodosView, initial: true),
])
class App {}`

**generated routes.router.dart**
`// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// StackedNavigatorGenerator
// **************************************************************************

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter/material.dart';
import 'package:stacked/stacked.dart' as _i1;
import 'package:stacked_services/stacked_services.dart' as _i3;
import 'package:todos_frontend/presentation/show_todos/show_todos_view.dart'
    as _i2;

class Routes {
  static const showTodosView = '/';

  static const all = <String>{showTodosView};
}

class StackedRouter extends _i1.RouterBase {
  final _routes = <_i1.RouteDef>[
    _i1.RouteDef(
      Routes.showTodosView,
      page: _i2.ShowTodosView,
    )
  ];

  final _pagesMap = <Type, _i1.StackedRouteFactory>{
    _i2.ShowTodosView: (data) {
      return _i1.buildAdaptivePageRoute<dynamic>(
        builder: (context) => const _i2.ShowTodosView(),
        settings: data,
      );
    }
  };

  @override
  List<_i1.RouteDef> get routes => _routes;
  @override
  Map<Type, _i1.StackedRouteFactory> get pagesMap => _pagesMap;
}

extension NavigatorStateExtension on _i3.NavigationService {
  Future<dynamic> navigateToShowTodosView([
    int? routerId,
    bool preventDuplicates = true,
    Map<String, String>? parameters,
    Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)?
        transition,
  ]) async {
    return navigateTo<dynamic>(Routes.showTodosView,
        id: routerId,
        preventDuplicates: preventDuplicates,
        parameters: parameters,
        transition: transition);
  }

  Future<dynamic> replaceWithShowTodosView([
    int? routerId,
    bool preventDuplicates = true,
    Map<String, String>? parameters,
    Widget Function(BuildContext, Animation<double>, Animation<double>, Widget)?
        transition,
  ]) async {
    return replaceWith<dynamic>(Routes.showTodosView,
        id: routerId,
        preventDuplicates: preventDuplicates,
        parameters: parameters,
        transition: transition);
  }
}`

**main.dart**
`import 'package:flutter/material.dart';
import 'package:stacked_services/stacked_services.dart';

import 'core/app/routes.router.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fullstack Todo App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      navigatorKey: StackedService.navigatorKey,
      onGenerateRoute: StackedRouter().onGenerateRoute,
    );
  }
}`

**Comment by KristiforMilchev** [comment]
It's easily reproducible if you create a flutter project with the flutter CLI, doesn't happen when you use the stacked CLI. Deleting the vsync parameter resolves the issue since it's marked as deprecated, although not a solution in general because it prevents any CI CD flow with the stacked package. 

It will be nice if this can be removed entirely, i know from compatibility reasons it's left in the package, however maybe we should consider making it optional, so that projects that don't depend on vsync don't need to jump hoops to build? 

I can add a PR for it if you want.

**Comment by FilledStacks** [comment]
@KristiforMilchev Stacked CLI also uses the flutter cli then copies some files over. If I can reproduce maybe I can figure out what it is. I won't be removing this as all our clients code bases depend on the skeleton loader functionality. 

What version of Flutter are you using?

**Comment by KristiforMilchev** [comment]
@FilledStacks  I tested it on the main flutter channel, and on the master branch.

**Comment by FilledStacks** [comment]
Could you upload a repo where this happens so we can recreated it. We can't reproduce this on our side. There's also hundreds of projects created using the cli every week, no one has experienced this. Might be an environment thing. 

What is your dart constraints in the pubspec?

**Comment by KristiforMilchev** [comment]
Yes, i finally found a easy way to replicate this, i didn't realize that the my flutter environment was set to the development branch >=3.0.0-322.0.dev <4.0.0 which causes the above mentioned issue, it's not a problem with the current stable release. 

You can close the issue.

**Comment by DanilKarasev** [comment]
Happening on flutter 3.10.0 now
