### ISSUE TITLE
Add pre-configured flavors on create app command

### ISSUE THREAD

**Issue by ferrarafer** [Stacked-Org/stacked#860]
Add `development`, `production` and `staging` **flavors** to the app when using create app command.

**Comment by FilledStacks** [comment]
## Feature

- Add development, production, and staging flavors to the CLI template for mobile
- Add development, production, and staging flavors to the CLI template for web

This feature will be complemented by #949 so they have to be done in the same release

**Comment by sebastianbuechler** [comment]
Maybe interesting for this feature could be the implementation of the "very good cli" from very good ventures as they setup flavors by default: https://cli.vgv.dev/docs/templates/core
