### ISSUE TITLE
Feature: Add ability to compile templates into the CLI

### ISSUE THREAD

**Issue by FilledStacks** [Stacked-Org/stacked#864]
# Problem

At the moment we cannot add templates for any of the create command. We are using a makeshift implementation for the `v1` flag that we check and then manually swap out the content to write out when the command is executed. 

# Solution

Add native supported for templating into the CLI by introducing a new folder structure.

## How it currently works

The way we create templates in our CLI is by compiling them directly into the package as a `const String`'s. The template map is created by looking at the folder structure and creating a set of modifications that align with that structure. The intention behind this was to ensure that a template can be stored using the final file structure we want it to take up. 

Each folder in the root of the `lib/src/templates` folder is for a specific create command. We have the following at the moment:
- app: The template applied when running `stacked create app`
- bottom_sheet
- dialog
- service
- view

This works well but we need it to be more extensible. 

## Why we need to change

As we're building the FilledStacks academy app in Flutter Web we have found the requirement to have a separate template for creating a web app. The current structure doesn't allow for us to do this. In addition to that we also want to update the `view` command to take in templates, specifically for creating views that we have templates for.

Things like a list view that already has continuous loading implemented, pull to refresh, etc. 

## How will we do it

Instead of compiling a single command from the root folders each root folder will serve as an entry for the templates and the folders inside of it will serve as the templates that we can pass in to the cli. This to add a template to the `app` command we'll have:

- app
    - mobile
    - web

This will then add those folder names to the options for the command when running `stacked create app --t=web` where running without the `--t` will use the default option defined for the template icon.

## Rabbit Holes

_The functionality below will be excluded from this work_

- Creating templates that includes pieces of the default template. For now we'll simply duplicate and create templates until it becomes un maintainable
- A root template folder without a default folder inside it should use the root as the template and not add --t options.

## Technical changes

To complete this functionality we will need to update the `compile` command to go a level deeper and build up template options using the subdirectories of the root command folder. 

When we do that we also need to update the templateMap to account for the templates. So instead of a single surface level mapping of  using the `StackedTemplate` directly after getting it from the `kCompiledStackedTemplates` we will instead do an additional index using the --template value passed in. This requires that we update the `StackedTemplate` to now store a map of templates for the Template types of the command. 

In addition to that, to keep things maintainable and have our domain language be solid we need to rename some of the naming from templates to commands since we'll have an actual template parameter now that we need to refer to.

**Comment by ferrarafer** [comment]
I like the specification of this function. The only thing I would change is to avoid a default folder and instead pass the default template as an option in the arguments. This makes changing the default template super easy and decoupled from the template system.

```
    argParser.addOption(
      ksTemplate,
      abbr: 't',
      defaultsTo: 'mobile',
    );
```

**Comment by FilledStacks** [comment]
@ferrarafer Great suggestion! I like it. Updating the original spec now.

**Comment by FilledStacks** [comment]
PR in #865
