### ISSUE TITLE
[CLI] Ability to specify custom path in create commands

### ISSUE THREAD

**Issue by Chappie74** [Stacked-Org/stacked#870]
Can we have the ability to add an argument for custom paths when using create command?

```
stacked create view  test_view 'ui/widgets'
```

I know that the config file exists, but there are cases where I may want the view to exist elsewhere (create a widget for example in another folder)

**Comment by FilledStacks** [comment]
@Chappie74 this is something that we can probably add. It's not going to be high on the list at the moment, but you're welcome to make a PR for it if you're comfortable. 

I'll label it and we will pick it up when our current content work is completed.

**Comment by FilledStacks** [comment]
This will go into the current improvements project and will be assigned a milestone once we review all improvements we want to make.

**Comment by ascorbic-acid** [comment]
hello guys, does this work or i dont understand something ?, im on version 1.11.3

```
stacked create view login 'ui/views/auth'

```

i expect to get auth folder with login feature but i get this error:
```
PathNotFoundException: Cannot open file, path = 'auth/stacked.json' (OS Error: No such file or directory, errno = 2)
```

**Comment by SandaruwanFdo** [comment]
@ascorbic-acid any solution?
