### ISSUE TITLE
Can't load Kernel binary: Invalid kernel binary format version.

### ISSUE THREAD

**Issue by markbulingit** [Stacked-Org/stacked#871]
Can't load Kernel binary: Invalid kernel binary format version.
Could not find a file named "pubspec.yaml" in "C:\Users\Mark Dionnie\AppData\Local\Pub\Cache\hosted\pub.dev\stacked_tools-0.1.5".

![image](https://user-images.githubusercontent.com/91706339/220497832-6a5199e3-210b-43f2-a3ce-f3f1ae484929.png)
![image](https://user-images.githubusercontent.com/91706339/220497870-79c33bc5-050f-487b-9e17-bf7e6946e39c.png)

**Comment by FilledStacks** [comment]
Please use `stacked_cli` instead of `stacked_tools`

Run `dart pub global deactivate stacked_tools && dart pub global activate stacked_cli`

Also please note, we do not control where you system installs the packages. Installations may differ based on your setup and your local environment.
