### ISSUE TITLE
[Feature] Ability to supply org and platform

### ISSUE THREAD

**Issue by felixkriechbaum** [Stacked-Org/stacked#874]
Hey folks,

I think I have a useful idea for the cli.
It would be cool if you could also specify an --org and a --platform like in flutter create

for example:
```shell
stacked create app demo --org com.test --platform ios,android
```

would be really cool

**Comment by chetanchoudhary08** [comment]
would be very helpful to have the above where user can put values for package name and language of android whether kotlin or java. much needed

**Comment by FilledStacks** [comment]
Interesting. I like that idea. I'll tag it. We won't get to this soon, but you're welcome to make a PR if you're comfortable.

**Comment by yangricardo** [comment]
Not saw this before, but also opened this
#974

**Comment by ferrarafer** [comment]
Feature added to the new CLI release.
