### ISSUE TITLE
Faulty listenToReactiveValues method in new ListenableServiceMixin

### ISSUE THREAD

**Issue by josipbarisic** [Stacked-Org/stacked#875]
ListenableServiceMixin’s listenToReactiveValues method checks for the runtimeType which is equal to StoredValue so the switch case's ReactiveValue case is never met and listening of the reactiveValue never starts, so in turn, the value change is not communicated to ViewModels as it was before.

```
/// ListenableServiceMixin’s method
void listenToReactiveValues(List<dynamic> reactiveValues) {
  for (var reactiveValue in reactiveValues) {
    switch (reactiveValue.runtimeType) {
      case ReactiveValue:
        reactiveValue.values.listen((value) => notifyListeners());        
        break;      
      case ReactiveList:
        reactiveValue.onChange.listen((event) => notifyListeners());        
        break;      
      case ChangeNotifier:
        reactiveValue.addListener(notifyListeners);        
        break;    
    }
  }
}
```
This is an example of how I defined a ReactiveValue in my service that is implementing ListenableServiceMixin:

```
final ReactiveValue<int> _userTaps = ReactiveValue<int>(0);

int get userTaps => _userTaps.value;

set userTaps(int taps) {
  _userTaps.value = taps;
}
```

In ListenableServiceMixin's predecessor, ReactiveServiceMixin, this check was handled differently. Condition `reactiveValue is ReactiveValue` would be equal to true for ReactiveValue of any type.

```
/// ReactiveServiceMixin’s method
void listenToReactiveValues(List<dynamic> reactiveValues) {
  for (var reactiveValue in reactiveValues) {
    if (reactiveValue is ReactiveValue) {
      reactiveValue.values.listen((value) => notifyListeners());    
    } 
    else if (reactiveValue is ReactiveList) {
      reactiveValue.onChange.listen((event) => notifyListeners());    
    } 
    else if (reactiveValue is ChangeNotifier) {
      reactiveValue.addListener(notifyListeners);    
    }
  }
}
```

**Comment by FilledStacks** [comment]
@josipbarisic yeah, the last one is more verbose and also more reliable. You think you can make a PR for that?

We've actually been removing the ReactiveValue functionality from our docs as I don't use it in production for any of the projects anymore. I prefer manually calling rebuildUi or notifyListeners in the service. 

If you submit a PR I'll review, push and merge.

**Comment by FilledStacks** [comment]
This is fixed in 3.1.1 😄

**Comment by josipbarisic** [comment]
@FilledStacks awesome, tnx a lot

**Comment by Netajam** [comment]
Thanks for the quick fix
