### ISSUE TITLE
Add functionality to ensure generated route arguments also overrides the equality and hashCode Operations.

### ISSUE THREAD

**Issue by devRaphe** [Stacked-Org/stacked#881]
ISSUE: View route argument objects are not equal, which causes failure when trying to unit test and compare objects, the test will fail.
Current Behaviour: VerifyAccountArguments() == VerifyAccountArguments() = false.
Expected Behaviour: VerifyAccountArguments() == VerifyAccountArguments() = true;

How to tackle issue: Ensure the stacked generator overrides the hashcode and equality operator of each view route argument.

**Comment by FilledStacks** [comment]
@devRaphe are you going to tackle this? 

Please add a bit more details in the description that goes over the following:
- What is the output that you expect
- What is it now

**Comment by devRaphe** [comment]
Yes I am going to tackle it. @FilledStacks.
I will add a description now and you can assign it to me.

**Comment by devRaphe** [comment]
ISSUE: View route argument objects are not equal, which causes failure when trying to unit test and compare objects, the test will fail.
Current Behaviour: VerifyAccountArguments() == VerifyAccountArguments() = false.
Expected  Behaviour: VerifyAccountArguments() == VerifyAccountArguments()  = true;

How to tackle issue: Ensure the  stacked generator overrides the hashcode and equality operator of each view route argument.

**Comment by devRaphe** [comment]
@FilledStacks @ferrarafer  I made the PR to the stacked generator repo. [Link here](https://github.com/Stacked-Org/generator/pull/4)

**Comment by FilledStacks** [comment]
@devRaphe we'll get to this soon. The course creation is taking all of our time.

**Comment by FilledStacks** [comment]
PR has been merged
