### ISSUE TITLE
[logger]: multi output logger should call "init" / "destroy" for each output.

### ISSUE THREAD

**Issue by buehler** [Stacked-Org/stacked#884]
The logger classes do support an "init"/"destroy" method.
When adding custom logger outputs (for example rolling file output),
the multi output logger should call init and destroy for all
inputs (they default to "noop").

**Comment by FilledStacks** [comment]
Thanks for the involvement and the PR. 

I am currently going through github issues and community questions, I'll hopefully get to this before my time is up today. Otherwise definitely tomorrow morning. 

I'm so happy there's more hands in Stacked ❤️
