### ISSUE TITLE
stacked.config warning should not be printed when creating an app

### ISSUE THREAD

**Issue by FilledStacks** [Stacked-Org/stacked#886]
Currently when you run `stacked create app my_app` it prints out the warning that `stacked.json` is not found. We should remove this.

**Comment by vladchuk** [comment]
I think this warning is useful and helpful - please consider leaving it in. Not everybody reads documentation, and, as a matter of fact, that is exactly how I discovered that project structure can be adjusted to one's liking. The more the system is self-documenting, the happier its user is :)

I left a comment to this effect in our discussion in Slack as well.

**Comment by ferrarafer** [comment]
> I think this warning is useful and helpful - please consider leaving it in. Not everybody reads documentation, and, as a matter of fact, that is exactly how I discovered that project structure can be adjusted to one's liking. The more the system is self-documenting, the happier its user is :)
> 
> I left a comment to this effect in our discussion in Slack as well.

We were talking yesterday with Dane and we will do some changes when time is available.

Thanks to your comments we realized that the use case you were talking about is a case which only happens as a CLI developer and is probably not needed as it is.

As a note, we are probably going to have 3 use cases in the config location.

1. Stacked CLI uses custom config, user conventions per project
2. Stacked CLI uses XDG_CONFIG_HOME config, global user conventions
3. Stacked CLI uses default config, Stacked conventions

**Comment by FilledStacks** [comment]
Given that my issue was created with the wrong idea of the solution I'm closing this.
