### ISSUE TITLE
Add support for sub-directory for stacked create view

### ISSUE THREAD

**Issue by Henriquedn** [Stacked-Org/stacked#888]
Hello @FilledStacks,

Many thanks for continued development of this stack of package.

I just started using the cli and I love it.

I would like to suggest addition of sub-directory support to **stacked create view** to enable grouping of views.

e.g if i wanted to create a view in the folder **lib/ui/views/users/profile_view/**  
I would want to use the cli with command like **stacked create view users/profile**

This can also apply to other stacked create commands

**Comment by FilledStacks** [comment]
@Henriquedn thanks for the issue. I like this request, I think we've now had it a few times.

I'll mark as a new feature and we'll tackle this when we free up. We're currently all hands on deck with the updates to get stacked ready for Flutter Web. 

This is a noted request. I'll comment here as soon as it put it into the pipeline.

**Comment by FilledStacks** [comment]
We have added #870 to our Improvements project and this request will be tracked there. We'll start working on this soon. 

Thanks for creating the issue @Henriquedn
