### ISSUE TITLE
[stacked_cli] Add desktop, tablet and mobile view files when using create view.

### ISSUE THREAD

**Issue by gscottschulz** [Stacked-Org/stacked#889]
Thanks for making stacked!
Thanks for making stacked!
Thanks for making stacked!

When using the CLI and running `stacked create view <<view_name>>`, we are only given the base view and viewmodel. When we create a new stacked app with the web template (`stacked create app -t web <<app_name>>`) we get the `Home` view with the base view and `home_view.desktop.dart`, `home_view.tablet.dart` and `home_view.mobile.dart`. Can you add the same `web` template parameter to the `stacked create view` functionality? Right now it only supports the empty template.

Thanks again!!

**Comment by FilledStacks** [comment]
@gscottschulz this is a task that's on my list for today 😄 I'm busy wrapping up the form from AutoRoute's latest version so we can get Navigator 2.0 support for Stacked and the web apps. 

When that's complete I'll move on to the stacked view template. If I don't get to it @ferrarafer might tackle it for us 😉
