### ISSUE TITLE
Allow watch for the stacked generate

### ISSUE THREAD

**Issue by Henriquedn** [Stacked-Org/stacked#891]
Hi @FilledStacks,

I love the stacked generate command instead of typing the whole build command or having to create a short command for the same.

It would be great to have the watch option on the stacked generate command.
This would also come in handy when using other packages that utilise the build runner e.g. freezed, json_serializable etc

Suggestions: 

**stacked generate --watch**
**stacked generate -w**

**Comment by FilledStacks** [comment]
Nice, I like that. I rarely use the watch command, but I should probably start doing that. I'll tag this and work on it when there's some time.
