### ISSUE TITLE
[Stacked CLI] Bug in StartupView for Web

### ISSUE THREAD

**Issue by ynnob** [Stacked-Org/stacked#892]
Hey there!

I think something is wrong with your generated StartupView on Web. It is just a deformed object with no animation.

![image](https://user-images.githubusercontent.com/34171562/224406727-ae644521-193e-4b54-b375-b7f5a7dcc63e.png)

**Comment by FilledStacks** [comment]
hahaha, that's the new stacked logo and that's not the startup view. That's the index.html file that's showing while flutter loads in the backround.

The startup view on web actually shows nothing, it navigates to homeView immediately, check out the StartupViewModel to see. 

I'm going to add built in support for a rive loader on the html.index so it can start loading immediately with a nice Fancy animation. That's coming in the updates I'm planning in the next 2 weeks.

**Comment by ynnob** [comment]
> hahaha, that's the new stacked logo and that's not the startup view. That's the index.html file that's showing while flutter loads in the backround.
> 
> 
> 
> The startup view on web actually shows nothing, it navigates to homeView immediately, check out the StartupViewModel to see. 
> 
> 
> 
> I'm going to add built in support for a rive loader on the html.index so it can start loading immediately with a nice Fancy animation. That's coming in the updates I'm planning in the next 2 weeks.

Ahhhh ahah ok. Well jeah that makes sense! Thanks
