### ISSUE TITLE
Stacked Transition bug

### ISSUE THREAD

**Issue by felixkriechbaum** [Stacked-Org/stacked#894]
Hey folks,

when I try to change the default transition and speed (regarding #732)
<img width="628" alt="image" src="https://user-images.githubusercontent.com/1184644/224579944-d8c8f967-c083-4ac5-82da-9ccaedf22b33.png">

But now when I replace or navigate to my intended view it still use the default "leftToRight" transition with the default speed
```dart
_navigationService.replaceWithLoginView();
//or
_navigationService.navigateToLoginView();
//or
_navigationService.navigateTo("login-view");
```

Am I using this wrong, or does anything changed ?

KR Felix

**Comment by FilledStacks** [comment]
Hey, the config doesn't work. It will be deprecated soon. 

Here's a guide for [custom transitions](https://stacked.filledstacks.com/docs/getting-started/navigation-basics#custom-transitions)
