### ISSUE TITLE
[bug]: test_helpers: null check operator used on a null value.

### ISSUE THREAD

**Issue by given8** [Stacked-Org/stacked#906]
### Describe the bug

The stacked generate command fails with this error message: 
```
[SEVERE] mockito:mockBuilder on test/helpers/test_helpers.dart:
Null check operator used on a null value
```

### To reproduce

1. Create an app using the stacked create command `stacked create app my_app`
2. Run the stacked generate command `stacked generate`

### Expected behavior

I expected the command to generate all the required mocks. **Note**: I did not edit the test_helper file. It is the default one that was created when I ran `stacked create my_app`

### Screenshots

<img width="1236" alt="Screenshot 2023-03-14 at 13 29 51" src="https://user-images.githubusercontent.com/10900605/224987661-ac822f2e-1de3-4bc9-98be-5901ad40ac23.png">
<img width="1236" alt="Screenshot 2023-03-14 at 13 30 59" src="https://user-images.githubusercontent.com/10900605/224987932-29cc7762-5a9c-4282-a4f9-8930eb1c66e7.png">

### Additional Context

Stacked cli version: 1.4.1
Flutter (Channel stable, 3.7.7, on macOS 13.1 22C65 darwin-x64, locale en-ZA)
Dart SDK version: 2.19.4 (stable) (Tue Mar 7 09:58:46 2023 +0000) on "macos_x64"

**Comment by FilledStacks** [comment]
What version of the cli are you using?

**Comment by given8** [comment]
Morning Dane, I'm using version 1.4.1.

**Comment by FilledStacks** [comment]
This usually happens when the generator is out of date.

Check out the latest version of the CLI and try again. I just pushed v1.5.0

**Comment by given8** [comment]
Thanks Dane, I updated the cli and made sure the stacked packages are the latest versions and it worked perfectly. Thank you for all your help.
