### ISSUE TITLE
[bug]: bottom nav bar example shows wrong selected nav bar item after browser refresh

### ISSUE THREAD

**Issue by mraaz97** [Stacked-Org/stacked#911]
### Describe the bug

The bottom nav bar example demonstrates the usage of the `NestedRouter()` with an `AppBar()` Widget. Selecting the NavBar Item 'History' e.g. will select the item and leads to this url: `.../bottom-nav-example/history-view`. After refreshing the browser, the url is still the same as expected and also shows the `HistoryView` but the favorites icon is selected. 

### To reproduce

1. Run router_example
2. Navigate to history view via the app bar item
3. Refresh the browser
4. HistoryView is shown but Favorites Icon is selected

### Expected behavior

Since there are many scenarios where Nested Routing is used with an appbar the expected behavior in web would be to see the correct nav bar item selected. 

### Screenshots

![Bildschirmfoto 2023-03-22 um 14 18 22](https://user-images.githubusercontent.com/43975565/226916580-827bcb0f-8c30-44c3-9801-34f1dfcb4f88.png)

**Comment by FilledStacks** [comment]
@mraaz97 yes, I actually saw this when I migrated the web app. It can be fixed using [exactly this technique](https://youtu.be/cGdNRnBdWpw?t=331) to get the url path id and match it with the tab. 

When we get some time we will update the example to include this information. Thank you for creating the issue. It will help make sure it doesn't slip through the cracks.

**Comment by FilledStacks** [comment]
Fix the issue in the example using the described solution.

**Comment by ferrarafer** [comment]
@mraaz97 where is the example app you mentioned? I wanna work on this bug.

**Comment by mraaz97** [comment]
Hi @ferrarafer, you can find it here: https://github.com/Stacked-Org/stacked/blob/master/example/router_example/lib/ui/bottom_nav/bottom_nav_example.dart
