### ISSUE TITLE
[bug]: Custom stacked.json is not copied to the target project

### ISSUE THREAD

**Issue by vladchuk** [Stacked-Org/stacked#912]
### Describe the bug

Custom configuration file (stacked.json) is used to generate a new project but is not copied to it. Instead, the default configuration ends up in the project.

Also, it would be nice to take a path to the custom config (absolute or relative to the current directory), instead of just looking for it in the current directory. This will remove all ambiguities and allow for easy selection of different templates, if desired.

### To reproduce

- create a new project using custom configuration (stacked.json)
- observe the default config file in the created project

**Comment by FilledStacks** [comment]
@vladchuk thanks for filing the issue. We've had another stacked.json related bug recently. When time opens up we'll prioritise this accordingly and provide feedback as we can.

**Comment by FilledStacks** [comment]
@ferrarafer there's two parts to this issue:

1. stacked.json config is not being used when creating a new project.
2. [Improvement]: Allow user to provide path to config, potentially set it globally once.

**Comment by vladchuk** [comment]
Unfortunately, this doesn't seem to be fixed. What happens now is that the stock (original stacked) configuration gets copied to the target project, *not* the custom one. On top of that, when any stacked commands are executed, the stock config is used, ignoring the already present custom "stacked.json" in the existing project. Other than using the wrong paths, the source formatting is screwed, which is very disruptive.

Also, generally, when the fix is made, the submitter is given the opportunity to verify it. Is there a good reason you are not following the common practice? That would help both you and the users, in testing and avoiding regressions. Please consider it.

**Comment by ferrarafer** [comment]
@vladchuk Sorry for the inconvenience, I will check this immediately. Did you use `--config-path` option when you created the app?

**Comment by ferrarafer** [comment]
> Also, generally, when the fix is made, the submitter is given the opportunity to verify it. Is there a good reason you are not following the common practice? That would help both you and the users, in testing and avoiding regressions. Please consider it.

@vladchuk  We will consider this, thanks !

**Comment by vladchuk** [comment]
I did not use the new switch, just wasn't aware of it - I'll check it out.

But my more important concern is an existing app: how do I make it use my
custom config instead of the stock one? I specifically mean the "generate" command.

**Comment by vladchuk** [comment]
Confirmed: --config-path is working great! ... however, the custom config that was copied to the new project is **not** getting used - the stock one is instead :(. Seem to be the case both for creating new artifacts and running "generate". 

Appreciate your looking into it!

**Comment by ferrarafer** [comment]
> I did not use the new switch, just wasn't aware of it - I'll check it out.

That's why, we changed the command to use a custom config from the new `config-path` option or `XDG_HOME_CONFIG` for a global custom config. If none of them where found, default config will be used.

**From stacked_cli help option**
```shell
-c, --config-path         Sets the file path for the custom config
```

> But my more important concern is an existing app: how do I make it use my custom config instead of the stock one?

Once the project is created, the config used is `stacked.json` on the root of the project. So, if you have a project already created, replace `stacked.json` file on the root of the project. **(I'm looking into this, seems not working right now, I will come back later with news)**

**Comment by ferrarafer** [comment]
@vladchuk A [PR](https://github.com/Stacked-Org/cli/pull/23) was pushed, will fix this issue once merged. Feel free to pull the PR and test it.
