### ISSUE TITLE
[bug]: Generated form controller missing form listener

### ISSUE THREAD

**Issue by vladchuk** [Stacked-Org/stacked#915]
### Describe the bug

See "To reproduce" section.

### To reproduce

- follow the mini-tutorial here: https://stacked.filledstacks.com/docs/getting-started/form-basics
- observe that key pressed are not registering with the controller

### Additional Context

Stacked stack:
stacked: ^3.2.0
stacked_services: ^1.0.0
stacked_generator: 1.0.0

It seems that `  void listenToFormUpdated(FormViewModel model)` was deprecated in 3.2.0 but it's successor `void syncFormWithViewModel(FormViewModel model)` never  found its way to the new version.

If possible, please consider modifying your bug reports to require the version submitted against. Case in point: this must have worked in v. 3.1.0 :)

**Comment by vladchuk** [comment]
A material omission: stacked_cli: 1.5.1

**Comment by FilledStacks** [comment]
Hi @vladchuk I don't quite know what the problem is since there's no problem statement. 

What is not working? What were you expecting to happen instead of what is happening?

**Comment by vladchuk** [comment]
Hm... I thought there was enough information. I'll try again: form input/edit events are not being listened to and, therefore, no form processing (reversing) or validation is happening. Hacking the following (not sure it's the correct fix) fixes it:
<pre>
@override
  TextReverseViewModel viewModelBuilder(
    BuildContext context,
  ) {
    var m = TextReverseViewModel();
    syncFormWithViewModel(m);
    return m;
  }
</pre>

Since nobody else is complaining about it, it is a possible omission/misconfiguration on my part. If so, it is not at all obvious.
Also, I can't seem to be able to update the description. 

To clarify: is it the problem description that is missing or is there not enough info to go on for this issue?..

**Comment by FilledStacks** [comment]
That's not a great fix. It is working fine our side when we call `syncFormWithViewModel` in the `onViewModelReady` override. Can you create a project with stacked_cli that reproduces the issue. I can take a look at it and see if we broke something in a recent release.

**Comment by vladchuk** [comment]
Aha, it's a user's error: I missed this instruction **Call the syncFormWithViewModel function when the viewModel is ready**
Sorry for the false alarm!
