### ISSUE TITLE
[feature]: Persistent Bottom Sheets

### ISSUE THREAD

**Issue by akhil-tlm-sg** [Stacked-Org/stacked#916]
### Is your feature request related to a problem? Please describe.

Can we have the functionality to create persistent bottom sheets that let the user continue interaction with the primary screen and bottom sheet does not fade the background or intrude.

### Describe the solution you would like

https://medium.flutterdevs.com/persistent-bottom-sheet-in-flutter-99e95449d798
Create persistent bottom sheets that do not fade the background or block interactions.

**Comment by FilledStacks** [comment]
Do you want us to add this to the Stacked Services as an option? 

stacked does not dictate which packages you can use. You can build your persistent bottom sheet as in that tutorial and use it with stacked. It shouldn't be an issue.
