### ISSUE TITLE
[bug]: onDispose() method is getting called every time we navigate to some screen ignoring the overrides

### ISSUE THREAD

**Issue by rehan-505** [Stacked-Org/stacked#919]
### Describe the bug

onViewModelReady() method is getting fired everytime we navigate back to the same screen. It is because onDispose Method of current view is getting called everytime we navigate to some other screen even using navigateToScreen() method.

HomeView.dart

```
`import 'package:flutter/material.dart';
import 'package:stacked/stacked.dart';
import 'package:stacked_dummy/ui/common/ui_helpers.dart';

import 'home_viewmodel.dart';

class HomeView extends StackedView<HomeViewModel> {
  const HomeView({Key? key}) : super(key: key);

  @override
  void onViewModelReady(HomeViewModel viewModel) {
    print("HOME SCREEN ON VIEW MODEL READY CALLED");
    super.onViewModelReady(viewModel);
  }

  @override
  Widget builder(
    BuildContext context,
    HomeViewModel viewModel,
    Widget? child,
  ) {

    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 25.0),
          child: Center(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                verticalSpaceLarge,
                Column(
                  children: [
                    const Text(
                      'Navigate To Second Screen',
                      style: TextStyle(
                        fontSize: 35,
                        fontWeight: FontWeight.w900,
                      ),
                    ),
                    verticalSpaceMedium,
                    MaterialButton(
                      color: Colors.black,
                      onPressed: viewModel.navigateTOSecondScreen,
                      child: const Text(
                        "Navigate Now",
                        style: TextStyle(color: Colors.white),
                      ),
                    ),
                  ],
                ),

                  ],
                ),
            ),
          ),
        ),
      );
  }


  @override
  HomeViewModel viewModelBuilder(
    BuildContext context,
  ) =>
      HomeViewModel();


  @override
  // TODO: implement disposeViewModel
  bool get disposeViewModel => false;

  @override
  void onDispose(HomeViewModel viewModel) {
    print("HOME SCREEN ON DISPOSE CALLED");
    super.onDispose(viewModel);
  }

}
`
```
HomeViewModel.dart

```
`import 'package:stacked_dummy/app/app.locator.dart';
import 'package:stacked_dummy/app/app.router.dart';
import 'package:stacked/stacked.dart';
import 'package:stacked_services/stacked_services.dart';

class HomeViewModel extends BaseViewModel {
  final navServ = locator<NavigationService>();



  void navigateTOSecondScreen() {
    navServ.navigateToSecondScreenView();
  }


}
`

```
SecondScreen.dart

```
`import 'package:flutter/material.dart';
import 'package:stacked/stacked.dart';
import 'package:toast/toast.dart';

import '../../common/ui_helpers.dart';
import 'second_screen_viewmodel.dart';

class SecondScreenView extends StackedView<SecondScreenViewModel> {
  const SecondScreenView({Key? key}) : super(key: key);

  @override
  void onViewModelReady(SecondScreenViewModel viewModel) {
    print("Second SCREEN ON VIEW MODEL READY CALLED".toUpperCase());
    super.onViewModelReady(viewModel);
  }


  @override
  Widget builder(
    BuildContext context,
    SecondScreenViewModel viewModel,
    Widget? child,
  ) {
    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 25.0),
          child: Center(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                verticalSpaceLarge,
                Column(
                  children: [
                    const Text(
                      'Navigate To First Screen',
                      style: TextStyle(
                        fontSize: 35,
                        fontWeight: FontWeight.w900,
                      ),
                    ),
                    verticalSpaceMedium,
                    MaterialButton(
                      color: Colors.black,
                      onPressed: viewModel.navigateBack,
                      child: const Text(
                        "Navigate Back",
                        style: TextStyle(color: Colors.white),
                      ),
                    ),
                  ],
                ),

              ],
            ),
          ),
        ),
      ),
    );
  }

  @override
  SecondScreenViewModel viewModelBuilder(
    BuildContext context,
  ) =>
      SecondScreenViewModel();

  @override
  // TODO: implement disposeViewModel
  bool get disposeViewModel => false;

  @override
  void onDispose(SecondScreenViewModel viewModel) {
    print("SECOND SCREEN ON DISPOSE CALLED");
    super.onDispose(viewModel);
  }

}
`

```
SecondScreenViewModel.dart

```
`import 'package:stacked/stacked.dart';
import 'package:stacked_services/stacked_services.dart';

import '../../../app/app.locator.dart';

class SecondScreenViewModel extends BaseViewModel {

  final _navServ = locator<NavigationService>();


  void navigateBack() {
    _navServ.back();
  }


}
`

```

### To reproduce

1.) Created an app with stacked create command
2.) Add 2 custom Views (assume HomeScreen and SecondScreen) and navigate from one screen to another screen.
3.) Override disposeViewModel data member and set the value to true or false (doesn't matter)
3.) Use print statements in OnViewModelReady and OnDispose methods to check they are getting called everytime we navigate to other screen.

### Expected behavior

1.) onViewModel ready should be called only once and should not be called again when we navigate back to same screen.
2.) onDispose shouldn't be called when disposeViewModel value is set to false.

**Comment by FilledStacks** [comment]
@rehan-505 thanks for the details. Could you upload the code so that I can clone the project and run it.

**Comment by rehan-505** [comment]
@FilledStacks sure, here is the code 
https://github.com/rehan-505/stacked_dummy

**Comment by FilledStacks** [comment]
This is happening with a normal Flutter app using no stacked. 

I create 2 views, normalView1 and normalView2. Both are stateful widgets and I add prints in the initState and dispose function call. Which is what stacked uses to fire `onViewModelReady` and `onDispose`. It prints out the same logs as I navigate to view2 and back to view1.

```
flutter: NORMAL VIEW 2: Init state fired
flutter: NORMAL VIEW 1: Dispose
flutter: NORMAL VIEW 1: Init state fired
flutter: NORMAL VIEW 2: Dispose
flutter: NORMAL VIEW 2: Init state fired
flutter: NORMAL VIEW 1: Dispose
flutter: NORMAL VIEW 1: Init state fired
flutter: NORMAL VIEW 2: Dispose
flutter: NORMAL VIEW 2: Init state fired
flutter: NORMAL VIEW 1: Dispose
flutter: NORMAL VIEW 1: Init state fired
flutter: NORMAL VIEW 2: Dispose
```

This seems to have been a change in Flutter which we don't have much control over with Stacked. An issue should be created with a repo that reproduces it and filed in the Flutter repo. 

I can make some time to do that tomorrow or probably on Sunday. I'll add it into my calendar. 

For now there's nothing we can do on the Stacked side. This might be a bug recently introduced in Flutter.

**Comment by maticla** [comment]
@rehan-505 Interesting, I wasn't able to reproduce this and I am using the similar setup to you. Try adding all of the below overrides to your `HomeView.dart` and see if it solves your issue:

```
  @override
  bool get disposeViewModel => false;

  @override
  bool get fireOnViewModelReadyOnce => true;

  @override
  bool get initialiseSpecialViewModelsOnce => true;

  @override
  bool get createNewViewModelOnInsert => false;
```

**Comment by FilledStacks** [comment]
@maticla what version of Flutter are you on. I reproduced it with the repo above and also with a generic flutter project it happens with stateful widgets / views.

**Comment by maticla** [comment]
@FilledStacks I was now able to reproduce the issue on both Flutter versions `3.7.5` and `3.7.8`.

It feels like `viewModelBuilder` is being fired everytime we navigate to the screens, creating the new instance of `ViewModel` and hence triggering the lifecycle methods each time over and over again. Also, all other overrides seem to be ignored and not respected by the `StackedView` 🤔

**Comment by francescopasin** [comment]
To prevent the view from calling `onDispose` when navigating to other views you can just set the `mantainState` property to true on the `MaterialRoute`. The view remains in memory and the state is preserved when navigating back to it.
This property is set to false by default.

**Comment by FilledStacks** [comment]
@francescopasin interesting. This never use to be the case. 

At minimum this value should default to true and can be set to false.

**Comment by francescopasin** [comment]
@FilledStacks Flutter's `MaterialPageRoute` widget has the variable `mantainState` set to true as default, as you can see both in the documentation (https://api.flutter.dev/flutter/material/MaterialPageRoute-class.html) and in the code (Flutter 3.7.8):
```class MaterialPageRoute<T> extends PageRoute<T> with MaterialRouteTransitionMixin<T> {
  /// Construct a MaterialPageRoute whose contents are defined by [builder].
  ///
  /// The values of [builder], [maintainState], and [PageRoute.fullscreenDialog]
  /// must not be null.
  MaterialPageRoute({
    required this.builder,
    super.settings,
    this.maintainState = true,
    super.fullscreenDialog,
    super.allowSnapshotting = true,
  }) : assert(builder != null),
       assert(maintainState != null),
       assert(fullscreenDialog != null) {
    assert(opaque);
  }
```

However the `MaterialRoute` that is defined in `stacked_router_annotations.dart` has that variable set to false:
```class MaterialRoute<T> extends StackedRoute<T> {
  const MaterialRoute({
    String? path,
    required Type page,
    bool initial = false,
    bool fullscreenDialog = false,
    bool maintainState = false,
    bool fullMatch = false,
    String? name,
    List<Type>? guards,
    bool usesPathAsKey = false,
    List<StackedRoute>? children,
    Map<String, dynamic> meta = const {},
    bool? deferredLoading,
  }) : super(
          page: page,
          guards: guards,
          fullMatch: fullMatch,
          initial: initial,
          usesPathAsKey: usesPathAsKey,
          fullscreenDialog: fullscreenDialog,
          maintainState: maintainState,
          path: path,
          children: children,
          name: name,
          meta: meta,
          deferredLoading: deferredLoading,
        );
}
```

You should probably update stacked to change this.

**Comment by maticla** [comment]
@francescopasin @FilledStacks 

The same thing should also be applied for `CupertinoPageRoute` (https://api.flutter.dev/flutter/cupertino/CupertinoPageRoute-class.html)

EDIT: Oddly enough, I have set `maintainState` to `true` in my `app.dart` like so:
```
@StackedApp(
  routes: [
    MaterialRoute(page: HomeView),
    MaterialRoute(page: StartupView),
    MaterialRoute(page: LoginView),
    MaterialRoute(page: NewsView, maintainState: true),
    MaterialRoute(page: RootView),
    // @stacked-route
  ],...
```
Ran the `stacked generate` and the `NewsView.dart` is still disposing itself. 

```
[log] [NewsView.dart] - @override viewModelBuilder fired!
[log] [NewsView.dart] - @override onViewModelReady fired!
[log] [NewsView.dart] - @override onDispose fired!
[log] [NewsView.dart] - @override viewModelBuilder fired!
[log] [NewsView.dart] - @override onViewModelReady fired!
[log] [NewsView.dart] - @override onDispose fired!
```

So maybe something else is causing this behavior?

**Comment by saifr383** [comment]
> @maticla what version of Flutter are you on. I reproduced it with the repo above and also with a generic flutter project it happens with stateful widgets / views.

I created an app with stacked CLI and I tested navigation between 2 normal stateful screens by using print statements in init state and onDispose methods, it is working fine. But in the same app stackedView (viewModelReady and onDispose) is still causing the issue. So maybe the issue is with stacked and not flutter?

I am unable to reproduce this bug in a simple flutter app (with no stacked).

**Comment by dvagala** [comment]
Same thing here. When I updated stacked packages to these versions, the `ViewModels` always dispose. (Tested on Flutter 3.7.0 and 3.3.6.):
```dart
  stacked: 3.2.0
  stacked_hooks: 0.2.3
  stacked_services: 1.0.0
  stacked_generator: 1.1.0
```


However, when I use these versions and run build_runner, it's behaving correctly. (Tested on Flutter 3.7.0 and 3.3.6.):
```dart
  stacked: 3.0.0
  stacked_hooks: 0.2.2
  stacked_services: 0.9.8
  stacked_generator: 0.8.1
```

So this led me to think it's a `Stacked` issue

**Comment by FilledStacks** [comment]
Thanks everyone for your input and your patience. I'm Trying my best to maintain 11 packages , a youtube channel, and run a company 😅 The changes don't seem that big. 

I've scheduled an hour in my calendar for Wednesday, 12 April around 17:15 pm (SAST). I'll try my best to respect that time and get it fixed for you in this week.

Thank you for using Stacked! 🚀

**Comment by FilledStacks** [comment]
Please test this out in v3.2.1 and let me know if it works. If it does please close the issue 😄

**Comment by saifr383** [comment]
Problem still exist

**Comment by rehan-505** [comment]
@FilledStacks still facing same issue on v3.2.1 as well.

**Comment by Sipioteo** [comment]
Confirming this error. I had to downgrade because everytime i open a page (eg. country picker) when i navigate.back(country) i get no result with this error on the roots.

**Comment by JeetChhatrala** [comment]
I tried repo given by @rehan-505 above and using `stacked: 3.2.1` i face the same issue.

BUT..

when i create new app using `stacked_cli:1.6.3` on ` flutter:3.7.11`
it does not matter if i use `3.2.0` or `3.2.1` stacked package, homeViewModel not getting disposed.

try this repo i copied Home and Second Screen from @rehan-505 's repo mentioned above.
Tried 3.2.1 or 3.2.0 , its working.

https://github.com/JeetChhatrala/stacked_test_app

I don't know the reason but this is the behaviour. It might help.


SORRY BEFORE I MENTIONED WRONG FLUTTER VERSION IT WAS `3.3.11` ACTUAL IS `3.7.11`

**Comment by FilledStacks** [comment]
I'll schedule some more time to look at this in this week.

**Comment by ferrarafer** [comment]
@FilledStacks I tested this on latest packages versions and is working as expected like @JeetChhatrala said, we can probably close this issue. Also with a project created with Stacked CLI v1.6.3 I could not reproduce it.

**Development Environment**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E261 darwin-x64, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.77.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Stacked Packages**
```
stacked: ^3.2.1
stacked_services: ^1.0.2
stacked_generator: ^1.3.2
```

Also, updated stacked packages on @rehan-505 project and I could not reproduce the issue.

**Comment by BilalAsif25** [comment]
Hi, is this issue resolved without using stacked_cli, i mean on the latest repos, My app has viewmodels, that are getting disposed when navigate to other viewmodel. ? @FilledStacks
