### ISSUE TITLE
[feature]: Ignore dart linter warnings in `application_models.g.dart`

### ISSUE THREAD

**Issue by francescopasin** [Stacked-Org/stacked#921]
### Is your feature request related to a problem? Please describe.

The `application_models.g.dart` file, generated by Freezed, uses a naming convention that Dart doesn't like.

### Describe the solution you would like

It would be nice to add `// ignore_for_file: non_constant_identifier_names` to the generated file to prevent vs code problems tab to fill up with useless warnings.

**Comment by FilledStacks** [comment]
@francescopasin I am not the maintainer freezed haha. This is also not a freezed issue, it in json serialisable. But there's a few things you can do:
1. File an issue on the  package
2. Make a PR to the package
3. (Preferred option) Add a linting rule to ignore all .g.dart files from analyzing 

In `analysis_options.yaml`

```yaml
analyzer:
  exclude:
    - lib/models/*.g.dart
    - lib/models/*.freezed.dart
```

**Comment by FilledStacks** [comment]
@francescopasin did the instructions above help?

Closing this issue. Let us know if there's anything we can do in Stacked to help you with this.
