### ISSUE TITLE
[bug]:  Unit testing issue

### ISSUE THREAD

**Issue by jimmy-rakh** [Stacked-Org/stacked#922]
### Describe the bug

How to unit test viewModel when we use ReactiveValue from Service in our viewModel.When i try to increment value in viewModel variable in Service doesn`t change
![Снимок экрана 2023-04-06 в 14 42 39](https://user-images.githubusercontent.com/59788736/230338959-cbe86880-f2bf-4437-b5ec-1a0cf1c00d0e.png)
![Снимок экрана 2023-04-06 в 14 42 54](https://user-images.githubusercontent.com/59788736/230339016-bfe8c17c-2efd-40c4-aacd-e7ecbf62b68a.png)

![Снимок экрана 2023-04-06 в 14 43 16](https://user-images.githubusercontent.com/59788736/230339111-b009e704-14fc-4bf6-a7a7-f547017f5627.png)
![Снимок экрана 2023-04-06 в 14 43 58](https://user-images.githubusercontent.com/59788736/230339418-12d81258-f565-47a5-abec-9254aeb622b4.png)

### To reproduce

write flutter test in terminal

**Comment by FilledStacks** [comment]
It sounds like you're trying to write an integration test where you test the interaction between the ViewModel and the Service and check the results on the service. To be clear this is not a unit test. You're multiple things together, the units you're testing is:

- When calling `incrementCounter` on the ViewModel it calls `incrementCounter` on the `IncrementService`
- When calling `incrementCounter` on `IncrementService` the counter is increased from 0 to 1

To test those two together you need to have an integration test setup. In this case it's easy. The services you're registering are Mocks. It's not the real service so nothing will fire. All you have to do is register a real version of the service in your test and it'll work.

**Comment by jimmy-rakh** [comment]
Thank you, it worked!
