### ISSUE TITLE
[bug]: Stacked web app can't return data to previous route

### ISSUE THREAD

**Issue by ScottAtRedHawk** [Stacked-Org/stacked#930]
### Describe the bug

I posted my original question here but this is the same thing. I believe it's a bug.
[https://github.com/FilledStacks/academy/issues/27](https://github.com/FilledStacks/academy/issues/27) 

### To reproduce

See above link.

**Comment by FilledStacks** [comment]
I saw the issue. I'll schedule some time in this week to look at it and see what's happening.

**Comment by ferrarafer** [comment]
@ScottAtRedHawk take a look to the comment I put on https://github.com/FilledStacks/academy/issues/27
