### ISSUE TITLE
[bug]: Browser-Refresh on routes with arguments crashes the app - Flutter Web-App -

### ISSUE THREAD

**Issue by rr-appadaptive** [Stacked-Org/stacked#931]
### Describe the bug

If I have a view (e.g. example-view) which expects an argument to display a certain example, the routing to that view works as expected (_navigationService.navigateToExampleView(example: exampleId)) If I then try to refresh the Browser, the whole App crashes and cannot be restored to functioning state.

### To reproduce

Steps to reproduce the behaviour.

1. Create an Stacked  Flutter Web-App with a standard view and a view expecting an argument to be properly display (see the new documentation)
2. Navigate to the standard view and refresh the browser ==> everything works fine.
3. Navigate to view with the argument and refresh the browser ==> the app crashes (red screen)
4.

### Screenshots

![Bildschirm­foto 2023-04-24 um 11 18 03](https://user-images.githubusercontent.com/17796896/233954794-ececabcc-c56a-4a7e-bd63-1fee094fb42f.png)

### Additional Context

I tracked the problem down to the point where the app executes the routing specified in the "onGenerateRoute:" setting of the main.dart. 
If I normally route to a view with an argument the "onGenerateRoute:"-settings include the necessary argument(s) for the view with argument(s). If I refresh the browser, the "onGenerateRoute:" settings are executed as well but without any argument. That might be due to the browser URL, the app tries to redirect itself to as it does not contain any argument.

**Comment by FilledStacks** [comment]
Hey, do you still have this problem?

**Comment by rr-appadaptive** [comment]
I worked around it in the routing-service routing the app to an argumentless view if a view with arguments is refreshed. 

If you made any changes to your routing-services I will retry it without my workaround an tell you if the error still occurs.

**Comment by FilledStacks** [comment]
Thanks for the response @rr-appadaptive since there's a workaround I will close this. 

I'm publishing new documentation next week on the routing updates. Hopefully those tend to your problem.

**Comment by rr-appadaptive** [comment]
Uuuups.... I suppose you misunderstood me. My workaround is just like a plaster on a ballon. It does not eliminate the problem. It should be possible to refresh a view that has route with arguments either by creating an URL containing the route and the argument(s) or doing that internally when refreshing such a view.

**Comment by FilledStacks** [comment]
I see. Yes, this is not an expected feature of the navigation service. We build a new routing service to handle web url navigation. The navigation service is using v1 of the navigator, the router service uses v2. 

When I publish the docs on it next week this functionality should work as expected. Before the latest release stacked wasn't fully supporting Flutter Web.

**Comment by FilledStacks** [comment]
@ferrarafer our back nav issue will probably solve this as well.

**Comment by ferrarafer** [comment]
@rr-appadaptive I just verified the issue and is not happening on RouterService which is our default router / navigator for Web platform on Stacked. I suggest you to migrate to RouterService if the project has web support.

In some time, RouterService will most likely be the default Stacked service for all platforms.

**Comment by csandovalgt** [comment]
hi, just asking if there is a solution for this??

thanks!
