### ISSUE TITLE
[bug]: Error at compile-time: The argument type 'Object?' can't be assigned to the parameter type 'T?'

### ISSUE THREAD

**Issue by conceptualben** [Stacked-Org/stacked#932]
### Describe the bug

Haven't changed my stacked dependency in a long while today after doing pub upgrade I guess I got this error when trying to run my flutter app:

`Error (Xcode): ../../.pub-cache/hosted/pub.dev/stacked_core-1.2.4/lib/src/code_generation/locator/stacked_locator.dart:405:19: Error: The argument type 'Object?' can't be assigned to the parameter type 'T?'.`

First got that for stacked_shared package, and now for stacked_core.

I checked stacked_shared on pub.dev (https://pub.dev/packages/stacked_shared/score) and I guess something's wrong because even there I can see they're getting the same error:

(I even tried to use an older version for this transitive dependency and then the same error appeared on stacked_core-1.2.4)

### To reproduce

1. Just doing flutter run (for iOS in my case)
2. "Failed to build iOS app"

### Screenshots

<img width="904" alt="Screenshot 2023-04-24 at 21 51 35" src="https://user-images.githubusercontent.com/11361371/234148541-acf0944b-28e4-49b9-bacb-62c4fb948b8c.png">

**Comment by alphalove** [comment]
Hello,
Yes, I've got the same issue.  I updated to the latest Flutter and did a re-install of Stacked cli and still getting the same error as you on iOS.

Cheers,

Alex

**Comment by ihadabs** [comment]
same

**Comment by Spiderbezno** [comment]
I have the same error in FLutter web

Error: The argument type 'Object?' can't be assigned to the parameter type 'T?'.
 - 'Object' is from 'dart:core'.
        instance: instance,

**Comment by ihadabs** [comment]
temp solution:

```yaml
dependencies:
    ...
    
dev_dependencies:   
    ...
    
# Add this
dependency_overrides:
    stacked_shared:
        git:
            url: https://github.com/ihadabs/core
```

(need to be tested)

**Comment by timsedev** [comment]
> temp solution:
> 
> ```yaml
> dependencies:
>     ...
>     
> dev_dependencies:   
>     ...
>     
> # Add this
> dependency_overrides:
>     stacked_shared:
>         git:
>             url: https://github.com/ihadabs/core
> ```
> 
> (need to be tested)

Tested. It works for now. Thank you

**Comment by ynnob** [comment]
Same error. All dependecies up to date:

```
[INFO] Generating build script...
[INFO] Generating build script completed, took 566ms

[INFO] Precompiling build script......
[WARNING] ../../../../../../.pub-cache/hosted/pub.dev/stacked_shared-1.3.1/lib/src/code_generation/locator/stacked_locator.dart:405:19: Error: The argument type 'Object?' can't be assigned to the parameter type 'T?'.
 - 'Object' is from 'dart:core'.
        instance: instance,
                  ^
[INFO] Precompiling build script... completed, took 8.4s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

**Comment by hiraparl** [comment]
Temporary solution works. But it should be fixed immediately on repo

**Comment by FilledStacks** [comment]
Wil check into this now.

**Comment by FilledStacks** [comment]
@ihadabs what was the fix that you made?

**Comment by FilledStacks** [comment]
This was due to a get_it update. It's fixed in latest stacked_shared. 

If this happens again we'll fix our versions and do manual updates in the future. Thanks for the patience and reporting the issue so quickly.

**Comment by FilledStacks** [comment]
Update to `stacked_shared: ^1.3.2`

**Comment by ujwalbasnet1** [comment]
```
../../../.pub-cache/hosted/pub.dev/stacked_core-1.2.4/lib/src/code_generation/locator/stacked_locator.dart:405:19: Error: The argument type 'Object?' can't be assigned to the parameter type 'T?'.
 - 'Object' is from 'dart:core'.
        instance: instance,
                  ^
Target kernel_snapshot failed: Exception
```

got error from stacked_core as well

**Comment by sqrg** [comment]
Provided solution doesn't seems to work. I added `stacked_shared: ^1.3.2` to the pubspec but I keep getting the same error

**Comment by hiraparl** [comment]
> Provided solution doesn't seems to work. I added `stacked_shared: ^1.3.2` to the pubspec but I keep getting the same error

Have cleaned Flutter ? 

flutter clean

**Comment by alphalove** [comment]
Yes, I agree, there also seems to be an issue with stacked_core.  pub.dev is showing a 'static analysis' failure on the 'score' tab and is the same error I'm getting run trying to run my project.  Downgraded get_it to 7.2.0 as a temporary fix.
