### ISSUE TITLE
[bug]:  Adding RouterService to app.dart breaks the application after code generation

### ISSUE THREAD

**Issue by bilaldbank** [Stacked-Org/stacked#939]
### Describe the bug

I am trying to use the RouterService within my project built with stacked architecture. When I add RouterService to app.dart and regenerate the code. The app.locator.dart is updated with the following lines added:

```
import 'package:stacked_services/src/navigation/router_service.dart';

import 'app.router.dart';
StackedRouterWeb? stackedRouter,

```

However the app.router.dart file is not updated with the definition of `StackedRouterWeb` and thus resulting in `Undefined class 'StackedRouterWeb'.`

I have created a sample project generated using stacked_cli to recreate the problem: https://github.com/bilaldbank/sample_routeguard

### To reproduce

1. Add RouterService to a newly generated stacked app (in app.dart)
2. Regenerate the code

### Expected behavior

The app.router.dart file should be updated to contain definition of class `StackedRouterWeb`

**Comment by CordMemescape** [comment]
@bilaldbank 

I've just created a new Stacked app (using the web template) and the `RouterService` is already part of `app.dart`. Are you trying to retrospectively add `RouterService` to an older Stacked app? What is the value of `v1` in your `stacked.json` file?

**Comment by bilaldbank** [comment]
Yes I need to add `RouterService` to an existing application but was facing the same issue in a newly generated project. I was missing the web template flag which fixed the issue for me. Maybe an error message indicating that the user needs to use the web template for using the `RouterService` might be helpful

**Comment by CordMemescape** [comment]
The web-template flag has a specific application (i.e. to create a responsive layout app) and is not needed for many apps. As far as I know, the `RouterService` (introduced in stacked 3.2.0) is used for web navigation, while the `NavigationService` is used for everything else.

Aside from the web-template flag, I don't know how to force an app to use the newer `RouterService`.

**Comment by FilledStacks** [comment]
@bilaldbank yes, there's some additional things you need to do which are not documented yet. There's a build.yaml file you need to add. 

I'll be writing docs for this over the next few weeks. I just finished up the new Flutter web course for stacked so my time will be a bit more open to working on the docs.

**Comment by FilledStacks** [comment]
If you create an app using the --template=web flag you can copy the build.yaml file into your project.

**Comment by FilledStacks** [comment]
I'll be writing new documentation this coming week which I'll link here and close when it's ready.

**Comment by bilaldbank** [comment]
Sounds great! Thanks for the awesome suite of packages!

**Comment by FilledStacks** [comment]
This doc will fall under migration from v1 to v2 navigator in Stacked

**Comment by FilledStacks** [comment]
Please setup the router like [this](https://stacked.filledstacks.com/docs/stacked-router/routing-basics) to get it working.

**Comment by Abhijit-Revamp** [comment]
@FilledStacks 
I just created a new app. Getting error  in "main.dart"  : Undefined name "Routes"

`
    return MaterialApp(

      initialRoute: Routes.startupView,

      onGenerateRoute: StackedRouter().onGenerateRoute,
`

Here are the steps I followed:
1. Latest flutter BETA channel
2. stacked update
3. stacked create app test_web_app --template=web
4. created "build.yaml" in root folder with exact contents in the documentation [link](https://stacked.filledstacks.com/docs/stacked-router/routing-basics/)
5. stacked create view login  

>> error in main.dart
 -- Undefined name "Routes"
-- StackedRouter() isn't defined.

If I change 2nd line to "StackedRouterWeb()" -- onGenerateRoute is undefined

Am I missing anything?

**Comment by Abhijit-Revamp** [comment]
@FilledStacks 
After spending few hours, found missing steps in the documentation (related to my previous comment)
or probably CLI needs to be updated to handle this

1. stacked create app test_web_app --template=web
2. created "build.yaml" in root folder with exact contents in the documentation [link](https://stacked.filledstacks.com/docs/stacked-router/routing-basics/)

**this is where more changes are required**
1. In main.dart, replace 
`
await setupLocator();
`
with
`
await setupLocator(stackedRouter: stackedRouter);
`

2. In main.dart, replace 
`
return MaterialApp(
...
);
`
with

```
    return MaterialApp.router(
      title: 'My App',
      theme: ThemeData(
         // if any
      ),
      routerDelegate: stackedRouter.delegate(),
      routeInformationParser: stackedRouter.defaultRouteParser(),
    );
```

3. in app.dart, set one of the route as initial. e.g.
`
MaterialRoute(page: StartupView, initial: true),
`

4. CRITICAL: do not forget to regenerate. Without this initial route exception will occur
`
stacked generate
`

**Comment by FilledStacks** [comment]
Interesting, those are in the template for web if you look [at the source](https://github.com/Stacked-Org/cli/blob/25c9c17fe4a045ebe1192dc39549373478d9e508/lib/src/templates/app/web/lib/main.dart.stk#L13) and on my side it's being generated. 

I'll see if there's any funny code causing some issues. 

Thank you for the detailed comment.

**Comment by Abhijit-Revamp** [comment]
@FilledStacks I thought so.
However, I can reproduce this issue every time. For more details
1. macOS Sonoma 14.3
2. VSCode latest version
3. Flutter (Channel beta, 3.19.0-0.3.pre, on macOS 14.3 23D56 darwin-x64, locale en-IN)

hope this helps. I will see if I can debug on my side (may need your help)

**Comment by Abhijit-Revamp** [comment]
@FilledStacks  Found the bug.

If I run the command as follows, things are perfect (see the space between -t and web)
`stacked create app debugtest2 -t web`

As per documentation, the parameter is described as --template=web. I think the "=" is an issue

Also the parameter "--org=com.xyz.temp" doesn't work. probably needs space

**Comment by FilledStacks** [comment]
Oooooooooooh yes, okay perfect! Okay, I'll update the docs now.

**Comment by FilledStacks** [comment]
Docs updated for the routing setup. Thanks for taking the time to figure out the bug.

**Comment by Abhijit-Revamp** [comment]
@FilledStacks I am seeing another issue. Last whole week I am struggling why forms are not working as documented.

I created project using "stacked create app debugtest2 -t web", so I expect everything to be at par

However, my pubspec.yaml still has following:
`stacked_generator: ^1.3.3`

The latest one is
`stacked_generator: ^1.6.0`
