### ISSUE TITLE
[bug]: Error: No named parameter with the name 'vsync'.

### ISSUE THREAD

**Issue by logan-keller** [Stacked-Org/stacked#942]
### Describe the bug

As of Flutter `3.10`, `AnimatedSize` no longer takes a `vsync` property

### To reproduce

1. Upgrade to Flutter `3.10`

**Comment by consciousmayank** [comment]
As of now, I went into .pub-cache/hosted/pub.dev/stacked-3.2.3/lib/src/view_models/ui/skeleton_loader.dart, and inside the code, removed "vsync: this," from AnimatedSize. 

The application works. But this is just a hack. not a solution

**Comment by RobertBrunhage** [comment]
@FilledStacks FYI this blocks Flutter 3.10 migration (compilation step) PR is opened here it seems: https://github.com/Stacked-Org/stacked/pull/941

Seems a bit odd that a deprecation like this was ignored instead of just letting older apps use older versions of the package.

**Comment by Ragini2722** [comment]
I'm also facing the same issue. can someone quickly approve the PR #941

**Comment by janbentz** [comment]
I am also facing the exact same issue :)

**Comment by FilledStacks** [comment]
PR has been merged. It will push to pub in the next few minutes.

**Comment by FilledStacks** [comment]
PR has been merged. It will push to pub in the next few minutes.

**Comment by FilledStacks** [comment]
PR has been merged. It will push to pub in the next few minutes.

**Comment by FilledStacks** [comment]
PR has been merged. It will push to pub in the next few minutes.

**Comment by FilledStacks** [comment]
Github is [experiencing issues ](https://twitter.com/githubstatus/status/1656654380433645568?s=20) I will publish the package as soon as it's back up.

**Comment by FilledStacks** [comment]
Issue is fixed in 3.2.5. Thank you all for your patience 👍
