### ISSUE TITLE
[bug]: [WARNING] stacked_generator:stackedRouterGenerator on example/ios/.symlinks/plugins/url_launcher_ios/pigeons/messages.dart

### ISSUE THREAD

**Issue by ziqq** [Stacked-Org/stacked#946]
### Describe the bug

<img width="750" alt="image" src="https://github.com/Stacked-Org/stacked/assets/20646071/3751a9cd-6895-4ca2-adbd-eab50d8919fa">

### To reproduce

`flutter pub run build_runner build --delete-conflicting-outputs`

**Comment by FilledStacks** [comment]
Hey, can you please create a project that reproduces this and share the link. 

Thank you.

**Comment by ziqq** [comment]
> Hey, can you please create a project that reproduces this and share the link.
> 
> Thank you.

It's fine. Close this issue. Thx.
