### ISSUE TITLE
[bug]: Dont need to use Dialog and Bottomsheet

### ISSUE THREAD

**Issue by felixkriechbaum** [Stacked-Org/stacked#948]
### Describe the bug

Hi Folks,

I don't need dialogs and bottomsheets and deleted them. Unfortunately I have to have a Dialog and BottomSheet otherwise I get an error: 

```
An enum must declare at least one constant name.
Try declaring a constant.
```

### To reproduce

Create a new stacked project and delete the dialogs and/or bottomsheets from the folder and clean up the unused code in the stacked classes.

### Expected behavior

No errors or warnings

**Comment by ferrarafer** [comment]
@felixkriechbaum I could not reproduce your issue. I just make a demo project for you to see it works as expected. Let me know if you have any doubt.

https://github.com/ferrarafer/without

**Comment by felixkriechbaum** [comment]
Hi Ferrarafer, thanks for your quick response.

Oke if you delete the files "app.bottomsheets" & "app.dialogs" then it really works.
I just deleted the dialogs and bottomsheets from these files so the enums were empty.

Like:
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// StackedBottomsheetGenerator
// **************************************************************************

import 'package:stacked_services/stacked_services.dart';

import 'app.locator.dart';

enum BottomSheetType {
}

void setupBottomSheetUi() {
  final bottomsheetService = locator<BottomSheetService>();

  final Map<BottomSheetType, SheetBuilder> builders = {
  };

  bottomsheetService.setCustomSheetBuilders(builders);
}

```

Thanks again for the answer and for the demo example
