### ISSUE TITLE
How i can get currentRoute?

### ISSUE THREAD

**Issue by ziqq** [Stacked-Org/stacked#951]
### How i can get currentRoute?

Before

```dart 
navigationService.currentRoute
```

**Comment by FilledStacks** [comment]
[If you want the current route use the route observer](https://pub.dev/packages/stacked_services#route-observation)

**Comment by ziqq** [comment]
> [If you want the current route use the route observer](https://pub.dev/packages/stacked_services#route-observation)

#### Not it's not working for me.

<img width="550" alt="image" src="https://github.com/Stacked-Org/stacked/assets/20646071/d6d5bfab-533a-477f-881a-1885d256481d">

**Comment by FilledStacks** [comment]
You can get the current route from the topRoute.
