### ISSUE TITLE
How I can use dependencies in StackedApp?

### ISSUE THREAD

**Issue by ziqq** [Stacked-Org/stacked#952]
###  How I can use dependencies in StackedApp with my config for **ApiService**? Can u suggest me how i can make like this not in **thirdparty_services_module**?

```dart
abstract class ThirdPartyServicesModule {
  @lazySingleton
  KeyValueStorageService get keyValueStorageService => KeyValueStorageService.getInstance();

  @LazySingleton(as: ApiConsumer)
  BBHttpClient getApiConsumer(
    KeyValueStorageService keyValueStorageService,
  ) {
    return BBHttpClient(
      baseUrl: '${dotenv.env[BaseUrlKey]}/api/',
      keyValueStorageService: keyValueStorageService,
    );
  }
}
```

**Comment by FilledStacks** [comment]
[Here is all the dependency registration methods we support.](https://github.com/Stacked-Org/stacked/blob/master/README_old.md#dependency-registration)

**Comment by ziqq** [comment]
> [Here is all the dependency registration methods we support.](https://github.com/Stacked-Org/stacked/blob/master/README_old.md#dependency-registration)

#### Not it's not working for me, because i need provide the params (**keyValueStorageService** & **baseUrl**)

**Comment by ziqq** [comment]
Can u help me to connect my dependency?

**Comment by FilledStacks** [comment]
Did you use the factory parameters as in the docs I linked?

**Comment by ziqq** [comment]
> 

#### Yep i don't understend how can include `BBHttpClient`

**Comment by FilledStacks** [comment]
If it's not in those docs then the feature is not supported the way you want to use it.
