### ISSUE TITLE
FilledStacks, Plz reopen my issues because i didn't get correct answers

### ISSUE THREAD

**Issue by ziqq** [Stacked-Org/stacked#956]
1. [One](https://github.com/Stacked-Org/stacked/issues/953)
2. [Two](https://github.com/Stacked-Org/stacked/issues/952)
3. [Three](https://github.com/Stacked-Org/stacked/issues/951)
4. [Four](https://github.com/Stacked-Org/stacked/issues/933)

**Comment by godspeed0310** [comment]
Apart from the 4th one which is a bug in the package, others are just questions as to how to use the package. For that you should join the FilledStacks slack channel and ask around. Github issues aren't meant for this.

**Comment by ziqq** [comment]
> Apart from the 4th one which is a bug in the package, others are just questions as to how to use the package. For that you should join the FilledStacks slack channel and ask around. Github issues aren't meant for this.

Is the channel closed or not? Link please.

**Comment by FilledStacks** [comment]
There's a [community run discord](https://discord.gg/YhDNY5rj) you can join.
