### ISSUE TITLE
[Improvement]: Forms

### ISSUE THREAD

**Issue by maikelAlma** [Stacked-Org/stacked#961]
### Is your feature request related to a problem? Please describe.

It's annoying that every time I run the generation of the stacked resources it overwrites the form fields.

### Describe the solution you would like

My recommendation is that the form fields keep the name no matter how it is written and only change it when the name of the function or variable is used and not in the names of the keys in the final result.

### Additional Context

in this example we see that the name is declared with an underscore:
@FormView(
  fields: [
    FormTextField(name: 'card_name'),
  ],
)

The code that generates me is this:
const String CardNameValueKey = 'cardName';

Therefore, when invoking the function [formValueMap], it returns a [Map] as follows:
{"cardName":"value"}

but I need the key to be [card_name] to obtain the result as follows:
{"card_name":"value"}

**Comment by ferrarafer** [comment]
@maikelAlma use value key generated field for consistency.

Instead of using

```dart
{"card_name": "value"}
```
use the following

```dart
{CardNameValueKey: "value"}
```

**Comment by maikelAlma** [comment]
Thanks for your answer, but it doesn't solve what I'm suggesting.

Even if I use {CardNameValueKey: "value"} the result will remain the same, when I put in the [name] of the field

`FormTextField(name: 'card_name'),`

It is because I need it to be called like this, it does not matter if consistency is broken, it is a name that I am going to use, that changes in the variables and in the functions that are generated does not affect me, if I want the result to be

`{"cardName":"value"}`

I just write

`FormTextField(name: 'cardName'),`

**Comment by FilledStacks** [comment]
We could probably do that for the key. 

We've already chosen all the work for next week so this can go into the pipeline for the following week.

**Comment by ferrarafer** [comment]
This is covered by the new release, closing issue.
