### ISSUE TITLE
[bug]: forced named parameter not found

### ISSUE THREAD

**Issue by designstyles** [Stacked-Org/stacked#965]
### Describe the bug

I installed the latest version of stacked_services (1.1.0) , when I tried to run my application, I got a gradle error message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/stacked-3.4.0/lib/src/view_models/view_model_widget.dart:31:13: Error: No named parameter with the name 'force'.
    rebuild(force: true);

If I manually amend the offending rebuild method, to remove the named paramter, the issue goes away. 

flutter doctor:
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [Version 10.0.19045.2965], locale en-ZA)
[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.6.0 Preview 6.0)
[!] Android Studio (version 3.6)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.78.2)
[√] Connected device (2 available)
[√] HTTP Host Availability

! Doctor found issues in 2 categories.

### To reproduce

flutter create test_app
pubspec ->
dependencies:
  stacked_services: ^1.1.0

run application

### Expected behavior

application runs

**Comment by ferrarafer** [comment]
@designstyles I just tested and I didn't find any issue. Try to update Flutter to latest stable version.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E772610a darwin-x64, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

**Steps (Stacked CLI 1.9.0)**
```
1. stacked create app my_app
2. update stacked_services from 1.0.0 to 1.1.0
3. flutter pub get
4. stacked generate
5. flutter run
```

If the issue continues, you can upload the project to a public repository and share it here.
