### ISSUE TITLE
[New Feature] Add `initState` method for `BaseViewModel`

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [Stacked-Org/stacked#97]
I know you can create a method in the ViewModel and call it from the `onModeReady`, but won't it be easier and make more sense if it is a method you can override in the view model. Like `initState` method in `StatefulWidget`.

Just a thought I had in mind 😎😁

**Comment by FilledStacks** [comment]
There is one in all the Special viewmodels that you can override but you have to call super. I might add it to the BaseViewModel as well.

**Comment by YazeedAlKhalaf** [comment]
But it is not in the docs, can you give me an example? 😁

**Comment by YTarikKalyoncu** [comment]
Yes this would be great.
I use `XviewModel extends BaseViewModel implements Initialisable` with @override `initialise` metod for now.

**Comment by FilledStacks** [comment]
@YazeedAlKhalaf 

```dart
class MyViewModel extends BaseViewModel implements Initialisable {
  @override
  void initialise() {
    // This will be called when init state cycle runs
  }
}
```

**Comment by vontdeux** [comment]
hi @FilledStacks,  
how do we use this initilise() with widgetBinding instance?

because currently I am using ShowCaseWidget package, that suggest to use

```
void initState(){
  startShowCase();
}

void startShowCase(){
  WidgetsBinding.instance!.addPostFrameCallBack((_) =>ShowCaseWidget.of(context)!.startShowCase([key1,key2]));
}
```

**Comment by FilledStacks** [comment]
@vontdeux You can call it in the onModelReady callback.

**Comment by vontdeux** [comment]
@FilledStacks but how do i pass the BuildContext using that? is there any example on this particular condition?

**Comment by FilledStacks** [comment]
@vontdeux we don't pass the build context. onModelReady fires in the view. If you read the readme, watch any of my stacked vids or read any of my tutorials you'll see that onmodel ready is one of the first things we teach.

**Comment by vontdeux** [comment]
@FilledStacks hmm, its kind of frustrating if I cant pass the BuildContext in init/once per view then because my app is heavily dependent on this. Or is it a wrong approach for MVVM pattern?

**Comment by FilledStacks** [comment]
@vontdeux it's the wrong context. What you're doing is the complete opposite of what stacked is trying to achieve. You want your viewmodel to contain only logic and state code, no UI code. nothing from the Flutter framework in there. eveything else should be in the view. 

the context is available in the onModelReady callback function since it fires in the build method. I think you might be confused or you're not using stacked as shown in the readme. What you want to do is definitely possible.

**Comment by vontdeux** [comment]
Thanks, It is my second day using stacked, (found it yesterday), I guess I need a deeper understanding before moving further.

**Comment by emmanuelsho9** [comment]
in the inistate, how will i add the buildcontext?

**Comment by ferrarafer** [comment]
@emmanuelsho9 what do you want to achieve? We don't use the `BuildContext` inside the ViewModel.

**Comment by emmanuelsho9** [comment]
@ferrarafer  i am using videos flutter package and in the inistate i need to pass context

**Comment by nfathoni79** [comment]
@emmanuelsho9 Sorry if OOT. If I use `FutureViewModel`, how do I show a dialog when the future is complete?

**Comment by emmanuelsho9** [comment]
@nfathoni79  i use getx for that to make it easy   Get.dialog()|

**Comment by ferrarafer** [comment]
@emmanuelsho9 please, paste here the link of the package you are using, I didn't find it.

**Comment by ferrarafer** [comment]
> Sorry if OOT. If I use FutureViewModel, how do I show a dialog when the future is complete?

@nfathoni79 why you are not using `DialogService`?

**Comment by nfathoni79** [comment]
> > Sorry if OOT. If I use FutureViewModel, how do I show a dialog when the future is complete?
> 
> @nfathoni79 why you are not using `DialogService`?

So should it be done from the ViewModel, not from the View?

**Comment by ferrarafer** [comment]
@nfathoni79 if you want to follow our conventions, all the presentation logic **should** be executed through the `ViewModel`.
