### ISSUE TITLE
[bug]: Stacked generator missing import for router's returnType 

### ISSUE THREAD

**Issue by akifarhan** [Stacked-Org/stacked#971]
### Describe the bug

When generating routes with a return type of a model from another file, the generated code in `app.router.dart` does not include the import that leads to this error `The name 'User' isn't a type, so it can't be used as a type argument.
Try correcting the name to an existing type, or defining a type named 'User'.` 

### To reproduce

Steps to reproduce:
1. Create a class in the `models` folder. 
2. Add return type to a route in the list of routes. eg: `MaterialRoute<User?>(page: SettingsView),`
3. Run `flutter pun run build_runner build --delete-conflicting-outputs`

Reproducible code [here](https://github.com/akifarhan/codegen)

### Expected behavior

The generated `app.router.dart` should include importing the `User` class with an alias. 

### Screenshots

![image](https://github.com/Stacked-Org/stacked/assets/38977468/5e59a187-8b9c-458b-aae8-5cefaaf291d5)
![image](https://github.com/Stacked-Org/stacked/assets/38977468/5e026c53-bb59-4eff-9ae1-3ad82c2a33f0)

**Comment by ferrarafer** [comment]
Hi @akifarhan , do you need to set the Return Type for any particular reason? Works out of the box without setting any `Type` on the declared Route. If you pass any **Type** to `result` property in **back** function is going to work.

Let me know if that makes sense for you.

**Comment by akifarhan** [comment]
Hi @ferrarafer , it makes sense and works without setting any Type on the declared Routes. However IMO, it's best to declare it, especially for the methods generated in the `NavigatorStateExtension`.

**Comment by FilledStacks** [comment]
@akifarhan that's a good catch. We'll keep this in our list of improvements and include it in one of our upcoming sprints.

**Comment by ziqq** [comment]
Hello everyone, i have this same issue.

```dart
CustomRoute<MCrop?>(
  page: ImageEditorView,
  name: 'imageEditorView',
  customRouteBuilder: modalsPageRouteBuilder,
)
```

<img src="https://github.com/Stacked-Org/stacked/assets/20646071/a2d3c0a4-1eee-4425-a7e4-20bc2d572c76" width="400" /> <img src="https://github.com/Stacked-Org/stacked/assets/20646071/43154ea4-f681-4152-9b46-3c791bbc1038" width="400" />

**Comment by akifarhan** [comment]
I would love to work on this but I'm unfamiliar with code gen. Can you help me to start with it @FilledStacks? Like any resources or the things that I gonna deal with to work on this?

**Comment by FilledStacks** [comment]
Hi @akifarhan there are no resources for this. I learned how to do it by looking at other packages like Freezed and auto_route. 

You basically just write strings to disk. YOu can search for the builder generator and start playing around there. 

We haven't added support for this functionality, since we also don't use it. It was inherited by the auto_route fork, so at the moment it's not expected to work.
