### ISSUE TITLE
[feature]: Stacked Create App with organization bundle identifier definition (non com.example)

### ISSUE THREAD

**Issue by yangricardo** [Stacked-Org/stacked#974]
### Is your feature request related to a problem? Please describe.

Always when i create a new app, i need to manually update de bundle identifiers.
Flutter create app provides the `--org` flag that already perform this for us...

```
--org                    The organization responsible for your new Flutter project, in reverse
                             domain name notation. This string is used in Java package names and as
                             prefix in the iOS bundle identifier.
                             (defaults to "com.example")
```

### Describe the solution you would like

`stacked create app <app name> --org <org bundle identifier>`

This would override the defaults `com.example` from current stacked create app that do not change the default behavior of `flutter create app`

**Comment by ferrarafer** [comment]
Hi @yangricardo, this feature is already in [pre-release](https://github.com/Stacked-Org/cli/commit/8287e25ee2ebbba4d7d49cbc52305b6610fddae9) code, will be out very soon.

**Comment by ferrarafer** [comment]
Stacked CLI v1.10.0 released including this feature.
