### ISSUE TITLE
How to implement AnimationController in this architecture?

### ISSUE THREAD

**Issue by azrael8576** [Stacked-Org/stacked#98]
AnimationController  need a vsync parameter.
But ViewModelBuilderWidget and ViewModelWidget extends StatelessWidget.

My method uses ViewModelWidget to provide data and then pass to StatefulWidget create _animationController & init animation value in initState().

Is there a better solution?

**Comment by FilledStacks** [comment]
Hey, yes there is. 

Use the HookViewModelWidget from the stacked_hooks package and then use the `useAnimationController` from the flutter_hooks package. 

You can do everything you want to do with stateful widget using hooks.

**Comment by Correct-Syntax** [comment]
Hi, maybe I missed it, but couldn't this be added to the documentation?
