### ISSUE TITLE
Stack generator produces wrong method: init() instead of initialise()

### ISSUE THREAD

**Issue by Dionnie** [Stacked-Org/stacked#986]
### Describe the bug

produces wrong method: init() instead of initialise() 

### To reproduce

Run flutter pub run build_runner build --delete-conflicting-outputs

### Expected behavior

On app.locator.dart

`await eCardService.initialise();`

### Screenshots

![image](https://github.com/Stacked-Org/stacked/assets/48149031/32e1554f-0fdb-4955-ac86-7dce9bf51748)

**Comment by eb-so** [comment]
@Dionnie123 Are you using `Presolve` to register the service?
if you are you should use `InitializableSingleton` instead

**Comment by ferrarafer** [comment]
@Dionnie123 also, rename `initialise` method to `init` method to use `InitializableSingleton`.

We added documentation [here](https://stacked.filledstacks.com/docs/in-depth/service-locator#initializablesingleton).

**Comment by Dionnie** [comment]
Thank you @ferrarafer @eb-so it works!!!
