### ISSUE TITLE
[feature]: nested view paths

### ISSUE THREAD

**Issue by sebastianbuechler** [Stacked-Org/stacked#988]
### Is your feature request related to a problem? Please describe.

If the application grows it can make sense to not just have a flat "views" folder but to nest similar views together. Having hundreds of views can make it hard to not use very long long view names.

### Describe the solution you would like

Make it possible to use `stacked create view folder/to/view/group/test` for creating a new view in a nested structure.

### Additional Context

Especially for processes with a lot of steps it's nice to put everything into one parent folder.

**Comment by ferrarafer** [comment]
I would say that for cases like that could be better to make use of packages to group views per feature or a selected criteria.

What do you think @FilledStacks ?

**Comment by SandaruwanFdo** [comment]
Hello, is this implemented?

**Comment by FilledStacks** [comment]
Yes you can supply a path using `-c`

@ferrarafer it would have probably been better to supply a path for output using `-p`

`stacked create view login -c lib/features/authentication/ui/`

**Comment by ferrarafer** [comment]
@FilledStacks yeah, maybe `-p` has more sense. It was `-c` because it overrides the custom config path.

I add this to the list of tasks.

**TASK**
Replace the -c argument with the -p argument for the file path in the stacked create view command.

This should probably apply to the rest of the commands where the -c argument is available.

**Comment by FilledStacks** [comment]
@sebastianbuechler let me know if this is not the feature you were asking for. I'm closing for now

**Comment by sebastianbuechler** [comment]
> @sebastianbuechler let me know if this is not the feature you were asking for. I'm closing for now

That was exactly what I asked for 💯 Thanks!
