### ISSUE TITLE
[bug]: stacked_services in last version back method from RouterService makes navigation through 2 routes, and not one as it was before

### ISSUE THREAD

**Issue by ziqq** [Stacked-Org/stacked#990]
### Describe the bug

Last version `back` method from `RouterService` makes navigation through 2 routes, and not one as it was before

https://github.com/Stacked-Org/stacked/assets/20646071/dd758939-65ee-4368-ad6b-5d7ae43812e1

### To reproduce

Make simple bottom sheet and from viewModel use `back` from `RouterService` to close it after you logic

### Solution
Revert 
```dart
void back<T extends Object?>({T? result}) => router.navigateBack();
```
To
```dart
Future<bool> back<T extends Object?>({T? result}) => router.pop(result);
```

**Comment by ferrarafer** [comment]
@ziqq please, use `pop` method instead of `back` for your use case. We changed this to align with `auto_route` package.
