### ISSUE TITLE
[bug]: Presolve is depricated and InitializableSingleton does not contain presolveUsing

### ISSUE THREAD

**Issue by JeetChhatrala** [Stacked-Org/stacked#991]
### Describe the bug

Presolve is depricated in recent build of stacked and InitializableSingleton is suggested to be used on its behalf. But InitializableSingleton does not have presolveUsing or similar feild, so we are not able to presolve our SharePreference using it. 

### To reproduce

create app using stacked_cli: 1.10

and using below code in app.dart

```
@StackedApp(
  routes: [
    MaterialRoute(page: StartupView),
// @stacked-route
  ],
  dependencies: [
    Presolve(
      classType: SharedPreferences,
      presolveUsing: SharedPreferences.getInstance,
    ), // WORKING but depricated
    InitializableSingleton(classType: SharedPreferences), // NOT WORKING calls init() in locator.dart generated file
    LazySingleton<DialogService>(classType: DialogService),
    LazySingleton<NavigationService>(classType: NavigationService),
// @stacked-service
  ],
  bottomsheets: [
    StackedBottomsheet(classType: NoticeSheet),
    // @stacked-bottom-sheet
  ],
  dialogs: [
    StackedDialog(classType: DropDialog),
// @stacked-dialog
  ],
)
class App {}
```

### Expected behavior

should have a parameter like presolveUsing on InitializableSingleton

**Comment by eb-so** [comment]
See this [example](https://github.com/Stacked-Org/stacked/blob/master/example/router_example/lib/services/shared_preferences_service.dart)

**Comment by ferrarafer** [comment]
@JeetChhatrala we added documentation [here](https://stacked.filledstacks.com/docs/in-depth/service-locator#initializablesingleton), let me know if you still have issues, we can help you.

**Comment by buehler** [comment]
Hey @ferrarafer,

I stumbled across the same issue when upgrading to the newest version.
You have LazySingleton with a presolve logic, but: this method is sync now. I have no chance on using the async logic now.

Use cases are:
```dart
class SharedPreferencesFactory {
  static Future<SharedPreferences> presolve() =>
      SharedPreferences.getInstance();
}
```

And grpc services as well:
```dart
class FooClientFactory extends FooClient {
  FooClientFactory(super.channel);

  static Future<FooClient> presolve() async {
    final appEnvironment = locator<AppEnvironment>();
    final channel = ClientChannel(
      appEnvironment.grpcApiHost,
      port: appEnvironment.grpcApiPort,
      options: const ChannelOptions(credentials: ChannelCredentials.insecure()),
    );
    return RecipeServiceClient(
      channel,
      options: CallOptions(providers: [
        appVersionProvider(),
      ]),
    );
  }
}
```

Especially with grpc clients, it is not possible to use "init".

It would be nice to still have the async possibility to register services.

**Comment by JeetChhatrala** [comment]
document clears it up, thank you @ferrarafer

**Comment by JeetChhatrala** [comment]
> See this [example](https://github.com/Stacked-Org/stacked/blob/master/example/router_example/lib/services/shared_preferences_service.dart)

this will also work, thank you sir. but ill be using LazySingleton with resolveUsing parameter
