### ISSUE TITLE
[bug]: type 'ConstTopLevelVariableElementImpl' is not a subtype of type 'ClassElement' in type cast

### ISSUE THREAD

**Issue by danielreghin** [Stacked-Org/stacked#992]
### Describe the bug

I Was unable to generate a routes file with the new package versions

This error occurred when tryed to update the project dependencies
dart run build_runner build

[SEVERE] stacked_generator:stackedRouterGenerator on lib/core/app/routes.dart:
type 'ConstTopLevelVariableElementImpl' is not a subtype of type 'ClassElement' in type cast

Regards,

### To reproduce

1) Download the following project https://github.com/saileshbro/full_stack_todo_dart
2) Go to frontend folder
3) Update the dependencies to:
dev_dependencies:
  stacked_generator: ^1.4.0

dependencies:
  stacked: ^3.4.1
  stacked_services: ^1.2.0

4) Execute  dart run build_runner build

**Comment by FilledStacks** [comment]
We see that this is not using all of Stacked as it's recommended, we'll confirm that it'll work this way in time and get back to you.

**Comment by danielreghin** [comment]
I created a project from scratch with the stacked CLI and it started working. So, I think it's not a big issue anymore. 
Thanks anyway.
