### ISSUE TITLE
[feature]: SkeletonLoader should adhere to the theme colors by default

### ISSUE THREAD

**Issue by eb-so** [Stacked-Org/stacked#996]
### Is your feature request related to a problem? Please describe.

Although the skeleton loader is a nifty widget, if you are using any theming it doesn't adhere to your color scheme 
Of course you can provide colors to   `startColor` `endColor ` but that's not very scalable cause you'll have to do that every time you call the widget

### Describe the solution you would like

Instead of using static color use flutter theme to get the default colors and you can still provide the colors `startColor` `endColor` if you're not a theme guy 👨‍🎨 
I don't exactly know what colors would be appropriate for this kind of widget but we can figure it out

### Additional Context

I can implement this but let me know what you think guys @FilledStacks @ferrarafer 

Bonus Note⭐: If we agree on this widget we can migrate all the other UI components that stacked use one by one after we finish this one

**Comment by ferrarafer** [comment]
Hi @eb-so ! I like the idea, let's wait and see what @FilledStacks thinks.
