### ISSUE TITLE
[feature]: Snack bar align issue

### ISSUE THREAD

**Issue by akshaychandt** [Stacked-Org/stacked#997]
### Is your feature request related to a problem? Please describe.

When I align the snack bar at the top of the screen, it aligns under the status bar, which is not what I intended.

### Describe the solution you would like

 I'm looking for a snack bar like the Netflix snack bar that shows connection status.

**Comment by ferrarafer** [comment]
Can you upload a picture of what do you want to achieve? I don't use that service too much.

**Comment by akshaychandt** [comment]
> Can you upload a picture of what do you want to achieve? I don't use that service too much.

This is what I get
![Simulator Screenshot - iPhone 14 Pro Max - 2023-07-26 at 15 20 11](https://github.com/Stacked-Org/stacked/assets/89569907/12b2184e-8d3b-47a5-a0ee-703174b0fe10)

This is what I am looking for

![IMG_6848](https://github.com/Stacked-Org/stacked/assets/89569907/3201681f-4255-430d-a32d-38be96d1cbfb)

**Comment by ferrarafer** [comment]
Hi @akshaychandt , how are you? You need to use a Custom Snackbar with `snackStyle` set to `SnackStyle.GROUNDED`. Also, is recommended to remove margin and border of the Snackbar.

**Comment by akshaychandt** [comment]
> You need to use a Custom Snackbar with `snackStyle` set to `SnackStyle.GROUNDED`. Also, is recommended to remove margin and border of the Snackbar.

I am doing well, and I trust this message finds you well. I want to express my gratitude for the invaluable solution you provided for the issue I posted. Your expertise and prompt assistance are greatly appreciated. Thank you for investing the time and effort to address my concern.

**Comment by ferrarafer** [comment]
Thanks, don't mention, I hope was useful for you.

Cheers !
